### PR TITLE
Fix vm::falloc()

### LINKED ISSUE #9763: GT HD debug elfs crash on load
When trying to load debug binary (with symbols) of Gran Turismo HD, pre-PS3 release/prototype from mid-2006, RPCS3 causes some kind of ELF loading error "invalid arguments" error  https://github.com/RPCS3/rpcs3/blob/06528702046dde739eae87b82925b496c71be1d7/rpcs3/Emu/Memory/vm.cpp#L665 Thus fails to even parse and boot the ELF.

https://cdn.discordapp.com/attachments/807830839756455937/807835564962349106/unknown_11.png

https://cdn.discordapp.com/attachments/807830839756455937/807855596333563936/GTHD_debug_elf.zip

### PR DESCRIPTION
**Pull request by elad335**
Handle unaligned addresses properly.

Fixes #9763

### CODE REVIEW

File: rpcs3/Emu/Memory/vm.cpp [hunk 1]
```diff
@@ -1233,18 +1233,22 @@ namespace vm
 			flags = this->flags;
 		}
 
-		// Determine minimal alignment
-		const u32 min_page_size = flags & 0x100 ? 0x1000 : 0x10000;
+		// Determine minimal alignment (shared memory requires atleast 64k)
+		const u32 min_page_size = !src && flags & 0x100 ? 0x1000 : 0x10000;
```
Comment (Nekotekina) [inline rpcs3/Emu/Memory/vm.cpp:1237]: Is this condition really necessary?

Comment (elad335) [reply rpcs3/Emu/Memory/vm.cpp]: Well not really.
