### PR TITLE
Fixes #1584 (Vulkan not being usable in non-w10 systems)

### LINKED ISSUE #1584: Config bug: Vulkan not working on non-w10 systems
```
<Myani> If I try to load a game with the VK rendered on my W7 OS it crashes the emulator, but if I try it on the W10 OS it works (VK drivers installed on both, dual-boot)
<Myani> Yeah I'm running it inside VS to try to find the cause
<Myani> Ok so it tried to load d3d12.dll ??
<Myani> Seems like it
<paulzz> yeah dx12 is dynamically linked
<paulzz> if not found then not supported
<Myani> I might know what is happening though, could be config related as DX12 doesn't appear because it isn't supported and Vulkan is in the place DX12 should be so it may be trying to load DX12 instead of VK? Checking this, just a sec
<Myani> I mean, OpenGL works and VK was a direct port from OGL AFAIK
<Myani> Yeah, it seems what I just said is happening
<Myani> Checked the config and Renderer=DX12
<Myani> when it's set to Vulkan
<Myani> I'll try to fix it myself otherwise I'll open an issue
<paulzz> well
<paulzz> no wonder it crashes :D
<+Nekoteki> it's fixed in my PR
<+Nekoteki> (accidentally)
<+Nekoteki> (I hope)
<Myani> Yeah since you have redone the config
<Myani> I'll try to submit a hotfix though as I wanted to test VK on my w7 os
<Myani> I'll open an issue anyways just for the record
```

In Operating Systems that do NOT support DirectX 12 like Windows 7, if Vulkan is selected as the Renderer, RPCS3 will assume we picked DX12 and crash.
That's due to the fact DX12 isn't showed in the list and Vulkan takes its place in the list.
Null, OpenGL, Vulkan instead of Null, OpenGL, DirectX 12, Vulkan

### PR DESCRIPTION
**Pull request by MyaniPT**
Hotfix for #1584

In the settings window, if another value isn't appended before Vulkan, the emulator will try to use DX12 when set to Vulkan in the Settings window

In W10: Null, OpenGL, DirectX 12, Vulkan
Not in W10: Null, OpenGL, Vulkan

When DirectX 12 is missing and Vulkan is set, the emulator tries to run DirectX 12. As is isn't compatible with the host OS, it crashed the emulator with an unhandled exception.

### CODE REVIEW

**Comment by MyaniPT** [comment]
Don't merge yet. I think I missed something

**Comment by kd-11** [comment]
You stumbled upon an interesting bug there. You're right it does seem hackish. What happens if you run the emulator with DX12 selected on win7? Maybe you could set the current renderer value to enum_value_of(checkbox.text) instead of just using the checkbox.selected_index value. Just trace where the configuration loader translates strings in config files to renderer enums and use that. I cant remember which file it's in, but i know it exists since I had to add vulkan there. That would be a more permanent solution.

**Comment by MyaniPT** [comment]
With this fix if I select the "DirectX 12 (Not available)" render option it produces the same outcome as trying to run it with "Vulkan" on current master (crashes with an Unhandled exception as seen on http://www.emunewz.net/forum/showthread.php?tid=174359&pid=230717#pid230717)
If I select "Vulkan", it runs with Vulkan.

I'll try to do it as you said, I need to find the file, as I also looked for it before and didn't find it.

**Comment by kd-11** [comment]
rpcs3/config.h line 105. Just try and adapt that. in rpcs3/Gui/SettingsDialog.cpp Line 506, we see how it sets the current renderer: cfg->rsx.renderer = cbox_gs_render->GetSelection(); Just change that to something like cfg->rsx.renderer = translate_to_render_type(cbox_gs_render->GetString(cbox_gs_render->GetSelection())) (I'm making an assumption about the wxwidgets checkbox getText method here) and try to use the template to perform the translation.

**Comment by MyaniPT** [comment]
I think the last commit is a more appropriated non-hacky fix.

I understood what you said above, that's what I initially tried to do, but since I lack a lot of C++ knowledge I couldn't do exactly as you said.

**Comment by MyaniPT** [comment]
@kd-11 Please review when you can, I've also edited the commit message.

File: rpcs3/Gui/SettingsDialog.cpp [hunk 1]
```diff
@@ -251,7 +252,6 @@ SettingsDialog::SettingsDialog(wxWindow *parent, rpcs3::config_t* cfg)
 		chbox_gs_overlay->Enable(false);
 	}
 
-	cbox_gs_render->Append("Vulkan");
```
Comment (MyaniPT) [inline rpcs3/Gui/SettingsDialog.cpp]: Why was Vulkan inside the check for a Microsoft OS? (Wouldn't that make Vulkan not usable in Linux/Mac OSX?)

Comment (vlj) [inline rpcs3/Gui/SettingsDialog.cpp]: OSX doesn't support Vulkan.
Currently the windowing system support is missing for Xorg/Wayland in Vulkan backend. It can be fixed if someone can test it...

Comment (MyaniPT) [inline rpcs3/Gui/SettingsDialog.cpp]: @vlj What about Linux?

Comment (oscarbg) [inline rpcs3/Gui/SettingsDialog.cpp]: @vlj can test Vulkan Linux rpcs3 builds if needed on Intel GPU and Nvidia GPU..

**Comment by MyaniPT** [comment]
Rebased

File: rpcs3/Gui/SettingsDialog.cpp (hunk 1 above)
Comment (kd-11) [inline rpcs3/Gui/SettingsDialog.cpp]: Its not as simple as compiling and running on linux: one has to set up the X11 setup for vulkan. Its not much work, but it will not run out of the box just yet.

Comment (MyaniPT) [inline rpcs3/Gui/SettingsDialog.cpp]: Gotcha. I find it better to leave vulkan outside the MS check though if it's possible to use on linux, but I can throw it back in untill it runs OOFB

**Comment by kd-11** [comment]
Its much better now. If there are no regressions, it can be merged.

**Comment by MyaniPT** [comment]
I tested OpenGL here and it works, so there's no reason the others won't work. (I can't test booting a game in VK/DX12 as they're not supported in my laptop)

File: rpcs3/Gui/SettingsDialog.cpp [hunk 2]
```diff
@@ -503,7 +503,16 @@ SettingsDialog::SettingsDialog(wxWindow *parent, rpcs3::config_t* cfg)
 		cfg->core.hook_st_func = chbox_core_hook_stfunc->GetValue();
 		cfg->core.load_liblv2 = chbox_core_load_liblv2->GetValue();
 
-		cfg->rsx.renderer = cbox_gs_render->GetSelection();
+		// Translates renderer string to id for config.h
+		if (cbox_gs_render->GetString(cbox_gs_render->GetSelection()) == "Null")
```
Comment (kd-11) [inline rpcs3/Gui/SettingsDialog.cpp]: One small thing: could you just use the enum values instead of 0-1-2-3? Use rsx_renderer_type::DX12 or rsx::renderer_type::Vulkan instead for readability by future contributors.

**Comment by MyaniPT** [comment]
Done and rebased

File: rpcs3/Gui/SettingsDialog.cpp [hunk 3]
```diff
@@ -503,7 +503,16 @@ SettingsDialog::SettingsDialog(wxWindow *parent, rpcs3::config_t* cfg)
 		cfg->core.hook_st_func = chbox_core_hook_stfunc->GetValue();
 		cfg->core.load_liblv2 = chbox_core_load_liblv2->GetValue();
 
-		cfg->rsx.renderer = cbox_gs_render->GetSelection();
+		// Translates renderer string to enum class for config.h
```
Comment (MyaniPT) [inline rpcs3/Gui/SettingsDialog.cpp]: _(Just changed the comment in the latest rebase)_

**Comment by Blackbird88** [comment]
Thank you so much! I thought I was going crazy :D
