### PR TITLE
cellRec: fix width of encoder frames

### LINKED ISSUE #14466: [Regression] echochrome no longer playable
### Quick summary

echochrome used to be playable but is now crashing when pressing a button after level load 

### Details

I was able to get it working on versions before https://github.com/RPCS3/rpcs3/pull/12894 but it new versions crash when pressing buttons after a level has loaded 

### Build with regression

v0.0.25-14432-b0e376ae

### Attach two log files

[broken RPCS3.log.gz v0.0.25-14432-b0e376ae](https://github.com/RPCS3/rpcs3/files/12324501/RPCS3.log.gz)
[working RPCS3.log.gz v0.0.25-14425-1811dd67](https://github.com/RPCS3/rpcs3/files/12324552/RPCS3.log.gz)

### Attach capture files for visual issues

_No response_

### System configuration

Windows 10 Build: 19044
Intel 8700k
Nvidia GTX 1070 (driver 536.67.0.0)

### Other details

seems to be related to the video encoder

### PR DESCRIPTION
**Pull request by Megamouse**
Turns out the pitch was accidentally used as width, leading to an out of bounds read/write. I kept the pitch in the struct for completeness' sake. It may be needed later, if only for error checks.

This fixes echochrome, which seems to be using recordings for some gameplay reason.
I didn't really bother trying to figure out how the gameplay works though.

Fixes #14466

Proof of the recording saved to dev_hdd1 and then exported to dev_hdd0
image
image
image

### CODE REVIEW

File: rpcs3/Emu/Cell/Modules/cellRec.cpp [hunk 1]
```diff
@@ -587,7 +587,7 @@ void rec_info::start_image_provider()
 						{
 							std::vector<u8> frame(frame_size);
 							std::memcpy(frame.data(), video_input_buffer.get_ptr(), frame.size());
-							encoder->add_frame(frame, input_format.pitch, input_format.height, input_format.av_pixel_format, timestamp_ms);
+							encoder->add_frame(frame, input_format.pitch, input_format.width, input_format.height, input_format.av_pixel_format, timestamp_ms);
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellRec.cpp:590]: This is the only important line in this PR :)
