### PR TITLE
[Qt/Input] Improve pad_settings_dialog a bit

### LINKED ISSUE #3539: Analog Axis not working: Castlevania Lords of Shadow 2
In Castlevania Lords of Shadow 2 analog axis is not working and I can't walking in the game.
errorcontrol

### LINKED ISSUE #3616: Rumble not working (Xbox one controller)
Xbox one rumble not working (I think this is happening since the latest changes of controller management, one or two months ago, this option was in Config>Input/output)

Now the rumble´s got a very great lag, for example playing demon´s souls, if one monster hits my character, no rumble in that moment. But the rumble for that hit can appear 5 minutes after. This happens even if the emulator is closed. I played some other games, with no rumble, and 10 minutes after i close the emulator, the controller starts to rumble/receive the rumble data. 

Note: This happens in all games, and only with the xbox one controller. The xbox 360 controller works fine.

### PR DESCRIPTION
**Pull request by Megamouse**
- [x] Adds a simple timer and only saves to config on Save button from now on.
- [x] Add full Xinput remapping + rumble settings + deadzones
- [x] Add DS4 remapping (no touch sensors or gyro changed) + rumble settings + deadzones
- [x] Add evdev remapping + deadzones (no rumble yet)
- [x] Add mmjoy remapping + deadzones

fixes #3616 
fixes #3539
maybe #1283 
last point of #3181
some of #3027

### CODE REVIEW

**Comment by toccata10** [comment]
You've started a big and very welcome change. On archlinux, when I want to remap a button, it segfaults:
`Segfault reading location 0000000000000004 at 00007ffb05dfb057.`
Maybe not related, but I always wondered why rpcs3 didn't use sdl. Seems easier to manage all these different OS.

File: rpcs3/rpcs3qt/gamepads_settings_dialog.cpp [hunk 1]
```diff
@@ -16,6 +17,9 @@
 
 input_config input_cfg;
 
+inline std::string sstr(const QString& _in) { return _in.toUtf8().toStdString(); }
```
Comment (danilaml) [inline rpcs3/rpcs3qt/gamepads_settings_dialog.cpp]: I think I've mentioned it before, but `toUtf8()` is unnecessary since [according to the documentation](http://doc.qt.io/qt-5/qstring.html#toStdString) it calls it during `toStdString` anyway.

**Comment by MelchiorGaspar** [comment]
lol WELL its about time lol ;) :P 
I have a PSX to USB adapter (Radio Shack, early 2000s for WinXP) 
works fine in Windows 7.
 I use follows... as a reference for mapping...

PS1 Digital controller (ie. No Joysticks or rumble) = SNES & Genesis emu maps great..
and for SNES I use L2 for "Fast Forward" and R2 for SaveState-Saving
except for Higan I use,  F1 SaveState-Save and F4 SaveState-Load
and the same for BizHawk since it does PS1, SNES, Genesis, etc...

PS1 emu I use PS1 controller Digital or PS2 controller for games that want Joysticks (ie. Dual Shock 1)
PS2 controller for PCSX2 of course ;) :P 
for PS1 and PS2 they map as they should.. and F1 SaveState-Save and F3 SaveState-Load

and for RPCS3, all I can use is the PS2 controller till I can 
buy a DS4 and USB cable.. or a M$ Xbox360 Controller..


I hope that gives a kind of idea on controller mapping works..

as for as more reference to RPCS3 controller mapping
the [START] and select were getting auto mapped backwards for some reason in the first ingame fmv/intro of FF13 where I had to hit [SELECT] to bring up the pause instead of START 
and [START] to skip it instead of SELECT... as prompted on screen..
strange... mapping backwards..

and "some times" the up key on the dpad doesn't work either

**Comment by Megamouse** [comment]
you don't even state the handler you were using or if the buttons were working in the pad dialog.
I can't use that information at all :(

**Comment by MelchiorGaspar** [comment]
sorry I wasn't done yet.. I some times wander off or tangent.. lol ;-)

handler?
I just grabbed build (v0.0.3.6604) with this commit...
this is not working.. yet ;-)
I am using 
- [ MMJoystick = MMJoy pad ]
as my adapter is old so its.. DirectInput the old method..
Xinput won't work for this older adapter, I don't have a DS4..


As I said its not working, I tried to remap my controllers inputs onto the on screen mapping..
BUT.. it would auto assign a "U-" to each controller button..
ie it does not wait for any input...
XInput and DS4 will show a timer waiting for an input BUT do not react to any of my buttons on my controller..  xD


screenshot__rpcs3__dev-build v0 0 3 6604 mmjoystick remapping _not working _

**Comment by Megamouse** [comment]
you have to increase the deadzones or thresholds.
your controller sends small signals even if you don't move it. that's why the buttons are being mapped to the u- axis. when you increase the deadzone it will filter out these small movements.
You can see the received signals by enabling log level notice in the log section of rpcs3 (rightclick on the log to open the context menu).
I suspect you constantly have something like: "mmjoy button U- pressed with value: 5".

For now I have no plan for making the value visible in the gui. soyou have to adjust to these minor inconveniences

**Comment by Megamouse** [comment]
In case you don't want the deadzone working ingame you can first map all the buttons with the deadzone and then put the sliders to 0.
Then save and it should be fine

**Comment by MelchiorGaspar** [comment]
ahhh... strange.. 
I never had this issue with any other emulator.. not one...
- ZSNES, KegaFusion, ePSXe, PCSX2, Higan, BizHawk, PJ64, etc..

:P ;-) 
anyway... as my old PS2 DS2 died.. ie only one to three buttons were still working... at all..
SO I bought a brand new still in original Sony packaging PS2 DS2 off of eBay over the weekend and got it in the mail yesterday.

so "new" lol :P 

hmm.. I tried adjusting the deadzones that seemed to help for all but the JoyStick axis.. 
RPCS3 was not responding to or allowing mapping to those axis.. so I left them on there default value..
but the mappings of my PS2 controller did have different buttons #s from what is set as default..
lol ;-) XD

ps: the deadzone sliders could use some TOOL-TIP popups with more detailed info as to what they actually do... lol ;p  and.. its one thing considering the PS2 controller has only buttons and joy and no triggers...   with one set of deadzone sliders set to max.. the detected button went from..
Joy deadzones maxed but TRIGGER deadzones at 0 = Z+ (ie. R2 button)
TRIGGER deadzones maxed but JOY deadzones at 0 = U- (RIGHT-Joystick, left direction)

if all deadzones are maxed.. 
all buttons register.. 
EXCEPT the Joystick directions, 
MEH! xD


ps2:  off I see it now the U- is default for LEFT on the RIGHT-JOYSTICK...
strange it should be sending signals,, this a BRAND NEW controller so there isn't any worn-ness in any one direction for the joysticks.. strange...

Here are my mapping pics.. first mine and then the defaults for comparison..

**Comment by Megamouse** [comment]
can't handle every single controller.
my usb snes controller displays two simultanuous button presses for each shoulder button.

**Comment by Oky12** [comment]
screenshot 36

my twin usb gamepad. only detected one joystick gamepad. not two joystick gamepad

**Comment by Megamouse** [comment]
that is another issue and is not addressed in this Pull Request

**Comment by Oky12** [comment]
well i understand. I will wait for config button is enable. to set my controller key :D

File: rpcs3/evdev_joystick_handler.cpp [hunk 2]
```diff
@@ -251,98 +373,117 @@ std::vector<std::string> evdev_joystick_handler::ListDevices()
...
+{
+	// Now we need to find the device with the same name, and make sure not to grab any duplicates.
+	fs::dir devdir{ "/dev/input/" };
+	fs::dir_entry et;
+	while (devdir.read(et))
+	{
+		// Check if the entry starts with event (a 5-letter word)
+		if (et.name.size() > 5 && et.name.compare(0, 5, "event") == 0)
+		{
+			std::string path = "";
```
Comment (scribam) [inline rpcs3/evdev_joystick_handler.cpp]: Is it normal to have an empty value for the variable `path` considering its (unique) usage at the line 408?
`auto it = std::find_if(devices.begin(), devices.end(), [path](EvdevDevice device) { return path == device.path; });`

File: rpcs3/evdev_joystick_handler.cpp [hunk 3]
```diff
@@ -251,98 +373,117 @@ std::vector<std::string> evdev_joystick_handler::ListDevices()
...
+			const std::string name = libevdev_get_name(dev);
+			if (libevdev_has_event_type(dev, EV_KEY) &&
+				libevdev_has_event_code(dev, EV_ABS, ABS_X) &&
+				libevdev_has_event_code(dev, EV_ABS, ABS_Y) &&
+				name == device)
+			{
+				// It's a joystick.
+
+				// Now let's make sure we don't already have this one.
+				auto it = std::find_if(devices.begin(), devices.end(), [path](EvdevDevice device) { return path == device.path; });
```
Comment (danilaml) [inline rpcs3/evdev_joystick_handler.cpp]: shouldn't it be `[&path](const EvdevDevice &device)`. No reason to copy strings around.

File: rpcs3/evdev_joystick_handler.cpp [hunk 4]
```diff
@@ -251,98 +373,117 @@ std::vector<std::string> evdev_joystick_handler::ListDevices()
...
+        pad->m_buttons.emplace_back(CELL_PAD_BTN_OFFSET_DIGITAL1, find_key(m_pad_config.select),   CELL_PAD_CTRL_SELECT);
+        pad->m_buttons.emplace_back(CELL_PAD_BTN_OFFSET_DIGITAL1, find_key(m_pad_config.l3),       CELL_PAD_CTRL_L3);
+        pad->m_buttons.emplace_back(CELL_PAD_BTN_OFFSET_DIGITAL1, find_key(m_pad_config.r3),       CELL_PAD_CTRL_R3);
+        pad->m_buttons.emplace_back(CELL_PAD_BTN_OFFSET_DIGITAL2, find_key(m_pad_config.ps),       0x100/*CELL_PAD_CTRL_PS*/);// TODO: PS button support
+				pad->m_buttons.emplace_back(CELL_PAD_BTN_OFFSET_DIGITAL2, 0, 0x0); // Reserved
+        pad->m_buttons.emplace_back(CELL_PAD_BTN_OFFSET_DIGITAL1, find_key(m_pad_config.up),       CELL_PAD_CTRL_UP);
+        pad->m_buttons.emplace_back(CELL_PAD_BTN_OFFSET_DIGITAL1, find_key(m_pad_config.down),     CELL_PAD_CTRL_DOWN);
+        pad->m_buttons.emplace_back(CELL_PAD_BTN_OFFSET_DIGITAL1, find_key(m_pad_config.left),     CELL_PAD_CTRL_LEFT);
+        pad->m_buttons.emplace_back(CELL_PAD_BTN_OFFSET_DIGITAL1, find_key(m_pad_config.right),    CELL_PAD_CTRL_RIGHT);
```
Comment (danilaml) [inline rpcs3/evdev_joystick_handler.cpp]: Messed up indentation

File: rpcs3/evdev_joystick_handler.cpp [hunk 5]
```diff
@@ -251,98 +373,117 @@ std::vector<std::string> evdev_joystick_handler::ListDevices()
...
-                    }
-
-                    // Alright, now that we've confirmed we haven't added this joystick yet, les do dis.
-                    joy_paths.emplace_back(fmt::format("/dev/input/%s", et.name));
-                }
-                libevdev_free(dev);
-                close(fd);
-            }
-        }
+				auto find_key = [=](const std::string& name)
```
Comment (danilaml) [inline rpcs3/evdev_joystick_handler.cpp]: Why capture by `value/copy`? `button_list`, `axis_list` and `rev_axis_list` are rather big maps. Capture by reference `[&]`, maybe list all captured entities explicitly.

File: rpcs3/rpcs3qt/gamepads_settings_dialog.cpp [hunk 6]
```diff
@@ -154,17 +126,38 @@ gamepads_settings_dialog::gamepads_settings_dialog(QWidget* parent)
...
+			// Device will be empty on some rare occasions, so fill them by force
+			ChangeInputType(i);
+		}
+	};
 
 	for (int i = 0; i < MAX_PLAYERS; i++)
 	{
 		connect(co_inputtype[i], &QComboBox::currentTextChanged, [=] { ChangeInputType(i); });
-		connect(co_deviceID[i], &QComboBox::currentTextChanged, [=] { ChangeDevice(i); });
+		connect(co_deviceID[i], &QComboBox::currentTextChanged, [=](const QString& dev)
```
Comment (danilaml) [inline rpcs3/rpcs3qt/gamepads_settings_dialog.cpp]: IMHO, it's better to be epxlicit, when capturing, especially when the capture list is small. It's easier to spot bug this way (when something is captured by value, when it should be by reference or vice-versa). Most (if not all) of this `[=]` connect captures can be changed to just `[i]`, `[this]` or `[this, i]`.

File: rpcs3/evdev_joystick_handler.cpp [hunk 7]
```diff
@@ -372,200 +513,79 @@ void evdev_joystick_handler::ThreadProc()
...
-                else
-                    pad->m_sticks[axis].m_value = scale_axis(evt.code, value);
-            }
-            break;
-        }
-        default:
-            LOG_ERROR(GENERAL, "Unknown joystick #%d event %d", i, evt.type);
-            break;
-        }
+				bool is_negative;
```
Comment (danilaml) [inline rpcs3/evdev_joystick_handler.cpp]: Something is wrong with indentation in this file.

File: rpcs3/keyboard_pad_handler.cpp [hunk 8]
```diff
@@ -174,42 +195,119 @@ std::vector<std::string> keyboard_pad_handler::ListDevices()
 	return list_devices;
 }
 
+const std::string keyboard_pad_handler::GetKeyName(const QKeyEvent* keyEvent)
```
Comment (danilaml) [inline rpcs3/keyboard_pad_handler.cpp]: returning `const` primitive values (`u32`, `double` and etc.) doesn't make any difference and returning `const std::string` might even make code slower. See this [SO question](https://stackoverflow.com/questions/8716330/purpose-of-returning-by-const-value).

File: rpcs3/rpcs3qt/gamepads_settings_dialog.cpp (hunk 6 above)
Comment (Megamouse) [reply rpcs3/rpcs3qt/gamepads_settings_dialog.cpp]: I'm doing this specifically because I had bugs before that, in the end, were caused by such things.
So I'd prefer to leave it as is right now.
Feel free to change these things in a follow up PR if you don't mind. I am tired of testing the code for every minute change.

Comment (danilaml) [reply rpcs3/rpcs3qt/gamepads_settings_dialog.cpp]: Because you probably connected to lambda that captured locals by reference. Or you forgot to add context parameter (to the connect), so the lambda-slot was called even after the associated object was destroyed (though in that case it'd still crash in most cases). Doesn't matter though.

Comment (Megamouse) [reply rpcs3/rpcs3qt/gamepads_settings_dialog.cpp]: yeah I had all of these at least once. And I also had a very weird follow up error that took me forever to backtrack until I ended up at some lambda with wrong capture hehe. Therefore I go the safe route first before I end up chasing ghosts.

**Comment by toccata10** [comment]
On Archlinux, no more segfault, but when I click on a button, it displays LZ+ instead of going to record (or listening) mode.
configure evdev_033

**Comment by Megamouse** [comment]
@toccata10 I know. the sticks are the only thing left that's bugged.
Buttons and triggers would be fine if the sticks wouldn't interfere.

**Comment by Megamouse** [comment]
Only sticks in evdev are bugged now guys.
Maybe someone can try to find a clue?
I'm on it as well, no rest for the wicked!

**Comment by Megamouse** [comment]
Okay I pushed the fix for ingame.
Only question is if I have to commit a small rewrite for the GetNextButtonPress Section.
(I'm certain I have to)
Need to rebase and format it first

**Comment by toccata10** [comment]
1st: thanks for your work on this subject. It'll be very useful (specially for custom sticks).
It's improving (used to just register a LZ+ with the dragonrise stick).
I try to give you a detailled feedback of my tests:

Test n°1:
xbox360 controller
I clicked on the different gui buttons to register the correct input.
1st thing: for the dpad and the buttons, the countdown stops instantly when I press.
For the analog inputs, it continues to countdown (maybe 2 more seconds) and finally registers the input.

Here's the result:
evdev-xbox-correct-but-non-working-01
I launch Gamepad test:
everything is allright excepted:
left analog stick: when I press right, it goes left (and left gives right). Up and down are not registered at all.
right analog: left and right are correct, but no up & down

Test n°2:
xbox360 controller
When recording the inputs, I swap right and left for the analog sticks:
evdev-xbox-working-01
Everything works fine: up, down, left, right: all is ok.

Test n°3:
DragonRise Inc. Generic USB Joystick (board to create custom sticks)
It's much more difficult to register the inputs: when I press a gui button, it instantly registers the last action (ex: LY+). I've got to repress several times (or wait a few seconds).
Finally, I painfully made it register these inputs:
evdev-dragonrise-correct-01

I launch Gamepad test:
everything is allright excepted:
left analog stick: when I press right, it goes left (and left gives right). Up and down are ok. But if I press up, it goes up a bit, then fully (at 0.5s). If I have a little deadzone, it's 1st a big move, then it goes a bit further. If I have a big deadzone, it's 1st a little move, then it moves to the maximum.

Test n°4:
DragonRise Inc. Generic USB Joystick
I tried to swap left and right.
evdev-dragonrise-reversed-01
left analog stick: when I press right, it goes right (fine!). Up & down are not registered. Deadzone calculation is still not instantly.

**Comment by Megamouse** [comment]
For now the button mapping in evdev is still a bit laggy for the sticks.
We decided to keep it that way for now, since it presents an improvement to not having the option at all.
If it doesn't work you can still manually enter the buttons in the yml like before.
And since you are able to remap the default left and right should not be of big concern (also it was decided by hcorion and I , since our controller seem fine with those defaults)

Maybe in future PRs people can change the defaults depending on detected controller type.

The not working y axis is quite troublesome, but I can't reproduce with my own xbox 360 controller.
And Deadzone should be okay as well, albeit not yet perfectly displayed or handled

File: rpcs3/evdev_joystick_handler.cpp [hunk 9]
```diff
@@ -13,560 +17,756 @@
...
+		pad->m_sticks[1].m_value = (ly + pad->m_sticks[1].m_value) / 2; // LY
+		pad->m_sticks[2].m_value = (rx + pad->m_sticks[2].m_value) / 2; // RX
+		pad->m_sticks[3].m_value = (ry + pad->m_sticks[3].m_value) / 2; // RY
+	}
 }
 
+// Search axis_orientations map for the direction by index, returns -1 if not found, 0 for positive and 1 for negative
+int evdev_joystick_handler::FindAxisDirection(std::unordered_map<int, bool> map, int index)
+{
+	for (auto it = map.begin(); it != map.end(); ++it)
```
Comment (scribam) [inline rpcs3/evdev_joystick_handler.cpp]: What about using the method `find` in this case ?

File: rpcs3/mm_joystick_handler.h [hunk 10]
```diff
@@ -5,53 +5,87 @@
...
-	//cfg::int32 right{this, "Right", 316};
-	//cfg::int32 up{this, "Up", 315};
-	cfg::int32 r1{this, "R1", JOY_BUTTON8};
-	cfg::int32 r2{this, "R2", JOY_BUTTON6};
-	cfg::int32 r3{this, "R3", JOY_BUTTON12};
-	cfg::int32 l1{this, "L1", JOY_BUTTON7};
-	cfg::int32 l2{this, "L2", JOY_BUTTON5};
-	cfg::int32 l3{this, "L3", JOY_BUTTON11};
+	// Unique names for the config files and our pad settings dialog
+	const std::unordered_map<u64, std::string> button_list =
```
Comment (scribam) [inline rpcs3/mm_joystick_handler.h]: Is there a reason to use an `u64` instead of an `u32` as key like in the others handlers?

File: rpcs3/evdev_joystick_handler.cpp [hunk 11]
```diff
@@ -13,560 +17,756 @@
...
-evdev_joystick_handler::evdev_joystick_handler() {}
+evdev_joystick_handler::evdev_joystick_handler()
+{
+	// Define border values
+	THUMB_MIN = 0;
+	THUMB_MAX = 255;
+	TRIGGER_MIN = 0;
+	TRIGGER_MAX = 255;
+	VIBRATION_MIN = 0;
+	VIBRATION_MAX = 65535;
```
[the remark this answers is not in the document]
Comment (Megamouse) [reply rpcs3/evdev_joystick_handler.cpp]: I used the values defined by documentations and tutorials and I think it is more understandable seeing real numbers. (I don't really know if the vibration max is correct since I didn't implement evdev haptics)

File: rpcs3/evdev_joystick_handler.cpp [hunk 12]
```diff
@@ -13,560 +17,756 @@
...
+	{
+		LOG_ERROR(GENERAL, "Failed to initialize libevdev for joystick: %s [errno %d]", strerror(-ret), -ret);
+		return false;
+	}
+
+	LOG_NOTICE(GENERAL, "Opened joystick: '%s' at %s (fd %d)", libevdev_get_name(dev), path, fd);
+
+	if (use_cell)
+	{
+		if (!was_connected)
```
[the remark this answers is not in the document]
Comment (Megamouse) [reply rpcs3/evdev_joystick_handler.cpp]: I copy pasta'd that part so feel free to change it once it's submitted

[the remark this answers is not in the document]
Comment (Megamouse) [reply rpcs3/evdev_joystick_handler.cpp]: nevermind. I'll do it

File: rpcs3/evdev_joystick_handler.cpp [hunk 13]
```diff
@@ -13,560 +17,756 @@
...
-    const int newX = Clamp0To255(((newLen * std::cos(angle)) + 1) * 127);
-    const int newY = Clamp0To255(((newLen * std::sin(angle)) + 1) * 127);
-    return std::tuple<u16, u16>(newX, newY);
+std::unordered_map<u64, std::pair<u16, bool>> evdev_joystick_handler::GetButtonValues(libevdev* dev)
+{
+	std::unordered_map<u64, std::pair<u16, bool>> button_values;
+
+	for (auto entry : button_list)
+	{
+		int code = entry.first;
```
[the remark this answers is not in the document]
Comment (Megamouse) [reply rpcs3/evdev_joystick_handler.cpp]: sure, I coded evdev completely on visual studio, so I didn't know the exact types

[the remark this answers is not in the document]
Comment (Megamouse) [reply rpcs3/evdev_joystick_handler.cpp]: I'll use auto

File: rpcs3/mm_joystick_handler.h (hunk 10 above)
Comment (Megamouse) [reply rpcs3/mm_joystick_handler.h]: I think the defined values are longs

File: rpcs3/evdev_joystick_handler.cpp [hunk 14]
```diff
@@ -13,560 +17,755 @@
...
+		int button_code = GetButtonInfo(evt, dev, value, is_negative);
+		if (button_code < 0 || value < 0)
+			continue;
+
+		bool is_button_or_trigger = evt.type == EV_KEY || button_code == ABS_Z || button_code == ABS_RZ;
+
+		// Translate any corresponding keycodes to our normal DS3 buttons and triggers
+		for (int i = 0; i < static_cast<int>(pad->m_buttons.size()); i++)
+		{
+			if (pad->m_buttons[i].m_keyCode != button_code)
```
Comment (toccata10) [inline rpcs3/evdev_joystick_handler.cpp]: this seems problematic to me: pad->m_buttons[17].m_keyCode has a value of 0. So if I press on the ABS_Y (value of 1), it never gets to the line 656. If I press ABS_X (value 0), it enters the condition on line 656.

File: rpcs3/evdev_joystick_handler.cpp [hunk 15]
```diff
@@ -13,560 +17,755 @@
...
+		// Translate any corresponding keycodes to our two sticks. (ignoring thresholds for now)
+		for (int idx = 0; idx < static_cast<int>(pad->m_sticks.size()); idx++)
+		{
+			bool pressed_min = false, pressed_max = false;
+			u16 val_min = 0, val_max = 0;
+
+			// m_keyCodeMin is the mapped key for left or down
+			if (pad->m_sticks[idx].m_keyCodeMin == button_code)
+			{
+				bool is_direction_min = false;
```
Comment (toccata10) [inline rpcs3/evdev_joystick_handler.cpp]: With this:
Left Stick Left: LY+
Left Stick Down: LX-
Left Stick Right: LY-
Left Stick Up: LX+
My device.stick_val[idx] is always 0 on the up-down axis (x-y axis goes from -255 to +255)
With this:
Left Stick Left: LY-
Left Stick Down: LX-
Left Stick Right: LY+
Left Stick Up: LX+
My device.stick_val[idx] moves from -255 to +255 on the up-down axis (x-y axis ok).

Comment (Megamouse) [reply rpcs3/evdev_joystick_handler.cpp]: should be okay now

File: rpcs3/mm_joystick_handler.h (hunk 10 above)
Comment (scribam) [reply rpcs3/mm_joystick_handler.h]: ok thanks for the info

File: rpcs3/evdev_joystick_handler.cpp (hunk 11 above)
[the remark this answers is not in the document]
Comment (scribam) [reply rpcs3/evdev_joystick_handler.cpp]: ok

File: rpcs3/Emu/Io/PadHandler.h [hunk 16]
```diff
@@ -238,23 +248,277 @@ struct Pad
...
+		{
+			if (it->second == name) return it->first;
+		}
+		return -1;
+	};
+	int FindKeyCode(std::unordered_map<u64, std::string> map, const std::string& name)
+	{
+		for (auto it = map.begin(); it != map.end(); ++it)
+		{
+			if (it->second == name) return it->first;
```
Comment (scribam) [inline rpcs3/Emu/Io/PadHandler.h]: In this case, `it->first` is an `u64`. Would it be ok to return an `u64` (64 bits) whereas the return type of this method is an `int` (32 bits)?

File: rpcs3/evdev_joystick_handler.cpp (hunk 15 above)
Comment (toccata10) [reply rpcs3/evdev_joystick_handler.cpp]: ok. With this change, I always get a signal now. It's still a bit buggy (I have to manually edit the config file to have the correct movements and, with my custom stick, when I move to the right, it registers 1st a small move to the right, then a big move). Now, nothing is a stopper for me anymore. So, if you want to merge, that's fine with me. We can improve this with investigation and subsequent PR. In the present state, it's certainly already a nice improvement to the existing situation.

Comment (Megamouse) [reply rpcs3/evdev_joystick_handler.cpp]: try again. I fixed the lag in the dialog

File: rpcs3/Emu/Io/PadHandler.h (hunk 16 above)
Comment (Megamouse) [reply rpcs3/Emu/Io/PadHandler.h]: would long be the correct value here?

Comment (Megamouse) [reply rpcs3/Emu/Io/PadHandler.h]: but Button has u32 as keycode....
no idea. I' haven't noticed any drawback with normal controllers yet

Comment (Megamouse) [reply rpcs3/Emu/Io/PadHandler.h]: xbox controller works fine at least.

File: rpcs3/evdev_joystick_handler.cpp [hunk 17]
```diff
@@ -13,560 +17,697 @@
...
+	VIBRATION_MIN = 0;
+	VIBRATION_MAX = 65535;
+
+	// Set this handler's type and save location
+	m_pad_config.cfg_type = "evdev";
+	m_pad_config.cfg_name = fs::get_config_dir() + "/config_evdev.yml";
+
+	// Set default button mapping
+	m_pad_config.ls_left.def  = rev_axis_list.at(ABS_X);
+	m_pad_config.ls_down.def  = rev_axis_list.at(ABS_Y);
```
Comment (toccata10) [inline rpcs3/evdev_joystick_handler.cpp]: `m_pad_config.ls_down.def  = axis_list.at(ABS_Y);`

File: rpcs3/evdev_joystick_handler.cpp [hunk 18]
```diff
@@ -13,560 +17,697 @@
...
+	m_pad_config.ls_right.def = axis_list.at(ABS_X);
+	m_pad_config.ls_up.def    = axis_list.at(ABS_Y);
```
Comment (toccata10) [inline rpcs3/evdev_joystick_handler.cpp]: `m_pad_config.ls_up.def    = rev_axis_list.at(ABS_Y);`

File: rpcs3/evdev_joystick_handler.cpp [hunk 19]
```diff
@@ -13,560 +17,697 @@
...
+				{
+					int index = BUTTON_COUNT + (idx * 2) + 1;
+					int max_direction = FindAxisDirection(axis_orientations, index);
+					if (max_direction < 0)
+					{
+						LOG_ERROR(HLE, "keyCodeMax FindAxisDirection = %d, Axis Nr.%d, Button Nr.%d, value = %d", max_direction, idx, index, value);
+					}
+					else
+					{
+						is_direction_max = is_negative == (max_direction == 1 ? true : false);
```
Comment (toccata10) [inline rpcs3/evdev_joystick_handler.cpp]: is_direction_max = is_negative == (max_direction == 1 ? false : true);

File: rpcs3/evdev_joystick_handler.cpp [hunk 20]
```diff
@@ -13,560 +17,697 @@
...
+				{
+					int index = BUTTON_COUNT + (idx * 2);
+					int min_direction = FindAxisDirection(axis_orientations, index);
+					if (min_direction < 0)
+					{
+						LOG_ERROR(HLE, "keyCodeMin FindAxisDirection = %d, Axis Nr.%d, Button Nr.%d, value = %d", min_direction, idx, index, value);
+					}
+					else
+					{
+						is_direction_min = is_negative == (min_direction == 1 ? true : false);
```
Comment (toccata10) [inline rpcs3/evdev_joystick_handler.cpp]: `is_direction_min = is_negative == (min_direction == 1 ? false : true);`

File: rpcs3/evdev_joystick_handler.cpp (hunk 19 above)
Comment (toccata10) [reply rpcs3/evdev_joystick_handler.cpp]: With these changes, it's completely coherent on my system: when I record an axis: it's correct. When I move my stick: it's correct.
If there's no config file, then my xbox 360 controller works fine with the default settings.

**Comment by toccata10** [comment]
With these changes, it behaves nicely.
The only remaining problem is with my custom stick. Here's its configuration
configure evdev_002
When I press a direction (ex: right), the system seems to register first a little movement, then a big one (it should always be a big one as it's an arcade stick with switches). I recorded my screen to show you (it's a mp4, I had to compress it to zip to be able to join it here).
[gamepad-dragonrise-01.zip](https://github.com/RPCS3/rpcs3/files/1464759/gamepad-dragonrise-01.zip)
With my xbox controller, it doesn't behave the same way: perfectly smooth.
[gamepad-xbox-02.zip](https://github.com/RPCS3/rpcs3/files/1464760/gamepad-xbox-02.zip)
I don't know why (of course), but I remember vaguely that they were different, like one of them was sending 0-255, the other one -32767 / +32767.

File: rpcs3/evdev_joystick_handler.cpp (hunk 20 above)
Comment (Megamouse) [reply rpcs3/evdev_joystick_handler.cpp]: what

File: rpcs3/evdev_joystick_handler.cpp [hunk 21]
```diff
@@ -13,560 +17,697 @@
...
+		{
+			std::tie(lx, ly) = ConvertToSquirclePoint(lx, ly, m_pad_config.padsquircling);
+			std::tie(rx, ry) = ConvertToSquirclePoint(rx, ry, m_pad_config.padsquircling);
+		}
+
+		pad->m_sticks[0].m_value = (lx + pad->m_sticks[0].m_value) / 2; // LX
+		pad->m_sticks[1].m_value = (ly + pad->m_sticks[1].m_value) / 2; // LY
+		pad->m_sticks[2].m_value = (rx + pad->m_sticks[2].m_value) / 2; // RX
+		pad->m_sticks[3].m_value = (ry + pad->m_sticks[3].m_value) / 2; // RY
+	}
```
Comment (toccata10) [inline rpcs3/evdev_joystick_handler.cpp]: That's the culprit for the delay. It's instant with:
```
pad->m_sticks[0].m_value = lx; // LX
pad->m_sticks[1].m_value = ly; // LY
pad->m_sticks[2].m_value = rx; // RX
pad->m_sticks[3].m_value = ry; // RY
```

File: rpcs3/evdev_joystick_handler.cpp (hunk 20 above)
Comment (Megamouse) [reply rpcs3/evdev_joystick_handler.cpp]: the code is correct. the issue you are referring to was a faulty index

File: rpcs3/evdev_joystick_handler.cpp (hunk 19 above)
Comment (Megamouse) [reply rpcs3/evdev_joystick_handler.cpp]: the code is correct. the issue you are referring to was a faulty index

**Comment by Megamouse** [comment]
should be fine now and defaults to xbox 360 controller on evdev.

File: rpcs3/evdev_joystick_handler.cpp (hunk 20 above)
Comment (danilaml) [reply rpcs3/evdev_joystick_handler.cpp]: Just a reminder that `(min_direction == 1 ? true : false)` is the same as `(min_direction == 1)`. Generally `boolexpr ? true : false` is redundant and can be replaced with just `boolexpr`.

**Comment by toccata10** [comment]
It's fine with the default xbox and it's fine when I remap with a custom stick. So everything is working on my side. Well done.
Now you can start working on choosing different profiles for the different controllers, saving/loading the profiles.... ;-)

**Comment by Megamouse** [comment]
that would need some neko yml magic.

File: rpcs3/evdev_joystick_handler.cpp (hunk 20 above)
Comment (Megamouse) [reply rpcs3/evdev_joystick_handler.cpp]: Thx. I think i replaced it with sth and this was the result.
Jarves had a similar case earlier. It's funny how sometimes our brains play tricks with us

**Comment by toccata10** [comment]
Suggestion: when recording input, discard anything (at least any analog entry) that is below 0.5*maximum_range: when remapping my xbox controller, I had trouble registering the correct axis because it's difficult to be perfectly on the y axis. So I had to do it several times because it was registering the small signal from x axis.

**Comment by Megamouse** [comment]
after deadzone preview was implemented.
until then it will be tied to deadzone directly

**Comment by Megamouse** [comment]
actually I think you're right and Jarves had the same opinion.
people are gonna complain because they'll have problems just like you.
better have the deadzone not interactive until the preview is there.
the only thing that can happen then is that someone opens an issue about no preview instead of hundreds of people asking for advice

**Comment by toccata10** [comment]
I was wondering if you intended to still improve this pr (which is in a nice state already) or just waiting for a merge.

**Comment by Megamouse** [comment]
after this commit I'm just waiting

**Comment by raveskirza** [comment]
With the PR Build. The non-alphabet keys are shown as numbers
image

Master
image

**Comment by Megamouse** [comment]
restore defaults

**Comment by ps2player** [comment]
PS2 controller not working in this build . but it's works on 0.0.4-7049
