### PR TITLE
sys: Fix hdd game dir name

### LINKED ISSUE #14954: Some PS3 apps crash on boot because RPCS3 expects different folder naming
### Quick summary

Many PS3 apps would use the same id for a different release of the app. For example Uncharted Eye of Indra would use the same id for all 4 episodes and even the bundle, so instead of being installed to NPUA80234 folder they would be installed to folders like NPUA80234_UNCHARTED2EOI002 NPUA80234_UNCHARTED2EOIALL. RPCS3 doesn't like that since it expects just game id folder

### Details

_No response_

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/13789594/RPCS3.log)

### Attach capture files for visual issues

_No response_

### System configuration

_No response_

### Other details

_No response_

### PR DESCRIPTION
**Pull request by Megamouse**
Some games are installed with other dir names than title id.
- Use the actual directory name instead of clamping it to 9 characters.
- Pass the actual directory name in cellGameBootCheck.

fixes #14954

### CODE REVIEW

File: rpcs3/Emu/System.cpp [hunk 1]
```diff
@@ -2113,15 +2113,30 @@ game_boot_result Emulator::Load(const std::string& title_id, bool is_disc_patch,
...
+					const std::string tail = resolved_path.substr(resolved_hdd0.size());
+					const std::string tail_usrdir = tail.substr(tail.find_first_of(fs::delim) + 1);
+					const std::string dirname = tail.substr(0, tail.find_first_of(fs::delim));
+					argv[0] = "/dev_bdvd/PS3_GAME/" + unescape(tail_usrdir);
+					m_dir = "/dev_hdd0/game/" + dirname + "/";
 					sys_log.notice("Disc path: %s", m_dir);
+
+					if (dirname != m_title_id)
+					{
+						vfs::mount("/dev_hdd0/game/" + m_title_id, vfs::get("/dev_hdd0/game/" + dirname));
```
Comment (elad335) [inline rpcs3/Emu/System.cpp:2125]: This cant be correct

Comment (elad335) [reply rpcs3/Emu/System.cpp:2125]: Do you have proof that the paths in the game are hardcoded to title_id?

Comment (Megamouse) [reply rpcs3/Emu/System.cpp]: No. but I found the real issue.

Comment (brian218) [reply rpcs3/Emu/System.cpp]: > Do you have proof that the paths in the game are hardcoded to title_id?

Yes, tons of totally different SCEEXE000 games did hardcode the `/dev_hdd0/game/title_id` path.
Image

This PR *was* very helpful for the scenario in which you have tons of such games.

**Comment by FlexBy420** [comment]
Tested some of the apps and they don't crash anymore
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13792917/RPCS3.log.gz)

File: rpcs3/Emu/Cell/Modules/cellGame.cpp [hunk 2]
```diff
@@ -746,7 +746,10 @@ error_code cellGameBootCheck(vm::ptr<u32> type, vm::ptr<u32> attributes, vm::ptr
 		*attributes = 0; // TODO
 
 		sfo = psf::load_object(vfs::get(Emu.GetDir() + "PARAM.SFO"));
-		dir = Emu.GetTitleID();
+
+		const std::vector<std::string> dirs = fmt::split(Emu.GetDir(), {std::string_view{&fs::delim[0], 1}, std::string_view{&fs::delim[1], 1}});
```
[the remark this answers is not in the document]
Comment (Megamouse) [reply rpcs3/Emu/Cell/Modules/cellGame.cpp]: fixed

**Review by elad335 — APPROVED** [review]

File: rpcs3/Emu/Cell/Modules/cellGame.cpp [hunk 3]
```diff
@@ -763,7 +763,8 @@ error_code cellGameBootCheck(vm::ptr<u32> type, vm::ptr<u32> attributes, vm::ptr
 
 	if (_type == u32{CELL_GAME_GAMETYPE_HDD} && dirName)
 	{
-		strcpy_trunc(*dirName, Emu.GetTitleID());
+		ensure(dir.size() < CELL_GAME_DIRNAME_SIZE);
```
Comment (elad335) [inline rpcs3/Emu/Cell/Modules/cellGame.cpp:766]: We may need to demand it when booting games or going through HDD0/game directories when enumerating for game list.

Comment (Megamouse) [reply rpcs3/Emu/Cell/Modules/cellGame.cpp:766]: There is no evidence that any game even triggers this ensure.
I refuse to spend even a second on this.
"if it ain't broke, don't fix it"
