### PR TITLE
SaveStates: Fix Gem Thread Reboot

### LINKED ISSUE #17569: Save State Crashing
### Quick summary

Save states

### Details

when I have mouse or raw mouse selected for the move handler and try to create or load a save state it will cause the emulator to crash. 

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/22858759/RPCS3.log.gz)

### Attach capture files for visual issues

_No response_

### System configuration

Windows 11
AMD Ryzen 9 5900X
NVidia RTX 4080
32GB Ram

### Other details

_No response_

### PR DESCRIPTION
**Pull request by elad335**
Fixes #17569

### CODE REVIEW

File: rpcs3/Emu/Cell/Modules/cellGem.cpp [hunk 1]
```diff
@@ -361,7 +361,7 @@ struct gem_config_data
 		case move_handler::mouse:
 		case move_handler::raw_mouse:
 		{
-			auto& handler = g_fxo->get<MouseHandlerBase>();
+			auto& handler = *ensure(g_fxo->try_get<MouseHandlerBase>());
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellGem.cpp:364]: I thought threads are started after all objects were initialized

Comment (elad335) [reply rpcs3/Emu/Cell/Modules/cellGem.cpp:364]: Yes but not for these manually created ones. I'll add a global solution.
