### PR TITLE
rsx: Improve NV308A_COLOR

### LINKED ISSUE #3493: Rendering errors on Dragon Ball Raging Blast 2 Demo [NPEB90287]
If you play game for the first time as (goku super sayan or Dabura) it will throw many unknow command errors and there will be many graphical glitches (especially on goku) for example:
obraz
Log+shaders cache+shaders log:
[Dragon Ball Raging Blast 2 Demo Schaders+Logs.zip](https://github.com/RPCS3/rpcs3/files/1326647/Dragon.Ball.Raging.Blast.2.Demo.Schaders.Logs.zip)
Also if you try to reload it will trow many other RSX errors (this log)[it crashed before going into game]:
[Dragon Ball Raging Blast 2 Demo.zip](https://github.com/RPCS3/rpcs3/files/1326626/Dragon.Ball.Raging.Blast.2.Demo.zip)
My CPU is Intel(R) Core(TM) i5-2300 CPU 
@ 2.80GHz. 
RAM:4GB 
GPU: ASUS NVIDIA GT440 1GB GDDR3 OpenGL
Edit: Dabura has more interesting error: RSX: Texture unit 3 is sampled as both a shadow texture and a depth texture
Dabura Log:[Dragon Ball Raging Blast 2 Demo Dabura Schaders.zip](https://github.com/RPCS3/rpcs3/files/1326661/Dragon.Ball.Raging.Blast.2.Demo.Dabura.Schaders.zip)
P.S. If something else is needed tell me.

### LINKED ISSUE #6803: Dragon Ball Raging Blast 2 crashes more frequently after #6737
On 0.0.7-8855 and newer, Dragon Ball Raging Blast 2 crashes when trying to load some characters with graphical glitches (Vegeta (Scouter) consistently causes crashes). This happens regardless of what settings I apply, I tested various versions between 0.0.7-8850 and 0.0.7-9122. Before testing each version I did clear caches.

If I need to add any more details, please let me know. 
[RPCS3 0.0.7-9035.log.gz](https://github.com/RPCS3/rpcs3/files/3781350/RPCS3.0.0.7-9035.log.gz)
[RPCS3 0.0.7-8852.log.gz](https://github.com/RPCS3/rpcs3/files/3746101/RPCS3.0.0.7-8852.log.gz)

### PR DESCRIPTION
**Pull request by elad335**
* Fix NV308A_COLOR methods range.
* Batch NV308A_COLOR methods execution together (optimization).
* Fix termination of bind_range<> in rsx methods binding.
* Reset all method registers at each boot. 

Fixes #6803
Fixes #3493

### CODE REVIEW

**Comment by kd-11** [comment]
Obviously we'll need proof that these actually run on CEX. We already know for certain they crash DEX for example, and the chances that a commercial game exists that runs on CEX but crashes on DEX are highly unlikely.

File: rpcs3/Emu/RSX/rsx_methods.cpp [hunk 1]
```diff
@@ -39,10 +39,19 @@ namespace rsx
 	{
 		//Don't throw, gather information and ignore broken/garbage commands
 		//TODO: Investigate why these commands are executed at all. (Heap corruption? Alignment padding?)
+		rsx->invalid_command_interrupt_raised |= !(_reg >= 0xac80 >> 2 && _reg < 0xb000 >> 2); // HACK: Allow these "unknown" methods
+ 
 		const u32 cmd = rsx->get_fifo_cmd();
-		rsx_log.error("Invalid RSX method 0x%x (arg=0x%x, start=0x%x, count=0x%x, non-inc=%s)", _reg << 2, arg,
-		cmd & 0xfffc, (cmd >> 18) & 0x7ff, !!(cmd & RSX_METHOD_NON_INCREMENT_CMD));
-		rsx->invalid_command_interrupt_raised = true;
+		if (rsx->invalid_command_interrupt_raised || _reg == 0xac80 >> 2)
```
Comment (kd-11) [inline rpcs3/Emu/RSX/rsx_methods.cpp]: Why are you only checking for ac80?

Comment (elad335) [reply rpcs3/Emu/RSX/rsx_methods.cpp]: Avoiding log spam, I will add a better solution for here that logs once the first invalid method from all this range even if it wasn't ac80.

File: rpcs3/Emu/RSX/rsx_methods.cpp [hunk 2]
```diff
@@ -39,10 +39,19 @@ namespace rsx
 	{
 		//Don't throw, gather information and ignore broken/garbage commands
 		//TODO: Investigate why these commands are executed at all. (Heap corruption? Alignment padding?)
+		rsx->invalid_command_interrupt_raised |= !(_reg >= 0xac80 >> 2 && _reg < 0xb000 >> 2); // HACK: Allow these "unknown" methods
```
Comment (kd-11) [inline rpcs3/Emu/RSX/rsx_methods.cpp]: This is messy. Just use a simple if...else.
if (in_range) log_trace;
else raise_flag + log error.

Comment (elad335) [reply rpcs3/Emu/RSX/rsx_methods.cpp]: error logging still occurs for this range, which is why I didn't op for this soluition

**Comment by Emulator-Team-2** [comment]
These games still crashing:
-Flock! crashes after the start the game.
-Dragon Ball Z Ultimate Tenkaichi crashes before the title screen.

```
[Flock!]

E {RSX [0x7902740]} RSX: Invalid RSX method 0xb000 (arg=0x0, start=0xa400, count=0x380, non-inc=false) x4792
```

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4374990/RPCS3.log.gz)

```
[Dragon Ball Z Ultimate Tenkaichi]

E {RSX [0x001267c]} RSX: Invalid RSX method 0xb000 (arg=0xe810240, start=0xa400, count=0x304, non-inc=false) x5042
```
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4374991/RPCS3.log.gz)

**Comment by elad335** [comment]
@Emulator-Team-2 Retest.

**Comment by Emulator-Team-2** [comment]
The latest commit fixes this issue.

**Comment by StevenMiller123** [comment]
This also fixes the crashing in J Stars.

**Comment by kd-11** [comment]
Can we get this properly tested on CFW? I'm not in love with the idea of going back to adding hacks just to make crashes go away. We had a testcase for this in the past, maybe we can get assistance testing it on discord.

**Comment by elad335** [comment]
Please retest all your games which were affected by this pr.

**Comment by Emulator-Team-2** [comment]
@elad335
@kd-11 
@StevenMiller123 
Build: https://github.com/RPCS3/rpcs3/pull/7846/commits/392847b04eb68e9944ae6cc58b4e545fdf64ba11
The latest build fixes broken and missing textures in:  

[Dragon Ball Z Ultimate Tenkaichi]
DBZ

[Dragon Ball: Raging Blast 1]
DBR1

[Dragon Ball: Raging Blast 2]
DBR2

[J-Stars Victory VS]
J

File: rpcs3/Emu/RSX/rsx_methods.cpp [hunk 3]
```diff
@@ -819,36 +819,85 @@ namespace rsx
...
 				case blit_engine::transfer_destination_format::y32:
 				{
-					// Bit cast
+					// Bit cast - optimize to mem copy
+
+					const auto dst = vm::_ptr<u8>(get_address(dst_offset + (x * 4) + (out_pitch * y), dst_dma, HERE));
+					const auto src = vm::_ptr<const u8>(get_address(src_offset, CELL_GCM_LOCATION_MAIN, HERE));
+
+					const u32 data_length = count * 4;
+					const bool is_overlapping = (dst_dma & CELL_GCM_LOCATION_MAIN) && [&]() -> bool
```
Comment (kd-11) [inline rpcs3/Emu/RSX/rsx_methods.cpp]: std::memmove should already do all this for you. Just use memmove and simplify this logic.

File: rpcs3/Emu/RSX/rsx_methods.cpp [hunk 4]
```diff
@@ -819,36 +819,85 @@ namespace rsx
...
+
+					for (u32 i = 0; i < count; i++)
+					{
+						// Input is considered to be ARGB8
+						const u32 input = src[i];
+						u32 r = (input >> 16) & 0xFF;
+						u32 g = (input >> 8) & 0xFF;
+						u32 b = input & 0xFF;
+
+						r = ::rounded_div(r * 32, 255);
```
Comment (kd-11) [inline rpcs3/Emu/RSX/rsx_methods.cpp]: Nope, not rounded but truncated. This might seem minor but is actually very destructive for shader parameters.

File: rpcs3/Emu/RSX/rsx_methods.cpp [hunk 5]
```diff
@@ -2523,16 +2561,15 @@ namespace rsx
 		{
 			static inline void impl()
 			{
-				methods[Id] = &T<Index>::impl;
-				bind_range_impl_t<Id + Step, Step, Count, T, Index + 1>::impl();
-			}
-		};
+				if constexpr (Count > 0)
```
Comment (kd-11) [inline rpcs3/Emu/RSX/rsx_methods.cpp]: add static assert if count == 0 while you're at it

File: rpcs3/Emu/RSX/RSXThread.h [hunk 6]
```diff
@@ -720,7 +722,7 @@ namespace rsx
 		bool capture_current_frame = false;
 
 	public:
-		bool invalid_command_interrupt_raised = false;
+		u32 skip_methods_count = 0;
```
Comment (kd-11) [inline rpcs3/Emu/RSX/RSXThread.h]: This should have been a struct and avoided special codes like -1/umax. Improves readability.

File: rpcs3/Emu/RSX/rsx_methods.cpp (hunk 3 above)
Comment (elad335) [reply rpcs3/Emu/RSX/rsx_methods.cpp]: Notice this isn't a memmove equivalent - It's executing a mem copy in u32 unit specifically as previous logic.

Comment (elad335) [reply rpcs3/Emu/RSX/rsx_methods.cpp]: But if realhw is known to handle it similarly as a memmove then ok,

File: rpcs3/Emu/RSX/rsx_methods.cpp (hunk 4 above)
Comment (elad335) [reply rpcs3/Emu/RSX/rsx_methods.cpp]: hmm, it was rounded before because of float usage, was it wrong?

File: rpcs3/Emu/RSX/rsx_methods.cpp (hunk 5 above)
Comment (elad335) [reply rpcs3/Emu/RSX/rsx_methods.cpp]: Done, also added useful asserts about range of methods specified.

File: rpcs3/Emu/RSX/RSXThread.h (hunk 6 above)
Comment (elad335) [reply rpcs3/Emu/RSX/RSXThread.h]: Used rsx->fifo_ctrl->skip_methods() directly as now it is a public member.

File: rpcs3/Emu/RSX/rsx_methods.cpp (hunk 3 above)
Comment (kd-11) [reply rpcs3/Emu/RSX/rsx_methods.cpp]: 1. There is no logical difference between the two paths. You can just use memcpy for both.
2. This overlap is not a reasonable condition anyway. Nobody is scheduling inline transfers to destroy fifo that is actively being processed and expecting it to work.

The way I see it, pick one, memcpy or memmove and call it a day.

File: rpcs3/Emu/RSX/rsx_methods.cpp (hunk 4 above)
Comment (kd-11) [reply rpcs3/Emu/RSX/rsx_methods.cpp]: rsx thread should not be rounding on int conversion. If it was/is rounding up, that is wrong.

File: rpcs3/Emu/RSX/rsx_methods.cpp (hunk 3 above)
Comment (elad335) [reply rpcs3/Emu/RSX/rsx_methods.cpp]: Ok then, I only uses the destination location as a hint to choose between memcpy and memmove.

**Comment by Loja181** [comment]
Hello, I am new and I saw your contributions I am a newbie in this but could you help me how to solve the problem of textures in dragon ball blast 2 I have the same problem because I don't know how to solve it I need your help please I would appreciate it a lot!
