### PR TITLE
Texture Cache: Refactor Predictor + Fixups

### LINKED ISSUE #5180: Write Color Buffers regression caused by #5115
Since #5115 was merged, Motorstorm no longer goes ingame when using Write Color Buffers.

### PR DESCRIPTION
**Pull request by ruipin**
This PR contains a few bug fixes for the texture cache, both regressions from my previous PR #5115 as well as newly discovered bugs.

I have done some testing with these changes, but as always please test and report any issues/changes/improvements.

* Resolves some miscellaneous bugs/issues with texture flushing, mainly around WCB
* Properly destroys textures in the texture cache when they become released. Should avoid certain driver crashes and reduce VRAM usage/leaks - improves #5130 and #5180 
* Split off the texture cache predictor into a different class independent from the cached texture sections - improves #5182
* Improve the texture cache prediction algorithm. Should reduce the number of hard faults per frame, especially in WCB games, improving performance slightly
* Adds a strict flushing option to the yaml configuration that forces flushing of textures in some situations where this is not necessary/correct. Enabling this option will tank performance in WCB games and can cause visual artifacts, but can be useful to debug certain texture cache issues.
* Removed "TODO" log spam from #5115 about potentially lost data and incorrectly unprotected sections. (These have now been fixed)
* Refactors texture cache templated classes to use a `texture_cache_traits` structure instead of 6+ template parameters
* General texture cache optimizations

### CODE REVIEW

**Comment by elhaya** [comment]
heavy rain goes ingame, i am able to load my previous save file but then it gets stuck right after loading on 'compiling shaders'. no error in the console though

File: rpcs3/Emu/RSX/VK/VKTextureCache.h [hunk 1]
```diff
@@ -28,16 +43,17 @@ namespace vk
...
 		using baseclass::cached_texture_section;
 
-		void reset(const utils::address_range &memory_range)
-		{
-			if (memory_range.length() > get_section_size())
-				release_dma_resources();
-
-			baseclass::reset(memory_range);
-		}
+		//void reset(const utils::address_range &memory_range)
```
Comment (VelocityRa) [inline rpcs3/Emu/RSX/VK/VKTextureCache.h]: I'd leave a comment explaining commented code. Or is it left-overs maybe?

File: rpcs3/Emu/RSX/GL/GLTextureCache.h [hunk 2]
```diff
@@ -277,6 +291,7 @@ namespace gl
 					init_buffer();
 
 				aa_mode = static_cast<gl::render_target*>(image)->read_aa_mode;
+				ASSERT( managed_texture.get() == nullptr );
```
Comment (VelocityRa) [inline rpcs3/Emu/RSX/GL/GLTextureCache.h]: Why space it like that?
```suggestion
				ASSERT(managed_texture.get() == nullptr);
```

File: rpcs3/Emu/RSX/GL/GLTextureCache.h [hunk 3]
```diff
@@ -351,8 +368,15 @@ namespace gl
 			}
 		}
 
-		void copy_texture(bool=false)
+		void copy_texture(bool manage_lifetime)
 		{
+			ASSERT( exists() );
```
Comment (VelocityRa) [inline rpcs3/Emu/RSX/GL/GLTextureCache.h]:
```suggestion
			ASSERT(exists());
```

File: rpcs3/Emu/RSX/GL/GLTextureCache.h [hunk 4]
```diff
@@ -466,14 +490,16 @@ namespace gl
 
 		bool flush()
 		{
+			ASSERT( exists() );
```
Comment (VelocityRa) [inline rpcs3/Emu/RSX/GL/GLTextureCache.h]:
```suggestion
			ASSERT(exists());
```

File: rpcs3/Emu/RSX/GL/GLTextureCache.h [hunk 5]
```diff
@@ -253,18 +268,17 @@ namespace gl
...
 		using baseclass::cached_texture_section;
 
-		void reset(const utils::address_range &memory_range)
-		{
-			vram_texture = nullptr;
-			managed_texture.reset();
-
-			baseclass::reset(memory_range);
-		}
+		//void reset(const utils::address_range &memory_range)
```
Comment (VelocityRa) [inline rpcs3/Emu/RSX/GL/GLTextureCache.h]: ditto about commented code

File: rpcs3/Emu/RSX/Common/texture_cache_utils.h [hunk 6]
```diff
@@ -1308,25 +1299,57 @@ namespace rsx
...
+			speculatively_flushed = false;
+
+			if (miss)
+			{
+				m_tex_cache->on_miss();
+			}
+			m_tex_cache->on_flush();
+
+			// We do not update the predictor statistics for flush_always sections
+			if(get_memory_read_flags() != memory_read_flags::flush_always)
```
Comment (VelocityRa) [inline rpcs3/Emu/RSX/Common/texture_cache_utils.h]: space before `(`
```suggestion
			if (get_memory_read_flags() != memory_read_flags::flush_always)
```

File: rpcs3/Emu/RSX/Common/texture_cache_predictor.h [hunk 7]
```diff
@@ -0,0 +1,389 @@
...
+		}
+
+		bool empty() const
+		{
+			return m_size == 0;
+		}
+
+		void push(u32 val)
+		{
+			if(m_size < buffer_size)
```
Comment (VelocityRa) [inline rpcs3/Emu/RSX/Common/texture_cache_predictor.h]: space before `(`
```suggestion
			if (m_size < buffer_size)
```

**Comment by DanteBC** [comment]
tested with Shadow of the colossus HD, Neverdead, Silent Hill Downpour, lollipop chainsaw, NieR (all with WCB enabled). No regressions noticed.

File: rpcs3/Emu/RSX/Common/texture_cache_predictor.h [hunk 8]
```diff
@@ -0,0 +1,389 @@
...
+			// Update history
+			write_history.push(m_writes_since_last_flush);
+			m_writes_since_last_flush = 0;
+
+			calculate_next_guess(true);
+		}
+
+		void on_write(bool mispredict)
+		{
+			if(mispredict || is_flush_likely())
```
Comment (VelocityRa) [inline rpcs3/Emu/RSX/Common/texture_cache_predictor.h]: space before `(`
Maybe run clang-format on this file.
```suggestion
			if (mispredict || is_flush_likely())
```

**Comment by ruipin** [comment]
Oops, I made a mistake and said this fixes #5180 when I wanted to say it fixes #5182.

The Heavy Rain/Motorstorm regressions should have improved, but I haven't yet found the time to look at them in all earnest. Been a busy few weeks at work.

**Comment by ruipin** [comment]
@VelocityRa thanks for the review, those style issues should now be fixed.

**Comment by legend800** [comment]
Time Crisis 4 broken w/ WCB on both backends. This game requires WCB to avoid white videos. 

Note: Current only works on OpenGL as Vulkan was broke a few months ago (screen washed out, similar to this PR's regression). Related regression logged here: https://github.com/RPCS3/rpcs3/issues/4949

PR:
2018-10-21 09_55_29-fps_ 55 03 _ opengl _ 0 0 5-bddcfc7c-wip-texture-cache-pr2 _ time crisis_ razing

Master:
2018-10-21 09_57_33-fps_ 47 16 _ opengl _ 0 0 5-7454 _ time crisis_ razing storm blus30528

**Comment by ruipin** [comment]
@legend800 I'll take a look later, but please try the new changes right now. They should fix some OpenGL crashes I was seeing, might also fix that issue.

File: rpcs3/Emu/RSX/Common/texture_cache.h [hunk 9]
```diff
@@ -771,7 +813,7 @@ namespace rsx
 					}
 					else
 					{
-						//allow_flush = false and not synchronized
+						//deferred_flush = true and not synchronized
```
Comment (HerrHulaHoop) [inline rpcs3/Emu/RSX/Common/texture_cache.h]: Space after `//`

File: rpcs3/Emu/RSX/Common/texture_cache_predictor.h [hunk 10]
```diff
@@ -0,0 +1,389 @@
...
+		using iterator       = typename map_type::iterator;
+		using const_iterator = typename map_type::const_iterator;
+
+	private:
+		// Member variables
+		map_type m_entries;
+		texture_cache_type* m_tex_cache;
+
+	public:
+		//	Per-frame statistics
```
Comment (HerrHulaHoop) [inline rpcs3/Emu/RSX/Common/texture_cache_predictor.h]: Looks like a tab after `//` lol

Comment (ruipin) [reply rpcs3/Emu/RSX/Common/texture_cache_predictor.h]: lol

File: rpcs3/Emu/RSX/Common/texture_cache.h (hunk 9 above)
Comment (ruipin) [reply rpcs3/Emu/RSX/Common/texture_cache.h]: eh, we have a lot of comments all over that file that don't have a space after the `//`

**Comment by stride21** [comment]
Motorstorm goes ingame on the 2nd and 3rd race with WCB enabled with this PR but WCB still has issues. It seems like WCB has a delay of when its working, like when in the main menu it could be completely black at first but then eventually it fix itself and look correct.

**Comment by Xcedf** [comment]
@stride21 with Motorstorm, especially if you use Vulkan it could be different issue, see https://github.com/RPCS3/rpcs3/issues/5239, i don't have Motorstorm itself but in Pacific Rift in some places it fails to work but then recover itself and may againt fail.

**Comment by Xcedf** [comment]
@stride21 with Motorstorm, especially if you use Vulkan it could be different issue, see https://github.com/RPCS3/rpcs3/issues/5239, i don't have Motorstorm itself but in Pacific Rift in some places it fails to work but then recover itself and may againt fail.

**Comment by Xcedf** [comment]
Heavy Rain demo now goes in menu with WCB, but when time comes to do it's job and work with corrupted characters textures, it stucks the emu tried on both OGL and Vulkan

**Comment by Xcedf** [comment]
Heavy Rain demo now goes in menu with WCB, but when time comes to do it's job and work with corrupted characters textures, it stucks the emu tried on both OGL and Vulkan
@stride21 with Motorstorm, especially if you use Vulkan it could be different issue, see https://github.com/RPCS3/rpcs3/issues/5239, i don't have Motorstorm itself but in Pacific Rift in some places it fails to work but then recover itself and may againt fail.

**Comment by stride21** [comment]
This PR fixes the crashes that happen when leveling up a weapon in Ratchet and Clank Future: Tools of Destruction. @Xcedf Motorstorm doesn't have that issue on master.

**Comment by stride21** [comment]
The PR fixes the random crashing that happens in Beyond Two Souls.

**Comment by psennermann** [comment]
I cannot see a new "strict flushing" option in the config.yml, where do I find it?

**Comment by ruipin** [comment]
@psennermann
https://github.com/RPCS3/rpcs3/pull/5276/files#diff-02403da9ee4837f139eb0fc90c945831R432

You will need to launch RPCS3 and "save" settings at least once for the JSON to be updated with the default value for that option.

**Comment by psennermann** [comment]
In fact with that option enabled Nier Replicant (WCB game) seems slightly better (smoother) but maybe it's just an impression...

**Comment by ruipin** [comment]
Must be your impression, enabling that option will only slow down rendering for an insignificant gain in "accuracy".

**Comment by Parthorisian** [comment]
Wet (2009) got significant performance boost using this pr:)

**Comment by HexyFify** [comment]
@Parthorisian could you provide us with some screenshots of the performance increase/avg fps increase

**Comment by psennermann** [comment]
I think what I described about the boss fight in Nier Replican (white screen) is somewhat related to the Time Crisis 4 issue reported by legend800: with this PR WCB option still doesn't work perfectly and sometimes the setting doesn't get triggered or is lost...

**Comment by DanteBC** [comment]
NieR with WCB had no issues with Kaine's first boss for me with this PR/

**Comment by psennermann** [comment]
It happens after a while during battle, not immediately...

File: rpcs3/Emu/RSX/GL/GLTextureCache.h (hunk 2 above)
Comment (kd-11) [reply rpcs3/Emu/RSX/GL/GLTextureCache.h]: Agreed, the format of asserts is mixed - some are spaced, some are not, all in the same commit. Should at least be uniform.

File: rpcs3/Emu/RSX/GL/GLTextureCache.h [hunk 11]
```diff
@@ -624,11 +630,16 @@ namespace gl
...
 		}
 
-		inline bool exists() const
+		bool exists() const
 		{
 			return (vram_texture != nullptr);
 		}
 
+		bool is_managed() const
+		{
```
Comment (kd-11) [inline rpcs3/Emu/RSX/GL/GLTextureCache.h]: why is is_managed returning true if vram_texture == nullptr? I mean, if there is no managed texture, how can we still say the section is managed? I get the feeling this is added to avoid and extra exists() check at the source, but that makes it less intuitive.

Comment (kd-11) [reply rpcs3/Emu/RSX/GL/GLTextureCache.h]: Also, try and verify that context == framebuffer if managed_texture is empty. Might cause issues for newly created sections but you shouldn't be calling is_managed on those either.

File: rpcs3/Emu/RSX/Common/texture_cache.h [hunk 12]
```diff
@@ -2534,7 +2476,7 @@ namespace rsx
 			return m_storage.m_unreleased_texture_objects;
 		}
 
-		virtual const u32 get_texture_memory_in_use() const
+		virtual const u64 get_texture_memory_in_use() const
```
Comment (kd-11) [inline rpcs3/Emu/RSX/Common/texture_cache.h]: Impossible situation, we cannot access 64-bits worth of memory unless there is a counting error. Just an observation.

File: rpcs3/Emu/RSX/Common/texture_cache.h [hunk 13]
```diff
@@ -1072,30 +1059,42 @@ namespace rsx
...
 			std::lock_guard lock(m_cache_mutex);
 
+			// Find a cached section to use
 			section_storage_type& region = *find_cached_texture(rsx_range, true, false);
 
-			if (region.get_context() != texture_upload_context::framebuffer_storage && region.exists())
+			if (!region.is_locked())
 			{
+				// Invalidate sections from surface cache occupying same address range
+				std::apply(&texture_cache::invalidate_range_impl_base<FlushArgs...>, std::tuple_cat(std::make_tuple(this, rsx_range, invalidation_cause::superseded_by_fbo), flush_extras));
```
Comment (kd-11) [inline rpcs3/Emu/RSX/Common/texture_cache.h]: I'll let c++ people take a look at this, just in case there is a cleaner way of passing the varags

File: rpcs3/Emu/RSX/Common/texture_cache.h [hunk 14]
```diff
@@ -258,35 +277,80 @@ namespace rsx
...
 		// Invalidation
 		static const bool invalidation_ignore_unsynchronized = true; // If true, unsynchronized sections don't get forcefully flushed unless they overlap the fault range
 		static const bool invalidation_keep_ro_during_read = true; // If true, RO sections are not invalidated during read faults
 
 
+
+
 		/**
-		 * Virtual Methods
+		 * Derived Wrappers
```
Comment (kd-11) [inline rpcs3/Emu/RSX/Common/texture_cache.h]: Isn't the whole point of traits to have a traits::method_call() structure? The whole derived()->call thing is just a makeshift man's virtual call impl with none of the benefits of traits afaik. But then again, I'm not very good at c++, so I'll ask for others to help with this.

File: rpcs3/Emu/RSX/Common/texture_cache.h [hunk 15]
```diff
@@ -258,35 +277,80 @@ namespace rsx
 		const u32 m_max_zombie_objects = 64; //Limit on how many texture objects to keep around for reuse after they are invalidated
 
 		//Other statistics
-		const u32 m_cache_miss_threshold = 8; // How many times an address can miss speculative writing before it is considered high priority
-		std::atomic<u32> m_num_flush_requests = { 0 };
-		std::atomic<u32> m_num_cache_misses = { 0 };
-		std::atomic<u32> m_num_cache_speculative_writes = { 0 };
-		std::atomic<u32> m_num_cache_mispredictions = { 0 };
+		std::atomic<u32> m_flushes_this_frame = { 0 };
```
Comment (kd-11) [inline rpcs3/Emu/RSX/Common/texture_cache.h]: If we ever extend the lifetime of statistics beyond the scope of a single frame, we'll have to rename these again. Previous naming was more general imo. Just an observation.

File: rpcs3/Emu/RSX/Common/texture_cache.h [hunk 16]
```diff
@@ -982,8 +983,8 @@ namespace rsx
 
 		virtual void on_frame_end()
 		{
-			m_predictor.on_frame_end();
 			m_temporary_subresource_cache.clear();
+			m_predictor.on_frame_end();
```
Comment (kd-11) [inline rpcs3/Emu/RSX/Common/texture_cache.h]: If the order here is important, leave a note

File: rpcs3/Emu/RSX/Common/texture_cache.h [hunk 17]
```diff
@@ -2468,11 +2471,43 @@ namespace rsx
 			return m_predictor;
 		}
 
+
+		/**
```
Comment (kd-11) [inline rpcs3/Emu/RSX/Common/texture_cache.h]: This moving around of code is not necessary. I get the idea to group similar methods, but preserve git history as much as possible.

**Comment by DanteBC** [comment]
I've managed to finish kaine's first boss twice (near her hut) and didn't had any issues.

**Comment by ruipin** [comment]
@psennermann I still am not sure if you only see that issue with this PR or if you also saw it on master. I was unable to replicate that issue on my system.

File: rpcs3/Emu/RSX/GL/GLTextureCache.h (hunk 11 above)
Comment (ruipin) [reply rpcs3/Emu/RSX/GL/GLTextureCache.h]: The reason is that "is_managed" means that a section is managed (and can be modifed) by the texture cache.
A section with `!exists()` is always "managed by the texture cache". If a section exists, then it is only "managed by the texture cache" when `managed_texture.get() != nullptr`.

This means that the texture cache can call `if(section.is_managed()) do_something();` without any issue.

The reason I didn't add the framebuffer check is because that should already be covered by the `managed_texture.get() != nullptr` check, that is the whole point. At most it would be an `AUDIT`/`ASSERT` in my opinion.

**Comment by psennermann** [comment]
On master I couldn't replicate the problem

**Comment by psennermann** [comment]
btw I think that this PR doesn't fix #5182 because NieR OpenGL performance is still horrible (Vulkan instead still has the "Vulkan-only" audio crackling problem that came out some months before the performance regression...but that should be another problem)

**Comment by ruipin** [comment]
I see no performance differences between OGL and Vulkan, at least as far as the texture cache is concerned.

**Comment by psennermann** [comment]
Master 7377 - OpenGL 30 fps (or more since it is capped)

desktop screenshot 2018 10 28 - 16 20 42 89

This PR 60b5c93c (like every other release starting from master 7385) - OpenGL 18 fps (and now I've also noticed that it doesn't even scale the right resolution…)

desktop screenshot 2018 10 28 - 16 23 19 58

**Comment by elad335** [comment]
Issues with strict texture flushing in Batman: Arkham City and Rac Tod demo ingame with vulkan:

**On**
image

**Off**
image

**On**
image

**Off**
image

**Comment by ruipin** [comment]
Yes, I will need to debug strict flushing later. This is why I didn't put the commit that adds it to the debug screen in this PR, some games don't seem to like it much.

File: rpcs3/Emu/RSX/GL/GLTextureCache.h (hunk 11 above)
Comment (kd-11) [reply rpcs3/Emu/RSX/GL/GLTextureCache.h]: My original meaning of managed meant that the GPU resource was managed by the section itself, thus if the managed_texture was null, there was nothing to 'manage' i.e clean up after the cache and lifetime. In this context is_managed() matches the meaning but from a different context - texture cache resource vs GPU resource. This is confusing for me, since is_managed() to me means "does this section have a managed resource?", but I honestly have no better ideas for better names.

**Comment by vietnam13231** [comment]
I'm getting consistent crash in P5 right before main menu after starting the game... And it's not only the game, whole emu crashes.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2526623/RPCS3.zip)
No gz, because it doesn't exist.

**Comment by tabnk** [comment]
Soulcalibur IV with PPU ASMJIT and  SPU LLVM.

This PR: 55 FPS
MASTER: 50 FPS

Nice performance.

**Comment by toccata10** [comment]
Test on mesa 18.2, r9 fury on Soulcalibur V, with Ogl: Wcl is needed or you'll have an overblooming effect.
On this PR, the characters are overbloomed even with wcb.
Same settings on master and this PR:
selection_027
selection_026

**Comment by ruipin** [comment]
@legend800 I did not manage to reproduce the issue you are seeing in Time Crisis on master and/or my PR, with both WCB on and off, and both VK and OGL. Nevertheless, please retest the latest version since there are various misc fixes.

@toccata10 I tried reproducing the overbloom in my latest version on OGL and it seems to be fine. Can you retest? (Note that SCV crashes in master with VK and this PR seems to fix it)

@psennermann I couldn't reproduce any of the Nier issues (other than the OGL "not upscaling" one, but that's been there since forever and is unrelated). Anyway, I'd appreciate it if you could retest the latest version.

**Comment by legend800** [comment]
@ruipin Are you checking TC4 via Razing Storm package (should be the same though as standalone). I grabbed the latest build, cleared cache, wiped config.xml and still getting nothing but white screens, which again is the same behavior as Master builds with WCB off. Tried VK/OGL and launched it probably 20 with various settings. Nothing fixed it. 

HOWEVER, maybe 2-3 times the screen fixed itself after about 10 secs in. Strange. White > Normal > back to full white after some time. None of this is reproducable, but maybe a clue. Sometimes it momentarily fixes itself. 

Simply copied over today's Master build and looks fine (on OpenGL). On VK thing are really washed out. There's definitely something funky with the lighting/bloom emulation on this title.

Your new build:
2018-11-03 14_30_02-window

Today's master (same settings):
2018-11-03 15_04_18-window

Master VK:
2018-11-03 15_07_53-window

**Comment by toccata10** [comment]
A very quick test on SCV with Ogl: it crashes (rpcs3 quits) just after "installing trophies", on Arch with r9 fury (mesa 18.2)

**Comment by ruipin** [comment]
@legend800 Oh I see, I was testing Razing Storm, not TC4. I can reproduce the issue with TC4.

@toccata10 does not crash here with either VK or OGL. In fact, VK crashes on master, but not with this PR.

**Comment by psennermann** [comment]
It's the first time that with this PR I could beat that boss without having the "white screen issue", so the problem might be fixed...

Speaking of OpenGL "not upscaling" in Nier, the problem has NOT been there since forever because master 7377 (and the visually broken 7380) do not have OpenGL scaling issues, it started only with 7385 PR #5115 that also killed OpenGL performance

**Comment by toccata10** [comment]
Compiled with gcc, it crashes after the load complete messages with this:
pa_write() failed while trying to wake up the mainloop: Mauvais descripteur de fichier
Invalid write to eventfd: Mauvais descripteur de fichier
Code should not be reached at pulsecore/fdsem.c:199, function pa_fdsem_post(). Aborting.
Re-raising signal for core dump handling.

./launch-rpcs3.sh : ligne 5 : 15256 Erreur de segmentation  (core dumped)
With SoulCalibur IV, it crashes after a few seconds with the same message.
On master, SoulCaliburIV works very well.

**Comment by toccata10** [comment]
I have a lot of troubles compiling rpcs3 for now on my Archlinux machine: even with master, I've got crashes when I launch SCV with a version compiled locally with gcc (and with clang 7, I can't link). So my pbs with SCV might be not related to your PR. I wanted to share this info with you. So, don't block the PR for me as I'm unable to test correctly for now.

**Comment by Xcedf** [comment]
Tested a bit your previous PR for Heavy Rain WCB Regression, but since commits were squashed i've tested this one https://github.com/ruipin/rpcs3/tree/wip3, and the regression came from https://github.com/ruipin/rpcs3/commit/e04e26fa9f641494a9bb92f94e78d109fb4eeed3

**Comment by kd-11** [comment]
Are there any regressions still present introduced by **this** PR?

**Comment by ruipin** [comment]
Yes, as far as I am aware there are two regressions unique to *this* PR:

1. Time Crisis 4 OGL regressed to white screen with WCB enabled. On master, only VK has this issue.
2. Soul Calibur V sometimes has overblooming with WCB enabled. On master, this does not seem to happen. (Note: VK crashes for me on master. This PR fixes the crash)

**Comment by stride21** [comment]
Sorry about the delay with this issue. The trail in Ratchet and Clank Future: Tools of Destruction can randomly become transparent with this PR.
PR:
prratchet
Master:
master

**Comment by theoldsport** [comment]
This PR fixes overbloom in Wipeout HD with WCB+Vulkan. Brings it on par with WCB+OpenGL

**Comment by slashbeast** [comment]
This PR fixes massive performance issues with NieR Replicant, no more audio issues when 'Write Color Buffers' is enabled. Any plan to merge it?

**Comment by ruipin** [comment]
Plan? Yes. Problem is that there is symptoms here of a large regression/bug around overblooming, and I've been busy lately so didn't spend enough time looking into it yet. Also need @kd-11 to take a look.

**Comment by legend800** [comment]
Time Crisis is all fixed up and even fixed old regression on VK on this game:
https://github.com/RPCS3/rpcs3/issues/4949

2018-12-09 16_59_20-window

**Comment by Xcedf** [comment]
Latest changes fix https://github.com/RPCS3/rpcs3/issues/5239, great work

**Comment by Emulator-Team-2** [comment]
overbloom issue is fixed in Soulcalibur V.

**Comment by toccata10** [comment]
Tried on Archlinux, mesa 18.2.6, r9 fury, launching with
KDE_DEBUG=1 rpcs3
Ogl works fine (with wcb: the overblooming is solved), but Vulkan is crashing again (was not before yesterday's commits) with```

F {rsx::thread} RSX: St13runtime_error thrown: Verification failed (e=11): 
(in file /home/jo/tmp/rpcs3/rpcs3/rpcs3/Emu/RSX/VK/VKCompute.h:137)
```
on the "vs" screen (before entering the arena).
The log file:
[RPCS3.log-SCV.gz](https://github.com/RPCS3/rpcs3/files/2662283/RPCS3.log-SCV.gz)

**Comment by kd-11** [comment]
@toccata10 That issue, while triggered by the texture cache is not really a bug; a workaround will be commited toon.
From our lengthy debugging sessions with ruipin, I don't believe there should be any more regressions specific to this PR but I'll leave this up for the next day or so to allow further testing.

**Comment by ruipin** [comment]
And that vkcompute failure is also present on master, so it's not a regression. Previous commits simply hid it due to mishandling overlapping framebuffers.

From my PoV this PR can now be merged, unless someone reports any regressions soon. I'll remove the "WIP" tag from the title.

**Comment by isshininu** [comment]
This PR ggreatly boost perfomance in FROMSOFTWARE games.

**Comment by ruipin** [comment]
To be expected, DeS and other FROMSOFTWARE games require WCB for the adaptive lighting. I expect this PR to improve performance for any game that requires WCB, but especially games where WCB causes multiple flushes per frame.

**Comment by frymezim** [comment]
@ruipin 
Can you rebase the PR I want to test it as well.

**Comment by ruipin** [comment]
@frymezim why do you need me to rebase? Just test as-is or build it yourself...

**Comment by stride21** [comment]
commit 4840a9d9 causes MotorStorm to black screen and crash when going ingame. Beyond Two Souls has frequent crashes again just like master, not sure which commit caused it but it had to be recent. Also, Ratchet and Clank Future: Tools of Destruction still has the issue with the trail being transparent.

**Comment by ruipin** [comment]
Which failure? If it's vkcompute.h, read what was discussed again.

**Comment by stride21** [comment]
Motorstorm has no exception or error it just hangs with a black screen when trying to get ingame when using WCB. Beyond Two Souls the majority of the time seems to crash similarly to Motorstorm but it happens ingame or during a cutscene. I was able to get an exception for Beyond Two Souls :  F {rsx::thread} RSX: class std::runtime_error thrown: Verification failed:(in file c:\projects\rpcs3\rpcs3\emu\rsx\rsxfifo.cpp:156)

Motorstorm log:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2664771/RPCS3.log)

Beyond Two Souls log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2664773/RPCS3.log.gz)

**Comment by kd-11** [comment]
It appears its just another timing issue since some people are able to get into motorstorm just fine. A lot of these race conditions are fixed by https://github.com/RPCS3/rpcs3/pull/5404.

**Comment by stride21** [comment]
This PR had fixed a regression with Motorstorm which had happen with #5115 where 2nd and 3rd races would black screen and crash just before getting ingame. Both Beyond Two Souls and Motorstorm are the exact same with this PR compared to master and Motorstorm does go ingame on the first race, but both worked better prior to commit 4840a9d . Sorry if I caused any confusion.

**Comment by digtal-devil** [comment]
Ninja Gaiden Sigma crashes at the main menu with Vulkan Renderer. Game works normally with OpenGL but the top line of the screen keeps flickering.

[Log](http://www.mediafire.com/file/u7m6dfzcbntjaf9/rpcs3%25282%2529.rar/file)
