### PR TITLE
cellPad: fix custom controller status

### LINKED ISSUE #14493: [Regression] DJ Hero 2 no longer responding to turntables as of 0.0.29-15470 (#14458)
### Quick summary

As of 0.0.29-15470 (#14458), DJ Hero 2 (BLUS30526) no longer responds to DJ Hero turntable input, for both real & emulated turntables.

### Details

- Configure a real turntable, or enable an emulated turntable
  - Config > I/O > DJ Hero Emulated turntable, set to 1 controller
  - Pads > Device Class, set to DJ
- Boot DJ Hero 2 and press buttons to try to skip the intro movies
  - Movies skipped and game playable in 0.0.29-15468, movies unskippable and game unplayable in 0.0.29-15470.

### Build with regression

v0.0.29-15470-4bbe885f

### Attach two log files

[RPCS3-15468.log.gz](https://github.com/RPCS3/rpcs3/files/12362258/RPCS3-15468.log.gz)
[RPCS3-15470.log.gz](https://github.com/RPCS3/rpcs3/files/12362259/RPCS3-15470.log.gz)

### Attach capture files for visual issues

_No response_

### System configuration

Windows 10 22H2
Intel i7-4720HQ
Nvidia GTX 860M, driver 531.41

### Other details

_No response_

### PR DESCRIPTION
**Pull request by Megamouse**
- CELL_PAD_STATUS_CUSTOM_CONTROLLER was lost in cellPad_NotifyStateChange. Use the whole status instead.
I don't know what config_event_entry usually sets. If it only sets the connection, I can update the code to work with the old param.
- Fixes a potential out of bounds read in cellPad_NotifyStateChange (max_connect vs. get_max_connect())
- Fixes some u32 warning in Midi code
- Improves readability a bit by using some local references

Probably fixes #14493

### CODE REVIEW

File: rpcs3/Emu/Cell/Modules/cellPad.cpp [hunk 1]
```diff
@@ -84,38 +84,38 @@ void cellPad_NotifyStateChange(u32 index, u32 state)
...
-	const auto handler = pad::get_current_handler();
-
-	const auto& pads = handler->GetPads();
-
-	const u32 old = info->reported_info[index].port_status;
+	pad_data_internal& reported_info = info->reported_info[index];
+	
+	const u32 oldStatus = reported_info.port_status;
 
-	// Ignore sent status for now, use the latest instead
```
Comment (elad335) [inline rpcs3/Emu/Cell/Modules/cellPad.cpp:98]: I think using the latest status instead of sent one with the event is fine, this event system seems meant to be a notification for the thread to update state.

Comment (Megamouse) [reply rpcs3/Emu/Cell/Modules/cellPad.cpp:98]: Updated to always use the entire status and added comments.
