### PR TITLE
sceNpTrophy: fix some bugs

### LINKED ISSUE #11319: NPEB90232: Game does not boot without a trophy file | Lego Harry Potter Years 1-4 DEMO
Quick summary:
The game wouldn't load without a TROPHY.TRP File even though it didn't come with any

Details:
The game doesn't come with a TROPDIR even though the emulator searches for that file on boot
and without a TROPHY.TRP the game doesn't boot here
a Workaround for this is copying a TROPDIR from a game that has one and renaming the NPWR folder to the one the game searches for which causes to game to load normally

Using Default Settings

Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7797881/RPCS3.log.gz)

Log with a TROPDIR from a game that has one and renamed appropriately:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/7798000/RPCS3.log) (For Some reason it didn't save a .gz) 

Screenshots:
Normal:
Screenshot (20)

With a TROPDIR from a game that has one and renamed appropriately, it goes ingame and is playable:
Screenshot (21)

Comparison with a real PS3:
On a real PS3 it ignores the missing trophy file and folder and loads the game normally
photo_2022-01-01_18-23-25

System configuration:
OS: Windows 10 Pro 21H2
CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz   4.00 GHz
GPU: ASUS ROG NVIDIA GeForce GTX 1070
RAM: 16GB DDR4

### LINKED ISSUE #11914: Infamous 2: Continue your infamous 1 story
* After unlocking all infamous 1 trophies and starting a new infamous 2 game I see
image
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8604819/RPCS3.log.gz)
* What I'm supposed to see
279370481_1057867094824095_3317533092166467737_n
followed by
279372770_1138527386945401_615180759297489776_n
These are not great bonuses but still is an RPCS3 issue.

Note: Save data is not required at all to unlock continue your story
Here is the infamous 1 trophy data for testing:
[NPWR00660_00.zip](https://github.com/RPCS3/rpcs3/files/8604837/NPWR00660_00.zip)

### PR DESCRIPTION
**Pull request by Megamouse**
- Adds an optional exit dialog to the trophy registration
- Adds some preliminary read_only logic
- Removes weird SCE_NP_TROPHY_ERROR_CONF_DOES_NOT_EXIST from sceNpTrophyCreateContext (No idea why it exists there. It makes no sense to check for a trophy install file when all you do is create a context for a comm_id)

In a hw test, sceNpTrophyRegisterContext returned _INVALID_CONTEXT if it was used with the read_only flag.
Same hw test showed that sceNpTrophyGetTrophyUnlockState does not seem to care about the registration if it was used with the read_only flag.

It's not entirely known what happens when the folder is not there, since the decr didn't let us delete it.

Fixes #11914
Fixes #11319

### CODE REVIEW

File: rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp [hunk 1]
```diff
@@ -384,23 +384,6 @@ error_code sceNpTrophyCreateContext(vm::ptr<u32> context, vm::cptr<SceNpCommunic
...
-	{
-		sceNpTrophy.warning("sceNpTrophyCreateContext failed to open trophy file from boot path: '%s'", trophy_path);
-		trophy_path = vfs::get("/dev_bdvd/PS3_GAME/TROPDIR/" + name + "/TROPHY.TRP");
-		stream.open(trophy_path);
-	}
-
-	// check if exists and opened
-	if (!stream)
-	{
-		return {SCE_NP_TROPHY_ERROR_CONF_DOES_NOT_EXIST, trophy_path};
```
Comment (elad335) [inline rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp:400]: It might be read-only error checking skip, you simply need to change the path to one that doesn't exist to test.

Comment (Megamouse) [reply rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp:400]: We used your trophy test for this.
In the last run i asked neko to remove the directory and the test still ran fine. It should have ended due to ENSURE_OK i guess.
You can run the test again to confirm if you want.

Anyway, Lego Harry Potter doesn't use the read-only flag but still fails on the same check.

Comment (Megamouse) [reply rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp:400]: Idk if he tested both options ☺️

Comment (elad335) [reply rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp:400]: that's what I'm asking..

Comment (Megamouse) [reply rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp:400]: (omitted some log spam)
sceNpTrophyGetTrophyUnlockState(error 0x80022904, line=118)
sceNpTrophyGetRequiredDiskSpace(error 0x8002291b, line=121)
sceNpTrophyGetTrophyInfo(error 0x80022904, line=127)
"sceNpTrophyRegisterContext(context, handle, complexCallback, &var, 0)" Failed at line 148! (error=0x8002291b)

Comment (Megamouse) [reply rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp:400]: so it seems the CreateContext doesn't care about the trophy file

Comment (elad335) [reply rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp:400]: okay

Comment (Megamouse) [reply rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp:400]: The original code is 8 years old. Who knows what hacks had been in place to get some games going xD
