### PR TITLE
SPU: Fix page faults notifications (non-TSX)

### LINKED ISSUE #8109: Gran Turismo 6 no longer goes in-game
Hello, after PR #8008 (rpcs3-v0.0.9-10219-0f6a0d27) Gran Turismo 6 BCES01893 v1.05 no longer goes in-game. The game just freezes at the SCE Presents screen.
Log from last working build (rpcs3-v0.0.9-10217-8cb1f4fe): 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4538255/RPCS3.log.gz)
Log from latest master (rpcs3-v0.0.9-10274-4f71c570):
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4538262/RPCS3.log)

Specifications:
Ryzen 7 2700
RX 580

### PR DESCRIPTION
**Pull request by elad335**
* Do not ever lock vm memory that is meant to be page faulted on or unmapped memory in general, this bug always existed but #8008 added another single case where the bug finally made it crash GT6.

Fixes #8109.

### CODE REVIEW

**Comment by xddxd** [comment]
Can confirm that this PR fixes #8109.

**Comment by lainiwaku** [comment]
on heavenly sword, i have a bug with this PR, i don't know how explain it 
the game  is still fluide 60 fps,  but every seconds  almost i have kind of Stuttering

**Comment by elad335** [comment]
Thanks for testing.

**Comment by lainiwaku** [comment]
ok i will test with  the newest  build when it will be finished building  i made  a little video showing the stutter  that don't happen on master branch if you want to see
https://www.youtube.com/watch?v=ql-OXvW1Av4&feature=youtu.be

**Comment by elad335** [comment]
upload a log then.

**Comment by LaneSh4d0w** [comment]
Second confirmation. Game do not lock anymore on savedata loading. Great job.

**Comment by elad335** [comment]
@lainiwaku Retest performance regression with latest commit.

File: rpcs3/Emu/Memory/vm.cpp [hunk 1]
```diff
@@ -604,6 +613,14 @@ namespace vm
 			g_addr_lock.release(0);
 		}
 
+		for (u32 i = addr / 4096; i < addr / 4096 + size / 4096; i++)
+		{
+			if (!(g_pages[i].flags.exchange(0) & page_allocated))
+			{
+				fmt::throw_exception("Concurrent access (addr=0x%x, size=0x%x, current_addr=0x%x)" HERE, addr, size, i * 4096);
+			}
+		}
```
Comment (sampletext32) [inline rpcs3/Emu/Memory/vm.cpp:622]: I think that replacing 3 divisions with 1 should improve performance.
I don't think, I calculated everything correctly, so please check.)

```suggestion
		for (u32 i = addr; i < addr + size; i += 4096)
		{
			if (!(g_pages[i / 4096].flags.exchange(0) & page_allocated))
			{
				fmt::throw_exception("Concurrent access (addr=0x%x, size=0x%x, current_addr=0x%x)" HERE, addr, size, i);
			}
		}
```

Comment (elad335) [reply rpcs3/Emu/Memory/vm.cpp:618]: Thanks for the advice but what's really performance expensive in this loop is line 614 with `exchange(0)`, and you can't add `addr + size` like that because of potential overflow.

Comment (elad335) [reply rpcs3/Emu/Memory/vm.cpp:618]: Tou avoid overflow you need to substruct 1 -> `for (u32 i = addr, end = addr + size - 1; i < end; i += 4096)`

Comment (elad335) [reply rpcs3/Emu/Memory/vm.cpp]: I've pushed an optimized version.

**Comment by xddxd** [comment]
I'm not sure which commit did it, but GT6 doesn't work with or without a save anymore.

**Comment by elad335** [comment]
Fixed.

**Comment by lainiwaku** [comment]
sorry to bother you but... still the same :( 
log  with this PR : 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4672962/RPCS3.log)
log with master
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4672967/RPCS3.log)


PR is on the right 
https://www.youtube.com/watch?v=u9XGTIo7gYY&feature=youtu.be

**Comment by lainiwaku** [comment]
i tried again with 3268da4 and ffb7595  merged , and still stutter+ now it  crash  after few seconds

**Comment by elad335** [comment]
Refixed.

**Comment by lainiwaku** [comment]
crash fixed, still have  those  kind of freeze/stutter

**Comment by Nekotekina** [comment]
May try to measure time spend in added while(true) loops, and report high values, to make sure it's not a livelock causing stutter.

**Comment by jokoputera** [comment]
The easiest to see the stutter is in Ridge Racer 7, as the running text (in main menu) and the car rotation of a car will have a micro stutter, while the FPS still run fluid 60.

This also noticed in Ico, Shadow of the Colosus, and some other games

**Comment by elad335** [comment]
I changed some things, can someone retest?

**Comment by lainiwaku** [comment]
still stutter :'(

**Comment by xddxd** [comment]
GT6 doesn't go in-game anymore. Last working build was rpcs3-v0.0.10-d0e64cb1

**Comment by elad335** [comment]
It's alright, the typo is fixed in latest push.

**Comment by elad335** [comment]
Should increase non-tsx performance in theory, unless I did something wrong.

**Comment by xddxd** [comment]
Yep, it goes in-game again. Performance seems the same, maybe a little bit more consistent.

**Comment by lainiwaku** [comment]
yep still stuter/freeze :(

**Comment by elad335** [comment]
Another retest please.

**Comment by elad335** [comment]
Closing due to the authour being incapable to continue developmenet on this pr.

**Comment by elad335** [comment]
the testing is still needed though.

**Comment by jokoputera** [comment]
Dont push yourself. Someday you're going to figure it out 😀

**Comment by xddxd** [comment]
I have tested both RR7 BCES00009 and Heavenly Sword Demo NPEA90016, and stutter wasn't present in either game.

**Comment by elad335** [comment]
urgent merge.

**Comment by elad335** [comment]
@Nekotekina @AniLeo

**Comment by lainiwaku** [comment]
heavenly sword  still stutter a lot  on BCES version  at least but whatever lets just merge it,  someone   will fix it someday  i guess ^^

**Comment by xddxd** [comment]
After looking at your log in https://github.com/RPCS3/rpcs3/pull/8280#issuecomment-633180193 all I can say your configuration is bad.

**Comment by elad335** [comment]
Seggestion for new rule for testing: all settings should be set to default unless changes are needed by game or the pull request requires it to test.

**Comment by lainiwaku** [comment]
just tested with default settings is definitely still stutter, as i say i don't care  we can merge it   and later do a regression issue  so it will be fixed later

**Comment by jokoputera** [comment]
for me, it checks out. fluid 30 / 60 fps, without micro stuttering, Vulkan Default Setting + Strict Rendering
