### PR TITLE
rsx: fix 3D aspect ratio

### LINKED ISSUE #17492: Anaglyph 3D displays squashed
### Quick summary

When the 3D option is enabled in the in-game settings, the whole display of the game get's squashed. This issue is present with all the Anaglyph 3D emulator options.

Image

### Details

Seeing this in Shadow of the Colossus [NPEA00280 and BCUS98259] in two different machines with default settings (apart from the 3D setting). Possible regression.

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/22269327/RPCS3.log.gz)

### Attach capture files for visual issues

_No response_

### System configuration

_No response_

### Other details

_No response_

### PR DESCRIPTION
**Pull request by Megamouse**
It seems we forgot to adjust the vertical resolution in aspect_convert_region when using the 3D option.
Our virtual height during the aspect ratio conversion was more than doubled due to the 3D frame packing.
This resulted in an overadjustment of the resulting output region in order to fit into our frame, manifesting itself as a squished image.

Fixes #17492

### CODE REVIEW

File: rpcs3/Emu/RSX/rsx_utils.cpp [hunk 1]
```diff
@@ -187,6 +187,16 @@ namespace rsx
 		}
 	}
 
+	size2u avconf::video_frame_size() const
+	{
+		if (state && stereo_mode != stereo_render_mode_options::disabled)
+		{
+			return size2u{ resolution_x, (resolution_y - 30) / 2 };
```
Comment (kd-11) [inline rpcs3/Emu/RSX/rsx_utils.cpp:194]: Won't this break regular 2D games? Even 3D games don't boot in 3D, so we'll squish it here.
We can just check the current output format for the info.

Comment (Megamouse) [reply rpcs3/Emu/RSX/rsx_utils.cpp:194]: This path will only be executed if the game already conigured the avconf with stereo.
See `stereo_mode != stereo_render_mode_options::disabled`

Comment (kd-11) [reply rpcs3/Emu/RSX/rsx_utils.cpp:194]: Ok
