### PR TITLE
Qt: try to fix locale nonsense on linux

### LINKED ISSUE #13440: EnhanceDoubleSpinBox 'Texture LOD Bias Addend' was used with an invalid type
### Quick summary

After changing my configuration using the defaults specified at [Help:Default Settings](https://wiki.rpcs3.net/index.php?title=Help:Default_Settings) I am receiving the error of the title:

```
F EnhanceDoubleSpinBox 'Texture LOD Bias Addend' was used with an invalid type
```

### Details

After changing my configuration using the defaults specified at [Help:Default Settings](https://wiki.rpcs3.net/index.php?title=Help:Default_Settings) I am receiving the error of the title:

```
F EnhanceDoubleSpinBox 'Texture LOD Bias Addend' was used with an invalid type
```
This error appears after I enter the "Config" menu. If I try to launch a game, another error appears:

```
E CFG: cfg::try_to_float('0,000000'): invalid float
```

The value generated on the "config.yml" for the "Texture LOD Bias Addend" parameter is `0,000000`.

I tried to change to `0`, `0.000000`, `0.00`, `3`, `+3` without success.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10818586/RPCS3.log)

### Attach capture files for visual issues

_No response_

### System configuration

[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.1.12-zen1-1-zen
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 2700 Eight-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             15.5 GB
Swap:            4.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 570 Series (polaris10, LLVM 15.0.7, DRM 3.49, 6.1.12-zen1-1-zen)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.3.6
OpenGL Core:     4.6 (Core Profile) Mesa 22.3.6
OpenGL ES:       OpenGL ES 3.2 Mesa 22.3.6
Vulkan:          Supported

### Other details

_No response_

### PR DESCRIPTION
**Pull request by Megamouse**
maybe fixes #13440

### CODE REVIEW

File: rpcs3/main.cpp [hunk 1]
```diff
@@ -423,6 +423,8 @@ void run_platform_sanity_checks()
 
 int main(int argc, char** argv)
 {
+	std::setlocale(LC_ALL, "C");
```
Comment (elad335) [inline rpcs3/main.cpp:426]: It may be more future proof to initialize it before main:
e.g.:

static const bool s_init_locale = []()
{
     std::setlocale(LC_ALL, "C");
    return true;
}();
