### PR TITLE
sceNp: add some array pointer checks

### LINKED ISSUE #15689: Nullpointer in sceNpMatching2SetRoomDataExternal
### Quick summary

When hosting a match (but requires custom servers) in 007: Legends or GoldenEye 007: Reloaded the game crashes due to a nullpointer in sceNpMatching2SetRoomDataExternal.

### Details

The `roomBinAttrExternalNum` says 1 element, yet `roomBinAttrExternal: *0x0` is a nullpointer, causing crash here?
https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/NP/np_structs_extra.cpp#L117

```
·W 0:01:24.327386 {PPU[0x1000011] Thread (Online Thread) [HLE:0x00df584c, LR:0x005bc478]} sceNp2: roomBinAttrExternal: *0x0
·W 0:01:24.327387 {PPU[0x1000011] Thread (Online Thread) [HLE:0x00df584c, LR:0x005bc478]} sceNp2: roomBinAttrExternalNum: 1
·F 0:01:24.327414 {PPU[0x1000011] Thread (Online Thread) [HLE:0x00df584c, LR:0x005bc478]} PPU: Function aborted: sceNpMatching2SetRoomDataExternal
```

### Attach a log file

[RPCS3_007_legends_create_match_crash.log](https://github.com/user-attachments/files/15780277/RPCS3_007_legends_create_match_crash.log)
[RPCS3_golden_eye_007_reloaded_create_match_crash.log](https://github.com/user-attachments/files/15780279/RPCS3_golden_eye_007_reloaded_create_match_crash.log)

### Attach capture files for visual issues

_No response_

### System configuration

_No response_

### Other details

Custom servers are required to get into Multiplayer menues, but the games are using NP matching2 for matchmaking

### PR DESCRIPTION
**Pull request by Megamouse**
- Don't print array elements if the array pointer is null
- Add some sceNp array pointer checks
- Add some rpcn array pointer checks (I get the feeling these should return an error instead)

Maybe fixes #15689

### CODE REVIEW

File: rpcs3/Emu/NP/np_structs_extra.cpp [hunk 1]
```diff
@@ -383,7 +384,7 @@ namespace extra_nps
 
 		const SceNpMatching2RoomDataExternal* cur_room = resp->roomDataExternal.get_ptr();
 
-		for (u32 i = 0; i < resp->roomDataExternalNum; i++)
+		for (u32 i = 0; i < resp->roomDataExternalNum && cur_room; i++)
```
Comment (RipleyTom) [inline rpcs3/Emu/NP/np_structs_extra.cpp:387]: cur_room will never be nullptr.

Comment (Megamouse) [reply rpcs3/Emu/NP/np_structs_extra.cpp:387]: Fixed I think
