### PR TITLE
Fix emulator crash when a pad gets disconnected (e.g. due to inactivity)

### LINKED ISSUE #14063: RPCS3 eventually closes itself if left unfocused / on background
### Quick summary

Title pretty much sums up the issue. RPCS3 eventually closes itself if the game window is left unfocused or in background for a **random period of time**. I had to check the Event Viewer in order to get some information, since the emulator simply closes, no window will appear informing of the crash.

While it's such a extremely specific issue that could just be "fixed" by simply focusing the window, I think it was worth reporting. 

I'll attach a log from Metal Gear Solid 4 as an example (it still happens in other games) and a screenshot of what Event Viewer says. 

eventviewer

### Details

_No response_

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11813619/RPCS3.log)

### Attach capture files for visual issues

_No response_

### System configuration

OS: Windows 10 Pro 22H2 19045.3086
CPU: AMD Ryzen 7 5800X
GPU: NVIDIA GeForce RTX 2060 [driver 536.23.0.0]

### Other details

_No response_

### PR DESCRIPTION
**Pull request by digant73**
Follow up of an old possible regression reported in #14063 related to emulator crash when a pad (DS3, DS4 etc.) got disconnected (e.g. due to inactivity).
It was reported by many users that build 0.0.25-14523 (#13175) (updating lib `hidapi` from 0.12.0 to  0.13.0) was possibly causing the crash of the emulator, since some random time, after the pad got disconnected.
That issue was reported by users on `Windows` and `Linux`. I also verified that since that build I also have the same issue on my env (`Windows 11`).
So, I just applied on current build the old `hidapi` version 0.12.0 (reported as working) and 0.13.0 (possibly broken) and verified that the emulator was crashing with both.
After some testing, I simply verified that the issue is caused by threads concurrent access to some (non multi-thread safe) `hidapi` functions.
I saw in the code that a similar issue was detected and fixed in the past for `MAC` env, so this PR is making something similar for all the other envs (with some minor exceptions for `Android`).

`NOTE:`
- For a DS3 pad, the issue was primarily due to the continuous invocation of `dev->open()` in `ds3_pad_handler::update_connection()` triggered by the disconnection of the pad. Not sure this bombing (a good penetration test to highlight bugs) is the desired behavior, or maybe a connection attempt after a time interval (e.g. 1 second)  makes more sense, Maybe something the main developers can improve in further PRs.

fixes #14063

### CODE REVIEW

**Comment by Megamouse** [comment]
The reason why this is not done in windows and linux builds is that I can not reproduce this at all and the mutex adds an input delay of up up to several seconds every enumeration (depending on how many usb devices you have connected).
Also the underlying issue on mac are non-thread-safe calls to the mac interfaces, and not hidapi calls per se.

**Comment by Megamouse** [comment]
Also, the main thread is only needed on mac because the mac calls need to happen on the main thread, so most of these changes can be simplified if they are really needed, by just locking the mutex in the else path as well.

**Comment by digant73** [comment]
> Also, the main thread is only needed on mac because the mac calls need to happen on the main thread, so most of these changes can be simplified if they are really needed, by just locking the mutex in the else path as well.

Yes, for the issue on Windows it was enough to simply lock the mutex. I then simply applied all (so also main thread...) what has been provided for MAC just to avoid other #ifdef.
I will apply only the lock on mutex for the non MAC env

**Comment by Megamouse** [comment]
can you please add a backtrace of the crash?

File: rpcs3/Input/hid_pad_handler.cpp [hunk 1]
```diff
@@ -104,6 +107,9 @@ hid_device* HidDevice::open()
 		hidDevice = hid_open_path(path.c_str());
 	}, false);
 #else
+	// Lock before calling "hid_open_path()"
+	std::lock_guard static_lock(g_hid_mutex);
```
Comment (Megamouse) [inline rpcs3/Input/hid_pad_handler.cpp]: just use the unique lock above

**Comment by digant73** [comment]
> can you please add a backtrace of the crash?

what do you mean? From VS I cannot debug and the rpcs3.log does not provide any details. I put some log and I saw there was an infinite number of `open()` when the pad was disconnected. I saw they were interleaved with `enumerate_devices()`. Avoiding (commenting out) the `open()` calls there was no more crash. Restoring `open()` and putting the lock on both those functions and the issue was no more present.

I do not understand why `update_devices()` is called by the thread calling `process()` (so it is continuously called). Wasn't it better to call `update_devices()` by the same thread calling `enumerate_devices()` (so every 1-2 seconds)? That would avoid the possibility to block (avoiding the delay you mentioned) the thread calling `process()` in case the devices list is changed (processed in `update_devices()`) while `enumerate_devices()` is locking the mutex possibly for a long time. Removing `update_devices()` from the main thread will also make the thread faster.
Also why updating enumerates and devices if at the end the emulator is always trying to use the selected device (the infinite number of calls to open() is related to the selected pad got disconnected)?

For Android env I see the following defined:

```
#ifdef ANDROID
std::vector<android_usb_device> g_android_usb_devices;
std::mutex g_android_usb_devices_mutex;
#endif

```
But they are only used in `enumerate_devices()`. Maybe an old code no more needed?

File: rpcs3/Input/hid_pad_handler.cpp (hunk 1 above)
Comment (digant73) [reply rpcs3/Input/hid_pad_handler.cpp]: exactly this?

`std::unique_lock static_lock(g_hid_mutex, std::defer_lock); `

or without the deferring

Comment (Megamouse) [reply rpcs3/Input/hid_pad_handler.cpp]: the entire lock section

Comment (digant73) [reply rpcs3/Input/hid_pad_handler.cpp]: done

**Comment by Megamouse** [comment]
Why can't you use VS ? Should be easy to get a backtrace if you can reproduce the crash...

It's called on the "main" thread because:
A: It makes no difference. It only does stuff if you actually dis/connect a relevant controller. Otherwise it does an early out.
B: You'd have to lock m_controllers anyway in other places, so might as well do it here
C: That's why there's a deferred lock in open(), so we don't block while it's enumerating

The android variables are used in a different project that's not part of RPCS3

File: rpcs3/Input/hid_pad_handler.cpp [hunk 2]
```diff
@@ -104,6 +107,9 @@ hid_device* HidDevice::open()
 		hidDevice = hid_open_path(path.c_str());
 	}, false);
 #else
+	// Lock before calling "hid_open_path()"
+	std::unique_lock static_lock(g_hid_mutex, std::defer_lock);
```
Comment (Megamouse) [inline rpcs3/Input/hid_pad_handler.cpp]: That makes no sense, it's dead code.
Just move the static_lock stuff in the mac path to the beginning of the function.
btw, just rename it to "lock", since it's not static (probably was in some intermediate commits of mine)

Comment (digant73) [reply rpcs3/Input/hid_pad_handler.cpp]: ops, yes that clearly restored the issue.
Do you mean, this:

```
hid_device* HidDevice::open()
{
	// Lock before calling "hid_open_path()"
	std::unique_lock lock(g_hid_mutex, std::defer_lock);

	if (!lock.try_lock())
	{
		// The enumeration thread is busy. If we lock and open the device, we might get input stutter on other devices.
		return nullptr;
	}

#ifdef ANDROID
	hidDevice = hid_libusb_wrap_sys_device(path, -1);
#elif defined(__APPLE__)
	Emu.BlockingCallFromMainThread([this]()
	{
		hidDevice = hid_open_path(path.c_str());
	}, false);
#else
	hidDevice = hid_open_path(path.data());
#endif

	return hidDevice;
}

```

Comment (Megamouse) [reply rpcs3/Input/hid_pad_handler.cpp]: yes

**Comment by digant73** [comment]
> Why can't you use VS ? Should be easy to get a backtrace if you can reproduce the crash...
> 
VS provides, in general, continuous  read/write access exception. I would need to disable those exception but it would also not intercept the issue

> It's called on the "main" thread because: A: It makes no difference. It only does stuff if you actually dis/connect a relevant controller. Otherwise it does an early out. B: You'd have to lock m_controllers anyway in other places, so might as well do it here C: That's why there's a deferred lock in open(), so we don't block while it's enumerating
> 
Yes, I know. I was referring to A in particular. This is the case where (with the lock in this PR) you could block the most important thread calling `process()`. `update_devices()` is also called by the same thread (it is called by `process()`).  So, if there is a change in the device list then the `update_devices()` could be blocked (so the entire thread executing `process()` is impacted) by the thread executing `enumerate_devices()`. Moving the execution of `update_devices()` on the same thread executing `enumerate_devices()` will simply avoid that scenario making also the most important thread executing `process()` lighter and faster

> The android variables are used in a different project that's not part of RPCS3
>
Ok

**Comment by ItsLaguna** [comment]
Tested for +30 mins twice on Linux and it never crashed. 
Now trying on Windows and it's been +10 mins and no crash, normally it'd have crashed by now.
