### PR TITLE
sys_fs: Implement ENOTDIR

### LINKED ISSUE #18491: [Regression] Uncharted 3 Freeze before Title Screen (#18395)
### Quick summary

Uncharted 3 seems to no longer go ingame when unpatched.
With game patches still works so others may not have observed the issue earlier.

### Details

Uncharted 3 spins the ring in the bottom right corner shows the warning screen then freezes and doesn't reach a title screen when not using the patches mentioned on the wiki.
Issue must be tested unpatched to replicate. Settings are the configuration mentioned on the wiki except for Write depth buffer because the note says Fixes lighting at wrong depth when rendering lighting on the GPU and we're not using the GPU lighting patch.
I tried settings configuration of only using Read color buffers on and then tried to add only Accurate RSX reservation access to no success.
So in my logs I am now using all wiki setting except WDB.

### Build with regression

https://github.com/RPCS3/rpcs3/pull/18395

### Attach two log files

[RPCS3-19096.log](https://github.com/user-attachments/files/26363171/RPCS3-19096.log)
[RPCS3-19107.log](https://github.com/user-attachments/files/26363172/RPCS3-19107.log)

### Attach capture files for visual issues

Not visual

### System configuration

Windows 11
Ryzen 7 7700x
GTX 1660 Super

### Other details

Must be tested without using game patches, Specific patch to hide issue is not tested.
RSX error messages are just noise from a previous build version and not causation of this issue.
This regression blocks https://github.com/RPCS3/rpcs3/issues/18441 from being tested as we can't get to the title screen or ingame when not using patches.

### PR DESCRIPTION
**Pull request by elad335**
*  System call argument contained a file path suffixed by additional entries as if it is a directory, leading to previously unhandled error code. Because the handling of this error is different between Windows and Unix, I implemented a generic path that determines if ENOTDIR should be returned ragardless of the actual error the Operating System reports.
 * Add support for SPU branch indirect instructions in Reduced Loop pattern. (they were detected unintentionally, but because they are valid and expand pattern recognition I decided to support it)
 * Fix Reduced Loop post-increment for variable increment loop.

Fixes https://github.com/RPCS3/rpcs3/issues/18462
Fixes #18491

### CODE REVIEW

File: rpcs3/Loader/ISO.cpp [hunk 1]
```diff
@@ -588,7 +588,7 @@ std::unique_ptr<fs::dir_base> iso_device::open_dir(const std::string& path)
 		// fs::dir::open -> ::readdir should return ENOTDIR when path is
 		// pointing to a file instead of a folder, which translates to error::unknown.
 		// doing the same here.
-		fs::g_tls_error = fs::error::unknown;
```
Comment (Megamouse) [inline rpcs3/Loader/ISO.cpp:591]: Don't forget the comment

Comment (elad335) [reply rpcs3/Loader/ISO.cpp:591]: Done.

**Comment by AniLeo** [comment]
Tested a few games, didn't spot any regression, merging as hotfix as it fixes some recent regressions
