### PR TITLE
Fix cellGameDataCheckCreate2

### LINKED ISSUE #4823: cellGameDataCheckCreate2 overwrites game data param.sfo with useless/empty data
cellGameDataCheckCreate2 overwrites game data param.sfo with useless/empty data.
This leads to failed boots in games like LAIR due to an empty title_id in Emu.Load() after an update was detected.

right: before
left: after
image

### PR DESCRIPTION
**Pull request by Farseer2**
Attempting to fix #4823

### CODE REVIEW

File: rpcs3/Loader/PSF.cpp [hunk 1]
```diff
@@ -187,7 +187,7 @@ namespace psf
 
 	void save_object(const fs::file& stream, const psf::registry& psf)
 	{
-		std::vector<def_table_t> indices; indices.reserve(psf.size());
```
Comment (Megamouse) [inline rpcs3/Loader/PSF.cpp]: without this change it works

File: rpcs3/Emu/Cell/Modules/cellGame.cpp [hunk 2]
```diff
@@ -479,7 +477,7 @@ error_code cellGameDataCheckCreate2(ppu_thread& ppu, u32 version, vm::cptr<char>
 	cbGet->sizeKB = CELL_GAMEDATA_SIZEKB_NOTCALC;
 	cbGet->sysSizeKB = 0;
 
-	psf::registry sfo = psf::load_object(fs::file(vfs::get(dir + "/PARAM.SFO")));
+	psf::registry sfo = psf::load_object(fs::file(vfs::get(dir + "/PARAM.SFO"), fs::read));
```
Comment (Nekotekina) [inline rpcs3/Emu/Cell/Modules/cellGame.cpp]: This is placebo change (default parameter)

**Comment by TheCrazyChopper** [comment]
Hi, I know this is an old post but i am stuck on how to fix. Could someone please help?
- Give step by step on how to fix this
