### PR TITLE
Fix buffer overrun in cert loading, made it more accurate. Fixes #3408

### LINKED ISSUE #3408: Research proper functionality of cellSslCertificateLoader
For some reason, when writing the string to the buffer, ie
```cpp
		memset(buffer.get_ptr(), 0, size-1);
		strncpy(buffer.get_ptr(), final.c_str(), size - 1);
		buffer.get_ptr()[size - 1] = '\0';
```
Which works for most games, TLoU crashes, with this implementation.
With this one:
```cpp
		memset(buffer.get_ptr(), 0, size);
		strncpy(buffer.get_ptr(), final.c_str(), size);
		buffer.get_ptr()[size] = '\0';
```
TLoU no longer crashes, but now it's writing outside of the buffer, which is unacceptable.
Some hardware tests need to be written to check functionality on PS3.

### PR DESCRIPTION
**Pull request by hcorion**
Let's leave this one open for review for a while this time :wink:

### CODE REVIEW

**Comment by AniLeo** [comment]
Only when you pour through every line and make sure it's bug free!

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp [hunk 1]
```diff
@@ -23,14 +23,22 @@ s32 cellSslEnd()
...
+	{
+		if (certID == 6)
+			newID = 23;
+		if (certID > 6 && certID <= 23)
+			newID = certID - 1;
+		if (certID == 13)
+			newID = 6;
+		if (certID == 18)
+			newID = 15;
+	}
```
Comment (woj1993) [inline rpcs3/Emu/Cell/Modules/cellSsl.cpp]: Why not if else? Why not switch case?

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp [hunk 2]
```diff
@@ -66,12 +78,15 @@ s32 cellSslCertificateLoader(u64 flag, vm::ptr<char> buffer, u32 size, vm::ptr<u
...
+				final.append(getCert(certPath, i, true));
+			else
+				final.append(getCert(certPath, i));
 		}
 
-		memset(buffer.get_ptr(), 0, size);
-		strncpy(buffer.get_ptr(), final.c_str(), size);
-		buffer.get_ptr()[size] = '\0';
+		memset(buffer.get_ptr(), '\0', size - 1);
+		memcpy(buffer.get_ptr(), final.c_str(), size);
```
Comment (paulsapps) [inline rpcs3/Emu/Cell/Modules/cellSsl.cpp]: I think this is wrong as it will leave the string not null terminated? Before changes it got explicitly null terminated (out of bounds mind). Assuming it is a c-style string its probably also wrong as final size might be less than size?

Comment (hcorion) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: I would agree, however, for some reason, if you add the null terminated character at the end, TLoU crashes.
I'll change the memcpy to `final.size()` though, thanks for pointing that out.

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp (hunk 1 above)
Comment (hcorion) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: Not `switch case` because you have to do the `break;` for each case which adds more lines than it's worth in this case.

I'll change it to `if else` though.

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp [hunk 3]
```diff
@@ -66,12 +78,15 @@ s32 cellSslCertificateLoader(u64 flag, vm::ptr<char> buffer, u32 size, vm::ptr<u
...
+				final.append(getCert(certPath, i, true));
+			else
+				final.append(getCert(certPath, i));
 		}
 
-		memset(buffer.get_ptr(), 0, size);
-		strncpy(buffer.get_ptr(), final.c_str(), size);
-		buffer.get_ptr()[size] = '\0';
+		memset(buffer.get_ptr(), '\0', size - 1);
+		memcpy(buffer.get_ptr(), final.c_str(), final.size());
```
Comment (danilaml) [inline rpcs3/Emu/Cell/Modules/cellSsl.cpp]: Btw, is `final.size()` always less than `size`?

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp (hunk 2 above)
Comment (danilaml) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: @paulsapps if `final.c_str()` fits into buffer, it'll be null terminated (since `c_str()` is null-terminated). It's strange, however, that setting last char of the buffer to `0` leads to a crash.
Possible causes: 1) TLoU passes wrong (decremented) value (either because of emulation inaccuracies or because it is what it does originally) 2) buffer is not supposed to be null-terminated 3) something else.

Btw, you say that this PR fixes #3408 but has anyone done any tests with the actual hw/lle to confirm the behavior?

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp (hunk 3 above)
Comment (hcorion) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: yes

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp [hunk 4]
```diff
@@ -23,14 +23,22 @@ s32 cellSslEnd()
...
 	int newID = certID;
-	if (certID == 6)
-		newID = 23;
-	if (certID > 6 && certID < 23)
-		newID = certID - 1;
+
+	// The 'normal' certs have some special rules for loading.
+	if (isNormalCert)
+	{
+		if (certID == 6)
```
Comment (danilaml) [inline rpcs3/Emu/Cell/Modules/cellSsl.cpp]: Can these constant be replaced by a proper enum?

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp [hunk 5]
```diff
@@ -52,11 +60,15 @@ s32 cellSslCertificateLoader(u64 flag, vm::ptr<char> buffer, u32 size, vm::ptr<u
...
 	{
 		*required = (u32)flagBits.count();
-		for (int i = 1; i < flagBits.size(); i++)
+		for (int i = 1; i <= flagBits.size(); i++)
 		{
 			if (!flagBits[i-1])
 				continue;
-			*required += (u32)(getCert(certPath, i).size() - 1);
+			// If we're loading cert 6 (the baltimore cert), then we need set that we're loading the 'normal' set of certs.
+			if (flagBits[5])
```
Comment (danilaml) [inline rpcs3/Emu/Cell/Modules/cellSsl.cpp]: This `if` looks fishy. Are you sure it should be run on every iteration? The condition doesn't change. Maybe factor it outside of the loop.

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp [hunk 6]
```diff
@@ -52,11 +60,15 @@ s32 cellSslCertificateLoader(u64 flag, vm::ptr<char> buffer, u32 size, vm::ptr<u
...
+				*required += (u32)(getCert(certPath, i, true).size() - 1);
```
Comment (danilaml) [inline rpcs3/Emu/Cell/Modules/cellSsl.cpp]: Can you please explain to me the reason for those ` - 1` here?

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp [hunk 7]
```diff
@@ -52,11 +60,15 @@ s32 cellSslCertificateLoader(u64 flag, vm::ptr<char> buffer, u32 size, vm::ptr<u
 	if (required)
 	{
 		*required = (u32)flagBits.count();
```
Comment (danilaml) [inline rpcs3/Emu/Cell/Modules/cellSsl.cpp]: Btw, does this implementation account for a `null` character? I.e. does it return the required length for a buffer + a `\0` char? If not, this might be the reason for TLoU crash.

Comment (hcorion) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: Required does pass the correct value, I wrote a test for it here: 
https://github.com/hcorion/ps3-homebrew/tree/master/ssl_certificate_test-tlou

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp (hunk 6 above)
Comment (hcorion) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: Without the `-1`, it reports the wrong size.

**Comment by hcorion** [comment]
btw, tests I created are here:
https://github.com/hcorion/ps3-homebrew/tree/master/ssl_certificate_test-tlou
and here
https://github.com/hcorion/ps3-homebrew/tree/master/ssl_certificate_test

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp [hunk 8]
```diff
@@ -52,11 +60,15 @@ s32 cellSslCertificateLoader(u64 flag, vm::ptr<char> buffer, u32 size, vm::ptr<u
...
-		for (int i = 1; i < flagBits.size(); i++)
+		for (int i = 1; i <= flagBits.size(); i++)
```
Comment (danilaml) [inline rpcs3/Emu/Cell/Modules/cellSsl.cpp]: Why it's `<=` here while it's `<` in the `else` branch?

Comment (hcorion) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: woops, thanks, good catch.

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp (hunk 6 above)
Comment (danilaml) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: Hm, and how do you determine that? What is the last char of `getCert` and why it's trimmed here? It's not deleted in the `else` branch. certs are appended as is, but the last cert is skipped for some reason.

Comment (hcorion) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: I figured that out using the tests I linked to below.

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp (hunk 7 above)
Comment (danilaml) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: @hcorion is `End of array is` there the same as `size: `?

Comment (hcorion) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: No. From what I remember size is `End of array` + the number of certs not loaded.

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp (hunk 6 above)
Comment (danilaml) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: @hcorion could be a coincidence. Shouldn't `final` here https://github.com/hcorion/rpcs3/blob/4a5454c84602a72a80da43c6a4d7c4586e106fe1/rpcs3/Emu/Cell/Modules/cellSsl.cpp#L86
have always the same `size` (`+ 1` because of `null char`) as a `required`? I.e. `required` should be the size of a buffer able to contain `final` + 1 null char. The operations done in the `if` branch seem like an attempt to much some specific test case.
For example most (if not all) of the `- 1` would be countered by the `flagBits.count()` (hence more or less expected output).

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp (hunk 7 above)
Comment (danilaml) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: That's strange, since fromhttps://github.com/hcorion/ps3-homebrew/blob/master/ssl_certificate_test-tlou/source/main.c#L112 `size` should be exactly the required length of the buffer to store certs, so here https://github.com/hcorion/ps3-homebrew/blob/master/ssl_certificate_test-tlou/source/main.c#L43 it should print the index past the cert loaded to `buf` - i.e. `size`.

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp (hunk 4 above)
Comment (hcorion) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: Done

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp (hunk 5 above)
Comment (hcorion) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: Done

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp (hunk 7 above)
Comment (hcorion) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: Sure. In theory it should do that, but from my findings, as I said, it doesn't seem to be what HW/LLE Ssl does.

If you can write some tests to prove my theory wrong, go ahead, I'd be happy to be proven wrong.

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp (hunk 6 above)
Comment (hcorion) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: > For example most (if not all) of the - 1 would be countered by the flagBits.count()

Yeah, exactly. That's the reason why `required` is not just set to 0 and I add `getCert.size()`. Because the numbers didn't match up with HW/LLE Ssl.

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp (hunk 2 above)
Comment (paulsapps) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: I don't think its strange because the old code of `buffer.get_ptr()[size] = '\0';` is writing one out of bounds no?

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp (hunk 6 above)
Comment (danilaml) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: @hcorion What is the reason? The numbers should be the same, since you do `- 1` exactly as many times as there are bits in a bitset, so they cancel out (assuming there are no other bugs).

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp (hunk 7 above)
Comment (danilaml) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: @hcorion I don't have ps3 HW available, so I'm not sure how I would be able to write proper tests) Btw, it looks like https://github.com/hcorion/ps3-homebrew/blob/master/ssl_certificate_test/console-output.txt is outdated (i.e. shouldn't the size be printed for every cert with the current code?)

Comment (hcorion) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: Just test against LLE Ssl. 
Yeah, console-output.txt is outdated.

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp [hunk 9]
```diff
@@ -23,14 +25,22 @@ s32 cellSslEnd()
...
 {
-	//Stupid cellssl
 	int newID = certID;
-	if (certID == 6)
-		newID = 23;
-	if (certID > 6 && certID < 23)
-		newID = certID - 1;
+
+	// The 'normal' certs have some special rules for loading.
+	if (isNormalCert)
```
Comment (woj1993) [inline rpcs3/Emu/Cell/Modules/cellSsl.cpp]: Cant we check if certID is in 6 to 23 range and don't do code block if it's not?
Eg. if (isNormalCert && certID >= BartimoreCert && certID <= GTECyberTrustGlobalCert)
{...

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp [hunk 10]
```diff
@@ -23,14 +25,22 @@ s32 cellSslEnd()
...
+	{
+		if (certID == BaltimoreCert)
+			newID = GTECyberTrustGlobalCert;
+		else if (certID == Class3G2V2Cert)
+			newID = BaltimoreCert;
+		else if (certID == EntrustNetCert)
+			newID = ClassSSV4Cert;
+		else if (certID > BaltimoreCert && certID <= GTECyberTrustGlobalCert)
```
Comment (woj1993) [inline rpcs3/Emu/Cell/Modules/cellSsl.cpp]: If we change first if check this can be changed to only else.

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp (hunk 6 above)
Comment (hcorion) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: No, I subtract `- 1` only when the bit is set to 1. So `required` is equal to size of the string + the number of bits not set.

Comment (danilaml) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: @hcorion cppreference.com/w/cpp/utility/bitset/count `count` return the number of bits that are set. So you just add the number of set bits at first and when subtract it.

Comment (hcorion) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: dang, you're right. Hm, why did I change that... thanks for pointing that out, I've got some testing to do.

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp (hunk 9 above)
Comment (hcorion) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: Done.

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp (hunk 6 above)
Comment (hcorion) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: Done.

File: rpcs3/Emu/Cell/Modules/cellSsl.cpp [hunk 11]
```diff
@@ -23,14 +25,22 @@ s32 cellSslEnd()
...
+	if (isNormalCert && certID >= BaltimoreCert && certID <= GTECyberTrustGlobalCert)
+	{
+		if (certID == BaltimoreCert)
+			newID = GTECyberTrustGlobalCert;
+		else if (certID == Class3G2V2Cert)
+			newID = BaltimoreCert;
+		else if (certID == EntrustNetCert)
+			newID = ClassSSV4Cert;
+		else
+			newID = certID - 1;
```
Comment (woj1993) [inline rpcs3/Emu/Cell/Modules/cellSsl.cpp]: newID == certID in this moment why not make it "--newID"? It should be faster than subtraction and slihghtly faster than "newID--"

Comment (danilaml) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: It won't be faster and it want matter in this case anyway.

Comment (woj1993) [reply rpcs3/Emu/Cell/Modules/cellSsl.cpp]: Ok.
