### PR TITLE
[hotfix] PPU Analyzer: Fixup verify_func

### LINKED ISSUE #14439: [Regression] Multiple PPU related issues since 0.0.29-15457 (#14437)
### Quick summary

1. PPU compilation of a game from scratch takes ages on 0.0.29-15457 #14437  compared to the previous master 0.0.29-15453.

2. After PPU compilation of a game  on Windows, rpcs3 just hard crashes. Example used for this issue report is Demon's Souls. 

### Details

Last working build for both issues noted in the summary is 0.0.29-15453. #14435 

Video showing extremely slow PPU compilation speed in 15457 
(over 4x slower than master, it is still not done even after 5 minutes)

https://github.com/RPCS3/rpcs3/assets/4345150/a857ba54-8146-48f0-9ebc-50e0412c9301

Compared to older master

https://github.com/RPCS3/rpcs3/assets/4345150/66882ff9-d80c-407e-aab7-005666211a24

Note that the speed of PPU Compilation is much quicker on this older master, only taking roughly 1 minute and 20 seconds. 

### Build with regression

v0.0.29-15457-39910885

### Attach two log files

Crashes after PPU compilation on 15457

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/12270327/RPCS3.zip)

Works just fine after PPU compilation on 15453

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12270335/RPCS3.log.gz)

### Attach capture files for visual issues

_No response_

### System configuration

SYS: 12th Gen Intel(R) Core(TM) i7-12700KF | 20 Threads | 63.86 GiB RAM | TSC: 3.610GHz | AVX+ | FMA3
SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19044, Service Pack: none, Compatibility mode: 0
RSX: Found Vulkan-compatible GPU: 'NVIDIA GeForce RTX 2080 Ti' running on driver 527.56.0.0
SYS: Firmware version: 4.88

### Other details

_No response_

### PR DESCRIPTION
**Pull request by elad335**
Fixes #14439

### CODE REVIEW

File: rpcs3/Emu/Cell/PPUAnalyser.cpp [hunk 1]
```diff
@@ -558,7 +558,7 @@ bool ppu_module::analyse(u32 lib_toc, u32 entry, const u32 sec_end, const std::b
 
 	auto verify_func = [&](u32 addr)
 	{
-		if (!entry)
+		if (entry)
```
Comment (mzji) [inline rpcs3/Emu/Cell/PPUAnalyser.cpp:561]: 🤣
