### PR TITLE
win/fs: check file handle with GetFileInformationByHandle when creating fs::file

### LINKED ISSUE #18001: [Regression] Crash when loading game list after ISO support (#18008)
### Quick summary

The "Full decrypted ISO support" changes in Windows build 0.0.39-18648 cause "RPCS3: Fatal Error" assertions at launch of RPCS3; can no longer launch RPCS3 successfully

### Details

I launched RPCS3 and was prompted to upgrade to the new version 0.0.39-18648 (including the ISO support changes).  I upgraded, and when RPCS3 restarted, it displays two "Verification failed" assertion errors in File.cpp:567.  After pressing OK on both assertion dialogs, RPCS3 exits.  Launching RPCS3 again gives the same Fatal Error dialogs.  After downgrading to the prior Windows build 0.0.39-18623, I can successfully launch and use RPCS3 again.

Here is a screenshot of RPCS3 showing the two assertion dialogs:

Image

### Build with regression

v0.0.39-18648-49bcc930

### Attach two log files

[RPCS3-0.0.39-18648-crash.log.gz](https://github.com/user-attachments/files/24538725/RPCS3-0.0.39-18648-crash.log.gz)

[RPCS3-0.0.39-18623-works.log.gz](https://github.com/user-attachments/files/24538726/RPCS3-0.0.39-18623-works.log.gz)

### Attach capture files for visual issues

_No response_

### System configuration

_No response_

### Other details

_No response_

### PR DESCRIPTION
**Pull request by Megamouse**
- Check file handle with GetFileInformationByHandle when creating fs::file
- Default initialize some members/variables

On empty mounted drives CreateFileW may return a valid handle even if the drive is not usable.
We have to check the file handle early. Otherwise other functions may fail later as a result.

Fixes #18001

### CODE REVIEW

File: Utilities/File.cpp [hunk 1]
```diff
@@ -1656,6 +1656,16 @@ fs::file::file(const std::string& path, bs_t<open_mode> mode)
...
 
+	// Check if the handle is actually valid.
+	// This can fail on empty mounted drives (e.g. with ERROR_NOT_READY or ERROR_INVALID_FUNCTION).
+	BY_HANDLE_FILE_INFORMATION info;
+	if (!GetFileInformationByHandle(handle, &info))
+	{
+		CloseHandle(handle);
+		g_tls_error = to_error(GetLastError());
+		return;
+	}
```
Comment (elad335) [inline Utilities/File.cpp:1667]: Well, CreateFileW can also open directories.
If you already got BY_HANDLE_FILE_INFORMATION.dwFileAttributes,  you need to add checks for FILE_ATTRIBUTE_DIRECTORY and FILE_ATTRIBUTE_SYSTEM - fail if either flags are present with fs::error::isdir or fs::error::acces.

Comment (Megamouse) [reply Utilities/File.cpp:1667]: I'm not sure why I need to.
The purpose is to check if the drive works. Not if the file/folder works

Comment (elad335) [reply Utilities/File.cpp:1667]: It would fix various other crashes later on, such as when reading or writing to fs::file.

Comment (Megamouse) [reply Utilities/File.cpp:1667]: I can't do that until Tuesday.
Feel free to merge and do a follow-up
