### PR TITLE
XAudio2.8+ fix

### LINKED ISSUE #2063: Regression : Xaudio2 failed again on latest build
image
It randomly hit this error again , on the older build is bdeccd8 is not hit this error

### PR DESCRIPTION
**Pull request by Nekotekina**
2.7 mirror
May fix #2063

### CODE REVIEW

File: rpcs3/Emu/Audio/XAudio2/XAudio28Thread.cpp [hunk 1]
```diff
@@ -131,6 +131,16 @@ void XAudio2Thread::xa28_open()
...
 void XAudio2Thread::xa28_add(const void* src, int size)
 {
+	XAUDIO2_VOICE_STATE state;
+	s_tls_source_voice->GetState(&state);
+
+	if (state.BuffersQueued > 32)
+	{
+		LOG_WARNING(GENERAL, "XAudio2Thread : too many buffers enqueued (%d, pos=%u)", state.BuffersQueued, state.SamplesPlayed);
+
+		return xa27_flush();
```
Comment (danilaml) [inline rpcs3/Emu/Audio/XAudio2/XAudio28Thread.cpp]: Probably typo. (27 instead of 28)

**Comment by neku397** [comment]
may i know how to apply this? 
i dont know how sorry

**Comment by Megamouse** [comment]
if you have the newest version of rpcs3 it is already applied
