### PR TITLE
PAD: Fix ldd_data transfer

### LINKED ISSUE #15164: Instruments do not pass button presses to Native Interface
### Quick summary

Anything that's not a "standard controller" has issues passing button presses when RPCS3's Native Interface is up. 

### Details

When the player brings up UI that requires the Native Interface, any button presses on "non-standard" controllers will simply not work. If the player does not have an alternative input method that works, they will be soft locked.

I have personally tested:
* MIDI to USB Rock Band 3 Mustang Guitar (Emulated MIDI Device)
* USB MIDI Keyboard (Emulated MIDI Device) [not logged]
* Rock Band 3 Keyboard (Zadig/USB Passthrough)

Other users in Milohax report this issue now and then. I will forward any messages from them here.

Current workaround is to disable the Native Interface for those that don't have an alternative input method set up.

PS3 hardware does not have this issue.

### Attach a log file

[Mustang - RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14187493/Mustang.-.RPCS3.log.gz)
[RB3 Keyboard Passthrough - RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14187494/RB3.Keyboard.Passthrough.-.RPCS3.log.gz)

### Attach capture files for visual issues

_No response_

### System configuration

Tested on a couple of Windows machines.

### Other details

Example of this happening on a Rock Band 3 Mustang Guitar connected via MIDI to USB and set up through the Emulated MIDI Device section in I/O.
https://youtu.be/x3bIaiRE7fY

### PR DESCRIPTION
**Pull request by Florin9doi**
- ldd_data was set but unused

### CODE REVIEW

File: rpcs3/Emu/Cell/Modules/cellPad.cpp [hunk 1]
```diff
@@ -269,11 +269,7 @@ void pad_get_data(u32 port_no, CellPadData* data, bool get_periph_data = false)
 	}
 	else if (pad->ldd)
 	{
-		pad->ldd_data = *data;
-		if (setting & CELL_PAD_SETTING_SENSOR_ON)
```
Comment (elad335) [inline rpcs3/Emu/Cell/Modules/cellPad.cpp:273]: Why did you remove this? you probably need to copy only data->len using memcpy.

**Comment by Megamouse** [comment]
just invert the assignment.
I accidentally changed this during refactoring.
image

**Comment by elad335** [comment]
In the rest of the function only data->len bytes are actually modified, see #5311

**Comment by Megamouse** [comment]
How is this supposed to fix native overlay input?
I understand that it may fix my other PR, but on its own?

**Comment by Florin9doi** [comment]
> How is this supposed to fix native overlay input? I understand that it may fix my other PR, but on its own?

You're right, I removed the link

File: rpcs3/Emu/Cell/Modules/cellPad.cpp [hunk 2]
```diff
@@ -269,11 +269,11 @@ void pad_get_data(u32 port_no, CellPadData* data, bool get_periph_data = false)
 	}
 	else if (pad->ldd)
 	{
-		pad->ldd_data = *data;
 		if (setting & CELL_PAD_SETTING_SENSOR_ON)
 			data->len = CELL_PAD_LEN_CHANGE_SENSOR_ON;
 		else
 			data->len = (setting & CELL_PAD_SETTING_PRESS_ON) ? CELL_PAD_LEN_CHANGE_PRESS_ON : CELL_PAD_LEN_CHANGE_DEFAULT;
+		std::memcpy(data->button, pad->ldd_data.button, data->len * sizeof(data->button[0]));
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellPad.cpp:276]: Just write sizeof(u16), it's never gonna change
