### PR TITLE
My Fixups

### LINKED ISSUE #4031: thread_ctrl::wait_for behaviour
I touched on that in #3918, but from my understanding (which could be wrong :-) there is an issue with thread_ctrL::wait_for. It is used throughout the emulator where the current thread is supposed to be delayed, for example while displaying a save dialog or a message dialog. But from my experience the behaviour is somewhat random.

For example Wolfenstein The New Order displays a message dialog during installaion. During that the background is animated and the sound continues playing. This matches the PS3 behaviour, so that is ok.

But for examle in Silent HiIl HD Collection when displaying a save dialog, the screen fades to red and a special sound plays. Both the animation and the sound are abruptly cut off when the dialog appears and only continue after it closes. The PS3 would instead smoothly fade the sound to a background noise that plays while the dialog is open and fade to another background image.

When replacing the waiting code in savedata_op() with:
```
// Display Save Data List asynchronously in the GUI thread.
atomic_t<bool> dlg_result(false);

Emu.CallAfter([&]()
{
	selected = Emu.GetCallbacks().get_save_dialog()->ShowSaveDataList(save_entries, focused, operation, listSet);
	dlg_result = true;
	lv2_obj::awake(ppu);
});

lv2_obj::sleep(ppu);

while (!ppu.state.test_and_reset(cpu_flag::signal))
{
	thread_ctrl::wait();
}
```
the game seems to behave the intended way.

I am not saying that this is the right way, but I wonder if thread_ctrl::wait_for is really working as intended.

With #4011 the save dialog also shows the blocking behaviour in SH, but there the UI code runs its own input loop and blocks the thread with that.

### LINKED ISSUE #5707: [Regression] Gran Turismo 5 access violation
Gran Turismo 5 regressed from ingame to nothing after e38b7aee
console shows
F {PPU[0x1000000] Thread (main_thread) [0x01ae1c70]} MEM: Access violation reading location 0x8
reverting it makes it work again, please take a look

### PR DESCRIPTION
**Pull request by elad335**
* Adjust _sys_lwcond_wait mutex unlock to the new unlocking method (only the first unlock flag is used there), logging fixes.
* Allow the usage of X8R8G8B8 in source format of rsx::image_in. fixes a regresssion from #5381 (#5510) 
todo: hw testing testing shows imgae_in supports more source formats than r5g6b6 and a8r8g8b8 at core.
Alpha is always ignored.
* Yield ppu thread in ShowSaveDataDialog to allow applications to continue execution in the background. Fixes #4031 (todo: Investiage similar situations with vsh as well)
* make RSXIOMem volatile, minor optimization to avoid double checking address returned.
* Fix potential deadlock when waiting for a zcull flush request to clear. (Vulkan)
* Fix sync bug in sys_event_flag_set regarding atomic op on event flags. 
* Fix shared memory page flags. fixes #5707

### CODE REVIEW

**Comment by Hasster1** [comment]
Epic! With this pr, "Transformers: The Game" is now properly saving and loading games, without that black screen.
GTA: SA should be fixed too, 'cause they both were having same problems with black screen after loading.

**Comment by MsDarkLow** [comment]
Yakuza Ishin no longer needs `Disable ZCull Occlusion Queries`.
Fixes the crashes related to zcull.

**Comment by uaqlover** [comment]
amazing pr elad

but still not working

Cars: Mater-National [BLES00162]

doesn't make save file at all 

Cars: Race-O-Rama [BLES00620]

game freeze at making new save or loading save file 

fps_ 682 28 _ opengl _ 0 0 6-2888fb56-fixup _ cars_ race-o-rama bles00620 02_03_2019 2_14_12 pm

thanks again for your hard work

**Comment by RainbowCookie32** [comment]
With this PR, [PROTOTYPE]™ [NPUB30389] no longer crashes when starting a new game. It freezes randomly after creating the save now, but it seems like it might be a race condition, since it doesn't crash consistently at the same spot always.

image
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2922561/RPCS3.log.gz)

**Comment by elad335** [comment]
@RainbowCookie32 I know Prototype 2 stability is fixed by #5346 , so I've created a build with this pr and that pr to check if the cause of the instability is related to that. https://ci.appveyor.com/project/elad335/rpcs3/builds/22779952/artifacts

**Comment by toccata10** [comment]
I confirm that Battle Fantasia is playable again (linux, r9 fury, vulkan), which is great.
Thanks for all your fixes, elad335.

**Comment by RainbowCookie32** [comment]
> @RainbowCookie32 I know Prototype 2 stability is fixed by #5346, so I've created a [build](https://ci.appveyor.com/project/elad335/rpcs3/builds/22779952/artifacts) with this pr and that pr to check if the cause of the instability is related to that.

Froze here with this build, the furthest I've got so far so it looks like Prototype also benefits with that PR's changes.
image

**Comment by elad335** [comment]
@RainbowCookie32 So it's better than on master? I'm trying to figure out if its a regression from this pr or just a stability issue in general.

**Comment by RainbowCookie32** [comment]
> @RainbowCookie32 So it's better than on master? I'm trying to figure out if its a regression from this pr or just a stability issue in general.

Yep, that build is better than master. I don't think it's a regression on this PR

**Comment by Xcedf** [comment]
Confirm https://github.com/RPCS3/rpcs3/issues/5707 fixed here, thanks

File: rpcs3/Emu/Cell/Modules/cellSaveData.cpp [hunk 1]
```diff
@@ -373,9 +374,15 @@ static NEVER_INLINE error_code savedata_op(ppu_thread& ppu, u32 operation, u32 v
 
 		while (funcList)
 		{
+			// Yield
+			lv2_obj::sleep(ppu);
```
Comment (kd-11) [inline rpcs3/Emu/Cell/Modules/cellSaveData.cpp]: :man_facepalming: Thanks

Comment (pollo790) [reply rpcs3/Emu/Cell/Modules/cellSaveData.cpp]: can you fix gow 3 pls ? ty about freezes

**Comment by RainbowCookie32** [comment]
@pollo790 Stop spamming PRs with useless "fix game" requests.

**Comment by pollo790** [comment]
dont read my post , and my question was not to you, just ignore my post

**Comment by RainbowCookie32** [comment]
Devs don't work on specific games, you are spamming a PR with useless messages and sending a notification  to everyone involved in that PR, so yes it includes me, and I'm pretty sure anyone would answer the same as I did

**Comment by pollo790** [comment]
you just ignore ok ?? what is your problem??? lets talk on different place
this is my email
vegeta79@live.it we see
