### PR TITLE
Do not allow to unpause after fatal error occured in emulation

### LINKED ISSUE #10590: Emu.Pause bug
When you launch a game with "Automatically start games after boot" set to false then it will enter the "Ready" state.
If you now Pause the game then it will instead boot in a broken state.

This might not really be a real world use case, but I've seen it happen during refactoring.

### PR DESCRIPTION
**Pull request by elad335**
Added a "fatal" paused state which cannot be resumed from, used with fatal errors. Previously the user could resume emulation after a fatal error occured, but it used to be a top secret flaw only developer knew. After #10830 it became less of a secret...
+ Fixes #10590

### CODE REVIEW

**Comment by Megamouse** [comment]
You could also take a look at the Emu.Pause issue i made recently

File: rpcs3/Emu/System.cpp [hunk 1]
```diff
@@ -1416,16 +1416,21 @@ void Emulator::Run(bool start_playtime)
 	}
 }
 
-bool Emulator::Pause()
+bool Emulator::Pause(bool no_resume)
```
Comment (MSuih) [inline rpcs3/Emu/System.cpp:1419]: Could just call it user_requested so that you don't have to invert it every time it is used in if condition.

Comment (elad335) [reply rpcs3/Emu/System.cpp:1419]: This description confuses even myself, because I'm there are times which we want debug tools for example to do that.

Comment (MSuih) [reply rpcs3/Emu/System.cpp:1419]: Ah, I see.

**Comment by elad335** [comment]
@Megamouse Done.

File: rpcs3/Emu/System.h [hunk 2]
```diff
@@ -221,7 +222,7 @@ class Emulator final
 
 	game_boot_result Load(const std::string& title_id = "", bool add_only = false, bool force_global_config = false, bool is_disc_patch = false);
 	void Run(bool start_playtime);
-	bool Pause();
+	bool Pause(bool no_resume = false);
```
Comment (Megamouse) [inline rpcs3/Emu/System.h:225]: Why not just call it on_fatal_error

**Comment by Megamouse** [comment]
I think you can just remove the bool return because we do not use it anywhere

File: rpcs3/Emu/System.cpp [hunk 3]
```diff
@@ -1416,17 +1416,27 @@ void Emulator::Run(bool start_playtime)
...
 	const u64 start = get_system_time();
 
+	const system_state pause_state = no_resume ? system_state::fatal : system_state::paused;
+
 	// Try to pause
-	if (!m_state.compare_and_swap_test(system_state::running, system_state::paused))
+	if (!m_state.compare_and_swap_test(system_state::running, pause_state))
 	{
-		if (!m_state.compare_and_swap_test(system_state::ready, system_state::paused))
+		if (!no_resume)
```
Comment (Megamouse) [inline rpcs3/Emu/System.cpp:1428]: this doesn't make any sense.
this means you can never go from ready to paused

Comment (elad335) [reply rpcs3/Emu/System.cpp:1428]: I don't understand why anyone want that. Please elaborate.

Comment (Megamouse) [reply rpcs3/Emu/System.cpp:1428]: nevermind then.

But i found another issue (maybe unrelated to Pause).

Start games into Ready state but don't press play.
If you now Press stop, the "Emulator took too long"

File: rpcs3/Emu/System.h (hunk 2 above)
Comment (elad335) [reply rpcs3/Emu/System.h:225]: I renamed it to embalm_state because I think it best describes what it does.

Comment (Megamouse) [reply rpcs3/Emu/System.h:225]: this is even worse lmao

Comment (elad335) [reply rpcs3/Emu/System.h:225]: The latest commit shows a different usage of it, not just for fatal errors, but purely for preserving emulation state forever until killed.

Comment (Megamouse) [reply rpcs3/Emu/System.h:225]: I think the word: frozen probably makes more sense.

**Comment by Megamouse** [comment]
btw, you can't use my commit. it doesn't work

File: rpcs3/Emu/System.h (hunk 2 above)
Comment (Megamouse) [inline rpcs3/Emu/System.h:225]: you need to rename this as well

**Comment by elad335** [comment]
> https://github.com/RPCS3/rpcs3/pull/10833#issuecomment-914495571
It's needed because this function can be called from any thread, thus the return value tells whether or not the currebt thread is the one which paused so it can resume later. A bit like a mutex.try_lock() operation.

File: rpcs3/Emu/System.cpp [hunk 4]
```diff
@@ -1436,7 +1453,10 @@ bool Emulator::Pause()
 
 	static atomic_t<u32> pause_mark = 0;
 
-	sys_log.success("Emulation is being paused... (mark=%u)", pause_mark++);
+	if (!freeze_emulation)
+	{
+		sys_log.success("Emulation is being paused... (mark=%u)", pause_mark++);
+	}
```
Comment (Megamouse) [inline rpcs3/Emu/System.cpp:1459]: I suggest logging it as a notice at least if (freeze_emulation)

**Comment by Megamouse** [comment]
Lgtm
