### PR TITLE
sceNpBasicAddPlayersHistoryAsync fix

### LINKED ISSUE #7072: PPU: Function aborted Winter Stars [BLES01224]
F {PPU[0x1000000] Thread (main_thread) [0x008c5aa0]} PPU: Function aborted: sceNpBasicAddPlayersHistoryAsync
F {PPU[0x1000000] Thread (main_thread) [0x008c5aa0]} MEM: Access violation reading location 0x0

[RPCS3 0.0.7-9209.zip](https://github.com/RPCS3/rpcs3/files/3934253/RPCS3.0.0.7-9209.zip)

### PR DESCRIPTION
**Pull request by elad335**
Attempts to address #7072

### CODE REVIEW

File: rpcs3/Emu/Cell/Modules/sceNp.cpp [hunk 1]
```diff
@@ -1043,12 +1043,25 @@ error_code sceNpBasicAddPlayersHistoryAsync(vm::cptr<SceNpId> npids, u64 count,
 		return SCE_NP_BASIC_ERROR_NOT_INITIALIZED;
 	}
 
-	if (!npids || npids->handle.data[0] == '\0')
+	if (!count || !npids)
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/sceNp.cpp]: npids should be checked after count len

**Comment by maxvicio** [comment]
No figura el juego en https://psndl.net/packages
