### PR TITLE
Fix idm remove

### LINKED ISSUE #16457: Borderland2 (BLES01684) crash when connected to rpcn
### Quick summary

The game work well if there is no connection to internet. When connected to rpcn, it crash after searching for user profile informations online. 

### Details

Step to reproduce : 
Launch the game BLES01684 with all dlc installed, the update 1.15 and connection to rpcn and a valid account. Let the logo display, then press start button and it crash when searching informations online.

### Attach a log file

Capture

### Attach capture files for visual issues

_No response_

### System configuration

Intel(R) Core(TM) i5-10300H CPU
8 gb RAM
Nvidia geforce GTX 1650

### Other details

Sorry for the quality of the ticket, I'm not at home and I can't install the version of rpcs3 I want. I found this bug on a bootable hard drive with a custom batocera and I can't get the log file for now. The Rpcs3 version is 0.0.34-17253. It worked perfectly last week with an older version. When I have time I will investigate to find wich one exactly introduce the bug.

### LINKED ISSUE #16458: [Regression] In Castlevania: Harmony of Despair (NPEB00563, NPUB30505) is crashing after playing one game
### Quick summary

This game use to work perfectly in 17229, since update 17253, the game constantly crashes after playing one chapter and going back to the main menu
A log file is linked including a session of chapter 1 played on normal difficulty on local play
[RPCS3.log](https://github.com/user-attachments/files/18246959/RPCS3.log)

### Details

The game is composed of chapters that can be played individually, you go from the main menu to chapter scene, after finishing a chatper you go back to the main menu.
Everytime the game tries to load the main menu after succesfully completing the chapter, it crashed
If the chapter is failed, the game behaves as usual.
the crash is reproducible on any chapter with any character as long as the chapter is completed by defeating the boss

Steps to reproduce
- launch a game on any chapter with any character
- win the chapter by defeating the boss
- game crashes on loading menu

### Build with regression

v0.0.34-17253-b2949f11

### Attach two log files

[RPCS3 - Copie.log](https://github.com/user-attachments/files/18246970/RPCS3.-.Copie.log)

### Attach capture files for visual issues

_No response_

### System configuration

The bug has been reproduced on 2 different PCs, one with nvidia RTX 4060 and one nvidia RTX 4070 SUPER

### Other details

_No response_

### PR DESCRIPTION
**Pull request by Megamouse**
idm remove calls shared_ptr::exchange with a null_ptr.
This calls the stored object's constructor with null args.
Let's just add an exchange overload for null_ptr

fixes #16457
fixes #16458

### CODE REVIEW

**Comment by elad335** [comment]
I see, instead, you can fix the definition is_stx_pointer to check for null_,ptr_t as well

File: rpcs3/util/shared_ptr.hpp [hunk 1]
```diff
@@ -603,9 +605,10 @@ namespace stx
 
 		template <typename T1>
 		static constexpr bool is_stx_pointer = false
-			|| is_instance_of<std::remove_cv_t<T1>, shared_ptr>::value
-			|| is_instance_of<std::remove_cv_t<T1>, single_ptr>::value
-			|| is_instance_of<std::remove_cv_t<T1>, atomic_ptr>::value;
+			|| is_instance_of<std::remove_cvref_t<T1>, shared_ptr>::value
+			|| is_instance_of<std::remove_cvref_t<T1>, single_ptr>::value
+			|| is_instance_of<std::remove_cvref_t<T1>, atomic_ptr>::value;
+			|| std::is_same_v<std::remove_cvref_t<T1>, null_ptr_t>;
```
Comment (elad335) [inline rpcs3/util/shared_ptr.hpp:611]: We need to thank C++ gods that std::is_same accepts incomplete types for this ;)

**Comment by digant73** [comment]
if I can provide a suggestion to help/simplify the user's life on testing/reporting issues, it should be better (when possible as in case of a regression) to provide info about which previous PR broke/changed something that was previously working. It will keep track of the chain of changes helping the users to easily identify the PRs to double check (possibly regressed, not regressed etc.)

**Comment by Megamouse** [comment]
Why are you randomly changing my code?
You don't even know if this works?
This is exactly why we are in these crap situations
