### PR TITLE
Rsx: fix unknown cull faces

### LINKED ISSUE #2444: RSX: Unknown cull face 0x0
I saw that in hack/versus too
[VIDEO](https://www.youtube.com/watch?v=2hOjqmS4vVc)

```
F {rsx::thread} class std::runtime_error thrown: Unknown cull face 0x0
(in file Emu\RSX\gcm_enums.cpp:861)
```

[LOG](https://mega.nz/#!HEc2EbYa!HfmcLZ6B5IUKzOqd92l2-tytEB7-okgUF7PruLcBYk4)

### PR DESCRIPTION
**Pull request by elad335**
- Add default vertex shader attributes values in `rsx_state::reset()`
- Fix method registers reset, move it to flip command instead of a driver flip. [testcase](https://github.com/elad335/myps3tests/tree/master/rsx_tests/driver%20flip)
testcase is writing a non-initial value into `NV4097_SET_CULL_FACE`, does a driver flip on head 0 and head 1, and emits a crash dump. the value written remained.
- Ignore unknown culll face modes. [testcase](https://github.com/elad335/myps3tests/tree/master/rsx_tests/unknown%20cull%20face)
testcase is writing a non-initial mode `CELL_GCM_FRONT` into `NV4097_SET_CULL_FACE`, then writes -1, and emits a crash dump, regiser's value is `CELL_GCM_FRONT`.

fixes #2444 , enables [Monster Jam: Path of Destruction](https://forums.rpcs3.net/thread-188969.html) to go in-game.
image

### CODE REVIEW

**Comment by MarioSonic2987** [comment]
Fixes Shikamaru's final attack hang (and possibly with other characters) with logged in console output: 

`Unknown cull face 0x0`

**Before** (the game hangs):
image

**After** (the game doesn't hang and continues as normal):
image

File: rpcs3/Emu/RSX/D3D12/D3D12Formats.cpp [hunk 1]
```diff
@@ -410,8 +410,8 @@ D3D12_CULL_MODE get_cull_face(rsx::cull_face cfv)
 		case rsx::cull_face::front: return D3D12_CULL_MODE_FRONT;
 		case rsx::cull_face::back: return D3D12_CULL_MODE_BACK;
 		case rsx::cull_face::front_and_back: return D3D12_CULL_MODE_NONE;
+		default: ASSUME(0);
```
Comment (Nekotekina) [inline rpcs3/Emu/RSX/D3D12/D3D12Formats.cpp]: Please avoid ASSUME for now, very hard to get right.

File: rpcs3/Emu/RSX/rsx_methods.h [hunk 2]
```diff
@@ -127,8 +127,8 @@ namespace rsx
 
 	struct rsx_state
 	{
-	protected:
-		std::array<u32, 0x10000 / 4> registers;
```
Comment (kd-11) [inline rpcs3/Emu/RSX/rsx_methods.h]: This needn't not be an array. A single variable entry will suffice since the bound method is called immediately after the register set. The rest of the logic can remain the same.

**Comment by elfrichi** [comment]
black textures in diablo 3 reaper of souls (blus31437)

**Comment by xelmasx** [comment]
Hİ!
I got a texture issue " Diablo III Reaper of Souls". 
screenshot from 2018-08-31 13-54-59
