### PR TITLE
Rsx refactor

### LINKED ISSUE #2116: RSX: Unknown vertex base type 0
Title: LittleBigPlanet

F {rsx::thread} class std::runtime_error thrown: Unknown vertex base type 0
(in file C:\rpcs3\rpcs3\Emu\RSX\gcm_enums.cpp:16)

### LINKED ISSUE #2136: Regression :  1942 Joint Strike broken in-game (CMP vertex base type)
1942 Joint Strike broken (vertex corruption) in-game using Vulkan backend .

Revert this following line make it back to normal https://github.com/RPCS3/rpcs3/pull/2134

		if (decode_reg().type() == rsx::vertex_base_type::cmp)
			return 4;

untitled

### PR DESCRIPTION
**Pull request by vlj**
The first commit should fix #2136 while the second should fix #2116 by setting the vertex array registers to 0x2 (0 size/stride/... and float type).

### CODE REVIEW

File: rpcs3/Emu/RSX/rsx_methods.cpp [hunk 1]
```diff
@@ -865,8 +865,10 @@ namespace rsx
 
 		registers[NV4097_SET_ZSTENCIL_CLEAR_VALUE] = 0xffffffff;
 
-		for (auto& tex : fragment_textures) tex.init();
-		for (auto& tex : vertex_textures) tex.init();
+		std::for_each(fragment_textures.begin(), fragment_textures.end(), [](auto& ft) { ft.init(); });
+		std::for_each(vertex_textures.begin(), vertex_textures.end(), [](auto& vt) { vt.init(); });
+		std::for_each(
+		    vertex_arrays_info.begin(), vertex_arrays_info.end(), [](auto& vtx) { vtx.reset(); });
```
Comment (Nekotekina) [inline rpcs3/Emu/RSX/rsx_methods.cpp]: What are you trying to achieve by using for_each there?

Comment (vlj) [inline rpcs3/Emu/RSX/rsx_methods.cpp]: I prefer to use std::for_each loops when there is no control flow instruction (break/continue) and no container modification (erase, insert...).
With C++17 the algorithms on loop (for_each, transform...) get new overloads by adding an execution policy : http://en.cppreference.com/w/cpp/algorithm  which gives an hint to the compiler on the iteration order. Hopefully it can help compiler to vectorize code.

Comment (Nekotekina) [inline rpcs3/Emu/RSX/rsx_methods.cpp]: Not sure that such loops with small number of iterations can take any hypothetical advantage from execution policies, but it's an obviously simple thing written in more complex way than necessary.

**Comment by vlj** [comment]
Use for instead of std::for_each
