### PR TITLE
vm/sys_config/sys_memory: Stack fixes

### LINKED ISSUE #5875: Regression on Mountain Crime: Requital
`·F 0:00:23.354951 {PPU[0x1000005] Thread (PreloadThread) [0x0019f4d4]} MEM: Access violation writing location 0xd01025e8`

log file 

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3102167/RPCS3.zip)

### PR DESCRIPTION
**Pull request by elad335**
* Implement sys_config's PPU stack for "_cfg_evt_hndlr" thread, I've discovered this through hw testing of stack spaces after calling cellPad/Kb/MouseInit, to confirm Ive looked at disassmebly as well for the exact behaviour. (one thread for all instances until they all close)
* Demi-fix for vm memory stack deallocation on stack area destructor: Always reset memory flags.
Also always clear stack memory on Emu.Stop(). (do not rely on manual cleanup)
* Fix sys_memory_get_page_attribute stack access rights to match realhw.

Testcase: https://github.com/elad335/myps3tests/tree/master/ppu_tests/print%20ppu%20stacks

Fixes #5875
Why it was fixed? the PPU written to memory outside of its stack bounds and failed on rpcs3, clearly into a poor and inactive firmware PPU stack area so it even goes unnoticed.

image

### CODE REVIEW

File: rpcs3/Emu/Memory/vm.cpp [hunk 1]
```diff
@@ -805,11 +805,11 @@ namespace vm
 			vm::writer_lock lock(0);
 
 			// Deallocate all memory
-			for (auto it = m_map.begin(), end = m_map.end(); !m_common && it != end;)
+			for (auto it = m_map.begin(), end = m_map.end(); it != end;)
 			{
 				const auto next = std::next(it);
 				const auto size = it->second.first;
-				_page_unmap(it->first, size, it->second.second.get());
+				_page_unmap(it->first, size, !m_common ? it->second.second.get() : nullptr);
```
Comment (Nekotekina) [inline rpcs3/Emu/Memory/vm.cpp:812]: I'm not sure what are you trying to signify by these changes, second.get() should already be nullptr in these cases.

Comment (elad335) [reply rpcs3/Emu/Memory/vm.cpp:812]: I see.

Comment (elad335) [reply rpcs3/Emu/Memory/vm.cpp]: Fixed.

**Comment by Nekotekina** [comment]
Weird rebase issue?

**Comment by elad335** [comment]
Yep, removed commit.
