### PR TITLE
Fix user_interface::alloc_thread_bit() usage

### LINKED ISSUE #10845: Crash after trying to stop the emulation in Ready state
See https://github.com/RPCS3/rpcs3/pull/10833#discussion_r703720397
Ready state is the state where emulation is in when "Automatically start games after boot" setting is disabled.

### PR DESCRIPTION
**Pull request by elad335**
The reason it crashed is because enqueued task which releases thread bits never executed in RSX overlays code, user_interface class.
Aims to fix #10845

### CODE REVIEW

**Comment by elad335** [comment]
Hmm maybe @Nekotekina can look into it later. This has many consequences in its current form.

**Comment by elad335** [comment]
Fixed in a simpler way.

**Comment by Nekotekina** [comment]
From my limited debugging attempt, these parts of code aren't called at all if I ready then stop the emulator. Could be something else.

**Comment by Megamouse** [comment]
I noticed 3 unknown threads dangling in VS. this PR seems to fix the issue.

**Comment by Megamouse** [comment]
there's something fishy here. I think I know why

**Comment by Megamouse** [comment]
found it

**Comment by Megamouse** [comment]
See #10838

**Comment by elad335** [comment]
Ok I'll elaborate, when Emu.Stop() is executed (can be executed at any given moment) all threads are aborted with their state transitioning first to thread_state::aborting. In this state, enqueued thread tasks may or may not be excuted. Previous alloc_thread_bit() usage assumed that the enqueued task is always executed.
After the thread has completely being terminated, its state transitions to either thread_state::errored (for errors) or thread_state::finished. In those states, enqueued tasks are guaranteed to not be executed.

File: rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp [hunk 1]
```diff
@@ -275,6 +283,11 @@ namespace rsx
 						thread_bits &= ~tbit;
 						thread_bits.notify_all();
 					});
+
+					while (dlg_thread < thread_state::errored && !*notify)
```
Comment (elad335) [inline rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp:287]: Fixed the order of checks, thread_state must be checked first.
