### PR TITLE
cellMic: add 16-bit PCM to 32-bit float conversion for DSP stream

### LINKED ISSUE #15085: Mic not working | Socom Confrontation
### Quick summary

For Socom: US Navy SEALs Confrontation (BCUS98152) the mic does not work.
Confirmed mic is working and input is detected in windows.

RPCS3 Version: 0.0.30-15996-93f51544 Alpha | master

### Details

Mic not working. Attempted mic input in game right before closing application to get logs.
RCPS3 detects device for Mic 1
The game shows a headset is detected
I can hear others talking (must be on actual PS3 console)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14017961/RPCS3.log.gz)

### Attach capture files for visual issues

_No response_

### System configuration

OS: Windows 10 Pro 64bit (build 19045)
System model: Z590 AORUS Master
Processor: i7-10700K
RAM: 32GB
GPU: NVIDIA GeForce RTX 4070

### Other details

Tried both bluetooth and wired headsets

### PR DESCRIPTION
**Pull request by snnaakee**
libmic provides three types of audio streams from the microphone input:
- DSP stream: Echo-cancelled and noise-reduced data stream (format : 32-bit float)
- RAW stream: Raw data stream directly from the device (format : 16-bit PCM)
- AUX stream: Reference data stream for echo cancellation (format : 16-bit PCM)

The PS3 captures raw data and then converts it to 32-bit float (higher precision) for digital signal processing.

The `get_dsp` function in `cellMic.cpp` has been updated to use the new `convert16BitPCMtoFloat` function when `attr_dsptype` is not `0x01`, converting the 16-bit PCM audio data to 32-bit float format before writing it to `rbuf_dsp`. If `attr_dsptype` is 
`0x01`, the original behavior of writing the raw buffer data is retained.

If there’s anything that needs to be addressed, please let me know. I have tried to keep modifications to the current cellMic code to a minimum while aligning as closely as possible with the PS3's approach.

Resolves #15085

### CODE REVIEW

File: rpcs3/Emu/Cell/Modules/cellMic.h [hunk 1]
```diff
@@ -323,6 +323,7 @@ class microphone_device
 private:
 	template <u32 bytesize>
 	static inline void variable_byteswap(const void* src, void* dst);
+	static inline std::vector<u8> convert16BitPCMtoFloat(const std::vector<u8>& buffer, size_t numBytes);
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.h:326]: snake_case

File: rpcs3/Emu/Cell/Modules/cellMic.h [hunk 2]
```diff
@@ -323,6 +323,7 @@ class microphone_device
 private:
 	template <u32 bytesize>
 	static inline void variable_byteswap(const void* src, void* dst);
+	static inline std::vector<u8> convert_16_bit_pcm_to_float(const std::vector<u8>& buffer, size_t numBytes);
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.h:326]: The argument as well

File: rpcs3/Emu/Cell/Modules/cellMic.cpp [hunk 3]
```diff
@@ -696,7 +725,17 @@ void microphone_device::get_dsp(const u32 num_samples)
 	const u32 bufsize = num_samples * sample_size;
 	ensure(bufsize <= buf.size());
 
-	rbuf_dsp.write_bytes(buf.data(), bufsize);
+	if (attr_dsptype != 0x01)
+	{
+		// Convert 16-bit PCM audio data to 32-bit float (DSP format)
+		std::vector<u8> float_buf = convert_16_bit_pcm_to_float(buf, bufsize);
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.cpp:731]:
```suggestion
		const std::vector<u8> float_buf = convert_16_bit_pcm_to_float(buf, bufsize);
```

File: rpcs3/Emu/Cell/Modules/cellMic.cpp [hunk 4]
```diff
@@ -696,7 +725,17 @@ void microphone_device::get_dsp(const u32 num_samples)
...
+		rbuf_dsp.write_bytes(float_buf.data(), bufsize * 2);
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.cpp:732]:
```suggestion
		rbuf_dsp.write_bytes(float_buf.data(), float_buf.size());
```

File: rpcs3/Emu/Cell/Modules/cellMic.cpp [hunk 5]
```diff
@@ -258,6 +258,35 @@ inline void microphone_device::variable_byteswap(const void* src, void* dst)
...
+{
+	ensure(numBytes % 2 == 0);
+	ensure(numBytes < buffer.size());
+
+	std::vector<u8> floatBuffer;
+	floatBuffer.reserve(numBytes * 2);
+
+	for (size_t i = 0; i < numBytes; i += 2)
+	{
+		s16 sample = static_cast<s16>((buffer[i] << 8) | buffer[i + 1]);
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.cpp:271]:
```suggestion
		const s16 sample = static_cast<s16>((buffer[i] << 8) | buffer[i + 1]);
```

File: rpcs3/Emu/Cell/Modules/cellMic.cpp [hunk 6]
```diff
@@ -258,6 +258,35 @@ inline void microphone_device::variable_byteswap(const void* src, void* dst)
...
+
+		f32 normalizedSample = static_cast<f32>(sample) / 32768.0f;
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.cpp:273]: snake_case

File: rpcs3/Emu/Cell/Modules/cellMic.cpp [hunk 7]
```diff
@@ -258,6 +258,35 @@ inline void microphone_device::variable_byteswap(const void* src, void* dst)
 	}
 }
 
+inline std::vector<u8> microphone_device::convert_16_bit_pcm_to_float(const std::vector<u8>& buffer, size_t numBytes)
+{
+	ensure(numBytes % 2 == 0);
+	ensure(numBytes < buffer.size());
+
+	std::vector<u8> floatBuffer;
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.cpp:266]: snake_case

File: rpcs3/Emu/Cell/Modules/cellMic.cpp [hunk 8]
```diff
@@ -258,6 +258,35 @@ inline void microphone_device::variable_byteswap(const void* src, void* dst)
...
+		normalizedSample = std::clamp(normalizedSample, -1.0f, 1.0f);
+
+		uint32_t temp = *reinterpret_cast<uint32_t*>(&normalizedSample);
+
+		temp = ((temp & 0x000000FF) << 24) |
+		       ((temp & 0x0000FF00) << 8) |
+		       ((temp & 0x00FF0000) >> 8) |
+		       ((temp & 0xFF000000) >> 24);
+
+		uint8_t* bytes = reinterpret_cast<uint8_t*>(&temp);
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.cpp:283]:
```suggestion
		const uint8_t* bytes = reinterpret_cast<const uint8_t*>(&temp);
```

File: rpcs3/Emu/Cell/Modules/cellMic.cpp (hunk 6 above)
Comment (Megamouse) [reply rpcs3/Emu/Cell/Modules/cellMic.cpp:273]: Also, maybe use std::numeric_limits<s16>::max();

File: rpcs3/Emu/Cell/Modules/cellMic.h [hunk 9]
```diff
@@ -323,6 +323,7 @@ class microphone_device
 private:
 	template <u32 bytesize>
 	static inline void variable_byteswap(const void* src, void* dst);
+	static inline std::vector<u8> convert_16_bit_pcm_to_float(const std::vector<u8>& buffer, size_t num_bytes);
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.h:326]:
```suggestion
	static inline std::vector<u8> convert_16_bit_pcm_to_float(const std::vector<u8>& buffer, usz num_bytes);
```

File: rpcs3/Emu/Cell/Modules/cellMic.cpp [hunk 10]
```diff
@@ -258,6 +258,35 @@ inline void microphone_device::variable_byteswap(const void* src, void* dst)
 	}
 }
 
+inline std::vector<u8> microphone_device::convert_16_bit_pcm_to_float(const std::vector<u8>& buffer, size_t num_bytes)
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.cpp:261]:
```suggestion
inline std::vector<u8> microphone_device::convert_16_bit_pcm_to_float(const std::vector<u8>& buffer, usz num_bytes)
```

File: rpcs3/Emu/Cell/Modules/cellMic.cpp [hunk 11]
```diff
@@ -258,6 +258,35 @@ inline void microphone_device::variable_byteswap(const void* src, void* dst)
...
+{
+	ensure(num_bytes % 2 == 0);
+	ensure(num_bytes < buffer.size());
+
+	std::vector<u8> floatBuffer;
+	floatBuffer.reserve(num_bytes * 2);
+
+	for (size_t i = 0; i < num_bytes; i += 2)
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.cpp:269]:
```suggestion
	for (usz i = 0; i < num_bytes; i += 2)
```

File: rpcs3/Emu/Cell/Modules/cellMic.cpp [hunk 12]
```diff
@@ -258,6 +258,35 @@ inline void microphone_device::variable_byteswap(const void* src, void* dst)
 	}
 }
 
+inline std::vector<u8> microphone_device::convert_16_bit_pcm_to_float(const std::vector<u8>& buffer, usz num_bytes)
+{
+	ensure(num_bytes % 2 == 0);
+	ensure(num_bytes < buffer.size());
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.cpp:264]: why < ? It should be <= shouldn't it?

File: rpcs3/Emu/Cell/Modules/cellMic.cpp [hunk 13]
```diff
@@ -258,6 +258,35 @@ inline void microphone_device::variable_byteswap(const void* src, void* dst)
...
+
+	std::vector<u8> float_buffer;
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.cpp:266]: For performance it would make more sense to just use a float_buf member (similar to temp_buf) and resize it here with
```
constexpr usz float_buf_size = 2 * inbuf_size;
static_assert((float_buf_size % sizeof(u32)) == 0);

float_buf.resize(float_buf_size);
ensure(num_bytes * 2 <= float_buf.size());

u32* dst = reinterpret_cast<u32*>(float_buf.data());
```
Then return the num_bytes * 2 and use that as bufsize for rbuf_dsp.write_bytes

File: rpcs3/Emu/Cell/Modules/cellMic.cpp [hunk 14]
```diff
@@ -258,6 +258,35 @@ inline void microphone_device::variable_byteswap(const void* src, void* dst)
...
+
+		u32 temp = *reinterpret_cast<u32*>(&normalized_sample);
+
+		temp = ((temp & 0x000000FF) << 24) |
+		       ((temp & 0x0000FF00) << 8) |
+		       ((temp & 0x00FF0000) >> 8) |
+		       ((temp & 0xFF000000) >> 24);
+
+		const u8* bytes = reinterpret_cast<u8*>(&temp);
+		float_buffer.insert(float_buffer.end(), bytes, bytes + sizeof(u32));
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.cpp:284]: You should then be able to use:
```suggestion
		write_to_ptr<u32>(dst++, temp);
```
or depending on endianness just:
`*dst++ = temp;`

File: rpcs3/Emu/Cell/Modules/cellMic.cpp (hunk 13 above)
Comment (snnaakee) [reply rpcs3/Emu/Cell/Modules/cellMic.cpp:266]: Then the function won't be static anymore

Comment (Megamouse) [reply rpcs3/Emu/Cell/Modules/cellMic.cpp:266]: well then don't make the function static ?

File: rpcs3/Emu/Cell/Modules/cellMic.cpp [hunk 15]
```diff
@@ -258,6 +258,35 @@ inline void microphone_device::variable_byteswap(const void* src, void* dst)
...
+
+		f32 normalized_sample = static_cast<f32>(sample) / std::numeric_limits<s16>::max();
+		normalized_sample = std::clamp(normalized_sample, -1.0f, 1.0f);
+
+		u32 temp = *reinterpret_cast<u32*>(&normalized_sample);
+
+		temp = ((temp & 0x000000FF) << 24) |
+		       ((temp & 0x0000FF00) << 8) |
+		       ((temp & 0x00FF0000) >> 8) |
+		       ((temp & 0xFF000000) >> 24);
```
[the remark this answers is not in the document]
Comment (snnaakee) [reply rpcs3/Emu/Cell/Modules/cellMic.cpp:281]: Converts the normalized_sample to big-endian

[the remark this answers is not in the document]
Comment (Megamouse) [reply rpcs3/Emu/Cell/Modules/cellMic.cpp:281]: we have a type called `be_t<f32>`.
You can probably just use this as type for normalized_sample and drop the temp variable altogether.

`const be_t<f32> normalized_sample = std::clamp(static_cast<f32>(sample) / std::numeric_limits<s16>::max(), -1.0f, 1.0f);;`

It's worth a try.

File: rpcs3/Emu/Cell/Modules/cellMic.cpp (hunk 14 above)
Comment (snnaakee) [reply rpcs3/Emu/Cell/Modules/cellMic.cpp:284]:
```
inline u32 microphone_device::convert_16_bit_pcm_to_float(const std::vector<u8>& buffer, usz num_bytes)
{
	constexpr usz float_buf_size = 2 * inbuf_size;
	static_assert((float_buf_size % sizeof(u32)) == 0);

	float_buf.resize(float_buf_size, 0);
	ensure(num_bytes * 2 <= float_buf.size());

	u32* dst = reinterpret_cast<u32*>(float_buf.data());

	for (usz i = 0; i < num_bytes; i += 2)
	{
		const s16 sample = static_cast<s16>((buffer[i] << 8) | buffer[i + 1]);

		f32 normalized_sample = static_cast<f32>(sample) / std::numeric_limits<s16>::max();
		normalized_sample = std::clamp(normalized_sample, -1.0f, 1.0f);

		u32 temp = *reinterpret_cast<u32*>(&normalized_sample);

		/*temp = ((temp & 0x000000FF) << 24) |
		       ((temp & 0x0000FF00) << 8) |
		       ((temp & 0x00FF0000) >> 8) |
		       ((temp & 0xFF000000) >> 24);*/

		write_to_ptr<u32>(dst++, temp);
	}

	return num_bytes * 2;
}
```

```
const u32 bufsize_float = convert_16_bit_pcm_to_float(buf, bufsize);
rbuf_dsp.write_bytes(float_buf.data(), bufsize_float);
```

cellMicRead doesn't get called anymore

Comment (snnaakee) [reply rpcs3/Emu/Cell/Modules/cellMic.cpp:284]: nevermind, it does

File: rpcs3/Emu/Cell/Modules/cellMic.cpp (hunk 15 above)
[the remark this answers is not in the document]
Comment (snnaakee) [reply rpcs3/Emu/Cell/Modules/cellMic.cpp]: it works

File: rpcs3/Emu/Cell/Modules/cellMic.cpp [hunk 16]
```diff
@@ -258,6 +258,28 @@ inline void microphone_device::variable_byteswap(const void* src, void* dst)
...
 
+inline u32 microphone_device::convert_16_bit_pcm_to_float(const std::vector<u8>& buffer, usz num_bytes)
+{
+	constexpr usz float_buf_size = 2 * inbuf_size;
+	static_assert((float_buf_size % sizeof(u32)) == 0);
+
+	float_buf.resize(float_buf_size, 0);
+	ensure(num_bytes * 2 <= float_buf.size());
+
+	u32* dst = reinterpret_cast<u32*>(float_buf.data());
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.cpp:269]: you can probably now try if the combination of:
```
	be_t<f32>* dst = reinterpret_cast<be_t<f32>*>(float_buf.data());
```
and
```
	*dst++ = normalized_sample_be;
```

works

File: rpcs3/Emu/Cell/Modules/cellMic.cpp [hunk 17]
```diff
@@ -258,6 +258,28 @@ inline void microphone_device::variable_byteswap(const void* src, void* dst)
...
+	static_assert((float_buf_size % sizeof(u32)) == 0);
+
+	float_buf.resize(float_buf_size, 0);
+	ensure(num_bytes * 2 <= float_buf.size());
+
+	be_t<f32>* dst = reinterpret_cast<be_t<f32>*>(float_buf.data());
+
+	for (usz i = 0; i < num_bytes; i += 2)
+	{
+		const s16 sample = static_cast<s16>((buffer[i] << 8) | buffer[i + 1]);
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.cpp:273]: Isn't this just extracting big endian s16? (correct me if I'm wrong)
So you can probably just use the same trick again:

Before the loop:
`const be_t<s16>* src = reinterpret_cast<const be_t<s16>*>(buffer.data());`

And then do:
`for (usz i = 0; i < num_bytes / 2; i++)`

In the loop:
`const be_t<s16> sample = src++;`

File: rpcs3/Emu/Cell/Modules/cellMic.h [hunk 18]
```diff
@@ -323,6 +323,7 @@ class microphone_device
 private:
 	template <u32 bytesize>
 	static inline void variable_byteswap(const void* src, void* dst);
+	inline u32 convert_16_bit_pcm_to_float(const std::vector<u8>& buffer, usz num_bytes);
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.h:326]: The return type has to be usz to prevent a warning on windows
```suggestion
	inline usz convert_16_bit_pcm_to_float(const std::vector<u8>& buffer, usz num_bytes);
```

File: rpcs3/Emu/Cell/Modules/cellMic.cpp [hunk 19]
```diff
@@ -258,6 +258,29 @@ inline void microphone_device::variable_byteswap(const void* src, void* dst)
...
 
+inline u32 microphone_device::convert_16_bit_pcm_to_float(const std::vector<u8>& buffer, usz num_bytes)
+{
+	constexpr usz float_buf_size = 2 * inbuf_size;
+	static_assert((float_buf_size % sizeof(u32)) == 0);
+
+	float_buf.resize(float_buf_size, 0);
+	ensure(num_bytes * 2 <= float_buf.size());
+
+	const be_t<s16>* src = reinterpret_cast<const be_t<s16>*>(buffer.data());
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.cpp:269]: This produces a "dereferencing type-punned pointer" warning on gcc.
Maybe we have to cast the buffer ptr to void...

```suggestion
	const be_t<s16>* src = reinterpret_cast<const be_t<s16>*>(static_cast<const void*>(buffer.data()));
```

File: rpcs3/Emu/Cell/Modules/cellMic.h [hunk 20]
```diff
@@ -345,6 +346,7 @@ class microphone_device
 
 	std::vector<mic_device> devices;
 	std::vector<u8> temp_buf;
+	std::vector<u8> float_buf;
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.h:349]: I think you also have to increase the size of:
`simple_ringbuf<inbuf_size> rbuf_dsp;`
below to:
`simple_ringbuf<inbuf_size * 2> rbuf_dsp;`

Or we may run into the ensure in write_bytes

File: rpcs3/Emu/Cell/Modules/cellMic.h (hunk 18 above)
Comment (Megamouse) [reply rpcs3/Emu/Cell/Modules/cellMic.h:326]: alternatively you can cast the return of the function to:
`return static_cast<u32>(num_bytes * 2);`
Or you will have a different warning when passing bufsize_float to write_bytes...

File: rpcs3/Emu/Cell/Modules/cellMic.cpp [hunk 21]
```diff
@@ -258,6 +258,29 @@ inline void microphone_device::variable_byteswap(const void* src, void* dst)
 	}
 }
 
+inline u32 microphone_device::convert_16_bit_pcm_to_float(const std::vector<u8>& buffer, usz num_bytes)
+{
+	constexpr usz float_buf_size = 2 * inbuf_size;
+	static_assert((float_buf_size % sizeof(u32)) == 0);
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.cpp:264]: We can now use f32 here so people don't get confused.
```suggestion
	static_assert((float_buf_size % sizeof(f32)) == 0);
```

File: rpcs3/Emu/Cell/Modules/cellMic.cpp [hunk 22]
```diff
@@ -258,6 +258,29 @@ inline void microphone_device::variable_byteswap(const void* src, void* dst)
...
+
+	float_buf.resize(float_buf_size, 0);
+	ensure(num_bytes * 2 <= float_buf.size());
+
+	const be_t<s16>* src = reinterpret_cast<const be_t<s16>*>(static_cast<const void*>(buffer.data()));
+	be_t<f32>* dst = reinterpret_cast<be_t<f32>*>(float_buf.data());
+
+	for (usz i = 0; i < num_bytes / 2; i++)
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.cpp:272]: I think we should use sizeof to make this less magical
```suggestion
	for (usz i = 0; i < num_bytes / sizeof(s16); i++)
```

File: rpcs3/Emu/Cell/Modules/cellMic.h [hunk 23]
```diff
@@ -360,7 +362,7 @@ class microphone_device
 	static constexpr usz inbuf_size = 400000; // Default value unknown
 
 	simple_ringbuf<inbuf_size> rbuf_raw;
-	simple_ringbuf<inbuf_size> rbuf_dsp;
+	simple_ringbuf<inbuf_size * 2> rbuf_dsp;
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.h:365]: I think we should move
`float_buf_size`
from convert_16_bit_pcm_to_float to below
`static constexpr usz inbuf_size = 400000; // Default value unknown`
And change it to calculate the multiplier with sizeof expressions
`static constexpr usz float_buf_size = inbuf_size * (sizeof(f32) / sizeof(s16));`

```suggestion
	simple_ringbuf<float_buf_size> rbuf_dsp;
```

File: rpcs3/Emu/Cell/Modules/cellMic.cpp [hunk 24]
```diff
@@ -258,6 +258,29 @@ inline void microphone_device::variable_byteswap(const void* src, void* dst)
 	}
 }
 
+inline u32 microphone_device::convert_16_bit_pcm_to_float(const std::vector<u8>& buffer, usz num_bytes)
+{
+	constexpr usz float_buf_size = 2 * inbuf_size;
+	static_assert((float_buf_size % sizeof(u32)) == 0);
+
+	float_buf.resize(float_buf_size, 0);
+	ensure(num_bytes * 2 <= float_buf.size());
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.cpp:267]: Again, less magical:
```suggestion

	const u32 bytes_to_write = static_cast<u32>(num_bytes * (sizeof(f32) / sizeof(s16)));
	ensure(bytes_to_write <= float_buf.size());
```

File: rpcs3/Emu/Cell/Modules/cellMic.cpp [hunk 25]
```diff
@@ -258,6 +258,29 @@ inline void microphone_device::variable_byteswap(const void* src, void* dst)
...
+	for (usz i = 0; i < num_bytes / 2; i++)
+	{
+		const be_t<s16> sample = *src++;
+
+		const be_t<f32> normalized_sample_be = std::clamp(static_cast<f32>(sample) / std::numeric_limits<s16>::max(), -1.0f, 1.0f);
+
+		*dst++ = normalized_sample_be;
+	}
+
+	return static_cast<u32>(num_bytes * 2);
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.cpp:281]:
```suggestion
	return bytes_to_write;
```

**Review by Megamouse — COMMENTED** [review]
I think this is fine now, except for some nitpicks.
Needs testing though

File: rpcs3/Emu/Cell/Modules/cellMic.cpp [hunk 26]
```diff
@@ -258,6 +258,29 @@ inline void microphone_device::variable_byteswap(const void* src, void* dst)
...
 
+inline u32 microphone_device::convert_16_bit_pcm_to_float(const std::vector<u8>& buffer, usz num_bytes)
+{
+	static_assert((float_buf_size % sizeof(f32)) == 0);
+
+	float_buf.resize(float_buf_size, 0);
+	const u32 bytes_to_write = static_cast<u32>(num_bytes * (sizeof(f32) / sizeof(s16)));
+	ensure(bytes_to_write <= float_buf.size());
+
+	const be_t<s16>* src = reinterpret_cast<const be_t<s16>*>(static_cast<const void*>(buffer.data()));
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMic.cpp:269]: hmm. this still produces a warning on gcc.
maybe try:
```suggestion
	const be_t<s16>* src = utils::bless<const be_t<s16>>(buffer.data());
```
