### PR TITLE
VFS: fix missing path deliminators

### LINKED ISSUE #11360: Games do not boot after #11178
After PR #11178 was merged path handling got broken in some way. Booting any disc game with it just shows "Booting failed: The selected file or folder is invalid or corrupted." error, and booting any HDD game makes emulator close after loading caches.

[broken_disc.RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7851617/broken.RPCS3.log.gz)
[broken_hdd.RPCS3.log](https://github.com/RPCS3/rpcs3/files/7851629/broken_hdd.RPCS3.log)
[working.RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7851618/working.RPCS3.log.gz)

Tested on windows, have gotten confirmation that linux is unaffected. The previous version (which was rollbacked on rpcs3.net/downloads) works fine.

### PR DESCRIPTION
**Pull request by Megamouse**
fixes #11360

### CODE REVIEW

File: rpcs3/Emu/VFS.cpp [hunk 1]
```diff
@@ -58,7 +57,7 @@ bool vfs::mount(std::string_view vpath, std::string_view path)
 		return false;
 	}
 
-	if (!final_path.ends_with(fs::delim) && delim_suffixed)
+	if (!final_path.ends_with(fs::delim) && (path.ends_with('/') || path.ends_with('\\')))
```
Comment (Nekotekina) [inline rpcs3/Emu/VFS.cpp:60]:
```suggestion
	if (!final_path.ends_with(fs::delim[0]) && !final_path.ends_with(fs::delim[1]) && (path.ends_with(fs::delim[0]) || path.ends_with(fs::delim[1])))
```

**Comment by Nekotekina** [comment]
Actually need also change `std::filesystem::path` to `std::filesystem::u8path` in File.cpp
