### PR TITLE
rsx: Support texel remapping with hardware formats

### LINKED ISSUE #15928: Resistance 3: wrong water effects / rain drops
### Quick summary

Just tested in deep the game playing it until the conclusion and noted crashes, graphical issues etc.

Target of this bug report is to fix the water effect issues reported below on the **GRAPHICAL GLITCHES:** section.
Sections **USED CUSTOM SETTINGS:** and **CRASHES DUE TO BUGS:** are provided just to help the developers on setup and to alert them on other bugs affecting the game (e.g. crash due to Lost-Device also present in other games) in case they want to spend time also on fixing them.

**USED CUSTOM SETTINGS:**
Despite the fact the R3's wiki reports to change (compared to default settings) only "ZCULL Accuracy" to "Relaxed", proper settings to use with current RPCS3 seems to be (tested on different HW):
- "ZCULL Accuracy" set to "Approximate" (of course Precise is usable but it impacts performance a little more):  ZCULL Accuracy set to Approximate makes performance a lot better than Relaxed (e.g. it also fixes the huge fps drop when zooming)
- "Write Color Buffer" set to "enabled": Write Color Buffer enabled fixes a graphical glitch present in the "Ambush" section in the "ST. Louis, MO" chapter

**CRASHES DUE TO BUGS:**
- The crashes (not so much frequent) are basically due to **Lost-Device** error reported on the log

**GRAPHICAL GLITCHES:**
- Water effects and water drops: They are present in different sections such as "Boat Ride" section and next ones in the "Haven, OK" chapter (water in the river is not rendered properly), "Ambush" section and next ones in "ST. Louis, MO" chapter (rain drops are not rendered properly on the ground) and "Forest" section and next ones in the "MT. Pleasant, PA" (water in the river is not rendered properly).

Attached a picture of the water issue on "Forest" section in the "MT. Pleasant, PA" chapter.

### Details

_No response_

### Attach a log file

water_on the_river

[RPCS3.log.gz](https://github.com/user-attachments/files/16590225/RPCS3.log.gz)

### Attach capture files for visual issues

_No response_

### System configuration

_No response_

### Other details

_No response_

### PR DESCRIPTION
**Pull request by kd-11**
Using hardware formats allows proper interpolation which gets rid of the noise and blockiness when some formats are used. PS3 is not a 1:1 match with desktop PC hardware though so using these formats has a minor tradeoff in precision. In most cases this wont matter so it is enabled by default. Internal heurestics and desktop API spec limitations limit how much we can use the hardware formats but for the most common cases this is good enough. A toggle is provided in the debug tab to disable using hardware formats outright.

Fixes blocky water rendering in R&C games introduced in the previous PR.

Relates to https://github.com/RPCS3/rpcs3/issues/18171
Closes https://github.com/RPCS3/rpcs3/issues/15928

### CODE REVIEW

**Comment by kd-11** [comment]
Marked as draft to investigate some flickering I'm seeing. I'm not sure if it's a regression or not, but better to be safe before merging.

File: rpcs3/Emu/RSX/GL/GLDraw.cpp [hunk 1]
```diff
@@ -299,95 +299,155 @@ void GLGSRender::load_texture_env()
...
-					{
-						m_graphics_state |= rsx::vertex_program_state_dirty;
-					}
-				}
-			}
-			else
-			{
-				*sampler_state = {};
-			}
+		const bool is_sampler_dirty = m_vertex_textures_dirty[i];
```
Comment (oltolm) [inline rpcs3/Emu/RSX/GL/GLDraw.cpp:428]: This variable is unused.

**Comment by digant73** [comment]
Flickering present in many games, broken water effects on KZ3, broken menu on KZ3. Raindrops on R3 seems still blocky while water effects on rivers are ok (no more blocky)

### PR: flickering and broken water effects on KZ3

https://mega.nz/file/ivpDATyY#RjypFcZaeOQF3y9F4o7lKxiTX-lxBYJ9SRV3eFr-2pQ

### PR: wrong menu on KZ3

image

### Master: good menu on KZ3

image

</br>
</br>
</br>

### PR: blocky raindrops on R3

https://mega.nz/file/z6Y2lSaJ#aHTXV6_JrpY9dcLCzqs1Laqe7dML5Q7fI52i4NsNCSA

### Master: good raindrops on R3

https://mega.nz/file/yy4UVY4I#E26VpdTOvPgGaeIwdLWOG60Kqvv4iadZyByOHOEdeZA

</br>
</br>
</br>

EDIT: Light sources on KZ3 produce bloom (red bloom on the screenshots). This is present only with HW remapping (SW remapping is OK). You can see also wrong lighting on all the environment compared to master

### PR KZ3: red bloom on light sources

image

### Master: proper light sources and lighting on environment (same as on PS3)

kz3_ok

**Comment by Toff-kun** [comment]
This PR brings water rendering in MGS4 much closer to the real PS3:
BLES00246_screenshot_2026_02_23_14_31_40

Real PS3 (taken from [16841](https://github.com/RPCS3/rpcs3/issues/16841)):
420791167-55b668b5-c4f2-4ba7-bc37-fdb1f751b163

Big splashes still cause blocky waves:
BLES00246_screenshot_2026_02_23_12_59_14

[RPCS3.log.gz](https://github.com/user-attachments/files/25492256/RPCS3.log.gz)
[RSX Capture](https://mega.nz/file/EcVBWTgB#SoiPZigGoqS5YiSfs0x1pd8GYIO2q9nqoOc3Fo7dlz0)

**Comment by AniLeo** [comment]
We need the log file for these reports, as we need to know used hardware and drivers.

**Comment by Toff-kun** [comment]
Log (and RSX Capture) added.

**Comment by kd-11** [comment]
@Toff-kun How do the big waves look like on PS3? It's impossible for me to know if the game itself just has a bug or if it's something entirely new to rpcs3.

**Comment by Toff-kun** [comment]
@kd-11 
The river water looks very similar to the real hardware now, but the swamp water looks wrong in general, very dark for some reason. You can see how the swamp water and splashes should look like here:
[YouTube](https://youtu.be/CGKfNAUJB7U?si=sIjGL0r7vhzXAKck&t=11396)

**Comment by cipherxof** [comment]
The lead developer for MGS4 had a presentation where they went over various rendering techniques, and covered the water/ripple effect specifically in the following article: https://game.watch.impress.co.jp/docs/20081204/3dmg4.htm

I'm not sure if it's useful or not, but I figure it would be worth mentioning.

**Comment by kd-11** [comment]
@digant73 
Flickering is fixed now, retest for any remaining issues.

**Comment by digant73** [comment]
> @digant73 Flickering is fixed now, retest for any remaining issues.

yes flickering seems fixed (tested on some games) while colors and reflections are broken on KZ3 (see screenshots I already attached on my previous post). It seems like green and blue components are reduced on some textures.
Raindrops on R3 are still blocky compared to PS3 (even in this case I attached a video on my previous post).

### Missing light reflection on KZ3:

kz3_2

**Comment by digant73** [comment]
light sources are ok with last commit but light reflection on some objects are still broken (e.g. see broken color on rifle)

EDIT: also menus are fixed

kz3_3

**Comment by kd-11** [comment]
The last commit should fix some of the broken games. As for some things remaining blocky - that's fully expected. What we can use hardware formats for is quite limited by desktop APIs. On PS3 every integer format can be interpreted as _SNORM including packed formats. I might check the raindrops but there is a high chance it's just not trivially doable with hardware formats. Of course in the most extreme case these can all be emulated fully using RGBA16F textures at a massive cost to performance but that's not practical for what the emulator is trying to achieve.

**Comment by kd-11** [comment]
> light sources are ok with last commit but light reflection on some objects are still broken (e.g. see broken color on rifle)
> 
> kz3_3

Need RRC for this. I have no idea what could cause the mismatch.

**Comment by digant73** [comment]
here the rrc on the water effect and rifle. As you can see from screenshots, light reflection is missing (on water) or broken (on rifle)

https://mega.nz/file/C6QWQSrL#ZqXSgObFgqgjvkm8W4uP03UKzGuRxQncGVTVjA9Ia7U

PR:

kz3_2

Master:

kz3_4

**Comment by kd-11** [comment]
@digant73 Remaining issues should be fixed now, please check.

**Comment by digant73** [comment]
> @digant73 Remaining issues should be fixed now, please check.

yes, KZ3 is now OK. Testing other games for no-regression

kz3_5

kz3_6

**Comment by MarioSonic2987** [comment]
Fixes pixelated water in Ratchet & Clank: Quest for Booty.

**Before:**
image

**After:**
image

**Comment by digant73** [comment]
@kd-11 with the exception of the blocky raindrops (minor bug for which I will open a bug report just to keep track of the remaining differences with PS3), you can mark #15928 as fixed.

EDIT: just made also some no-regression tests (only visual) on other games and it seems they are ok

**Comment by alexconsole04** [comment]
image

Everything seems good on ratchet's side.

**Comment by digant73** [comment]
> @kd-11 The river water looks very similar to the real hardware now, but the swamp water looks wrong in general, very dark for some reason. You can see how the swamp water and splashes should look like here: [YouTube](https://youtu.be/CGKfNAUJB7U?si=sIjGL0r7vhzXAKck&t=11396)

@Toff-kun please re-test

**Comment by cipherxof** [comment]
Rendering in MGS4 looks broken with this PR. The water also still looks the same.

[RPCS3.zip](https://github.com/user-attachments/files/25531435/RPCS3.zip)

PR:
Screenshot From 2026-02-24 13-49-52

Master:
image

**Comment by AniLeo** [comment]
Rendering in The Lord of the Rings: Conquest is also broken

master
Screenshot_20260224_231327

pr
Screenshot_20260224_231520

I tried undoing [cd8e9a9](https://github.com/RPCS3/rpcs3/pull/18224/commits/cd8e9a9e2b0b32327af00fc31d5cce5625d1ff81) as well as using **Disable Hardware ColorSpace Remapping**, and neither of these fixed the issue

**Comment by kd-11** [comment]
@AniLeo @cipherxof Both should be fixed. It was just a generic regression.

**Comment by Jonathan44062** [comment]
Looks perfect now, but the water texture is the same, maybe is a different problem?
Captura de pantalla 2026-02-24 185608
Captura de pantalla 2026-02-24 185637
Captura de pantalla 2026-02-24 190014
[RPCS3.log.gz](https://github.com/user-attachments/files/25533700/RPCS3.log.gz)

**Comment by Toff-kun** [comment]
> @Toff-kun please re-test

[This](https://github.com/RPCS3/rpcs3/actions/runs/22329548395) version (81b33be8) is the last one with better-looking water. The pause menu has rendering bugs and the resolution scaling is inconsistent. (_I didn't report on those because this PR was marked as a draft._)

[This](https://github.com/RPCS3/rpcs3/actions/runs/22374819247) version (3e0b0428) reverts the water back to its previous "quicksilver" look and fixes the regressions introduced in this PR.

Could it be that the water was simply missing one of the sky reflection layers responsible for the "quicksilver" look, which made it seem like an improvement? Maybe @kd-11 knows the answer.

**Comment by AniLeo** [comment]
LOTR: Conquest now rendering properly again

**Comment by kd-11** [comment]
@Toff-kun Does disabling hardware color formats in the debug tab fix the issue?

**Comment by kd-11** [comment]
MGS4 will be investigated separately as it is not a regression from the PR.

**Comment by Toff-kun** [comment]
> @Toff-kun Does disabling hardware color formats in the debug tab fix the issue?

Nope, doesn't seem to affect the water look.

**Comment by cjghost2000** [comment]
don't know if this helps or has happened to more people but for me and 2 people i've talked too (all full AMD) Yakuza Ishin crashes (rpcs3 + game) once you reach gameplay starting from this build (0.0.39-18847) onward, the last playable build seems to be (0.0.39-18824) #18231
