### PR TITLE
cellPad, cellVdec and sys_process fixes

### LINKED ISSUE #4489: Yakuza 0 & 3, Bugs and Crashes [BLES00834], [BLJM61249]
I'll be leaving here all the problems I have encountered in Yakuza Games, mainly 0 and 3.
All of these issues have been there since the very day they got ingame, there has been a few improvements here and there but the bugs persist.
The build test for the post: https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.5-6692/artifacts

Laptop: i5-7300HQ + GTX 1050 + 16GB RAM

Yakuza 0 (Ryu Ga Gotoku 0) [BLJM61249]
Current issues:

- Pre-rendered cutscenes have stutters (All Yakuza games)
The cutscenes are pretty stuttery even if you have constant 30 FPS.
Log: [Yakuza 0 Pre-Rendered Cutscenes and LogSpam.log.gz](https://github.com/RPCS3/rpcs3/files/1952267/Yakuza.0.Pre-Rendered.Cutscenes.and.LogSpam.log.gz)

- All characters go black (Also at: #4141 )
This one is pretty bizarre, whenever I launch the game sometimes all the characters go black and sometimes they look completely normal.
Upscaling the game and tweaking the AF seem to make this occur almost 100% of the time.
Images: https://imgur.com/a/By0aOrc
Log Normal: [Yakuza 0 Color Normal.log.gz](https://github.com/RPCS3/rpcs3/files/1952261/Yakuza.0.Color.Normal.log.gz)
Log Black: [Yakuza 0 Color Black.log.gz](https://github.com/RPCS3/rpcs3/files/1952262/Yakuza.0.Color.Black.log.gz)

- The blood in combat has a T-Pose Model
This one is self-explanatory with the pictures
Images: https://imgur.com/a/v3AkwyH
Log: [Yakuza 0 Blood T-Pose.log.gz](https://github.com/RPCS3/rpcs3/files/1952263/Yakuza.0.Blood.T-Pose.log.gz)

- 1 FPS Lock (Temporary fix)
The default settings in RPCS3 lock the game to 1FPS, there is a temporary solution that fixes it.
Go to game's config.yml and change Driver Recovery Timeout to a lower ammount.
The lower the value, the higher the framerate, setting around between 1 to 100 is good
Log Value 1: [Yakuza 0 No 1 FPS Lock.log.gz](https://github.com/RPCS3/rpcs3/files/1952271/Yakuza.0.No.1.FPS.Lock.log.gz)
Log Value Default: [Yakuza 0 1 FPS Lock.log.gz](https://github.com/RPCS3/rpcs3/files/1952270/Yakuza.0.1.FPS.Lock.log.gz)

- Log spam: 
_E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x40300FE0_
This simply shows up whenever something is being displayed on the screen, the more frames, the more spam!
Use the log from Pre-rendered cutscenes have stutters. (You'll find this in every log)
Image: https://i.imgur.com/JY26hEH.jpg

- Freezing when going out of focus, no output from the log (All Yakuza games)
Sometimes when you tab out of RPCS3's game window, the game freezes.
You can still control RPCS3, you can't give any input and the audio works flawlessly.
Video: https://youtu.be/oOEm7tXg1sw
Note: The log is not the same as in the video, the one I got here was at the very start of the game
Log: [Yakuza 0 Crash Going Out Of Focus.log.gz](https://github.com/RPCS3/rpcs3/files/1952278/Yakuza.0.Crash.Going.Out.Of.Focus.log.gz)

- Crashes after some time (Driver Crash)
This one is certain, as soon as I go ingame and play for a little while the game will crash, and if I try to shut it down it freezes RPCS3, leaving me the only option to terminate RPCS3 through the task manager.
Error: F {rsx::thread} class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:937)
Image: https://i.imgur.com/kMxjKcX.png
Log: [Yakuza 0 Crash.zip](https://github.com/RPCS3/rpcs3/files/1952280/Yakuza.0.Crash.zip)

Gameplay Video: https://youtu.be/U4ahYjgDCHA

Yakuza 3 [BLES00834]
Current issues:

- Pre-rendered cutscenes have stutters (All Yakuza games)
The cutscenes are pretty stuttery even if you have constant 30 FPS.
Log:  [Yakuza 3 Pre Rendered Cutscenes.log.gz](https://github.com/RPCS3/rpcs3/files/1952247/Yakuza.3.Pre.Rendered.Cutscenes.log.gz)

- Exploding Vertices and Missing Visuals
Early in the game you'll find trees with broken LOD and exploding Vertices.
Images: https://imgur.com/a/kjPkCQ7
Log: [Yakuza 3 Exploding Vertices and Missing Rendering.log.gz](https://github.com/RPCS3/rpcs3/files/1952240/Yakuza.3.Exploding.Vertices.and.Missing.Rendering.log.gz)

- Freezes randomly, no output from the log (All Yakuza games)
The game tends to freeze with no output from the log and its pretty random, sometimes it even freezes at the startup.
Take this one as an Example: https://gfycat.com/BrokenJubilantCockatoo
Log:  [Yakuza 3 Freezing at startup.log.gz](https://github.com/RPCS3/rpcs3/files/1952248/Yakuza.3.Freezing.at.startup.log.gz)

I look forward in providing info, logs, renderdocs or anything, whenever necessary.
Discord: MsLow#2316

### LINKED ISSUE #5713: Regression: Yakuza 1&2 HD EDITION [BLJM60471] (#5244)
i7-8700K @ 4.6GHz | GTX 1070 | 16GB RAM

Yakuza 1&2 HD EDITION no longer goes ingame since #5244 
The game crashes the emulator upon selecting which game you want to play (Y1 or Y2)

The last merged build that worked was in https://github.com/RPCS3/rpcs3/pull/5250
No options seem to help the game to go ingame.

Edit: If we boot Yakuza 1 or Yakuza 2 directly w/ `Boot SELF/ELF` it goes ingame just fine. Its only the selection screen crashing the game.

Log Latest: [RPCS3YLatest.log](https://github.com/RPCS3/rpcs3/files/2958240/RPCS3YLatest.log)
Log of no longer going ingame: [RPCS3Y5244NoWork.log](https://github.com/RPCS3/rpcs3/files/2958256/RPCS3Y5244NoWork.log)
Log Working: [RPCS3Y5250Works.log.gz](https://github.com/RPCS3/rpcs3/files/2958259/RPCS3Y5250Works.log.gz)

### PR DESCRIPTION
**Pull request by elad335**
* Fix passing ASSIGN_CHANGES flag in cellPadGetInfor since its not supported by this function.
* Minor optimizations in pad_thread, use raw ptr when possible and replace std::vector with std::array in m_pads container.
* Fix segfault when reading stack memory in the debugger.
* Remove handle in cellVdecClose.
* Fix page fault range check. (old bug)
* Allow recieving frame information only once in cellVdecGetPicItem, fixes Toy Home. (used to iterate this func infinitely)
* Fix Emulator crash after SPU access violation.
* Fix sys_process_exit2 when waiting for SPUs at av handler to terminate. Fixes #5713 
* Improve vblank timing, fixing potential stutter and micro frame rate spikes.
* Fix timer (sys_timer) state after event queue destruction. [testcase](https://github.com/elad335/myps3tests/tree/master/ppu_tests/timer%20state%20afte%20event%20queue%20destruction)
* Implemented sys_vm_append/return_memory, improved sys_vm error checking.

### CODE REVIEW

File: rpcs3/Emu/Memory/vm.cpp [hunk 1]
```diff
@@ -355,6 +355,7 @@ namespace vm
 		if (!shm)
 		{
 			utils::memory_protect(g_base_addr + addr, size, utils::protection::rw);
+			utils::memory_protect(g_sudo_addr + addr, size, utils::protection::rw);
```
Comment (Nekotekina) [inline rpcs3/Emu/Memory/vm.cpp]: It was supposed to always have rw protection in this case, without the necessity to set it every time. It's a bug in another place.

File: Utilities/Thread.cpp [hunk 2]
```diff
@@ -1394,7 +1394,24 @@ bool handle_access_violation(u32 addr, bool is_writing, x64_context* context)
...
+			LOG_FATAL(MEMORY, "Access violation %s location 0x%x", is_writing ? "writing" : "reading", addr);
+
+			// TODO:
+			// RawSPU: Send appropriate interrupt
+			// SPUThread: Send sys_spu exception event
+			cpu->state += cpu_flag::dbg_pause;
+			if (cpu->check_state())
+			{
+				static_cast<spu_thread*>(cpu)->cpu_stop();
+				throw cpu_flag::exit;
```
Comment (Nekotekina) [inline Utilities/Thread.cpp]: Need better solution than throwing. Seen it somewhere.

File: rpcs3/Emu/Cell/Modules/cellVdec.cpp [hunk 3]
```diff
@@ -84,7 +85,7 @@ struct vdec_context final
 	u64 next_dts{};
 	u64 ppu_tid{};
 
-	std::queue<vdec_frame> out;
+	std::deque<vdec_frame> out;
```
Comment (Nekotekina) [inline rpcs3/Emu/Cell/Modules/cellVdec.cpp]: I don't get why you changed it to deque.

File: rpcs3/Emu/Cell/Modules/cellVdec.h [hunk 4]
```diff
@@ -76,7 +76,7 @@ enum CellVdecFrameRate : s32
 // Codec Type Information
 struct CellVdecType
 {
-	be_t<s32> codecType; // CellVdecCodecType
+	be_t<u32> codecType; // CellVdecCodecType
```
Comment (Nekotekina) [inline rpcs3/Emu/Cell/Modules/cellVdec.h]: I'd prefer to keep their types accurate, even at the cost of bogus check.

File: rpcs3/Emu/Cell/Modules/cellVdec.cpp (hunk 3 above)
Comment (elad335) [reply rpcs3/Emu/Cell/Modules/cellVdec.cpp]: for iteration support.

**Comment by elad335** [comment]
This also fixed Siren Blood Curse halt with hle cellvdec.

**Comment by Parthorisian** [comment]
cant see any flickering for [BLUS30443] - it seems fixes [4587](https://github.com/RPCS3/rpcs3/issues/4857), 3eab2e86 at least

**Comment by uaqlover** [comment]
any update when it will merge to the master thanks again elad : )

File: Utilities/Thread.cpp (hunk 2 above)
Comment (elad335) [reply Utilities/Thread.cpp]: Can you answer what it is? this is the review comment that needs to be solved.

**Comment by elad335** [comment]
Doom 3 [NPUB30889] (nothing ->playable)
image

File: Utilities/Thread.cpp (hunk 2 above)
Comment (Nekotekina) [reply Utilities/Thread.cpp]: It's better to use falloc after emulation is stopped. Throwing is not portable.

File: rpcs3/Emu/Cell/lv2/sys_timer.cpp [hunk 5]
```diff
@@ -93,6 +92,8 @@ error_code sys_timer_destroy(u32 timer_id)
 			return CELL_EISCONN;
 		}
 
+		// Signal thread using invalid state
+		timer.state = -1;
```
Comment (Nekotekina) [inline rpcs3/Emu/Cell/lv2/sys_timer.cpp]: What race?

File: Utilities/Thread.cpp (hunk 2 above)
Comment (elad335) [reply Utilities/Thread.cpp]: ahh, falloc may fail on non-existent blocks.
I've used it in page faults handling because its not the case there.

Comment (Nekotekina) [reply Utilities/Thread.cpp]: May be possible to create a block though. Or use utils::memory_commit instead.

Comment (elad335) [reply Utilities/Thread.cpp]: Added a force flag for falloc, when used block is created automatically.
memory_commit had issues with memory_decommit in vm::close();

File: rpcs3/Emu/Cell/lv2/sys_timer.cpp (hunk 5 above)
Comment (elad335) [reply rpcs3/Emu/Cell/lv2/sys_timer.cpp]: state setting can be replaced with STOP instead of -1.
To solve this I've moved timer.state store to lock scope, and checked the state in the timer thread's lock scope.

Comment (elad335) [reply rpcs3/Emu/Cell/lv2/sys_timer.cpp]: another way to solve it is waiting for the thread to finnish current time check in sys_timer_stop,

Comment (Nekotekina) [reply rpcs3/Emu/Cell/lv2/sys_timer.cpp]: Correct fix is compare_and_swap in timer thread, not removing on_abort.

**Comment by dlim389** [comment]
Does it actually slowdown when running Vulkan API on God of War 1 & 2 HD Collection and God of War Ghost of Sparta and God of War Chains of Olympus?

**Comment by AniLeo** [comment]
Locking to prevent the usual batch of unrelated comments

**Comment by Megamouse** [comment]
@elad335 I just found out that this fixed input in Blazing Angels 2
