### PR TITLE
SPU: Fix FREST

### LINKED ISSUE #5886: SPU LLVM causes wrong pixel colors on several games
Several games have an issue where numerous pixels get the wrong color rendered. Example: In Captain America, there's red/green dots over image only when using SPU LLVM. Fine with ASMJIT. I tried numerous SPU/GFX settings but nothing fixes it unless I switch to ASMJIT. 

**Games Impacted:**
- [ ] Captain America
- [ ] God of War 3 
- [ ] House of the Dead
- [ ] Motorstorm Apocalypse
- [ ] LittleBigPlanet 3
- [ ] Sly Cooper Thieves in Time 

**Captain America screenshots/log :**
LLVM:
2019-04-25 19_52_33-Window

ASMJIT:
2019-04-25 19_46_43-Window

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3119553/RPCS3.log.gz)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

### PR DESCRIPTION
**Pull request by elad335**
Using rcpps instead of divps seem to produce values closer to realhw's, it is unknown if there is a range of values which the difference is so big it would make sense it completely fixes #5886. ~~(testers needed)~~ (tested) Currently fixes it for Captian America on all SPU LLVM variations and SPU Precise interpreter.
It seems there are alot of inaccuracies around frest and frsqesr instructions but it can be fixed after this pr.

TODO: FRSQEST as well?

### CODE REVIEW

**Comment by Xcedf** [comment]
I only have GoW3 from https://github.com/RPCS3/rpcs3/issues/5886's list but it looks totally fine now even on Default path

**Comment by Asinin3** [comment]
While this fixed the white dots in Sly Cooper, there's a big performance loss of 9-13fps loss from this PR when using SPU LLVM at least compared to master.

**Comment by Asinin3** [comment]
Performance seems like it's mostly back with newest commit, was 44fps on master here will check a bit more thoroughly.
image

**Comment by MsDarkLow** [comment]
The white dots is also fixed on Yakuza Ishin (same applies to others) however they were only noticeable when disabling zcull.

Master


PR

**Comment by legend800** [comment]
Fantastic work elad. All those crazy pixels are gone in all the games and I haven't seen any gfx/perf regressions yet. I'll post if that changes. Thanks for the awesome fix!

**Comment by RainbowCookie32** [comment]
DmC Devil May Cry was also affected by this and it's now fixed in this PR.

Master:
DMC_Master

This PR:
DMC_PR

**Comment by slashiee** [comment]
Fixed for LittleBigPlanet 2

<details>
<summary>LBP2</summary>

Master


PR


</details>

**Comment by Wagnard** [comment]
I can confirm weird pixel are fixed for me in GoW 3 with this.

File: rpcs3/Emu/Cell/SPUInterpreter.cpp [hunk 1]
```diff
@@ -1903,21 +1903,20 @@ inline bool isdenormal(double x)
...
 			spu.fpscr.setDivideByZeroFlag(i);
-			result = extended(std::signbit(a), 0x7FFFFF);
+			res._f[i] = extended(std::signbit(a), 0x7FFFFF);
 		}
-		else if (isextended(a))
-			result = 0.0f;
-		else
-			result = 1 / a;
-		spu.gpr[op.rt]._f[i] = result;
+		else if (fexpf(a) >= 253)
```
Comment (kd-11) [inline rpcs3/Emu/Cell/SPUInterpreter.cpp]: Add braces as appropriate to match the if block above. I know the previous implementation had no braces, but code style enforcement was changed since then.

File: rpcs3/Emu/Cell/SPUInterpreter.cpp [hunk 2]
```diff
@@ -1903,21 +1903,20 @@ inline bool isdenormal(double x)
...
+			res._f[i] = 0.0f;
 	}
+	spu.gpr[op.rt] = res;
```
Comment (kd-11) [inline rpcs3/Emu/Cell/SPUInterpreter.cpp]: Space above this line

File: rpcs3/Emu/Cell/SPURecompiler.cpp [hunk 3]
```diff
@@ -7216,9 +7216,14 @@ class spu_llvm_recompiler : public spu_recompiler_base, public cpu_translator
...
-			set_vr(op.rt, fsplat<f64[4]>(1.0) / get_vr<f64[4]>(op.ra));
+		{
+			const auto a = get_vr<f32[4]>(op.ra);
+			const auto mask_ov = sext<s32[4]>(bitcast<s32[4]>(fabs(a)) > splat<s32[4]>(0x7e7fffff));
+			const auto mask_de = eval(noncast<u32[4]>(sext<s32[4]>(fcmp_uno(a == fsplat<f32[4]>(0.)))) >> 1);
+			set_vr(op.rt, (bitcast<s32[4]>(fre(a)) & ~mask_ov) | noncast<s32[4]>(mask_de));
+		}
 		else
-			set_vr(op.rt, fsplat<f32[4]>(1.0) / get_vr<f32[4]>(op.ra));
+			set_vr(op.rt, fre(get_vr<f32[4]>(op.ra)));
```
Comment (kd-11) [inline rpcs3/Emu/Cell/SPURecompiler.cpp]: Braces
