### PR TITLE
Savestate Fixes part 3 out of 3

### LINKED ISSUE #14007: [Regression] Savestates
### Quick summary

Savestates have several regressions.
First creating it isn't possible after: RPCS3/rpcs3/pull/13672
After this pr loading old savestates is imposible: RPCS3/rpcs3/pull/13558
It show this message eaven on the newest build.
image
Games tried: Gran Turismo 5, Ratchet & Clank Future: Tools of Destruction

### Details

_No response_

### Build with regression

v0.0.27-14881

### Attach two log files

Logs will be provided if needed as of this regression includes several builds.

### Attach capture files for visual issues

_No response_

### System configuration

_No response_

### Other details

_No response_

### PR DESCRIPTION
**Pull request by elad335**
Makes savestates a thing again.

Fixes #14007

### CODE REVIEW

**Comment by Ordinary205** [comment]
The game does boot up properly, however this causes more time to build SPU caches, and the performance behaves slower on Midnight Club Los Angeles.
Master:
13 seconds to finish compiling SPU caches.
18.2/20.7/21.4 FPS
Midnight club los angeles performance master
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12774321/RPCS3.log.gz)

PR:
2 minutes 8 seconds to finish compiling SPU caches.
17.1/18.8/19.6 FPS
Midnight Club Los Angeles performance
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12774303/RPCS3.log.gz)

File: rpcs3/Emu/Cell/SPURecompiler.cpp [hunk 1]
```diff
@@ -6071,10 +6170,11 @@ class spu_llvm_recompiler : public spu_recompiler_base, public cpu_translator
 
 						for (auto [a2, b2] : sucs)
 						{
-							auto ins = b2->block->getFirstNonPHI();
-
+								continue;
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/SPURecompiler.cpp:6173]: ?

File: rpcs3/Emu/Cell/SPURecompiler.cpp [hunk 2]
```diff
@@ -4474,6 +4474,11 @@ class spu_llvm_recompiler : public spu_recompiler_base, public cpu_translator
 
 		// Store instructions
 		std::array<llvm::StoreInst*, s_reg_max> store{};
+
+		// Store reordering/elimination protection
+		std::array<usz, s_reg_max> store_context_last_id = fill_array<usz>(0); // Protects against illegal forward ordering
+		std::array<usz, s_reg_max> store_context_first_id = fill_array<usz>(usz{umax}); // Protects against illegal past store elimination (bakcwards ordering is not implemented)
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/SPURecompiler.cpp:4480]:
```suggestion
		std::array<usz, s_reg_max> store_context_first_id = fill_array<usz>(usz{umax}); // Protects against illegal past store elimination (backwards ordering is not implemented)
```

File: rpcs3/Emu/Cell/SPURecompiler.cpp [hunk 3]
```diff
@@ -4474,6 +4474,11 @@ class spu_llvm_recompiler : public spu_recompiler_base, public cpu_translator
 
 		// Store instructions
 		std::array<llvm::StoreInst*, s_reg_max> store{};
+
+		// Store reordering/elimination protection
+		std::array<usz, s_reg_max> store_context_last_id = fill_array<usz>(0); // Protects against illegal forward ordering
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/SPURecompiler.cpp:4479]:
```suggestion
		std::array<usz, s_reg_max> store_context_last_id{}; // Protects against illegal forward ordering
```

File: rpcs3/rpcs3qt/tooltips.h [hunk 4]
```diff
@@ -52,6 +52,7 @@ class Tooltips : public QObject
...
 		const QString disable_msl_fast_math        = tr("Disables Fast Math for MSL shaders, which may violate the IEEE 754 standard.\nDisabling it may fix some artifacts, especially on Apple GPUs, at the cost of performance.");
 		const QString suspend_savestates           = tr("When this mode is on, emulation exits when saving and the savestate file is concealed after loading it, preventing reuse by RPCS3.\nThis mode is like hibernation of emulation: if you don't want to be able to cheat using savestates when playing the game, consider using this mode.\nDo note that the savestate file is not gone completely, just ignored by RPCS3. You can manually relaunch it if needed.");
+		const QString compatible_savestates        = tr("When this mode is on, SPU Emulation is optimized for savestates suitability and compatibility instead at the cost of slight performance downgrade.\nIf this mode is off, attempting to make a savestate may result in an SPU pause error in the log that would disallow doing so for some games.");
```
Comment (Darkhost1999) [inline rpcs3/rpcs3qt/tooltips.h:55]: When this mode is on, SPU emulation prioritizes savestate compatibility, however, it may reduce performance slightly. \nWhen this mode is off, some games may not allow making a savestate and show an SPU pause error in the log.

File: rpcs3/Emu/Cell/SPURecompiler.cpp (hunk 3 above)
Comment (elad335) [reply rpcs3/Emu/Cell/SPURecompiler.cpp:4479]: Dunno what is wrong with explicitly, this is all constexpr anyways so compiler output should be the same.

**Comment by elad335** [comment]
@Darkhost1999 Retest.

**Comment by Ordinary205** [comment]
Still takes the exact same time when building SPU caches. But the performance is slightly better than the master.
SPU cache: 2 minute 8 seconds.
19.2/21.1/21.6 FPS
Midnight Club LA performance
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12776273/RPCS3.log.gz)

**Comment by Ordinary205** [comment]
The SPU caches can now be finished approximately 14 seconds.
And the performance is slightly the same.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12776707/RPCS3.log.gz)
