### PR TITLE
rsx: Fix index vertex array range with modulo calculation

### LINKED ISSUE #9055: {RSX [0x02a6238]} VM: Access violation reading location 0xcf900000 (unmapped memory) (Dynasty Warriors 8 XL)
image

The game crashes when entering a stage, always within the first few seconds. I can get through a few minutes of the tutorial before the same happens.

Debug console mode changes the error from: F {RSX [0x0399668]} VM: Access violation reading location 0xcf900000 (unmapped memory)

To: F {PPU[0x1000000] Thread (main_thread) [0x00441ca4]} VM: Access violation writing location 0x0 (unmapped memory)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5359105/RPCS3.log)

### PR DESCRIPTION
**Pull request by elad335**
In #9055, modulo op with frequency was used on vertex indices wiuth some values already surpoassing frequency divider value. We incorrectly assumed that this means that the upper bound of vertex data memory data is the frequency divider in this case, but actually we still need to check for each element max_index = max(index % frequency, max_index). This is also true for min_index.
This re-iteration over all indices can be quite expensive for this exceptionally rare case, so do it if an access violation is guarenteed due to unallocated memory access. I think this can be optimized in the future for single frequency across the entire vertex arrays but I won't do it in this pr.

Fixes #9055

### CODE REVIEW

File: rpcs3/Emu/RSX/RSXThread.cpp [hunk 1]
```diff
@@ -2586,6 +2695,10 @@ namespace rsx
 		}
 		else
 		{
+			rsx::index_array_type index_type = rsx::method_registers.current_draw_clause.is_immediate_draw ?
```
Comment (Megamouse) [inline rpcs3/Emu/RSX/RSXThread.cpp:2698]: const

File: rpcs3/Emu/RSX/RSXThread.cpp [hunk 2]
```diff
@@ -2798,9 +2911,13 @@ namespace rsx
 
 		if (persistent != nullptr)
 		{
-			for (const auto &block : layout.interleaved_blocks)
+			rsx::index_array_type index_type = rsx::method_registers.current_draw_clause.is_immediate_draw ?
```
Comment (Megamouse) [inline rpcs3/Emu/RSX/RSXThread.cpp:2914]: const

File: rpcs3/Emu/RSX/RSXThread.cpp [hunk 3]
```diff
@@ -2544,7 +2649,11 @@ namespace rsx
 				}
 			}
 
-			persistent_memory_size = layout.calculate_interleaved_memory_requirements(first_vertex, vertex_count);
+			rsx::index_array_type index_type = rsx::method_registers.current_draw_clause.is_immediate_draw ?
```
Comment (Megamouse) [inline rpcs3/Emu/RSX/RSXThread.cpp:2652]: const

File: rpcs3/Emu/RSX/RSXThread.cpp [hunk 4]
```diff
@@ -295,24 +305,119 @@ namespace rsx
...
 					_max_index = std::max<u32>(_max_index, utils::aligned_div(max_index, attrib.frequency));
 				}
 			}
 		}
 
+		while (freq_count > 0 && freq_count != umax)
+		{
+			const u32 index_size = 4 >> static_cast<u32>(type);
+
+
```
Comment (Megamouse) [inline rpcs3/Emu/RSX/RSXThread.cpp:338]: empty line

File: rpcs3/Emu/RSX/RSXThread.cpp [hunk 5]
```diff
@@ -295,24 +305,119 @@ namespace rsx
...
+			// If min cannot get lower and we can access a bit a more memory than required - do it
+			// The alternative would be re-iterating again over all of them
+			if (_min_index == 0)
+			{
+				const auto render = rsx::get_current_renderer();
```
Comment (Megamouse) [inline rpcs3/Emu/RSX/RSXThread.cpp:343]: should go in the scope below

File: rpcs3/Emu/RSX/RSXThread.cpp [hunk 6]
```diff
@@ -295,24 +305,119 @@ namespace rsx
...
+
+				auto ptr = vm::_ptr<u32>(address);
+
+				for (u32 _index = first; _index < first + count; _index++)
+				{
+					const u32 value = ptr[_index];
+
+					for (u32 freq_it = 0; freq_it < freq_count; freq_it++)
+					{
+						u32 res = value % frequencies[freq_it];
```
Comment (Megamouse) [inline rpcs3/Emu/RSX/RSXThread.cpp:374]: const

File: rpcs3/Emu/RSX/RSXThread.cpp [hunk 7]
```diff
@@ -295,24 +305,119 @@ namespace rsx
...
+
+				auto ptr = vm::_ptr<u16>(address);
+
+				for (u32 _index = first; _index < first + count; _index++)
+				{
+					const u32 value = ptr[_index];
+
+					for (u32 freq_it = 0; freq_it < freq_count; freq_it++)
+					{
+						u32 res = value % frequencies[freq_it];
```
Comment (Megamouse) [inline rpcs3/Emu/RSX/RSXThread.cpp:401]: const

File: rpcs3/Emu/RSX/RSXThread.cpp [hunk 8]
```diff
@@ -295,24 +305,119 @@ namespace rsx
...
+						if (res < _min_index)
+						{
+							_min_index = value;
+						}
+					}
+				}
+			}
+
+			break;
+		}
```
Comment (Megamouse) [inline rpcs3/Emu/RSX/RSXThread.cpp:417]: newline after scope

File: rpcs3/Emu/RSX/RSXThread.cpp [hunk 9]
```diff
@@ -295,24 +305,119 @@ namespace rsx
 						// Actually uses the modulo operator
 						_min_index = 0;
 						_max_index = attrib.frequency - 1;
+
+						if (freq_count != umax)
+						{
+							if (std::find(std::begin(frequencies), std::begin(frequencies) + freq_count, attrib.frequency) == std::begin(frequencies) + freq_count)
+							{
+								frequencies[freq_count++] = attrib.frequency;
```
Comment (Megamouse) [inline rpcs3/Emu/RSX/RSXThread.cpp:313]: how is ensured that freq_count is not >= 16 ?

File: rpcs3/Emu/RSX/RSXThread.cpp [hunk 10]
```diff
@@ -295,24 +305,119 @@ namespace rsx
...
 				{
 					// Division operator
+					freq_count = umax;
 					_min_index = std::min(_min_index, first / attrib.frequency);
 					_max_index = std::max<u32>(_max_index, utils::aligned_div(max_index, attrib.frequency));
 				}
 			}
 		}
 
+		while (freq_count > 0 && freq_count != umax)
```
Comment (Megamouse) [inline rpcs3/Emu/RSX/RSXThread.cpp:334]: what's the purpose of a loop if you always break in the first iteration?

File: rpcs3/Emu/RSX/RSXThread.cpp [hunk 11]
```diff
@@ -295,24 +305,119 @@ namespace rsx
...
+						if (res < _min_index)
+						{
+							_min_index = value;
+						}
+					}
+				}
+			}
+			else
+			{
+				// See above
```
Comment (Megamouse) [inline rpcs3/Emu/RSX/RSXThread.cpp:390]: template lambdas are a thing in c++20 afaik

File: rpcs3/Emu/RSX/RSXThread.cpp (hunk 10 above)
Comment (elad335) [reply rpcs3/Emu/RSX/RSXThread.cpp:334]: because `break`.

Comment (Megamouse) [reply rpcs3/Emu/RSX/RSXThread.cpp:334]: makes no sense.

Comment (elad335) [reply rpcs3/Emu/RSX/RSXThread.cpp:334]: But this is C++, you can't break inside a regular block.

File: rpcs3/Emu/RSX/RSXThread.cpp [hunk 12]
```diff
@@ -295,24 +305,101 @@ namespace rsx
...
+						{
+							_min_index = value;
+						}
+					}
+				}
+			};
+
+			if (index_size == 4)
+			{
+				re_evaluate(u32{});
```
Comment (Megamouse) [inline rpcs3/Emu/RSX/RSXThread.cpp:390]: weird right?
I stumbled upon the same issue lol

Comment (Megamouse) [reply rpcs3/Emu/RSX/RSXThread.cpp:390]: Maybe just pass "auto ptr = vm::get_super_ptr<u32>(address);" here and use auto in the lambda.
Then there would be no such useless param.

File: rpcs3/Emu/RSX/RSXThread.cpp [hunk 13]
```diff
@@ -294,25 +308,100 @@ namespace rsx
 					{
 						// Actually uses the modulo operator
 						_min_index = 0;
-						_max_index = attrib.frequency - 1;
+						_max_index = std::max<u32>(_max_index, attrib.frequency - 1);
```
Comment (elad335) [inline rpcs3/Emu/RSX/RSXThread.cpp:311]: This is another bugfix, it should do max not assign,

Comment (kd-11) [reply rpcs3/Emu/RSX/RSXThread.cpp:311]: No, it shouldn't. This is a memory range to read, we should never read above the modulo wraparound.

File: rpcs3/Emu/RSX/RSXThread.cpp (hunk 9 above)
Comment (kd-11) [reply rpcs3/Emu/RSX/RSXThread.cpp:317]: This is a very hot path, if you can do without loops it would be best.

File: rpcs3/Emu/RSX/RSXThread.cpp (hunk 13 above)
Comment (kd-11) [reply rpcs3/Emu/RSX/RSXThread.cpp:311]: Ah, nvm, its correct because of the attrib loop.

File: rpcs3/Emu/RSX/RSXThread.cpp [hunk 14]
```diff
@@ -294,25 +308,100 @@ namespace rsx
...
 				}
 			}
+
+			_max_index = 0;
+			_min_index = first;
+
+			// Force aligned indices as realhw
+			const u32 address = (0 - index_size) & get_address(rsx::method_registers.index_array_address(), rsx::method_registers.index_array_location());
+
+			auto re_evaluate = [&](auto ptr)
```
[the remark this answers is not in the document]
Comment (kd-11) [reply rpcs3/Emu/RSX/RSXThread.cpp:367]: Iterating over the IB is way too slow for this to be a real fix.

**Comment by elad335** [comment]
I added a debug message for when this fallback is hit named "This sucks" in red error message, please test many games and upload logs if you see it spammed fequantly.
In the game in the issue it is about once per second.

**Comment by Ordinary205** [comment]
I've tested most of the games and haven't noticed a single error named "This sucks".
So it seems fine to me.

**Comment by ReLyf47** [comment]
No other game except specifically the DW series spits out "This Sucks"
so it doesnt affect other game
but it makes DW games works

**Comment by arcadee1977** [comment]
GT6 have broken graphic in this PR
