### PR TITLE
SPU: Lock-line reservation optimizations + Savestates bugfix

### LINKED ISSUE #12513: Trying to load a Demon's Souls savestate with the UNLOCK FPS patch enabled crashes the entire emulator
### Quick summary
UPDATE: After a bit of troubleshooting i found that the issue lies on the UNLOCK FPS game patch. If the game runs at 60 fps the savestates will not work. I am unsure if this affects all games or Demon's Souls only. If i disable this patch the savestates work. What i wrote below is what my post was first about, i will not edit that as there may be info that you guys may find useful in it. 

Trying to load a savestate for Demon's Souls crashes the entire emulator. The game screen will appear but it will be frozen and after a few seconds the emulator will close and i have to launch it again. 

### Details

When i try to load my savestate the game loads and i get a single frame of the game, pretty much a screenshot of where i left off and then it freezes. After waiting about 2-3 seconds the entire emulator, not just the game, crashes. The emulator does not re-open itself, i have to manually launch it again. I have tried to make a new character and use a different save slot and save in different places in the game but nothing worked. 

I have tried savestates in Shadow Of Colossus and they worked perfectly there, never had a problem, i used them multiple times. 
I understand you guys also say to send my TTY.log file but i checked it myself and it was empty, so i didn't send it. I only sent the RPCS3.log file. 

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9334285/RPCS3.log)

### Attach capture files for visual issues

_No response_

### System configuration

Windows 10 64 bit Home Edition

AMD Ryzen 5 3600x

RTX 2060 Version 516.59 (Not the latest but very close, i tried savestates in Demon's Souls with latest version before and they didn't work)

16GB RAM

### Other details

My version of Demon's Souls is: BLUS30443     Version: 1.00

I deleted all the shader cache and that did not fix the issue.

My RPCS3 is updated to the latest version.

I have tried to load savestates in Demon's Souls for ages now and they have never worked, even before you guys made the official announcement that the feature was live. I tried 1 week ago as well, yesterday and right before making this post. They have never worked for me in Demon's Souls.

### PR DESCRIPTION
**Pull request by elad335**
* "SPU GETLLAR polling detection" setting (which was yielding resources when it's set to true) has been transformed to "SPU Reservation Busy Waiting Percentage" and is off ("0") by default. (0 is yielding resources, 100 is always busy-waiting)
* It's now responsible for SPU events waiting as well, so the yielding can be replaced with busy-waiting there. You can test if you get perf gains with it set to on if your CPU has many threads. 
* It's not allowed to be changed for TSX users because TSX is very sensitive to memory touching. It's always as if this setting is set to "0" for it.
* Fix the detection of GETLLAR spin and optimize the actual yielding.
* Add some more minor optimizations.
* Fix PPU HLE injection.
* Fix PPU function analysis for savestates.
* Added an experimental SPU setting called "SPU Accurate Reservations" which may benefit CPUs, especially without TSX when set to "false" ("true" is the default and was the default before this pull request). Game config file only atm.
* Detect PPU lwmutex updates, do not notify SPU threads when it's detected.
* Implement specialized atomic waiting for SPU reservations - emphasizing on cheap thread sleep entering and exiting cost.
* Disable notifications when no data was changed in PUTLLC.

This pull request is known to fix audio stutters and heavy framerate drops in Demon Souls for low threaded CPUs.
Fixes #12513

### CODE REVIEW

**Comment by elad335** [comment]
Added experimental SPU setting called "SPU Inaccurate Reservations" which may benefit non-TSX users. Game config file only atm.

**Comment by Nerboruto** [comment]
generally it seems to keep 30 fps better and more fluidity on xeon e5450 quadcore 3 ghz, without changing the optimizations I have on at the moment, 3 spurs threads ... 
the heaviest scene is the one in the picture only that the values ​​I get are discordant and perhaps depend on windows scheduler, between 20 and 23fps we dance 3fps. some times it starts at 20 others at 23...
it would take a more empirical method to test however it seems more fluid...

rpcs3 2022-08-18 12-30-29
rpcs3 2022-08-18 12-34-14

**Comment by elad335** [comment]
@Nerboruto Tested with inaccurate SPU reservations?

**Comment by Nerboruto** [comment]
> @Nerboruto Tested with inaccurate SPU reservations?

I have not tried to change anything in config, now I'm going to try again ..

**Comment by Nerboruto** [comment]
> @Nerboruto Tested with inaccurate SPU reservations?

Accurate RSX reservation access: false

I also tried to enable it but it doesn't change anything in the initial scene. it seems more fluid with the pr but unfortunately I don't have a way to evaluate it correctly because sometimes it starts at 20fps others at 23fps ...

**Comment by elad335** [comment]
Fixed a bug which made the new setting randomly not optimize.

**Comment by Nerboruto** [comment]
i tried with spu inaccurate reservation false and true...
unfortunately I still have the margin for error ... i also read 24fps.
it seems to be smoother but I have no way of having actual proof.
the game fluctuates between 20 and 30 but is more on 30, the slowdowns are there in some places.

**Comment by Nerboruto** [comment]
> Added another optimization, please test and report performance regressions.

unfortunately I have some work to do, when I come back tonight I will do other tests, I hope someone else will help in the meantime. however this emulator starts to perform really well with DS even on old hardware.

**Comment by Nerboruto** [comment]
well first i attach my config to see if i'm wrong something, i set it to true..
I have not seen any regression.
I put the master back to compare and in the opening scene there are about + 2fps of difference for the pr.
I tried to play a bit but the difference is obvious, pr has much more consistent and high minimum fps. in short, it is a nice performance improvement.

[config_BLES00932.zip](https://github.com/RPCS3/rpcs3/files/9376201/config_BLES00932.zip)

**Comment by Nerboruto** [comment]
I tried the latest build of the pr and considered that audio on DS is now completely free of stuttering thanks to various optimizations, I also tried to enable spu loop detection which provides approximately +1fps which perhaps helps to free up cpu.

File: rpcs3/Emu/RSX/RSXZCULL.cpp [hunk 1]
```diff
@@ -323,9 +325,13 @@ namespace rsx
...
-			rsx::reservation_lock<true> lock(sink, 16);
-			auto report = vm::get_super_ptr<atomic_t<CellGcmReportData>>(sink);
-			report->store({ timestamp, value, 0 });
+			{
+				rsx::reservation_lock<true> lock(sink, 16);
+				auto report = vm::get_super_ptr<atomic_t<CellGcmReportData>>(sink);
+				report->release({ timestamp, value, 0 });
+			}
+
+			vm::reservation_notifier(sink).notify_all(-128);
```
Comment (kd-11) [inline rpcs3/Emu/RSX/RSXZCULL.cpp:334]: I'm pretty sure this is undesired. notify_all is slow and we often have to pause everything to drain a large number of zcull objects.

File: rpcs3/Emu/Cell/Modules/cellSpurs.cpp [hunk 2]
```diff
@@ -2408,21 +2456,30 @@ s32 _spurs::add_workload(ppu_thread& ppu, vm::ptr<CellSpurs> spurs, vm::ptr<u32>
...
 	});
 
-	vm::atomic_op<true>((wnum <= 15 ? spurs->wklSignal1 : spurs->wklSignal2), [&](be_t<u16>& data)
+	(wnum <= 15 ? spurs->wklSignal1 : spurs->wklSignal2).atomic_op([&](be_t<u16>& data)
 	{
 		data &= ~(0x8000 >> index);
 	});
 
-	spurs->wklFlagReceiver.compare_and_swap(wnum, 0xff);
+	if (spurs->wklFlagReceiver == wnum)
```
Comment (kd-11) [inline rpcs3/Emu/Cell/Modules/cellSpurs.cpp:2473]: Why if..cmpxchg?

Comment (elad335) [reply rpcs3/Emu/Cell/Modules/cellSpurs.cpp:2473]: Relaxed operation if succeeds, better performance.

File: rpcs3/Emu/Cell/SPUThread.cpp [hunk 3]
```diff
@@ -3387,31 +3414,86 @@ bool spu_thread::process_mfc_cmd()
...
+				// Last check for event before we replace the reservation with a new one
+				if (reservation_check(raddr, rdata))
+				{
+					set_events(SPU_EVENT_LR);
+				}
+			}
+			else
+			{
+				// Check if we can reuse our existing reservation
+				if (rtime == vm::reservation_acquire(addr) && cmp_rdata(rdata, data))
```
Comment (kd-11) [inline rpcs3/Emu/Cell/SPUThread.cpp:3430]: This seems like we can skip some steps later if you go with reservation_try_lock + cmp_rdata for the optimistic path.

File: rpcs3/Emu/Cell/Modules/cellSpurs.cpp (hunk 2 above)
Comment (kd-11) [reply rpcs3/Emu/Cell/Modules/cellSpurs.cpp:2473]: I get that, but I'm wondering if the optimization is worth it. Mostly for 2 reasons, I don't know often this call is made say in one second, and also is regular cmpxchg that slow? I know cmpxchg16b is bad, but this is the regular 4 byte version. Is it that much more likely that the condition is false? I'm not familiar with the HLE cellSpurs methods.

Comment (kd-11) [reply rpcs3/Emu/Cell/Modules/cellSpurs.cpp:2473]: Maybe a comment there would help.

File: rpcs3/Emu/Cell/SPUThread.cpp (hunk 3 above)
Comment (elad335) [reply rpcs3/Emu/Cell/SPUThread.cpp:3430]: I'm not sure I umderstand the motivation behind this, the reads are relaxed and locking can make other threads lose their reservation.

Comment (kd-11) [reply rpcs3/Emu/Cell/SPUThread.cpp:3430]: I mean, in the case of success, you're still trampling rdata which will still make the other threads lose their reservation.
With try_lock you have the benefit of skipping a second atomic_load + cmp_rdata. In the worst case the outcome should be very similar with the only difference between them being relaxed compare vs atomic cas fail.

Comment (kd-11) [reply rpcs3/Emu/Cell/SPUThread.cpp:3430]: cmp_rdata is just not cheap enough to avoid the cas

Comment (elad335) [reply rpcs3/Emu/Cell/SPUThread.cpp:3430]: Second cmp_rdata is needed regardless of locking when using accurate getllar, this is a special way to load any amount of data atomically on any CPU I think.

Comment (kd-11) [reply rpcs3/Emu/Cell/SPUThread.cpp:3430]: Ok, got it.

File: rpcs3/Emu/Cell/Modules/cellSpurs.cpp (hunk 2 above)
Comment (kd-11) [inline rpcs3/Emu/Cell/Modules/cellSpurs.cpp:2473]: A [[likely]] or [[unlikely]] annotation would greatly help with readability and valuation of intent here.

**Comment by Hasster1** [comment]
i5-4210u - Doesn't help with audio stutters. Am i doing something wrong?
Tried with and without SPU Inaccurate Reservations, no difference.

https://user-images.githubusercontent.com/20757715/185735991-81b66f4d-813d-4e16-8319-5e716162958b.mp4

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9386502/RPCS3.log)

**Comment by readywer** [comment]
Hasster1
That cpu is way below the recommended spec. Likely the audio threads are starving thats why you have audio  stutters.

**Comment by elad335** [comment]
It's because I made a typo in 537cb3c0dea4f559e4517863a945fc0e22741f12

**Comment by Nerboruto** [comment]
> i5-4210u - Doesn't help with audio stutters. Am i doing something wrong? Tried with and without SPU Inaccurate Reservations, no difference.
> 
>  Nope.mp4 
> [RPCS3.log](https://github.com/RPCS3/rpcs3/files/9386502/RPCS3.log)

i5-4210u is a cpu with only 2 cores + hyperthreading, in my opinion we need at least 4 real cores for this game.

**Comment by Nerboruto** [comment]
I have a strong doubt...
Inaccurate SPU Reservations: false or true in config?

**Comment by elad335** [comment]
true.

**Comment by Hasster1** [comment]
Downloaded latest commit. For some reason, it started to frequently freeze / crash (Just closes the game without any message) in different places (before the into, while loading the save, etc). Cleaned up SPU cache, and for some reason this thing started to appear.

https://user-images.githubusercontent.com/20757715/185742719-86222f34-c584-40cb-a284-d6e7b150a656.mp4

Updated to the latest mater build, it wasn't there. Went back to this pull - It started to freeze/crash again.
Here's the log with a bunch of attempts at booting the game, the second one was a success, and after it i cleaned up the cache again. After that, every single boot resulted in closing the game.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9386937/RPCS3.log)

After that, i have opened rpcs3, deleted spu cache once again, booted demon's souls, and it closed the game while trying to load my save.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9386965/RPCS3.log)

Tried it again, and this time it froze before showing any graphics.
image
(Can't upload the log for some reason, infinite uploading)


Yeah, my CPU is terrible, but if i overclock it (which i can't do, because it's a laptop), the cpu will probably melt through the laptop.

**Comment by Hasster1** [comment]
Managed to load the game, this time there was no graphical artifacts. That was probably something else. But the freezes/crashes are definitely present.

**Comment by Nerboruto** [comment]
> Managed to load the game, this time there was no graphical artifacts. That was probably something else. But the freezes/crashes are definitely present.


I did the test with the latest build cleared the cache on shaders etc ..
no problem super fluid all at 30fps especially in the first part which is lighter.
no crash freaze and vertex explosion.

rpcs3 2022-08-20 13-44-41

**Comment by Hasster1** [comment]
Disabled SPU Inaccurate Reservations, fixed all of these crashes. Should've disabled it in the first place.

**Comment by Hasster1** [comment]
Doesn't matter whether you delete spu cache or not, it still might crash/freeze, or it might play normally for a while. Looks like i'm the only one with that problem.

**Comment by Nerboruto** [comment]
> Doesn't matter whether you delete spu cache or not, it still might crash/freeze, or it might play normally for a while. Looks like i'm the only one with that problem.

time ago when I tried this game on dualcore cpu already crashes on character selection while on quad core it worked.
I'm talking about an old version of the emulator.
i haven't tried it on that cpu anymore, but i could do it to see if the problem still exists.

**Comment by AhayriSG** [comment]
[config + json files for capframeX.zip](https://github.com/RPCS3/rpcs3/files/9387154/config.%2B.json.files.for.capframeX.zip)
image
image
image
image

**Comment by Hasster1** [comment]
> time ago when I tried this game on dualcore cpu already crashes on character selection while on quad core it worked. I'm talking about an old version of the emulator. i haven't tried it on that cpu anymore, but i could do it to see if the problem still exists.

I mean with the Inaccurate SPU reservations. Without it, the game runs just great.

**Comment by Nerboruto** [comment]
on my dualcore DS does not start, it crashes while creating the spu cache with this error 👍 
F {PPU[0x1000000] Thread (main_thread) [0x00028310]} SIG: Thread terminated due to fatal error: Null function: roundevenf
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\Utilities\JIT.cpp:399[:22], in function null) (error=0x7e)

**Comment by Nerboruto** [comment]
> [config + json files for capframeX.zip](https://github.com/RPCS3/rpcs3/files/9387154/config.%2B.json.files.for.capframeX.zip) image image image image

excellent I have never used it. I have to look for a tutorial on how to use it. tried on the fly opens and closes without doing anything.

**Comment by elad335** [comment]
@Hasster1 Thanks, seemingly fixed it and some performance miss-optimizations with it.

**Comment by Hasster1** [comment]
> @Hasster1 Thanks, seemingly fixed it and some performance miss-optimizations with it.

Wonderful job, nothing is freezing/crashing anymore with the inaccurate SPU reservations. Thank you.

**Comment by Hasster1** [comment]
Looks like Inaccurate SPU Reservations breaks InFamous. Freezes right after the intro without any errors.
image
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9387974/RPCS3.log)

File: rpcs3/Emu/system_config.h [hunk 4]
```diff
@@ -41,6 +41,7 @@ struct cfg_root : cfg::node
 		cfg::_enum<spu_block_size_type> spu_block_size{ this, "SPU Block Size", spu_block_size_type::safe };
 		cfg::_bool spu_accurate_getllar{ this, "Accurate GETLLAR", false, true };
 		cfg::_bool spu_accurate_dma{ this, "Accurate SPU DMA", false };
+		cfg::_bool spu_inaccurate_reservations{ this, "Inaccurate SPU Reservations", false };
```
Comment (Nekotekina) [inline rpcs3/Emu/system_config.h:44]: It's only confusing this way. Change it to "Accurate"=true please.

File: rpcs3/Emu/Cell/PPUThread.cpp [hunk 5]
```diff
@@ -3392,6 +3454,19 @@ bool ppu_initialize(const ppu_module& info, bool check_only)
 				}
 			}
 
+			if (jit)
+			{
+				const auto far_jump = ppu_get_far_jump(func.addr) ? g_fxo->get<ppu_far_jumps_t>().gen_jump(func.addr) : nullptr;
+
+				if (far_jump)
+				{
+					// Replace the function with ppu_far_jump
```
Comment (Nekotekina) [inline rpcs3/Emu/Cell/PPUThread.cpp:3463]: I don't think it works as intended. Module-local jumps don't use the global mapping.

Comment (elad335) [reply rpcs3/Emu/Cell/PPUThread.cpp:3463]: Yes but it updates its PPU hash and forces recompilation. That's how it was handled before.

**Comment by Hasster1** [comment]
Latest commits have fixed InFamous with inaccurate SPU reservations enabled.

**Comment by Hasster1** [comment]
Excuse me, what?
image
Also i can't find that the inaccurate reservations are enabled in the logs.
image

File: rpcs3/Emu/Cell/PPUThread.cpp (hunk 5 above)
Comment (Nekotekina) [reply rpcs3/Emu/Cell/PPUThread.cpp:3463]: That's good but how forcing recompilation would handle local branches? Especially with PPUTranslator having far jump part removed.

**Comment by Hasster1** [comment]
Oh, i see that it's been reversed to avoid confusion. Sorry.

File: rpcs3/Emu/Cell/PPUThread.cpp (hunk 5 above)
Comment (elad335) [reply rpcs3/Emu/Cell/PPUThread.cpp:3463]: It uses the global table now if I'm not mistaken because the function is removed from llvm, that's why it installs the LLVM value manually.

Comment (elad335) [reply rpcs3/Emu/Cell/PPUThread.cpp:3463]: The code below is responsie for its compilation in llvm and that's skipped.

Comment (Nekotekina) [reply rpcs3/Emu/Cell/PPUThread.cpp:3463]: Okay, I see now.
