### PR TITLE
cellMusic: Implement some error checking

### LINKED ISSUE #2526: WWE SmackDown vs. Raw 2009 / WWE Legends of WrestleMania - sys_mutex_destroy failed
Tested by https://github.com/RPCS3/rpcs3/commit/ed711c0e59abab4900f0ea2b30c084f4dacd8100

Both of these games have the same issue and hangs at the same point (after movies)

**WWE SmackDown vs. Raw 2009**
`E {PPU[0x1000016] Thread (CMovieControlPS3) [0x00a3d84c]} 'sys_mutex_destroy' failed with 0x8001000a : CELL_EBUSY`
[LOG](https://mega.nz/#!uE0w1BzR!YW4WxX8esFR8lvo62QUHD9Qa7ayIkgvTRu6upaFk2IU)

**WWE Legends of WrestleMania**
`E {PPU[0x1000016] Thread (CMovieControlPS3) [0x00946ac4]} 'sys_mutex_destroy' failed with 0x8001000a : CELL_EBUSY`
[LOG](https://mega.nz/#!zMUDmKKR!nd1wtBpkXw8U2W-jg9-1EBD0p8zmGubIgI1SzZ6Pc4A)

### PR DESCRIPTION
**Pull request by elad335**
Check if we have an attached context.

fixes #2526. 
Based on hw test https://github.com/elad335/myps3tests/commit/23826062007a255e225b5c5e3d3e2beca5b813d1.

### CODE REVIEW

File: rpcs3/Emu/Cell/Modules/cellMusicSelectionContext.cpp [hunk 1]
```diff
@@ -242,6 +242,7 @@ bool music_selection_context::load_playlist()
 		playlist.push_back(track_node[i].Scalar());
 	}
 
+	valid = true;
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellMusicSelectionContext.cpp:245]: And when is it set to false?

Comment (elad335) [reply rpcs3/Emu/Cell/Modules/cellMusicSelectionContext.cpp:245]: Fixed.
