### PR TITLE
SPU/PPU LLVM: Fixups and minor optimizations

### LINKED ISSUE #14555: [Regression] Jak and Daxter Collection crash with PPU LLVM after #14547
### Quick summary

Every individual Jak game crashes on the first loading screen when using the PPU recompiler. 

### Details

Ever since #14547 this effect happens all the time, although I would hesitate to call it a regression because this error happened before when you load the games in a savestate, it's just that that pull somewhat melded the problem into the regular launching cycle so now it happens all the time. Windows 10 crashes to desktop but Steam Deck just gets caught in a loop, saying something about PPU thread GOAL(the proprietary scripting language for the Jak games).

### Attach a log file

[RPCS3Win10JakInter.log](https://github.com/RPCS3/rpcs3/files/12444449/RPCS3Win10JakInter.log)
[RPCS3Win10JakLLVM.log](https://github.com/RPCS3/rpcs3/files/12444450/RPCS3Win10JakLLVM.log)
[RPCS3Win10JakLLVMWorking.log](https://github.com/RPCS3/rpcs3/files/12444455/RPCS3Win10JakLLVMWorking.log)
[RPCS3Win10JakLLVMSavestate.log](https://github.com/RPCS3/rpcs3/files/12444457/RPCS3Win10JakLLVMSavestate.log)

### Attach capture files for visual issues

_No response_

### System configuration

- SYS: AMD Ryzen 5 3600 6-Core Processor | 12 Threads | 15.95 GiB RAM | TSC: 3.600GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19045, Service Pack: none, Compatibility mode: 0
- SYS: Current Time: 2023-08-25T19:46:42
- RSX: Found Vulkan-compatible GPU: 'NVIDIA GeForce RTX 2070 SUPER' running on driver 522.25.0.0
- SYS: Firmware version: 4.88

### Other details

_No response_

### LINKED ISSUE #14600: [Regression] God of War Ascension causes RPCS3 to CTD after starting a New Game on a new profile since v0.0.29-15528 #14547
### Quick summary

Issue as per title. 

This crash only affects starting a New Game on a new profile, older saves created before this build and chapter replays can be loaded without issue. 

### Details

Last working build is v0.0.29-15526 https://github.com/RPCS3/rpcs3/pull/14545

image

Reproduction Steps:-

1. Boot up the game on v0.0.29-15528 or newer and start a new profile.
2. Start a New Game at any difficulty.
3. Game and rpcs3 will CTD after a loading attempt.

### Build with regression

v0.0.29-15528-82c5c4d2

### Attach two log files

Build with regression (0.0.29-15528)
[RPCS3 15528 bad.log](https://github.com/RPCS3/rpcs3/files/12503071/RPCS3.15528.bad.log)

Working build
[RPCS3 15526 good.log.gz](https://github.com/RPCS3/rpcs3/files/12503072/RPCS3.15526.good.log.gz)

### Attach capture files for visual issues

_No response_

### System configuration

SYS: 12th Gen Intel(R) Core(TM) i7-12700KF | 20 Threads | 63.86 GiB RAM | TSC: 3.610GHz | AVX+ | FMA3
SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 19044, Service Pack: none, Compatibility mode: 0
RSX: Found Vulkan-compatible GPU: 'NVIDIA GeForce RTX 2080 Ti' running on driver 537.13.0.0
SYS: Firmware version: 4.88

### Other details

_No response_

### LINKED ISSUE #14613: [Regression] Unchated 3 - Crashes in Chapter 15
### Quick summary

Once you complete the chapter 14, the emulator itself closes, and if you're gonna to load the save, it crashes and the emulator closes 

### Details

Working 0.0.29-15526
image

Broken 0.0.29-15528 (https://github.com/RPCS3/rpcs3/pull/14547)
https://github.com/RPCS3/rpcs3/assets/78843189/e1ebd4c6-2240-422c-9a57-221f2a324834

### Build with regression

0.0.29-15528

### Attach two log files

[UC3_Working.log.gz](https://github.com/RPCS3/rpcs3/files/12508438/UC3_Working.log.gz)

UC3 Broken -> [RPCS3.log](https://github.com/RPCS3/rpcs3/files/12508446/RPCS3.log)

### Attach capture files for visual issues

_No response_

### System configuration

Windows 10 22H2
Intel Core i7-8700
15.93 GiB RAM
GPU: NVIDIA GeForce GTX 1070 Ti (537.13)

### Other details

_No response_

### PR DESCRIPTION
**Pull request by elad335**
* Fix greedy PPU instruction search, there was a typo there and it was not considering BCLR and BCCTR.
* Add an optimization for PPU LLVM whener there are direct-unconditional branches following one another or ending up in an empty function (BLR).
* Add an optimization regarding PPU traps conditions, detect "always trap" forms and detect possible but theorectical simple "inequality" trap form. (either when both signed greater/lower or unsigned greater/lower are set).
* Improve SPU LLVM precompilation a bit.
* PPU LLVM: Patch unregistered BLRs.

May fix #14555
May fix #14600
May fix #14613

### CODE REVIEW

**Comment by elad335** [comment]
Caution: invalidates cache of some games.

**Comment by Nekotekina** [comment]
I didn't get why it's supposed to invalidate caches?

**Comment by elad335** [comment]
Because of the analyzer fixes.

**Comment by JimScript** [comment]
Hey, Jak and Daxter works again, even the savesates load now(and the precompiling is pretty fast too).

**Comment by solarmystic** [comment]
Confirmed to fix #14600 

Starting a New Game on a new profile works again.

image

File: rpcs3/Emu/Cell/PPUAnalyser.cpp [hunk 1]
```diff
@@ -1845,8 +1887,8 @@ bool ppu_module::analyse(u32 lib_toc, u32 entry, const u32 sec_end, const std::b
 								break;
 							}
 						}
-						else if (u32 target0 = (test_op.aa ? 0 : target) + (type == ppu_itype::B ? +test_op.bt24 : +test_op.bt14);
-							target0 < segs[0].addr || target0 >= segs[0].addr + segs[0].size)
+						else if (u32 target0 = (test_op.aa ? 0 : target) + (type0 == ppu_itype::B ? +test_op.bt24 : +test_op.bt14);
+							(type0 == ppu_itype::B || ppu_itype::BC) && target0 < segs[0].addr || target0 >= segs[0].addr + segs[0].size)
```
Comment (oltolm) [inline rpcs3/Emu/Cell/PPUAnalyser.cpp:1891]: Clang produces warnings:

```
[94/535] Building CXX object rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/Cell/PPUAnalyser.cpp.obj
C:/src/rpcs3/rpcs3/Emu/Cell/PPUAnalyser.cpp:1891:31: warning: converting the enum constant to a boolean [-Wint-in-bool-context]
                                                        (type0 == ppu_itype::B || ppu_itype::BC) && target0 < segs[0].addr || target0 >= segs[0].addr + segs[0].size)
                                                                               ^
C:/src/rpcs3/rpcs3/Emu/Cell/PPUAnalyser.cpp:1891:49: warning: '&&' within '||' [-Wlogical-op-parentheses]
                                                        (type0 == ppu_itype::B || ppu_itype::BC) && target0 < segs[0].addr || target0 >= segs[0].addr + segs[0].size)
                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~ ~~
C:/src/rpcs3/rpcs3/Emu/Cell/PPUAnalyser.cpp:1891:49: note: place parentheses around the '&&' expression to silence this warning
                                                        (type0 == ppu_itype::B || ppu_itype::BC) && target0 < segs[0].addr || target0 >= segs[0].addr + segs[0].size)
                                                                                                 ^
                                                        (
                    )
2 warnings generated.
```

File: rpcs3/Emu/Cell/PPUThread.cpp [hunk 2]
```diff
@@ -4694,6 +4702,11 @@ bool ppu_initialize(const ppu_module& info, bool check_only)
 
 			const u64 addr = reinterpret_cast<uptr>(ensure(jit_mod.funcs[index++]));
 
+			if (func.size == 4 & !BLR_func && *info.get_ptr<u32>(func.addr) == ppu_instructions::BLR())
```
Comment (oltolm) [inline rpcs3/Emu/Cell/PPUThread.cpp:4705]: Clang produces warnings:

```
[137/535] Building CXX object rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/Cell/PPUThread.cpp.obj
C:/src/rpcs3/rpcs3/Emu/Cell/PPUThread.cpp:4724:23: warning: & has lower precedence than ==; == will be evaluated first [-Wparentheses]
                        if (func.size == 4 & !BLR_func && *info.get_ptr<u32>(func.addr) == ppu_instructions::BLR())
                            ~~~~~~~~~~~~~~~^
C:/src/rpcs3/rpcs3/Emu/Cell/PPUThread.cpp:4724:23: note: place parentheses around the '==' expression to silence this warning
                        if (func.size == 4 & !BLR_func && *info.get_ptr<u32>(func.addr) == ppu_instructions::BLR())
                                           ^
                            (             )
C:/src/rpcs3/rpcs3/Emu/Cell/PPUThread.cpp:4724:23: note: place parentheses around the & expression to evaluate it first
                        if (func.size == 4 & !BLR_func && *info.get_ptr<u32>(func.addr) == ppu_instructions::BLR())
                                           ^
                                         (            )
C:/src/rpcs3/rpcs3/Emu/Cell/PPUThread.cpp:4748:23: warning: & has lower precedence than ==; == will be evaluated first [-Wparentheses]
                        if (func.size == 4 & !BLR_func && *info.get_ptr<u32>(func.addr) == ppu_instructions::BLR())
                            ~~~~~~~~~~~~~~~^
C:/src/rpcs3/rpcs3/Emu/Cell/PPUThread.cpp:4748:23: note: place parentheses around the '==' expression to silence this warning
                        if (func.size == 4 & !BLR_func && *info.get_ptr<u32>(func.addr) == ppu_instructions::BLR())
                                           ^
                            (             )
C:/src/rpcs3/rpcs3/Emu/Cell/PPUThread.cpp:4748:23: note: place parentheses around the & expression to evaluate it first
                        if (func.size == 4 & !BLR_func && *info.get_ptr<u32>(func.addr) == ppu_instructions::BLR())
                                           ^
                                         (            )
2 warnings generated.
```

**Comment by nastys** [comment]
This seems to break the "Unlock all songs and modules" patch in Hatsune Miku: Project DIVA Dreamy Theater extend (and possibly others) when using PPU LLVM.
