### PR TITLE
[spu] random fixes

### LINKED ISSUE #2456: Unknown STOP code: 0x100 (Out_MBox is empty)
BATTLEFIELD Bad Company 2 [NPUB90347]
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/814643/RPCS3.zip)

> F {SPU[0x2000005] Thread (Job Manager - Job Thread)} class std::runtime_error thrown: Unknown STOP code: 0x100 (Out_MBox is empty)
(in file Emu\Cell\SPUThread.cpp:1310)

### PR DESCRIPTION
**Pull request by elad335**
- remove redundent and harming check from tag update completion type 2 condition

- implement stop code 0x100 , fixes #2456 

- add a missing check in sys_spu

### CODE REVIEW

**Comment by Kravickas** [comment]
No more stop code error and no more 0.03 fps
https://youtu.be/Z5n3B2wcQCI

Still unstable tho, but improvement 900%

File: rpcs3/Emu/Cell/SPUThread.cpp [hunk 1]
```diff
@@ -644,6 +644,11 @@ void SPUThread::process_mfc_cmd()
 	{
 	case MFC_GETLLAR_CMD:
 	{
+		if (mfc_queue.size() > 15) // lock-line commands requares an empty slot in the queue, even though they execute immediately
```
Comment (OverlordCW) [inline rpcs3/Emu/Cell/SPUThread.cpp]: requires not requares?

Comment (elad335) [reply rpcs3/Emu/Cell/SPUThread.cpp]: will fix lol

**Comment by Margen67** [comment]
What about #3943?
