### PR TITLE
PPU Precise/LLVM: Support NJ modes

### LINKED ISSUE #6296: Naughty Dog games another Trap Issue
To investigate this issue i used a build with hack that not throws exception on Trap. Here's the few examples that i've found
In Uncharted 2 i've found two of them, both look like overflow or smth, the first with temple trap screen becomes black and console spams with Traps, the second is camera disortion and also Traps
Here's the video:
https://youtu.be/rZEhjkeG35A
In Uncharted 3 issue that looks like second in U2 camera disortion(usually) and Trap, on video it also crashes, this place keeps me from further playing through this game, until this place it more or less possible to play
here's the video:
https://youtu.be/Q8kNyUyosFI
And The Last of Us also has issue, trap spamming and blackscreen impossible to play further
here's the video:
https://youtu.be/pGIgCpoNuB8
If any other info or save files required just let me know

### PR DESCRIPTION
**Pull request by elad335**
Support enabled Non-Java mode, which originally behaves like FTZ (Flush-To-Zero) and DAZ (Denormals-Are-Zero) both enabled on x86.
On PPU Precise Interpreter both FTZ and DAZ alike behaviours are implemented without changing any setting.
On PPU LLVM only FTZ alike behaviour is supported due to serious needs of optimizations for DAZ alike behaviours, this is not enabled by default and you need the "PPU LLVM Java Mode Handling" setting to be set to true in config file.
I recommend testing this pull request with precise interpreter.

Misc:
Fixes "PPU LLVM Accurate Vector NaN values" to actually respect the settings' value on LLVM which previously was unconditionally enabled in most cases, so if you want to test PPU LLVM you may need to enable this setting as it was unconditionally enabled on master.

Fixes #6296

### CODE REVIEW

**Comment by Xcedf** [comment]
Does this PR supposed to do the same as https://github.com/RPCS3/rpcs3/pull/8601 or it has it's own purpose? Cause tested it for Traps and they are not fixed here.

File: rpcs3/Emu/Cell/PPUTranslator.h [hunk 1]
```diff
@@ -77,6 +77,7 @@ class PPUTranslator final : public cpu_translator
 	DEF_VALUE(m_cnt, m_g_cnt, 170) // XER.CNT
 	DEF_VALUE(m_sat, m_g_sat, 171) // VSCR.SAT bit, sticky saturation flag
 	DEF_VALUE(m_nj, m_g_nj, 172) // VSCR.NJ bit, non-Java mode
+	DEF_VALUE(m_jm_mask, m_g_jm_mask, 174) // Jave-Mode helper mask
```
Comment (Whatcookie) [inline rpcs3/Emu/Cell/PPUTranslator.h:80]: "Jave-mode"

**Comment by Whatcookie** [comment]
Perhaps the reason why it doesn't solve the same issue as https://github.com/RPCS3/rpcs3/pull/8601 is because our default setting for the non-java bit might be different than the real hardware?

**Comment by elad335** [comment]
I've HW tested default NJ bit state and it turns out trhat it is infact ON by default using two MFVSCR reads on main ppu thread and a nother one, before and after setting SAT bit.
Hw test: https://github.com/elad335/myps3tests/commit/281bb588f1ee4056b6e3863dd2775df2b729897c

Results on Pr and DECR:
```
[000] | 00 00 00 00 | 00 00 00 00 |
[008] | 00 00 00 00 | 00 01 00 00 |
[000] | 00 00 00 00 | 00 00 00 00 |
[008] | 00 00 00 00 | 00 01 00 01 |
END MAIN THREAD
[000] | 00 00 00 00 | 00 00 00 00 |
[008] | 00 00 00 00 | 00 01 00 00 |
[000] | 00 00 00 00 | 00 00 00 00 |
[008] | 00 00 00 00 | 00 01 00 01 |
END HOST THREAD
```
Results on Master:
```
[000] | 00 00 00 00 | 00 00 00 00 |
[008] | 00 00 00 00 | 00 00 00 00 |
[000] | 00 00 00 00 | 00 00 00 00 |
[008] | 00 00 00 00 | 00 00 00 01 |
END MAIN THREAD
[000] | 00 00 00 00 | 00 00 00 00 |
[008] | 00 00 00 00 | 00 00 00 00 |
[000] | 00 00 00 00 | 00 00 00 00 |
[008] | 00 00 00 00 | 00 00 00 01 |
END HOST THREAD
```
TLoU should be fixed by those changes until it disables this bit explictly which is unlikely.

**Comment by elad335** [comment]
Remember that precise and interpreter and LLVM hasve different implementations so test each separately.

**Comment by Xcedf** [comment]
Ran my Traps once more, on Precise and LLVM, now fixed!! Thanks

File: rpcs3/Emu/Cell/PPUTranslator.cpp [hunk 2]
```diff
@@ -231,6 +233,25 @@ Value* PPUTranslator::VecHandleNan(Value* val)
...
+	const auto mask = SExt(m_ir->CreateICmpEQ(m_ir->CreateAnd(value, Broadcast(RegLoad(m_jm_mask), 4)), ConstantVector::getSplat(4, m_ir->getInt32(0))), GetType<s32[4]>());
+	const auto nz = m_ir->CreateLShr(mask, 9);
+	const auto result = m_ir->CreateAnd(m_ir->CreateNot(nz), value);
+
+	return type == GetType<u32[4]>() ? result : m_ir->CreateBitCast(result, type);
+}
+
+Value* PPUTranslator::VecHandleResult(Value* val)
+{
+	val = g_cfg.core.llvm_ppu_accurate_vector_nan ? VecHandleResult(val) : val;
```
Comment (sampletext32) [inline rpcs3/Emu/Cell/PPUTranslator.cpp:250]: I think this will recursively loop forever with _accurate_ setting enabled.
not a pro in this kind of questions.

Comment (elad335) [reply rpcs3/Emu/Cell/PPUTranslator.cpp:250]: It won't.

Comment (sampletext32) [reply rpcs3/Emu/Cell/PPUTranslator.cpp:250]: ok, sorry)

Comment (elad335) [reply rpcs3/Emu/Cell/PPUTranslator.cpp:250]: Nvm, I see the typo now 🤦

Comment (sampletext32) [reply rpcs3/Emu/Cell/PPUTranslator.cpp]: Haha, I was right! You are doing incredible job. Wish you luck.
