### PR TITLE
LV2/cellPad: Implement priority-based connection updates

### LINKED ISSUE #6093: The Simpsons the Game [BLES00142] - Broken Controller Input
The controller inputs are not fully accepted.  it is not possible to navigate by analog stick or control pad (menus) and within gameplay is the same result. Only Input of the X or Start buttons has been accepted and trying to remove the controller and plugging it back in does not change anything. Elad mentioned before that it might have something to do with **pad thread rewrite and timing hacks/fixes**. This is the only issue I know so far thats preventing the game to be fully playable.

Tested Build :
rpcs3-v0.0.6-8254

Hardware Specs :
Nvidia GeForce GTX 960M
Intel Core i7 6700HQ
16GB of Ram
Windows 10
Xbox 360 Controller
Capture1

## Update
- Checking the Latest Master Version v0.0.10-10321-72bef8dd Alpha, The controller issue is fixed somehow. I can navigate through the menu options and in game options without any issues now. I am not sure which PR fixed this issue, but the controller Input problem no longer occurs. I have tested it using Xbox 360 controller. Unless the issue still stands, I am closing this Issue.

### PR DESCRIPTION
**Pull request by elad335**
* Fix max_connect value in cellPadGetInfo, this value is the unmodified one from cellPadInit.
* cellPadGetInfo does not execute even a single syscall to read controller state, it relies on data updates from the _cfg_ev_hndlr input thread. This thread has a priority of 512 and most of the threads in The Simposns Game have priority of 256 including the main thread which calls the cellPad functions. This means, that in order for a connection to be registered the IO thread (_cfg_ev_hndlr) needs to able to run first which means it is dependant on the LV2 schedular to allow it. ~~I went along and implemented this functionality HLE style for LV2, I think this probably has more uses.~~ Written in LLE style with event queue in the end.

This fixes input in The Simpsons Game which expects controller readings to report disconnected at first then connected.
Fixes #6093

### CODE REVIEW

File: rpcs3/Emu/Io/PadHandler.cpp [hunk 1]
```diff
@@ -734,8 +744,14 @@ void PadHandlerBase::process()
 			if (last_connection_status[i])
 			{
 				input_log.error("%s device %d disconnected", m_type, i);
+
 				pad->m_port_status &= ~CELL_PAD_STATUS_CONNECTED;
 				pad->m_port_status |= CELL_PAD_STATUS_ASSIGN_CHANGES;
+
+				std::array<s32, CELL_MAX_PADS> status = fill_array(-1);
+				status[i] = 0 & CELL_PAD_STATUS_CONNECTED;
```
Comment (Megamouse) [inline rpcs3/Emu/Io/PadHandler.cpp:752]: Why & CELL_PAD_STATUS_CONNECTED ?
That's just confusing.
Just say 0 or CELL_PAD_STATUS_DISCONNECTED

File: rpcs3/Emu/Io/PadHandler.cpp [hunk 2]
```diff
@@ -701,8 +703,12 @@ void PadHandlerBase::process()
 			if (!last_connection_status[i])
 			{
 				input_log.success("%s device %d connected", m_type, i);
-				pad->m_port_status |= CELL_PAD_STATUS_CONNECTED;
-				pad->m_port_status |= CELL_PAD_STATUS_ASSIGN_CHANGES;
+				atomic_storage<u32>::fetch_or(pad->m_port_status, CELL_PAD_STATUS_CONNECTED + CELL_PAD_STATUS_ASSIGN_CHANGES);
+
+				std::array<s32, CELL_MAX_PADS> status = fill_array(-1);
+				status[i] = CELL_PAD_STATUS_CONNECTED;
+				cell_PadEnqueueConnectionChanges(status);
```
Comment (Megamouse) [inline rpcs3/Emu/Io/PadHandler.cpp:710]: Just make a helper function that only takes an index and 0 or CELL_PAD_STATUS_CONNECTED.
The pad Händler shouldn't deal with these cell intrinsics

File: rpcs3/Emu/Cell/Modules/cellPad.cpp [hunk 3]
```diff
@@ -63,12 +64,51 @@ void pad_info::save(utils::serial& ar)
...
+	lv2_obj::enqueue_priority_callback(512, [info, ctr = init_count, statuses]()
+	{
+		std::lock_guard lock(pad::g_pad_mutex);
+
+		if (!info->max_connect || info->init_count != ctr)
+		{
+			return;
+		}
+
+		for (u32 i = 0; i < CELL_MAX_PADS; ++i)
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellPad.cpp:97]:
```suggestion
		for (u32 i = 0; i < statuses.size(); ++i)
```

File: rpcs3/Emu/Cell/Modules/cellPad.cpp [hunk 4]
```diff
@@ -79,8 +119,28 @@ error_code cellPadInit(u32 max_connect)
...
 	config.port_setting.fill(CELL_PAD_SETTING_PRESS_OFF | CELL_PAD_SETTING_SENSOR_OFF);
+	config.reported_statuses = {};
+
+	std::array<s32, CELL_MAX_PADS> statuses{};
+
+	const auto handler = pad::get_current_handler();
+
+	const auto& pads = handler->GetPads();
+
+	for (u32 i = 0; i < CELL_MAX_PADS; ++i)
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellPad.cpp:132]:
```suggestion
	for (u32 i = 0; i < statuses.size(); ++i)
```

File: rpcs3/Emu/Cell/Modules/cellPad.h [hunk 5]
```diff
@@ -192,12 +192,24 @@ struct pad_info
 {
 	atomic_t<u32> max_connect = 0;
 	std::array<u32, CELL_PAD_MAX_PORT_NUM> port_setting{ 0 };
+	std::array<u32, CELL_MAX_PADS> reported_statuses{};
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellPad.h:195]: I don't see a reason why this should be CELL_MAX_PADS.
It's never using more than CELL_PAD_MAX_PORT_NUM.

File: rpcs3/Emu/Cell/Modules/cellPad.cpp [hunk 6]
```diff
@@ -63,12 +64,51 @@ void pad_info::save(utils::serial& ar)
 	ar(max_connect, port_setting);
 }
 
+void cell_PadEnqueueConnectionChanges(std::array<s32, CELL_MAX_PADS> statuses, usz locked = true)
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellPad.cpp:67]: I don't see a reason why this should be CELL_MAX_PADS.
It's never using more than CELL_PAD_MAX_PORT_NUM

**Comment by Blackbird88** [comment]
This also fixes The Godfather: Don's Edition [BLUS30023] pad detection. It no longer requires the pad to be disconnected and reconnected to progress.

**Comment by elad335** [comment]
I need regression testing with other games, possibly conecting and reconnecting controller fast to see if anything breaks.

File: rpcs3/Emu/Cell/Modules/sys_io_.cpp [hunk 7]
```diff
@@ -13,53 +17,106 @@ struct libio_sys_config
...
 	{
-		// Belongs to "_cfg_evt_hndlr" thread (8k stack)
-		cfg.stack_addr = ensure(vm::alloc(0x2000, vm::stack, 4096));
+		// Some delay
+		thread_ctrl::wait_for(10000);
+
+		// Wakeup
+		ppu.check_state();
+
+		[[maybe_unused]] const u64 arg1 = ppu.gpr[5];
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/sys_io_.cpp:42]: Why maybe unused.
Makes no sense

File: rpcs3/Emu/Cell/Modules/cellPad.h [hunk 8]
```diff
@@ -192,14 +192,25 @@ struct pad_info
...
 	pad_info() = default;
 	pad_info(utils::serial& ar);
 	void save(utils::serial& ar);
+
+	u32 get_max_connect() const
+	{
+		return std::min<u32>(max_connect, CELL_PAD_MAX_PORT_NUM);
+	}
+
+	bool may_be_connected(u32 port_no) const
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellPad.h:208]: I don't think the may_be is necessary.
From a cell perspective it's either true or not.
It doesn't matter what the game thinks here

File: rpcs3/Emu/Cell/Modules/cellPad.cpp [hunk 9]
```diff
@@ -63,8 +64,40 @@ void pad_info::save(utils::serial& ar)
...
+
+	if (~(old ^ state) & CELL_PAD_STATUS_CONNECTED)
+	{
+		return;
+	}
+
+	info->reported_statuses[index] = (state & CELL_PAD_STATUS_CONNECTED) | CELL_PAD_STATUS_ASSIGN_CHANGES;
+}
+
+extern void PadStateNotifyStateChange(u32 index, u32 state)
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellPad.cpp:95]: snake_case

File: rpcs3/Emu/Cell/Modules/cellPad.h (hunk 8 above)
Comment (elad335) [reply rpcs3/Emu/Cell/Modules/cellPad.h:208]: But this is an old result from thread, it does not reflect the state of cellPadGetData.

Comment (Megamouse) [reply rpcs3/Emu/Cell/Modules/cellPad.h:208]: Well then it's probably more fitting to say confirmed_connected or something like that

Comment (elad335) [reply rpcs3/Emu/Cell/Modules/cellPad.h]: No, because it is not a confirmation, it is a merely a cached result that may be inaccuarte if the game's thread prority is lower than 512. I renamed to "is_reportedly_connected".

**Comment by elad335** [comment]
Btw I do not touch cellPadPeriphGetInfo for now because it seems more accuracte on first glance, but this optimization exists in cellPadPeriphGeData.

**Comment by tommapar97** [comment]
Hi, ever since I updated the application's been having issues with multimonitor setups. Can't fullscreen on main monitor, it defaults to the second monitor, and same thing happens with drop down menus on the emulator UI itself.

**Comment by RainbowCookie32** [comment]
Already reported on #14405, don't post on unrelated PRs
