### PR TITLE
Fix C00 boot from external HG games

### LINKED ISSUE #13383: Booting failed. Edat not converting trial to full game
### Quick summary

Game trial not being converted to full game by an edat.

### Details

I extracted the pkg of a game in folder form and copied the game's edat file to RPCS3's "exdata" folder. Then I added the game to RPCS3 using the "Add game" option. But when trying to run the game it shows "Booting failed: No bootable content was found" error.

This error doesn't seem to occur in games(in folder form) that don't have a trial.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10712912/RPCS3.log.gz)

### Attach capture files for visual issues

_No response_

### System configuration

_No response_

### Other details

_No response_

### PR DESCRIPTION
**Pull request by Megamouse**
- Fixes mounting of game path and path in games.yml if m_sfo_dir ends with C00
- Fixes argv[0] if m_sfo_dir ends with C00 (USRDIR was cropped to DIR)
- Removes /USRDIR/../ from C00 sfo paths

fixes #13383

### CODE REVIEW

File: rpcs3/Emu/System.cpp [hunk 1]
```diff
@@ -1633,8 +1633,16 @@ game_boot_result Emulator::Load(const std::string& title_id, bool add_only, bool
 
 			if (!m_title_id.empty() && !from_hdd0_game && m_cat == "HG")
 			{
+				std::string game_dir = m_sfo_dir;
+
+				// Don't use the C00 subdirectory in our game list
+				if (game_dir.ends_with("/C00"))
```
Comment (elad335) [inline rpcs3/Emu/System.cpp:1639]: Assume \ is a possible delimiter on win32.

Comment (Megamouse) [reply rpcs3/Emu/System.cpp:1639]: it's added by us with + /C00

Comment (Megamouse) [reply rpcs3/Emu/System.cpp]: fixed
