### PR TITLE
Fix startup failure on invalid games.yml

### LINKED ISSUE #7495: game.yml corruption can cause emulator crash
I currently don't have the corrupt file with incomprehensible characters after an emulator crash.
I solved it by deleting the file.

### PR DESCRIPTION
**Pull request by Nekotekina**
May fix #7495

### CODE REVIEW

File: rpcs3/rpcs3qt/game_list_frame.cpp [hunk 1]
```diff
@@ -532,7 +532,33 @@ void game_list_frame::Refresh(const bool fromDrive, const bool scrollAfter)
...
+				{
+					return YAML::Load(games.to_string());
+				}
+				else
+				{
+					game_list_log.error("Failed to load games.yml, check permissions.");
+					return {};
+				}
+			}
+			catch (...)
```
Comment (CookiePLMonster) [inline rpcs3/rpcs3qt/game_list_frame.cpp]: Don't they throw anything more generalized? Might be worth catching that instead of a catch-all.

Comment (Nekotekina) [reply rpcs3/rpcs3qt/game_list_frame.cpp]: They do but literally who cares.

Comment (CookiePLMonster) [reply rpcs3/rpcs3qt/game_list_frame.cpp]: You could catch some fatal error from `fs::file` constructor this way for example.
