### PR TITLE
Firmware libraries settings overhaul

### LINKED ISSUE #6442: Option "Manually load selected libraries" does compiling them but NOT loading
If I'm choosing firmware option "Manually load selected libraries", the emulator compiles their PPU modules on the first launch, but does nothing with *loading* them into the PS3 OS. At the same time, options "Load automatic and manual selection", "Load liblv2.sprx and manual selection" and others related to manual selection, do exactly inverse thing: they load modules automatically on demand (by game), but does *not* compiling manually selected modules on the first time. I think the logic of every these option is broken.

### LINKED ISSUE #9394: Regression: PS1 Classics don't work
## Quick summary
Black screen.

## Details
Under investigation...

### PR DESCRIPTION
**Pull request by elad335**
* Remove all lib loading types. E.g. "liblv2.sprx only" etc, replace their usage with two lists. Empty lists is default fw loading behaviour.
Selecting an SPRX file via HLE-default list will LLE it, selecting an SPRX file via HLE-default list will LLE it.
As a nice side effect makes HLEing of libs simpler than ever by selecting them in list such as SPURS or GCM. (if they are LLEd by default).
Previously you had to use manual list type and randomly select LLE-by-defaults libs until the game works, only then unselect the lib you want to HLE.
* Minor libsysmodule.sprx loading fix.
* Fixed LLVM compilation of firmware. (simply didn't compile after installation)
* Handle invalid settings in EnhanceRadioButton (GUI button groups), select default setting button instead of selecting nothing.
* Fixed g_prx_list sorting by using std::map instead of std::unordered_map.
* Fixed PS1 classics. fixes #9394 
* Added a reset button for libraries list.

MISC:
closes #6442

### CODE REVIEW

File: rpcs3/rpcs3qt/emu_settings.cpp [hunk 1]
```diff
@@ -611,17 +612,34 @@ void emu_settings::EnhanceRadioButton(QButtonGroup* button_group, emu_settings_t
 		return;
 	}
 
-	for (int i = 0; i < options.count(); i++)
+	for (int i = 0, unchecked = 1, def_pos = -1; i < options.count() + unchecked; i++)
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/emu_settings.cpp:615]: I'd like to move the default setter out of this loop. I found it rather confusing to read.
Something like:
```
bool found = false;
int def_pos = -1;

// loop () {}

if (!found && def_pos >= 0)
{
	button_group->button(def_pos)->setChecked(true);
}
```

File: rpcs3/rpcs3qt/emu_settings.cpp [hunk 2]
```diff
@@ -611,17 +612,34 @@ void emu_settings::EnhanceRadioButton(QButtonGroup* button_group, emu_settings_t
...
 
 		button_group->button(i)->setText(localized_setting);
 
 		if (options[i] == selected)
 		{
+			unchecked = 0;
 			button_group->button(i)->setChecked(true);
 		}
 
+		if (def_pos == -1 && options[i] == def)
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/emu_settings.cpp:638]: I think this can safely be an else if

File: rpcs3/rpcs3qt/settings_dialog.cpp [hunk 3]
```diff
@@ -1057,12 +1053,40 @@ settings_dialog::settings_dialog(std::shared_ptr<gui_settings> gui_settings, std
 	}
 
 	ui->searchBox->setPlaceholderText(tr("Search libraries", "Library search box"));
+	ui->searchBox->setEnabled(true);
+	ui->lleList->setEnabled(true);
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/settings_dialog.cpp:1057]: these are redundant

File: rpcs3/rpcs3qt/settings_dialog.cpp [hunk 4]
```diff
@@ -1057,12 +1053,40 @@ settings_dialog::settings_dialog(std::shared_ptr<gui_settings> gui_settings, std
...
+		{
+			items.push_back(ui->lleList->item(i)->clone());
+		}
+
+		for (uint i = 0; i < items.size(); i++)
+		{
+			const auto text = sstr(items[i]->text());
+
+			// Select default LLE sprx list for manual lib loading, otherwise all libs are unchecked
+			items[i]->setCheckState(id == static_cast<int>(lib_loading_type::manual) && g_prx_list.count(text) && !g_prx_list.at(text)? Qt::Checked : Qt::Unchecked);
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/settings_dialog.cpp:1074]: This is more readable imo:
```suggestion
			const bool selected = id == static_cast<int>(lib_loading_type::manual) && g_prx_list.count(text) && !g_prx_list.at(text);
			items[i]->setCheckState(selected ? Qt::Checked : Qt::Unchecked);
```

File: rpcs3/rpcs3qt/settings_dialog.cpp [hunk 5]
```diff
@@ -1057,12 +1053,40 @@ settings_dialog::settings_dialog(std::shared_ptr<gui_settings> gui_settings, std
...
+		{
+			return (i1->checkState() != i2->checkState()) ? (i1->checkState() > i2->checkState()) : (i1->text() < i2->text());
+		});
+
+		// refill library list
+		ui->lleList->clear();
+
+		for (uint i = 0; i < items.size(); i++)
+		{
+			ui->lleList->addItem(items[i]);
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/settings_dialog.cpp:1088]: There is an undefined behavior:
The search filter is not considered when changing the lib mode...

File: rpcs3/rpcs3qt/settings_dialog.cpp [hunk 6]
```diff
@@ -1057,12 +1053,40 @@ settings_dialog::settings_dialog(std::shared_ptr<gui_settings> gui_settings, std
...
+
+		// duplicate current items, we need clones to preserve checkstates
+		for (int i = 0; i < ui->lleList->count(); i++)
+		{
+			items.push_back(ui->lleList->item(i)->clone());
+		}
+
+		for (uint i = 0; i < items.size(); i++)
+		{
+			const auto text = sstr(items[i]->text());
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/settings_dialog.cpp:1071]: I think the auto type should be reserved for complicated types.
This only makes it harder to read and review.

```suggestion
			const std::string text = sstr(items[i]->text());
```

File: rpcs3/rpcs3qt/settings_dialog.cpp (hunk 5 above)
Comment (elad335) [reply rpcs3/rpcs3qt/settings_dialog.cpp]: Fixed, fixed, fixed, fixed, fixed and fixed.

File: rpcs3/rpcs3qt/emu_settings.cpp [hunk 7]
```diff
@@ -611,22 +612,37 @@ void emu_settings::EnhanceRadioButton(QButtonGroup* button_group, emu_settings_t
...
+			def_pos = i;
+		}
 
 		connect(button_group->button(i), &QAbstractButton::clicked, [=, this]()
 		{
 			SetSetting(type, sstr(options[i]));
 		});
 	}
+
+	if (!found)
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/emu_settings.cpp:640]: Missing check for count > 0.
Maybe check that in the early out above

File: rpcs3/rpcs3qt/settings_dialog.cpp [hunk 8]
```diff
@@ -1094,6 +1083,44 @@ settings_dialog::settings_dialog(std::shared_ptr<gui_settings> gui_settings, std
...
+
+		std::vector<QListWidgetItem*> items;
+
+		// duplicate current items, we need clones to preserve checkstates
+		for (int i = 0; i < ui->lleList->count(); i++)
+		{
+			items.push_back(ui->lleList->item(i)->clone());
+		}
+
+		for (uint i = 0; i < items.size(); i++)
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/settings_dialog.cpp:1098]: I'd simply integrate this into the other lambda and just get the text and button Id in the lambda itself or as arg.

Comment (elad335) [reply rpcs3/rpcs3qt/settings_dialog.cpp]: Fixed, fixed.

**Comment by elad335** [comment]
Something inflated azure build heap memory usage...

File: rpcs3/rpcs3qt/settings_dialog.cpp [hunk 9]
```diff
@@ -1107,11 +1105,6 @@ settings_dialog::settings_dialog(std::shared_ptr<gui_settings> gui_settings, std
 		}
 	});
 
-	if (const int lib_mode_button_id = lib_mode_bg->checkedId(); lib_mode_button_id >= 0)
-	{
-		on_lib_button_clicked(lib_mode_button_id);
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/settings_dialog.cpp:1112]: this needs to be called anyway, since we want to presort the libs

Comment (elad335) [reply rpcs3/rpcs3qt/settings_dialog.cpp:1112]: 1 - We dont need to sort them anymore because they are sorted in g_prx_list.
2 - Calling it invalidates selection state of the checkboxes which we only want after switching mode.

File: rpcs3/rpcs3qt/settings_dialog.cpp [hunk 10]
```diff
@@ -1087,6 +1076,15 @@ settings_dialog::settings_dialog(std::shared_ptr<gui_settings> gui_settings, std
 
 		for (uint i = 0; i < items.size(); i++)
 		{
+			if (id >= 0)
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/settings_dialog.cpp:1079]: do this in the loop above, otherwise sorting is broken

File: rpcs3/rpcs3qt/settings_dialog.cpp (hunk 9 above)
Comment (Megamouse) [reply rpcs3/rpcs3qt/settings_dialog.cpp:1112]: alright

File: rpcs3/rpcs3qt/settings_dialog.cpp (hunk 10 above)
Comment (elad335) [reply rpcs3/rpcs3qt/settings_dialog.cpp:1079]: Fixed.

File: rpcs3/rpcs3qt/settings_dialog.cpp [hunk 11]
```diff
@@ -1095,8 +1093,8 @@ settings_dialog::settings_dialog(std::shared_ptr<gui_settings> gui_settings, std
 	};
 
 	// Events
-	connect(lib_mode_bg, &QButtonGroup::idClicked, on_lib_button_clicked);
-	connect(ui->searchBox, &QLineEdit::textChanged, on_search_box_text_changed);
+	connect(lib_mode_bg, &QButtonGroup::idToggled, [this, on_lib_state_changed](int id){ on_lib_state_changed(ui->searchBox->text(), id); });
```
Comment (elad335) [inline rpcs3/rpcs3qt/settings_dialog.cpp:1096]: idToggled is more appropriate here I think.

Comment (Megamouse) [reply rpcs3/rpcs3qt/settings_dialog.cpp:1096]: A: the function args are wrong.
B: no it is not. with this you'll call state changed on programmatical changes, which we usually want to prevent

File: rpcs3/rpcs3qt/emu_settings.cpp [hunk 12]
```diff
@@ -611,22 +612,36 @@ void emu_settings::EnhanceRadioButton(QButtonGroup* button_group, emu_settings_t
...
 		{
 			SetSetting(type, sstr(options[i]));
 		});
 	}
+
+	if (!found && def_pos >= 0)
+	{
+		// Select the default option on invalid setting string
+		button_group->button(def_pos)->setChecked(true);
+	}
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/emu_settings.cpp:644]: I noticed that we are missing something here:

```suggestion
	if (!found)
	{
		ensure(def_pos >= 0);

		cfg_log.error("EnhanceRadioButton'%s' tried to set an invalid value: %s. Setting to default: %s.", cfg_adapter::get_setting_name(type), sstr(selected), sstr(def));
		m_broken_types.insert(type);

		// Select the default option on invalid setting string
		button_group->button(def_pos)->setChecked(true);
	}
```

**Review by Megamouse — CHANGES_REQUESTED** [review]

File: rpcs3/rpcs3qt/settings_dialog.cpp (hunk 11 above)
Comment (Megamouse) [reply rpcs3/rpcs3qt/settings_dialog.cpp]: to clarify:
Qt itself calls click() when the user changes selection (for example by mouse or keyboard).
If you now use toggle, you'll trigger the signal whenever we change the value in code, which might add weird errors in the future. We then would have to add a signal blocker when we don't want the slot being called....

So it's much easier to just call the slot ourselves if necessary after we are finished toggling buttons.

File: rpcs3/rpcs3qt/emu_settings.cpp [hunk 13]
```diff
@@ -611,22 +612,41 @@ void emu_settings::EnhanceRadioButton(QButtonGroup* button_group, emu_settings_t
...
 		{
 			SetSetting(type, sstr(options[i]));
 		});
 	}
+
+	if (!found)
+	{
+		ensure(def_pos >= 0);
+
+		cfg_log.error("EnhanceRadioButton'%s' tried to set an invalid value: %s. Setting to default: %s.", cfg_adapter::get_setting_name(type), sstr(selected), sstr(def));
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/emu_settings.cpp:644]: sorry, I made a typo during copy pasta
```suggestion
		cfg_log.error("EnhanceRadioButton '%s' tried to set an invalid value: %s. Setting to default: %s.", cfg_adapter::get_setting_name(type), sstr(selected), sstr(def));
```

File: rpcs3/rpcs3qt/settings_dialog.cpp (hunk 11 above)
Comment (elad335) [reply rpcs3/rpcs3qt/settings_dialog.cpp]: Fixed lambda args, thanks. I want to invalidate selection state *only* after switching mode and not just random clicks on the same setting so I think idToggled is better for this..

Comment (elad335) [reply rpcs3/rpcs3qt/settings_dialog.cpp]: oh hmm I'll think of something better without this signal.

Comment (Megamouse) [reply rpcs3/rpcs3qt/settings_dialog.cpp]: if you're worried about selection state during the dialog then you're doing something wrong.
The global library state should only be altered on apply_configs.
Calling the lambda with the current selection after initialization should not have any effect.

Comment (elad335) [reply rpcs3/rpcs3qt/settings_dialog.cpp]: Fixed.

File: rpcs3/rpcs3qt/settings_dialog.h [hunk 14]
```diff
@@ -60,6 +60,9 @@ private Q_SLOTS:
 	bool m_use_discord;
 	QString m_discord_state;
 
+	// Lib loading state
+	int last_lib_mode = -1;
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/settings_dialog.h:64]: Ah, now I understand. You meant the reset of unapplied values when clicking the same button after changing the libs.
Anyway, here some advise:
```suggestion
	int m_last_lib_mode = -1;
```

Comment (elad335) [reply rpcs3/rpcs3qt/settings_dialog.h]: Fixed.

**Review by Megamouse — APPROVED** [review]
I guess it's fine now from a pure GUI side of things

**Comment by elad335** [comment]
* liblv2 and libsysmodule modes now hide all irrelavant "LLE-by-default" sprx files. (it didnt matter if their checkbox was selected or not on master, LLE was always used)

File: rpcs3/rpcs3qt/settings_dialog.cpp [hunk 15]
```diff
@@ -1085,18 +1087,42 @@ settings_dialog::settings_dialog(std::shared_ptr<gui_settings> gui_settings, std
...
 		{
 			ui->lleList->addItem(items[i]);
 
-			// only show items filtered for search text
-			ui->lleList->setRowHidden(i, !items[i]->text().contains(search_term));
+			const QString qtext = items[i]->text();
+			const std::string text = sstr(qtext);
+
+			const bool lle_default = g_prx_list.count(text) && !g_prx_list.at(text);
+			const bool hidden = !qtext.contains(search_term) || (lle_default && id != static_cast<int>(lib_loading_type::manual));
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/settings_dialog.cpp:1104]: Switch terms for some optimization

File: rpcs3/rpcs3qt/settings_dialog.cpp [hunk 16]
```diff
@@ -1074,6 +1063,19 @@ settings_dialog::settings_dialog(std::shared_ptr<gui_settings> gui_settings, std
...
 		{
 			items.push_back(ui->lleList->item(i)->clone());
+
+			if (id >= 0)
+			{
+				const std::string text = sstr(items[i]->text());
+
+				// Select default LLE sprx list for manual lib loading, otherwise all libs are unchecked and hidden
+				const bool lle_default = g_prx_list.count(text) && !g_prx_list.at(text);
+
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/settings_dialog.cpp:1073]: Mismatch between comment and code...
The comment suggests:
const book selected = lle_default && id == static_cast<int>(lib_loading_type::manual);
items[i]->setCheckState(selected ? Qt::Checked : Qt::Unchecked);

Comment (elad335) [reply rpcs3/rpcs3qt/settings_dialog.cpp:1073]: Solved comments.

Comment (Megamouse) [reply rpcs3/rpcs3qt/settings_dialog.cpp:1073]: It still doesn't make sense since you don't really uncheck them

**Comment by elad335** [comment]
* Fixed LLVM compilation of firmware. (regression)
* Removed lib loading types.

image

**Comment by elad335** [comment]
I also invalidated all old fw load settings, the default will be used after this version.

File: rpcs3/rpcs3qt/settings_dialog.cpp [hunk 17]
```diff
@@ -1012,68 +1018,41 @@ settings_dialog::settings_dialog(std::shared_ptr<gui_settings> gui_settings, std
...
+		// 0: No override
+		const int res = static_cast<int>(set.count(std::string(lib.first) + ":hle") - set.count(std::string(lib.first) + ":lle"));
 
 		QListWidgetItem* item = new QListWidgetItem(qsv(lib.first), ui->lleList);
 		item->setFlags(item->flags() | Qt::ItemIsUserCheckable); // set checkable flag
-		item->setCheckState(Qt::Unchecked); // AND initialize check state
+		item->setCheckState(res && res != (lib.second * 2 - 1) ? Qt::Checked : Qt::Unchecked); // AND initialize check state
+
+		QString tip = lib.second ? 
+			QStringLiteral("Select to LLE. (HLE by default)") :
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/settings_dialog.cpp:1037]: Why are these not tooltips in tooltips.h ?

Comment (Megamouse) [reply rpcs3/rpcs3qt/settings_dialog.cpp:1037]: Or at least translated

Comment (elad335) [reply rpcs3/rpcs3qt/settings_dialog.cpp]: Fixed.

**Comment by Megamouse** [comment]
I haven't really looked at it yet. But is there a way to reset them?
Otherwise this is gonna get everyone in a world of pain

**Comment by elad335** [comment]
Empty list is default, manual reset is to unselect until empty. Theres no explicit way to reset it and there werent really any before.

**Comment by elad335** [comment]
I can add if requested of course.

**Comment by elad335** [comment]
Added a reset button.

File: rpcs3/rpcs3qt/settings_dialog.ui [hunk 18]
```diff
@@ -2030,14 +1950,25 @@
                </widget>
               </item>
               <item>
-               <widget class="QLineEdit" name="searchBox">
-                <property name="sizePolicy">
-                 <sizepolicy hsizetype="Preferred" vsizetype="Fixed">
-                  <horstretch>0</horstretch>
-                  <verstretch>0</verstretch>
-                 </sizepolicy>
+               <layout class="QHBoxLayout" name="horizontalLayout_2" stretch="1,0">
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/settings_dialog.ui:1953]: rename this layout

File: rpcs3/rpcs3qt/settings_dialog.cpp [hunk 19]
```diff
@@ -1012,68 +1018,36 @@ settings_dialog::settings_dialog(std::shared_ptr<gui_settings> gui_settings, std
...
-		}
+		// -1: Override LLE
+		// 1: Override HLE
+		// 0: No override
+		const int res = static_cast<int>(set.count(std::string(lib.first) + ":hle") - set.count(std::string(lib.first) + ":lle"));
 
 		QListWidgetItem* item = new QListWidgetItem(qsv(lib.first), ui->lleList);
 		item->setFlags(item->flags() | Qt::ItemIsUserCheckable); // set checkable flag
-		item->setCheckState(Qt::Unchecked); // AND initialize check state
+		item->setCheckState(res && res != (lib.second * 2 - 1) ? Qt::Checked : Qt::Unchecked); // AND initialize check state
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/settings_dialog.cpp:1034]: it's not really clear to the reader what you're doing here

**Review by Megamouse — CHANGES_REQUESTED** [review]

File: rpcs3/Emu/System.cpp [hunk 20]
```diff
@@ -1359,9 +1369,13 @@ game_boot_result Emulator::Load(const std::string& title_id, bool add_only, bool
 
 			const std::string game_path = "/dev_hdd0/game/" + m_path.substr(hdd0_game.size(), 9);
 
-			sys_log.notice("Forcing manual lib loading mode");
```
Comment (elad335) [inline rpcs3/Emu/System.cpp:1362]: Someone smoked somthing real good when deciding HLE all libs for PS1 classics... well fixed.

File: rpcs3/rpcs3qt/settings_dialog.cpp (hunk 19 above)
Comment (elad335) [reply rpcs3/rpcs3qt/settings_dialog.cpp:1037]: Added comment.

**Comment by elad335** [comment]
One last addition before merge.
image

File: rpcs3/Emu/System.cpp (hunk 20 above)
Comment (Nekotekina) [reply rpcs3/Emu/System.cpp:1363]: I think it had its reasons at its time
