### PR TITLE
Some fixes

### LINKED ISSUE #1072: error: static_assert failed "Unsupported vm::cast() type"
Hi all,

after pulled out last changes from remote master, I ran building project but I got this error:

```
In file included from /Users/federico/Downloads/rpcs3/rpcs3/rpcs3.cpp:2:
In file included from /Users/federico/Downloads/rpcs3/rpcs3/Emu/Memory/Memory.h:92:
/Users/federico/Downloads/rpcs3/rpcs3/Emu/Memory/vm.h:98:3: error: static_assert failed "Unsupported vm::cast() type"
                static_assert(std::is_same<T, u32>::value, "Unsupported vm::cast() type");
                ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/federico/Downloads/rpcs3/rpcs3/Emu/Memory/vm.h:114:11: note: in instantiation of template class 'vm::cast_ptr<unsigned long long>' requested
      here
                        return cast_ptr<u64>::cast(addr, func);
                               ^
/Users/federico/Downloads/rpcs3/rpcs3/Emu/Memory/vm.h:129:9: error: explicit specialization of 'vm::cast_ptr<unsigned long long>' after instantiation
        struct cast_ptr<u64>
               ^~~~~~~~~~~~~
/Users/federico/Downloads/rpcs3/rpcs3/Emu/Memory/vm.h:114:11: note: implicit instantiation first required here
                        return cast_ptr<u64>::cast(addr, func);
                               ^
1 warning and 2 errors generated.
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/rpcs3.cpp.o] Error 1
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
make: *** [all] Error 2
```

Could anyone help me?

Thanks!

### PR DESCRIPTION
**Pull request by Nekotekina**
1) Excessive use of vm::cast moderated (could fix #1072)
2) std::bind replaced with lambdas (related with VS 2015 RC compilation)
3) ConvertWCharToUTF8() bug fixed

### CODE REVIEW

File: rpcs3/Emu/SysCalls/Modules/cellFs.cpp [hunk 1]
```diff
@@ -477,6 +477,11 @@ s32 cellFsStReadStart(u32 fd, u64 offset, u64 size)
 		return CELL_FS_EBADF;
 	}
 
+	if (size > std::numeric_limits<u32>::max()) // ???
```
Comment (Bigpet) [inline rpcs3/Emu/SysCalls/Modules/cellFs.cpp]: these are for some 4GB file limit?

**Comment by Bigpet** [comment]
alright lgtm :+1: . I don't understand the #ifdef __APPLE__ stuff but you put it there so you'd know better :smile: (and it seems related to #1072 )

(I'll assume the size increase in `fs_st_cb_rec_t` never touches the ps3 memory, since it seems to be only included `fs_file_t` which only ever gets passed to the ps3 client program via one u32 file descriptor)

I guess I'll merge this after the weekend if no one else gets around to it.
