### PR TITLE
PPU LLVM: Memory Consumption Enhancements

### LINKED ISSUE #11469: Regression: PES 2018 doesn't boot with LLVM PPU Decoder (#9059)
Hello team,

Pro Evolution Soccer 2018 (BLES02252) doesn't boot after #9059 with PPU Decoder set to (Recompiler) LLVM, it crashes the emulator after linking PPU modules. The game boots fine with previous builds with (Recompiler) LLVM.

First affected build version: 0.0.12-11001, #9059 pull request
Latest working build version:  0.0.12-10997, #9015 pull request

However, the game boots fine in the affected build with PPU Decoder set to Interpreter (fast), or to Interpreter (static) for the master build.

Maybe we should add this game to this list #5831
Thanks.

The log file is for 0.0.12-11001 build, with LLVM PPU Decoder.
[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/7967447/RPCS3.log.zip)

### PR DESCRIPTION
**Pull request by elad335**
PPU LLVM's memory manager was not able to handle more than 512MB of data, but at same time instead of reporting an error on outage it reused memory buffers. This resulted in corrupted PPU LLVM cache files for affected titles.

Fixes PES games with their humongous executable file.
Fixes #11469 (you need to remove broken PPU LLVM and SPU LLVM cache)

# Additional impovements
* Reduces RPCS3 RAM memory consumption by 100MB-300MB ingame and more than twice this amount during PPU LLVM compilation. This is because PPU analyzer information is stored much more efficiently, size of data members has been reduced and PPU LLVM compilation no longer makes copies of this memory.

**Before (Demon's Souls)**
image

**After - Around 160MB reduction in memory!**
image

### CODE REVIEW

**Comment by BrentPeterson2028** [comment]
Could this potentially fix Condemned 2's Flicker/Blur issue?

**Comment by elad335** [comment]
Maybe the proper solution would also require splitting huge executable files caches.

**Comment by Satan86** [comment]
Same crash with PES 2017.
[RPCS3.log](https://github.com/user-attachments/files/18383044/RPCS3.log)
It's EBOOT.BIN is 16.996 KB and there are 347 PPU LLVM modules.

**Comment by Satan86** [comment]
PES 2017 crashes to desktop after Compiling PPU Modules. It has 347 modules and the EBOOT.BIN is 16.996 KB.
[RPCS3.log](https://github.com/user-attachments/files/18383225/RPCS3.log)
The log says this at the end: ·F 0:05:53.309380 {PPU[0x1000000] main_thread} JIT: Out of memory (size=0xd1a78, align=0x10)

**Comment by bigol83** [comment]
I don't know if this is relevant but FF XIII still crashes when applying PPU modules 

The game has 119 modules and the eboot is 8.150 KB

**Comment by Darkhost1999** [comment]
> I don't know if this is relevant but FF XIII still crashes when applying PPU modules 

I was thinking about adding a comment https://github.com/RPCS3/rpcs3/issues/16112
Because this PR didn't introduce the issue.
If this PR did introduce the issue I would've commented here.

FFXIII has gone through ~3 or 4 regressions experiencing close to desktop on a clean cache. If the llvm cache version is bumped again then only older builds will be able to play for now. But it seems we can compile on the older build, update, and play just fine on the current master.

**Comment by digant73** [comment]
> PPU LLVM's memory manager was not able to handle more than 512MB of data, but at same time instead of reporting an error on outage it reused memory buffers. This resulted in corrupted PPU LLVM cache files for affected titles.
> 

is that an issue we could see just at boot? or something that can occur during the game (e.g. access on unmapped memory etc.)?

**Comment by elad335** [comment]
Thanks to PES 2018 and my 8GB ram stick dying off, I discovered that we can save hundreds of megabytes of RAM for every RPCS3 game instance including in compilation and when running.

File: rpcs3/Emu/Cell/PPUAnalyser.h [hunk 1]
```diff
@@ -13,9 +14,8 @@
 #include "PPUOpcodes.h"
 
 // PPU Function Attributes
-enum class ppu_attr : u32
+enum class ppu_attr : u8
```
Comment (pchome) [inline rpcs3/Emu/Cell/PPUAnalyser.h:17]: I remember some similar changes where proposed while running `clang-tidy` on Emu/Cell
For example for this file:
```log
../../work/rpcs3-9999/rpcs3/Emu/Cell/PPUAnalyser.h:16:12: warning: enum 'ppu_attr' uses a larger base type ('u32' (aka 'unsigned int'), size: 4 bytes) than necessary for its value set, consider using 'std::uint8_t' (1 byte) as the base type to reduce its size [performance-enum-size]
   16 | enum class ppu_attr : u32
      |            ^
../../work/rpcs3-9999/rpcs3/Emu/Cell/PPUAnalyser.h:268:13: warning: enum 'type' uses a larger base type ('int', size: 4 bytes) than necessary for its value set, consider using 'std::uint16_t' (2 bytes) as the base type to reduce its size [performance-enum-size]
  268 |         enum class type
      |                    ^
```

The full list (in case this can help to pick more optimizations related to this PR):
<details><summary>clang-tidy --checks="-*,performance*"</summary>

<br>

Command (from build directory, where `compile_commands.json` file is):
```command
clang-tidy --checks="-*,performance*" -header-filter=.* ../../work/rpcs3-9999/rpcs3/Emu/Cell/*.cpp -- -I../../work/rpcs3-9999/rpcs3 -I../../work/rpcs3-9999 -std=c++23
```

[clang-tidy.Emu.Cell.perf.log.gz](https://github.com/user-attachments/files/18463910/clang-tidy.Emu.Cell.perf.log.gz)

</details>

**Comment by AniLeo** [comment]
Tested on arm64 Linux (rpi5) with Demon's Souls (233 modules): 
- Loaded existing PPU cache
- Recompiled PPU cache from scratch

Would be great if more games on x64 could be tested before merging, specially games listed on #5831

**Comment by Darkhost1999** [comment]
Yay ready for review. Will test the AC series and final fantasy

**Comment by Darkhost1999** [comment]
> Yay ready for review. Will test the AC series and final fantasy

No change in compatibility, and not a blocker.

1 thing I observed was my thread usage was around 10-15% during batch compiler, right click -> create llvm cache, or even booting the game normally.


On the current master, the threads start at 100% usage and maintain that usage. With the obvious swapping to the next process/game has a little subtle break.

**Comment by Satan86** [comment]
PES now works with PPU LLVM, but it took absolutely ages to compile PPU LLVM modules when booting, using 10% of the CPU.
image

**Comment by elad335** [comment]
@Satan86 Can you upload log? I want to see the compilation stage of it.

**Comment by Darkhost1999** [comment]
image
Compiling times are back to normal or faster. Just not 10% observed

**Comment by elad335** [comment]
I need someone to test the ARM build for 100+ modules games.

**Comment by Satan86** [comment]
> @Satan86 Can you upload log? I want to see the compilation stage of it.

Tested now with the latest version of the Pull Request. Compilation was a lot faster and everything still works in PES 2017.

[RPCS3.log.gz](https://github.com/user-attachments/files/18511180/RPCS3.log.gz)

**Comment by elad335** [comment]
@mavethee Yeah MacOS is good for testing

**Comment by elad335** [comment]
@Satan86 there was a problem with logging before, can you retest on latest build? also provide a log with master for comparison

**Comment by mavethee** [comment]
Did, a quick test for now, so only one game - `Battlefield: Bad Company 2`:

## Master:
ARM_Master_BC2_CPU
ARM_Master_BC2_RAM
## PR:
ARM_PR_BC2_CPU
ARM_PR_BC2_RAM

Compilation times are about the same, ~6 mins for both, but was able to save ~200MB.

**One problem tho, on master the game boots, on PR it segfaults.**

## **Logs:**
[ARM_PR_BC2_Segfault_2ndRUN.log.gz](https://github.com/user-attachments/files/18517691/ARM_PR_BC2_Segfault_2ndRUN.log.gz)
[ARM_PR_BC2_Segfault.log.gz](https://github.com/user-attachments/files/18517692/ARM_PR_BC2_Segfault.log.gz)
[ARM_Master_BC2.log.gz](https://github.com/user-attachments/files/18517718/ARM_Master_BC2.log.gz)

**Comment by Darkhost1999** [comment]
I'm still on a084761 and can update when the next build compiles yet observed that attempting to batch compile cache at some point I experience a close to desktop. I forgot to check which title was running last but I do like to after batch compiling boot every title and see what was missed and will compile when I just boot the game directly. VSH was accidentally left booting overnight and never finished ppu compilation complaining of `Potentially invalid function has been added`
[RPCS3.log](https://github.com/user-attachments/files/18521043/RPCS3.log)
Final Fantasy was the assumed reason for close to desktop as previous regression report indicates however, I assume cache version number was bumped and so old cache no longer works. I tried both with and without pre-existing cache to experience the same crash.
[RPCS3.log](https://github.com/user-attachments/files/18521131/RPCS3.log)

**Comment by elad335** [comment]
I don't know why it regressed but it's because the firmware ps2 emulator, I disabled its compilation altogether. RPCS3 can't launch it in the first place.

**Comment by Darkhost1999** [comment]
Thanks, I just observed the Windows build canceled so I checked out, compiled, and tested as working.

**Comment by Darkhost1999** [comment]
There was another user on Discord but with Macos to receive an error with RPCS3 using 41GB of memory when their system has 8GB.
However, they were not utilizing this Pull Request. It doesn't seem that we can pin the blame here and will need to figure out how to replicate the issue.

**Comment by carlosgamer23** [comment]
LEGO Marvel Avengers - I managed to open the game without updates, however, when I went to install the updates and open it again, the emulator used 92% of my processor. Couldn't this process be done in parts? Compilation is the only problematic thing about the emulator, after all, it is what causes the processor to overheat. Skipping this part everything works. There should be a healthier way of compiling, I'm using all the emulator's functions to reduce CPU usage, and as I said, I only have problems compiling. In addition to using LLMV, I tested it in static mode, in which compilation occurs correctly, but this function makes the game terribly slow, so even if the game opens, it is not worth using.

**Comment by Augusto7743** [comment]
@elad335

Thanks !

**Comment by dj9o1** [comment]
I still cannot get PES 2018 to work and Im trying to not get mad but I have deleted LLVM cache and it still wont boot
