### PR TITLE
cellVoice/cellAudio Fixes

### LINKED ISSUE #6884: [Regression] PR #6757 broke Backbreaker games
Game crashes on boot now with a PPU mem error. Caused by: https://github.com/RPCS3/rpcs3/pull/6757

Broken: 0.0.7-8945
Fine: 0.0.7-8944

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3774333/RPCS3.zip)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

### PR DESCRIPTION
**Pull request by elad335**
* Use shared lock wherever possible. (std::unordered_map::find is safe to use under shared lock)
* Fix cellVoiceSetVolume.
* Fix NOT_INIT checks.
* Fix error logging of cellVoiceCreateNotifyEventQueue, cellAudioCreateNotifyEventQueue.
* Fix cellVoiceCreatePort.
* Implement 0 event source handling.
* Implement cellAudioCreateNotifyEventQueueEx.
* Implement event source for cellAudio events
* Fix cellAudioCreateNotifyEventQueue queue depth.

Other improvements:
* Minor error checking fixes for sys_prx from firmware.

Fixes #6884
Fixes Test Drive Unlimited.

### CODE REVIEW

File: rpcs3/Emu/Cell/Modules/cellAudio.cpp [hunk 1]
```diff
@@ -1318,21 +1322,22 @@ error_code cellAudioSetPortLevel(u32 portNum, float level)
...
-	attr->type     = SYS_PPU_QUEUE;
+	attr->type     = queue_type;
 	attr->name_u64 = 0;
 
 	for (u64 i = 0; i < MAX_AUDIO_EVENT_QUEUES; i++)
 	{
 		// Create an event queue "bruteforcing" an available key
 		const u64 key_value = 0x80004d494f323221ull + i;
 
-		if (const s32 res = sys_event_queue_create(id, attr, key_value, 32))
```
Comment (elad335) [inline rpcs3/Emu/Cell/Modules/cellAudio.cpp]: Any reason this was 32 before? this is surely incorrect looking at firmware values but im asking in case it is a workaround for something.

**Comment by ruthan** [comment]
There is not too much audio related fixes, so i gave a try, old UT3 bug: 
#5134 Unreal Tournament III [BLES00200] very broken ingame sound

No luck, so far.

**Comment by elad335** [comment]
It ain't about sound quality.

**Comment by Augusto7743** [comment]
Spelunker has a bug that few seconds that a game is started the music tempo goes normal to slow.
Music tempo was correct in versions before 2018.

**Comment by elad335** [comment]
if it isn't a regression do not report
