### PR TITLE
Qt: Fix multi package install dialog on Linux

### LINKED ISSUE #16895: [Regression] qt: Batch PKG Installation file list entries have shifted up text (#12692)
### Description
When installing packages in batch, the text inside the file list is shifted up. This is not a theme issue, as it happens with all the themes, including Default and Native.

Image
Image
Image

### Steps to Reproduce
1. Drag and drop multiple update packages
2. See the Batch PKG Installation dialog

### System Information
RPCS3 v0.0.35-17672-76495f07 Alpha | master
Qt version: Compiled against Qt 6.8.2 | Run-time uses Qt 6.8.2
Operating system: POSIX, Name: Linux, Release: 6.13.7-1-MANJARO

### PR DESCRIPTION
**Pull request by AniLeo**
Fixes #16895 by undoing the workaround in #12692 which actually introduces this issue

I don't think this workaround is required anymore. We used Qt 5.15.2 back then, and now we're on Qt 6.8.3. Testing locally on both local build and AppImage allows the entries to display properly.

AppImage
Screenshot_20250408_052938

Local
Screenshot_20250408_050206

@RipleyTom to verify if it still displays fine without the workaround

Tested on KDE Plasma 6.3.3.

### CODE REVIEW

File: rpcs3/rpcs3qt/richtext_item_delegate.h [hunk 1]
```diff
@@ -38,12 +38,7 @@ class richtext_item_delegate : public QStyledItemDelegate
 
 		// Adjust our painter parameters with some magic that looks good.
 		// This is necessary so that we don't draw on top of the optional widget.
-		// If you're not happy with this code don't hesitate to contact Megamouse
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/richtext_item_delegate.h:41]: Why are you removing this 🤣

Comment (AniLeo) [reply rpcs3/rpcs3qt/richtext_item_delegate.h:41]: Because it was added on the same commit I'm undoing
