### PR TITLE
cellGame: Fix PPU deadlocks  on concurrent execution

### LINKED ISSUE #14672: [Regression] Trinity Universe (BLES00971) cellGame functions deadlock (#14537)
### Quick summary

Trinity Universe won't boot after 0.0.29-15521, including latest update (0.0.29-15631). On latest update, gets stuck at compiling screen, on 0.0.29-15521, screen goes black after compilation.

However, when using 0.0.29-15518, games compiles fine, and boots up.

### Details

Game won't boot at all when launching it, but depending on the update, it either shows a black screen directly, or shows a PPU/SPU compilation screen with the game's PS3 background instead.

Screenshot of 0.0.29-15518:
Game loads and shows normally

Screenshot of 0.0.29-15521:
Game doesn't load, completely black screen

Screenshot of 0.0.29-15631:
Game doesn't load, stuck at the Building SPU Cache screen instead

### Build with regression

v0.0.29-15521

### Attach two log files

[0.0.29-15518 Working Log](https://github.com/RPCS3/rpcs3/files/12708665/RPCS3.log.gz)
[0.0.29-15521 Not Working Log](https://github.com/RPCS3/rpcs3/files/12708692/RPCS3.log.gz)

### Attach capture files for visual issues

_No response_

### System configuration

**Settings:**
- Default Settings, but also tested with PPU/SPU Decompilation Off.

**Specs:**
- CPU:  Intel i7-13700K
- GPU: RTX 3080Ti (Driver: 537.34)
- OS: Windows 10 22H2

### Other details

_No response_

### PR DESCRIPTION
**Pull request by elad335**
Because PPU threads were awake when waiting on mutex lock, deadlocks occurred when multiple threads used cellGame functions.
This fixes #14672

### CODE REVIEW

File: rpcs3/Emu/Cell/Modules/cellGame.cpp [hunk 1]
```diff
@@ -373,6 +373,61 @@ extern void lv2_sleep(u64 timeout, ppu_thread* ppu = nullptr)
...
+			// Sleep before waiting on lock
+			lv2_obj::sleep(*ppu);
+		}
+		else
+		{
+			// Wake up after acquistion or failure to acquire
+			ppu->check_state();
+		}
+	}, ppu);
+}
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellGame.cpp:429]: This is not really cellGame code, so it should not be implemented here.

**Comment by jnackmclain** [comment]
@elad335 @Megamouse this commit broke loading game updates and dlc for Rock Band 3
0.0.31-16163 restores this. it looks like nothing can be read from dev_hdd0 by the game in 0.0.31-16164

Highly recommend reverting these two commits because they are actually devastating

**Comment by jnackmclain** [comment]
0.0.31-16168 is fixed. ignore my above comment
