### PR TITLE
sceNp/vm: Fix strings read, implement safe string reader

### LINKED ISSUE #14882: [NPUB90003] Full Auto 2 Battlelines Demo - Crashes on boot - Probably since #14584
### Quick summary

The build that most likely broke it didn't compile. kekw

Whenever you launch the game it will crash with
`F {PPU[0x1000000] Thread (main_thread) [HLE:0x008d16f4, LR:0x00103cd0]} PPU: Function aborted: sceNpDrmIsAvailable`
`F {PPU[0x1000000] Thread (main_thread) [HLE:0x008d16f4, LR:0x00103cd0]} VM: Access violation reading location 0xd0081000 (unmapped memory)`

### Details

_No response_

### Build with regression

0.0.29-15561 Probably

### Attach two log files

[Working](https://github.com/RPCS3/rpcs3/files/13625858/RPCS3.log.gz)
[Broken](https://github.com/RPCS3/rpcs3/files/13625867/RPCS3.log.gz)

### Attach capture files for visual issues

_No response_

### System configuration

_No response_

### Other details

_No response_

### PR DESCRIPTION
**Pull request by elad335**
Attempts to fix #14882, introduce a safe string reader.

### CODE REVIEW

**Comment by Megamouse** [comment]
Maybe just make it a string wrapper class that evaluates to false if it can't be built properly?
You will then still have all the string functionality afterwards.

**Comment by Ordinary205** [comment]
Can confirm that it resolves this issue on Full Auto 2 demo.
Full Auto
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13634080/RPCS3.log.gz)

File: rpcs3/rpcs3qt/main_window.cpp [hunk 1]
```diff
@@ -3530,7 +3527,7 @@ void main_window::AddGamesFromDirs(const QStringList& paths)
 		Emu.AddGamesFromDir(sstr(path));
 	}
 
-	m_game_list_frame->AddRefreshedSlot<class KeyType>([this, paths = std::move(paths), existing = std::move(existing)](std::set<QString>& IDs)
+	m_game_list_frame->AddRefreshedSlot([this, paths = std::move(paths), existing = std::move(existing)](std::set<std::string>& claimed_paths)
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/main_window.cpp:3530]: The move here is the main culprit
