### PR TITLE
rsx: Reduce capture size + image_in fixes

### LINKED ISSUE #4747: RSX: NV3089_IMAGE_IN: Invalid dimensions or scaling factor.
**Genji: Days of the Blade-(Demo)**
bez tytulu1
`E {rsx::thread} RSX: NV3089_IMAGE_IN: Invalid dimensions or scaling factor. Request ignored (ds_dx=1048576, dt_dy=4293918720)`

`F {rsx::thread} class std::runtime_error thrown: Verification failed: 
(in file c:\projects\rpcs3\rpcs3\emu\rsx\rsx_cache.h:105)`

Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2094670/RPCS3.log.gz)

-----------------------------------------------------------------------------------------------------------
**Atomic Ninjas-(Demo)**
bez tytulu2
`E {rsx::thread} RSX: NV3089_IMAGE_IN: Invalid dimensions or scaling factor. Request ignored (ds_dx=1048576, dt_dy=4293918720)`

Log:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2094676/RPCS3.log.gz)

### PR DESCRIPTION
**Pull request by elad335**
* Reduce capture size.
* ignore image_in transfers with empty clip region. its not executed at all according to hw tests.
* Dont "fix" in_pitch and out_pitch when 0 (image_in and buffer notify)
e.g when src pitch is 0, the same line is copied to the destination.
[testcase](https://github.com/elad335/myps3tests/tree/master/rsx_tests/image%20in) used
original [texture](https://imgur.com/k43HvCX).
[result](https://imgur.com/dkNa1ym) using image_in with zero src pitch.
[result](https://imgur.com/T2CQj9o) using buffer_notify with zero dst pitch;
[result](https://imgur.com/dkNa1ym) using buffer_notify with zero src pitch.
* Minor size of rect fixes.
* Add rsx lv2 defaults for sempahore context, cus vsh.
* Implement backwards source image reading in image_in. Fixes #4747.

### CODE REVIEW

**Comment by Deminating** [comment]
Will edit with findings as they go along

Surf's Up loadable -> ingame
NCAA March Madness 08 intro -> ingame, needs a mix of WCB/SRM/blit to show graphics
Mamorukun Curse ingame -> most likely playable, story mode fixed

File: rpcs3/Emu/RSX/rsx_utils.h [hunk 1]
```diff
@@ -182,6 +182,15 @@ namespace rsx
 		return result;
 	}
 
+	// Copy memory in inverse direction from source
```
Comment (kd-11) [inline rpcs3/Emu/RSX/rsx_utils.h]: Move this func above the Z index method to keep the morton order functions together (calculate_z_index, convert_linear_swizzle, convert_linear_swizzle_3d)

File: rpcs3/Emu/RSX/rsx_methods.cpp [hunk 2]
```diff
@@ -172,38 +172,35 @@ namespace rsx
 		void texture_read_semaphore_release(thread* rsx, u32 _reg, u32 arg)
 		{
 			// Pipeline barrier seems to be equivalent to a SHADER_READ stage barrier
-
-			const u32 index = method_registers.semaphore_offset_4097() >> 4;
 			// lle-gcm likes to inject system reserved semaphores, presumably for system/vsh usage
 			// Avoid calling render to avoid any havoc(flickering) they may cause from invalid flush/write
-
-			if (index > 63 && !rsx->do_method(NV4097_TEXTURE_READ_SEMAPHORE_RELEASE, arg))
+			const u32 offset = method_registers.semaphore_offset_4097() & -16u;
```
Comment (kd-11) [inline rpcs3/Emu/RSX/rsx_methods.cpp]: If the only usable values of context are DMA_SEMAPHORE_R and DMA_SEMAPHORE_RW, isn't this new code the same as the old one?

File: rpcs3/Emu/RSX/rsx_methods.cpp [hunk 3]
```diff
@@ -900,7 +900,7 @@ namespace rsx
 			u8* pixels_dst = vm::_ptr<u8>(get_address(dst_offset + out_offset, dst_dma));
 
 			const auto read_address = get_address(src_offset, src_dma);
-			rsx->read_barrier(read_address, in_pitch * in_h);
+			rsx->read_barrier(read_address, in_pitch * (in_h - 1) + (in_w * in_bpp));
```
Comment (kd-11) [inline rpcs3/Emu/RSX/rsx_methods.cpp]: good catch

File: rpcs3/Emu/RSX/rsx_methods.cpp [hunk 4]
```diff
@@ -853,25 +853,19 @@ namespace rsx
...
 				dst_dma = method_registers.blit_engine_output_location_nv3062();
 				dst_offset = method_registers.blit_engine_output_offset_nv3062();
 				dst_color_format = method_registers.blit_engine_nv3062_color_format();
 				out_pitch = method_registers.blit_engine_output_pitch_nv3062();
 				out_alignment = method_registers.blit_engine_output_alignment_nv3062();
-				break;
-
-			case blit_engine::context_surface::swizzle2d:
+			}
+			else
```
Comment (kd-11) [inline rpcs3/Emu/RSX/rsx_methods.cpp]: not sure why the switch was removed, allows invalid context_surface to get through here instead of throwing or showing error like before. The context value is 32 bits and has only 2 usable values, unless you confirmed that invalid context defaults to swizzle shuffle.

**Comment by digitaldude555** [comment]
screenshot 1285
game no longer black screen.

File: rpcs3/Emu/RSX/rsx_methods.cpp (hunk 2 above)
Comment (elad335) [reply rpcs3/Emu/RSX/rsx_methods.cpp]: the register is allowed to point to DEVICE_RW, only the initial value after sys_rsx init point to semaphore context.

File: rpcs3/Emu/RSX/rsx_methods.cpp (hunk 4 above)
Comment (elad335) [reply rpcs3/Emu/RSX/rsx_methods.cpp]: its already handled in the exception handler when converting to blit_engine::context_surface, so adding a default case here is no-op.

File: rpcs3/Emu/RSX/rsx_methods.cpp (hunk 2 above)
Comment (kd-11) [reply rpcs3/Emu/RSX/rsx_methods.cpp]: is device_rw different from semaphore_rw? If so, doesn't this undo part of your 406e_semaphore address work?

File: rpcs3/Emu/RSX/rsx_methods.cpp (hunk 4 above)
Comment (kd-11) [reply rpcs3/Emu/RSX/rsx_methods.cpp]: those to_xxxxx methods will be removed down the line, so all code going forward should assume they have no checks.

File: rpcs3/Emu/RSX/rsx_methods.cpp (hunk 2 above)
Comment (elad335) [reply rpcs3/Emu/RSX/rsx_methods.cpp]: I think I've rushed out the tests to fix skate, didnt notice the result were incorrect as it seemed "fitting" with his skate's behavior. later attempts to reproduce this failed so im leaving device context as is for now.

**Comment by micaelis72** [comment]
The huge amount of "RSX: NV3089_IMAGE_IN: Invalid dimensions or scaling factor." that exists on Macross 30 vanished. Other problems remains on the game, but this message has gone.
