### PR TITLE
PPU/SPU Interpreter + Recompiler instruction fixes and improvements

### LINKED ISSUE #2827: Regression: [BLES00296] SoulCalibur IV - PPU Interpreter Precise: Broken graphics in the menu orb (#2736)
Starting from the commit #2736

The graphics inside the ORB is pixelated in PPu precise. This was reported on the Pull request, however i misunderstood on how Github and Appveyor builds work and thought it was fixed by a different build

image

In PPU Interpreter (fast) and (precise prior to the commit). This is how the ORB looks, there is some graphics rendering and it is not pixelated
image

This is a minor issue but wanted to report as it may give some clue on the PPU threads and the Graphics rendering.

### LINKED ISSUE #4087: Sonic Unleashed [BLUS30244] PPU LLVM Errors
RPCS3 v0.0.5-7077-f0a9799b4 Alpha | HEAD
Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz | 4 Threads | 15.94 GiB RAM | AVX+ | TSX

Compatibility threads: [US](https://forums.rpcs3.net/thread-187276-post-297444.html) | [EU](https://forums.rpcs3.net/thread-184131.html)

Issues that can't be accessed easily on master will not be mentioned.

Missing Byte on Save ID
---
On PPU Recompiler LLVM, the save ID is cut off by one byte. (BLUS30244 -> BLUS3024) Both PPU interpreters do not have this issue.

Both logs go to the world map.
[PPU Interpreter Fast](https://github.com/RPCS3/rpcs3/files/2173121/RPCS3-SaveFast.log.gz)
[PPU Recompiler LLVM](https://github.com/RPCS3/rpcs3/files/2173119/RPCS3-SaveLLVM.log.gz)

Quickstep black screen while moving
---

Whenever Sonic is moving past his walking animations, the game will have a high tendency of black screening when doing the quick step move.

[Video Demonstration](https://streamable.com/za0bs)

Log goes until multiple quick steps in Holoska (Cool Edge) Act 1 day.
[PPU Interpreter Fast](https://github.com/RPCS3/rpcs3/files/2173122/RPCS3-QSFast.log.gz)
[PPU Recompiler LLVM](https://github.com/RPCS3/rpcs3/files/2173124/RPCS3-QSLLVM.log.gz)

Enemy Crash
---

Whenever an enemy spawns, the game will crash with an access violation.

[Video Demonstration](https://youtu.be/bJKg0ApFJxM)

Log goes until the first event setter in Apotos (Windmill Isle) Act 1 night.
[PPU Interpreter Fast](https://github.com/RPCS3/rpcs3/files/2173130/RPCS3-EventFast.log.gz)
[PPU Recompiler LLVM](https://github.com/RPCS3/rpcs3/files/2173127/RPCS3-EventLLVM.log.gz)

### PR DESCRIPTION
**Pull request by elad335**
* Fix a few SIMD with saturation instructions on ppu Fast and Precise decoders: Properly handle cases where destination reg is also one of the source registers. Fixes loading icon in Beyond Two Souls with ppu precise. Fixes #2827

* Improve FPCC handling in ppu interpreter to be closer to LLVM implementation, fixing part of #3516

* Rewrite VPKSHUS in ppu precise decoder to be almost as fast as its "fast" counterpart.

* Fix default non-java mode reported.

* Status check added to sys_prx_start/stop_module.

* like ppu interpreters, if the instruction/function is not found fallback to decoding single instructions in PPU LLVM recompiler, fixes part of #2909 . 

* Fix STSWI and LWSI instructions in ppu llvm when number of bytes isnt 32bit aligned.
* Increment cia manually in unregistered hle func access, this is not done automatically in llvm. Fixes #4087

* Prefetch byteswapped opcodes in PPU Interpreter, register usage optimizations.

* Implement BISLED instruction for all SPU decoders.

* Fix CFLTU instruction for SPU LLVM decoders.

### CODE REVIEW

File: rpcs3/Emu/Cell/PPUInterpreter.cpp [hunk 1]
```diff
@@ -368,7 +368,7 @@ bool ppu_interpreter_precise::VADDSBS(ppu_thread& ppu, ppu_opcode_t op)
 
 	for (u8 i = 0; i < 16; i++)
 	{
-		const s16 sum = a._s8[i] + b._s8[i];
+		const s16 sum = (s16)a._s8[i] + (s16)b._s8[i];
```
Comment (Nekotekina) [inline rpcs3/Emu/Cell/PPUInterpreter.cpp]: It's not a bug. Arithmetic ops promote smaller types to int.

File: rpcs3/Emu/Cell/PPUInterpreter.cpp [hunk 2]
```diff
@@ -1478,45 +1479,15 @@ bool ppu_interpreter_precise::VPKSHUS(ppu_thread& ppu, ppu_opcode_t op)
 {
 	const auto& a = ppu.vr[op.va];
 	const auto& b = ppu.vr[op.vb];
-	auto& d = ppu.vr[op.vd];
 
-	for (u8 i = 0; i < 8; i++)
+	// Detect saturation
+	if (const u64 _mask = 0xFF00FF00FF00FF00ULL;
```
Comment (Nekotekina) [inline rpcs3/Emu/Cell/PPUInterpreter.cpp]: Please, don't abuse new `if` syntax like this. It lies outside of its purpose: const doesn't effectively have a lifetime, it's only strange to read.

File: rpcs3/Emu/Cell/PPUInterpreter.cpp [hunk 3]
```diff
@@ -1530,7 +1501,7 @@ bool ppu_interpreter_precise::VPKSWSS(ppu_thread& ppu, ppu_opcode_t op)
 {
 	const auto& a = ppu.vr[op.va];
 	const auto& b = ppu.vr[op.vb];
-	auto& d = ppu.vr[op.vd];
+	v128 d;
```
Comment (Nekotekina) [inline rpcs3/Emu/Cell/PPUInterpreter.cpp]: Good catch but there are also some other instruction with similar problem missing.

File: rpcs3/Emu/Cell/PPUInterpreter.cpp [hunk 4]
```diff
@@ -2941,7 +2916,7 @@ bool ppu_interpreter::B(ppu_thread& ppu, ppu_opcode_t op)
 bool ppu_interpreter::MCRF(ppu_thread& ppu, ppu_opcode_t op)
 {
 	CHECK_SIZE(ppu_thread::cr, 32);
-	reinterpret_cast<u32*>(ppu.cr)[op.crfd] = reinterpret_cast<u32*>(ppu.cr)[op.crfs];
+	reinterpret_cast<u32*>(&ppu.cr)[op.crfd] = reinterpret_cast<u32*>(&ppu.cr)[op.crfs];
```
Comment (Nekotekina) [inline rpcs3/Emu/Cell/PPUInterpreter.cpp]: Don't reinterpret pointer to the struct, it's more correct to reinterpret `+ppu.cr.bits`.

File: rpcs3/Emu/Cell/PPUInterpreter.cpp [hunk 5]
```diff
@@ -4673,36 +4648,59 @@ bool ppu_interpreter::FNMADDS(ppu_thread& ppu, ppu_opcode_t op)
...
+
 	if (UNLIKELY(op.rc)) ppu_cr_set(ppu, 1, ppu.fpscr.fg, ppu.fpscr.fl, ppu.fpscr.fe, ppu.fpscr.fu);
 	return true;
 }
 
 bool ppu_interpreter::MFFS(ppu_thread& ppu, ppu_opcode_t op)
 {
 	LOG_WARNING(PPU, "MFFS");
-	ppu.fpr[op.frd] = 0.0;
+	ppu.fpr[op.frd] = u64{ppu.fpscr.fl} << 15 | u64{ppu.fpscr.fg} << 14 | u64{ppu.fpscr.fe} << 13 | u64{ppu.fpscr.fu} << 12;
```
Comment (Nekotekina) [inline rpcs3/Emu/Cell/PPUInterpreter.cpp]: Won't produce a correct result due to conversion from u64 to double.

File: rpcs3/Emu/Cell/PPUInterpreter.cpp [hunk 6]
```diff
@@ -4716,12 +4714,15 @@ bool ppu_interpreter::MTFSF(ppu_thread& ppu, ppu_opcode_t op)
 
 bool ppu_interpreter::FCMPU(ppu_thread& ppu, ppu_opcode_t op)
 {
-	const f64 a = ppu.fpr[op.fra];
-	const f64 b = ppu.fpr[op.frb];
-	ppu.fpscr.fg = a > b;
-	ppu.fpscr.fl = a < b;
-	ppu.fpscr.fe = a == b;
-	//ppu.fpscr.fu = a != a || b != b;
+	if (const f64 a = ppu.fpr[op.fra]; true)
```
Comment (Nekotekina) [inline rpcs3/Emu/Cell/PPUInterpreter.cpp]: Syntax abuse, again. What's the point of having a scope here?

File: rpcs3/Emu/Cell/PPUThread.cpp [hunk 7]
```diff
@@ -612,15 +612,15 @@ void ppu_thread::exec_task()
 
 			// Decode single instruction (may be step)
 			const u32 op = *reinterpret_cast<const be_t<u32>*>(base + cia);
-			if (reinterpret_cast<func_t>((std::uintptr_t)ppu_ref(cia))(*this, {op})) { cia += 4; }
+			if (reinterpret_cast<func_t>((std::uintptr_t)(cache + cia))(*this, {op})) { cia += 4; }
```
Comment (Nekotekina) [inline rpcs3/Emu/Cell/PPUThread.cpp]: It seems you forgot to cast and dereference the pointer `cache + cia`.

File: rpcs3/Emu/Cell/PPUInterpreter.cpp (hunk 5 above)
Comment (elad335) [reply rpcs3/Emu/Cell/PPUInterpreter.cpp]: right.

File: rpcs3/Emu/Cell/PPUInterpreter.cpp (hunk 3 above)
Comment (elad335) [reply rpcs3/Emu/Cell/PPUInterpreter.cpp]: Hopefully I've covered all the problematic cases.
In cases such as https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/Cell/PPUInterpreter.cpp#L365
it doesnt matter because of the way the register is being treated in equal sized slices between source and destination registers.

File: rpcs3/Emu/Cell/PPUInterpreter.cpp (hunk 6 above)
Comment (elad335) [reply rpcs3/Emu/Cell/PPUInterpreter.cpp]: Its to avoid assigning too many registers at a time for the compiler, keep in mind ppu_cr_set is inlined and assigns regs as well.
I'll reduce scope usage to only what benefits compiled code.

File: rpcs3/Emu/Cell/PPUInterpreter.cpp (hunk 2 above)
Comment (elad335) [reply rpcs3/Emu/Cell/PPUInterpreter.cpp]: used constexpr without scope instead.

File: rpcs3/Emu/Cell/PPUInterpreter.cpp (hunk 6 above)
Comment (Nekotekina) [reply rpcs3/Emu/Cell/PPUInterpreter.cpp]: That's an interesting claim. However I have doubts that even MSVC compiler is so bad it can't handle it automatically. I tried mostly newer versions of GCC and Clang, MSVC too (with /Ox parameter): https://godbolt.org/z/U8-FWF
Adding or removing the scope doesn't seem to affect generated code at all.

Comment (Nekotekina) [reply rpcs3/Emu/Cell/PPUInterpreter.cpp]: I won't say the example copies RPCS3 exactly - I'd like to see actual difference if it exists.

Comment (elad335) [reply rpcs3/Emu/Cell/PPUInterpreter.cpp]: ok checked it and there is no difference.

**Comment by Xcedf** [comment]
Baja Edge of Control, now works with LLVM and a lot faster with it
Interpreter fast

LLVM

**Comment by stride21** [comment]
Killzone 3 now goes ingame with PPU LLVM, but their doesn't seem to be a significant performance difference between PPU LLVM or Fast. 
PPU LLVM:
kz3 llvm
PPU Fast:
fast kz3

**Comment by Kravickas** [comment]
**WRC 5 FIA World Rally Championship** works with PPU LLVM

**Comment by raveskirza** [comment]
Fixes #2827 

With PPU precise
image

**Comment by jenci8888** [comment]
GT5 fixes PPU LLVM error, changed to Memory access violation (game version v2.06 or later)
`F {PPU[0x1000000] Thread (main_thread) [0x00f8f260]} MEM: Access violation reading location 0x1e7`
[RPCS3.gz](https://github.com/RPCS3/rpcs3/files/2990221/RPCS3.gz)

Then, GT6 disappeared PPU LLVM error, and still won't boot it. (Only Interpreter can boot it)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2990225/RPCS3.log.gz)

**Comment by Kravickas** [comment]
MGS Peace walker still broken with PPU LLVM - Unregistered function called (LR=0xc48c5c)

**Comment by MsDarkLow** [comment]
Yakuza 1&2 HD Edition now work with PPU LLVM. Performance is pretty much the same


Performance is pretty much the same between Interpreter & Recompiler because the game is lightweight

**Comment by uaqlover** [comment]
PPU LLVM

Pro Evolution Soccer 2015
Pro Evolution Soccer 2016 

black screen after stop the emulator

log file 
[RPCS3 4.log.gz](https://github.com/RPCS3/rpcs3/files/2990684/RPCS3.4.log.gz)

**Comment by arcadee1977** [comment]
<0.0.6-ddd0bb17>
SONIC UNLEASHED[BLES00425] crash issue at PPU LLVM still exist.

https://github.com/RPCS3/rpcs3/issues/5712

**Comment by elad335** [comment]
@Kravickas is it only logging that error you posted in recompiler?

**Comment by Dreamcast98** [comment]
**RBI Baseball 14** now works with PPU LLVM.

**Comment by Kravickas** [comment]
Oh it is logging unreg fuction even with interpreters, never noticed that and it go ingame 🤔

**Comment by TigiHof** [comment]
**Singularity** and **The Elder Scrolls IV: Oblivion** now work with PPU LLVM! 👍

**Comment by Xcedf** [comment]
Sonic Unleashed dark stages seems to be fixed now, and just like on Interpreted before had different savefolder, i needed to play from the beginning to see this, Thanks for an awesome work

**Comment by arcadee1977** [comment]
@Xcedf  Thank you for reminding me. It really no longer crash at night stages (Sonic Unleashed).

**Comment by elad335** [comment]
@Kravickas retest MGS Peace walker.

**Comment by Zangetsu38** [comment]
@elad335 works :) 
image

**Comment by Kravickas** [comment]
we need v2 PPU cache ?

**Comment by elad335** [comment]
Already updated cache ver in the first commit, but if you have older cache from that commit in this pr you need to clear it.
No need for v3 in the same pr.

**Comment by darkdragonz12** [comment]
dbz burst limit, crashes having these configurations,

ppu LLVM, LLVM RECOMPILER, SPU BLOCK SIZE = SAFE

I do not know if this can be repaired in this pr
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2997305/RPCS3.log.gz)

**Comment by uaqlover** [comment]
with 
0.0.6-2fe457bd
build it work pes 2015

FPS_ 59 87 _ Vulkan _ 0 0 6-2fe457bd-new-wip _ Pro Evolution Soccer 2015  BLES02088  22_03_2019 2_07_00 PM

pes 2016 

FPS_ 60 10 _ Vulkan _ 0 0 6-2fe457bd-new-wip _ Pro Evolution Soccer 2016  BLUS31564  22_03_2019 2_14_51 PM

pes 2017 also

FPS_ 59 87 _ OpenGL _ 0 0 6-2fe457bd-new-wip _ Pro Evolution Soccer 2017  BLUS31598  22_03_2019 2_20_58 PM

pes 2018 also

FPS_ 59 92 _ Vulkan _ 0 0 6-2fe457bd-new-wip _ PRO EVOLUTION SOCCER 2018  BLUS31612  22_03_2019 2_26_37 PM

Truck Racer [NPEB01838] black screen

FPS_ 199 69 _ Vulkan _ 0 0 6-2fe457bd-new-wip _ Truck Racer  NPEB01838  22_03_2019 2_29_32 PM

**Comment by uaqlover** [comment]
Pro Evolution Soccer 2015 only 

first time play the game it's fine second time it show black screen only if i remove ppu it will work again 

[RPCS3 pes 2015.log.gz](https://github.com/RPCS3/rpcs3/files/2998401/RPCS3.pes.2015.log.gz)

**Comment by yolanda123a** [comment]
with Sonic unleashed after a minuts
 F {RSX [0x005f748]} RSX: class std::runtime_error thrown: [attrib buffer] Working buffer not big enough, buffer_length=402653184 allocated=4294656 requested=4238650072 guard=4194304 largest_pool=1642752
(in file c:\projects\rpcs3\rpcs3\emu\rsx\common\ring_buffer_helper.h:78)

**Comment by money123451** [comment]
this PR allows unity games to run with ppu llvm which is a major speed up for many of them form ppu fast here are some examples

Before/After Comparisons (Click to Expand)
<details>
 <summary>MALICIOUS™  NPUA80797</summary>

PPU fast before
PPU LLVM after
</details>

<details>
 <summary> Oddworld: New 'n' Tasty  NPUB3141</summary>

PPU fast before
PPU LLVM after
</details>

<details>
 <summary> rain  NPUA80711</summary>

PPU fast before
PPU LLVM after
</details>

<details>
 <summary> CounterSpy™  NPUA80870</summary>

PPU fast before
PPU LLVM after
</details>

**Comment by toccata10** [comment]
Sky Force Anniversary [NPUB31813]:
on master:
F {PPU[0x1000005] Thread (UnityMain) [0x0156febc]} St13runtime_error thrown: Unregistered PPU function
With this PR: the PPU Recompiler gives a very welcomed boost compared to the ppu interpreter !
FPS: 59,93 | Vulkan | 0 0 6-7910-0b5bf22f-new-wip | Sky Force Anniversary  NPUB31813 _083

**Comment by elad335** [comment]
Doom 3 [NPUB30889] (nothing -> playable)
image

**Comment by questore** [comment]
Uncharted: Drake's Fortune freezes with:
F {RSX [0xa501fcc]} RSX: class std::runtime_error thrown: Unknown primitive type 208
(in file c:\projects\rpcs3\rpcs3\emu\rsx\gcm_enums.cpp:46)

**Comment by slashiee** [comment]
Testing the build you posted on #4994, LBP physics (#5011) are not fixed.

**Comment by toccata10** [comment]
Teslagrad doesn't launch on master with LLVM Recompiler:
F {PPU[0x1000005] Thread (UnityMain) [0x0124febc]} St13runtime_error thrown: Unregistered PPU function
It works very well (60fps) with your PR. I can imagine all the unity games listed in #2909 will improve by the same factor.

**Comment by uaqlover** [comment]
Test it with almost 40 games with unregistered PPU function fix all of it

**Comment by elad335** [comment]
Catherine, LOTR conquest, Initial D and Slpatterhouse are now working with SPU LLVM.

**Comment by CrabLugo** [comment]
This PR (don't know since which commit) fixed Fighting Climax Igniton SPU LLVM all intro freeze issues. This issue with intro freeze was occuring in few other games too

**Comment by legend800** [comment]
@elad335 Splatterhouse has always worked on SPU LLVM, but it's got the infiniete spam issue (I've run around the same hallway for like 10 mins and it never stops/contstantly freezing. 

Tried latest build with SPU ASMJIT and still freezes as it's loading into each level: 
F {PPU[0x1000000] Thread (main_thread) [0x003e0c44]} MEM: Access violation reading location 0x11e

Fingers crossed you can figure out this long-standing issue. 

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3051053/RPCS3.zip)

**Comment by uaqlover** [comment]
Now Professional BaseBall Spirits 2013 [BLAS50575] works fine with LLVM

FPS_ 56 46 _ Vulkan _ 0 0 6-4120ca14-new-wip _ Professional BaseBall Spirits 2013  BLAS50575  06_04_2019 6_14_22 PM

**Comment by uaqlover** [comment]
RPCS3 v0.0.6-4120ca14 Alpha | new-wip

FIX Juiced 2 : Hot Import Nights [BLES00143] ALSO FIX ISSUE WITH LOADING SAVE FILE IN MASTER GET OUT OF GAME 

MASTER 
RPCS3 v0.0.6-7934-7625f7df Alpha | HEAD




PR

FPS_ 30 00 _ OpenGL _ 0 0 6-4120ca14-new-wip _ Juiced 2 _ Hot Import Nights  BLES00143  06_04_2019 7_15_16 PM

**Comment by uaqlover** [comment]
Professional BaseBall Spirits 2014 [BLJM61148] works with LLVM with this pr

this pr been one of best because it made 30% games playable so like to see it merge soon

**Comment by maximilian578** [comment]
Resistance 3 [BCES01118] Ingame with PPU&SPU LLVM | Vulkan. Fps is close to 30 in closed environments but occasionally crashes with a `F {PPU[0x1000000] Thread (main_thread) [0x0085539c]} class std::runtime_error thrown: Trap! (0x85539c)`
Capture

**Comment by arcadee1977** [comment]
Gran Turismo 5 [BCAS20108] crash after loading game :
F {PPU[0x1000000] Thread (main_thread) [0x005c9944]} MEM: Access violation reading location 0x0

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3064557/RPCS3.zip)

**Comment by elad335** [comment]
@arcadee1977 does it work on ppu interpreters?

**Comment by arcadee1977** [comment]
> @arcadee1977 does it work on ppu interpreters?

Yes, I try. But it's still crash with ppu interpreters (precise & fast) : F {PPU[0x1000000] Thread (main_thread) [0x005c9960]} MEM: Access violation reading location 0x0

**Comment by AniLeo** [comment]
Gran Turismo doesn't work on some game versions even on master, beware of false regression reports

**Comment by arcadee1977** [comment]
> @arcadee1977 does it work on ppu interpreters?

Sorry,It's my fault. The game runs before it's install finished , so it crash.
