### PR TITLE
vk: Rework data heaps and revise our descriptor binding model

### LINKED ISSUE #18600: Worse GPU Performance on Pascal after vulkan rewrites
### Quick summary

There is a huge loss in gpu performance after rpcs3 ver. 0.0.38-18185. 

### Details

With rpcs3 version 0.0.38-18235 and above, there is a huge loss in gpu performance. As you can see bellow in the screenshots, Demon's Souls runs at 60 fps @1800p resolution in version 0.0.38-18185, but with every rpcs3 version after that one, the gpu usage goes to 100% and fps goes down to 40 (not just in Demon's Souls, but with every other game I've tested, gpu performance is worse especially when there are a lot of transparecy effects like fog and smoke).  To get the same level of performance as before, I need to drop the internal resolution to 1440p. I don't know if this is the indended behavior with newer rpcs3 builds where gpu is supposed to do more work, but yeah, a huge loss in performance.  

Image
Image

### Build with regression

v0.0.38-18235

### Attach two log files

Log file from version 0.0.38-18185: 

[RPCS3.log](https://github.com/user-attachments/files/26863187/RPCS3.log)
 
Log file from version 0.0.40-19193: 

[RPCS3.log](https://github.com/user-attachments/files/26863199/RPCS3.log)

### Attach capture files for visual issues

_No response_

### System configuration

Operating System: Windows 11 IOT Enterprise LTSC Version 24H2
CPU: Ryzen 7 9800x3D stock 
GPU: GTX 1080 driver version 576.88
RAM: Kingston Fury Beast 32GB DDR5 6000mhz cl30
SSD: NVMe WD_Black SN8100 2TB

### Other details

_No response_

### LINKED ISSUE #18625: Required Vulkan SDK is unavailable
### Quick summary

The Vulkan SDK version required for RPCS3 is no longer available online. 

### Details

The [build](https://github.com/RPCS3/rpcs3/blob/master/BUILDING.md) guide requires Vulkan SDK` 1.3.268.0` specifically.  However, this version isn't availble on the Vulkan [website](https://vulkan.lunarg.com/sdk/home) anymore as it is no longer officially supported, and a mirror doesn't appear to be available anywhere that I could find.  Could the build guide provide links to the SDK until support for more modern versions is added?

### LINKED ISSUE #18634: [Regression] Performance drops and graphical artifacting.
### Quick summary

After PR #17427 by kd-11, I've been experiencing a performance drop and lots of graphical artificating after the pr took effect.

### Details

This is what it supposed to look like: Image

The Regression: Image

### Build with regression

v0.0.38-18235-1cae72c8

### Attach two log files

[RPCS3Regressive.log](https://github.com/user-attachments/files/27086015/RPCS3Regressive.log)

[RPCS3Normal.log](https://github.com/user-attachments/files/27086016/RPCS3Normal.log)

### Attach capture files for visual issues

This is the working:
[BLUS30200_20260425101339_capture.rrc.gz](https://github.com/user-attachments/files/27086018/BLUS30200_20260425101339_capture.rrc.gz)
This is the regression:
[BLUS30200_20260425102040_capture.rrc.gz](https://github.com/user-attachments/files/27086022/BLUS30200_20260425102040_capture.rrc.gz)

### System configuration

I have a radxa rock 5c with 8gb of ram. It has the rk3588s SOC built in. It is running Ubuntu linux 24.04 and I installed rockchip proprietary drivers for the mali G610, the vahall g29p1 for specifics. Gpu driver version is 29.1.0. So mostly a Wayland + Vulkan + OpenGl ES graphics stack.

### Other details

Version I tested the working on: v0.0.38-18185-9e49b910

### PR DESCRIPTION
**Pull request by kd-11**
Reworks data heap management. Major changes include:

### 1. Simplify and optimize some rarely used paths
Some systems such as macOS use VRAM shadows for some functionality such as buffer textures and some SSBOs. The sync method was unoptimized, which is now fixed. Flags have also been added to make it possible to trivially make use of VRAM shadows without much complication - just set the heap flag and it's all handled behind the scenes.

### 2. Revert to UBOs for constant data whenever possible
During the descriptor rewrites, one pattern that was adopted was to use data heaps as arbitrary memory, similar to a C pointer. Stuff all the GPU data as you would on a CPU and forget about it. This has 2 benefits. First, there is no need to worry about access alignments. Secondly, we never need to update the descriptor bindings once we have created the objects once since the bindings never change. However, some hardware (especially NV hardware) has really slow memory access when using SSBOs in fragment shaders with long stalls accessing memory. Moving data to Re-BAR space helps but in the end we just had to go back to UBOs. On AMD, there is no difference between the UBOs and SSBOs but on NVIDIA the UBOs have a lot of restrictions making the allocate and forget pattern impossible. However, with some wrappers and window management helpers, this is now possible without much headache to create a sliding window and also a bulk allocator to allow C-style arrays while also respecting the hardware restrictions on address alignments.

### 3. Long overdue - upgrades glslang and Vulkan SDK to the latest versions.
This allows us to compile for SPIRV 1.5 target and generate SPIRV that supports Vulkan 1.2 model. This opens doors for some more modern techniques such as subgroup operations.

Closes https://github.com/RPCS3/rpcs3/issues/18600
Closes https://github.com/RPCS3/rpcs3/issues/18625
Closes https://github.com/RPCS3/rpcs3/issues/18634

### CODE REVIEW

File: rpcs3/Emu/RSX/VK/vkutils/data_heap.h [hunk 1]
```diff
@@ -58,8 +65,38 @@ namespace vk
...
+				// Driver specific. AMD allows viewing upto 4GB as UBO no problem.
+				return { *heap, 0, VK_WHOLE_SIZE };
+			}
+
+			if (utils::address_range64::start_length(offset, range).inside(m_cached_buffer_range)) [[ likely ]]
+			{
+				return { *heap, m_cached_buffer_range.start, m_cached_buffer_range.length() };
+			}
+
+			const u64 aligned_window_size = static_cast<u64>(window_size / Alignment) * Alignment;
```
Comment (Megamouse) [inline rpcs3/Emu/RSX/VK/vkutils/data_heap.h:89]: What if window size is 0

Comment (kd-11) [reply rpcs3/Emu/RSX/VK/vkutils/data_heap.h:89]: User error. If window is 0 it means we cannot even give the caller anything valid back.

**Comment by Virtua64** [comment]
The last commit is causing a lot of flashing/artifacts on the three games I tested. RTX 5050 / Windows 10.

RPCS3 v0.0.40-fdebfea3 = ok
RPCS3 v0.0.40-2e8b1924 = flashing

RPCS3 v0.0.40-2e8b1924:

https://github.com/user-attachments/assets/ece3d17a-cbcd-4a8c-8cf8-134e55b9cfa0


edit- Async Texture Streaming is disabled.

**Comment by kd-11** [comment]
@Virtua64 If you have the vulkan SDK enabled, you can share a log with debug output enabled (debug tab). It's strange to me how different NVIDIA cards are having different symptoms. AMD should be unaffected as their hardware does not require any kind of windowing (4GB heap bind supported).

**Comment by kd-11** [comment]
Ok, fixed the flickering and crashing issue. It was NV specific and only affecting some hardware generations.

**Comment by digant73** [comment]
I will make some more in deep testing this night. I tested yesterday night some games and I didn't see any regression on rtx5090.

**Comment by woj1993** [comment]
Can't start asuras wrath or eternal sonata on this branch. I wonder if shader interpreter is at fault here. Logs from starting asura's wrath (it hanged after compiling PPU the same as Ethernal Sonata)
[log.zip](https://github.com/user-attachments/files/27208007/log.zip)

Edit it seems that mode Async with shader interpreter is broken

**Comment by AniLeo** [comment]
Docker version and SDK link need to be updated. Looks good otherwise

**Comment by kd-11** [comment]
Finally all done. I need to run some perf testing on linux before merge though. NVIDIA's descriptor framework is quite awful with very restrictive ranges, so I'll need to verify that no regressions are introduced to other vendors.
In theory the changes done are a NOP on AMD/RADV with the only change being changing some bindings from SSBO to UBO. In theory that should help performance since we're using the same code but with better access patterns. Most of that is attributable to the raised min vulkan version really, since we wouldn't have runtime arrays otherwise.

**Comment by digant73** [comment]
made some testing yesterday night (so not on the latest commit) and it seems performance are good also on rtx5090. As far as I see, rebar setting (enabled by default on `Advanced` tab) has no impact on performance compared to current build

**Comment by kd-11** [comment]
Proceeding with merge since the results seem purely beneficial. I'll verify linux separately since a cleanup PR will be needed anyway.

File: rpcs3/Emu/RSX/VK/vkutils/data_heap.cpp [hunk 2]
```diff
@@ -192,7 +202,18 @@ namespace vk
...
 		{
-			dirty_ranges.push_back({ offset, offset, size });
+			bool insert = true;
+			if (!dirty_ranges.empty() && (dirty_ranges.back().dstOffset + dirty_ranges.back().size) == offset) [[ likely ]]
+			{
+				dirty_ranges.back().size += size;
+				insert = false;
+			}
+
+			if (insert)
```
Comment (Megamouse) [inline rpcs3/Emu/RSX/VK/vkutils/data_heap.cpp:212]: If else would also have done the trick  :)
