### PR TITLE
PPU/cellSpurs: MGS4: Fix cellSpursAddUrgentCommand race condition

### LINKED ISSUE #6514: Metal Gear Solid 4 24fps issue
It is well known issue, was able to bypass it with using libaudio.sprx
here's the video, normally i have 24fps stuck at this stage always
https://youtu.be/ximnrNKHC24
But with libaudio.sprx, video rendering is broken, menu broken as well have to blindly press Start and X to boot from save, and what most improtant as it shown in the end of the video it doesn't goes well with cutscenes and i can't progress further.
I bet on SPU problem, seen same thing before in Mass Effect 2&3, and some other game even before that, than it was fixed by some spu changes from Nekotekina.
If any other information is required, please let me konw.

### PR DESCRIPTION
**Pull request by elad335**
cellSpursAddUrgentCommand searches in 4 slots for an empty slot to put the command at.

image

At first, it seems to do so unordered.

Meanwhile, on SPU side, it expects an order between all the commands because it pops them it in FIFO manner.
Not keeping track of how many commands are queued in total.
This is the SPU function resposible:
image

[SPU_unqueue.txt](https://github.com/user-attachments/files/19407636/SPU_unqueue.txt.txt)

After second observation of cellSpursAddUrgentCommand, something odd takes places here.
Usually, reservation loops are individual and are expected to be closed without any changes of the previous loop affected by the proceeding one.
But in this case, after a single failure, the entire operation is reset, a loop of 4 reservation operations suddenly is reset completely.

This makes one wonder if it the HW expects something else here, perhaps it caches the reservation internally here?
After some adjustments to LDARX and STDCX to cache the reservation between succeeding loops, Metal Gear Solid 4 no longer freezes!

This commit also disables the MG4 cellSpurs Freeze patch by RPCS3, as it is no longer needed and can hurt performance.

Here is an MGS4 screenshot just for fun:

image

Now that the function behaves properly, the SPURS urgent command queue size is now 4 which is plenty room for the PPU and it no longer needs to spin on this function, waiting for an empty slot to become available.
I believe the behaviour of the hack is why #16903 affected MGS4 performance so much.

@cipherxof Please test performance on this build too!

Fixes #6514

### CODE REVIEW

File: Utilities/bin_patch.cpp [hunk 1]
```diff
@@ -907,6 +907,12 @@ static usz apply_modification(std::vector<u32>& applied, patch_engine::patch_inf
 {
 	const usz old_applied_size = applied.size();
 
+	if (patch.description.find("cellSpurs urgent commands hack") != umax && patch.hash.find("PRX-") != umax)
```
Comment (Megamouse) [inline Utilities/bin_patch.cpp:910]: please remove this. The software shouldn't have this type of nonsense.

Comment (elad335) [reply Utilities/bin_patch.cpp:910]: It hurts performance and is hack.

Comment (Megamouse) [reply Utilities/bin_patch.cpp:910]: well then remove it from the wiki man

Comment (Megamouse) [reply Utilities/bin_patch.cpp:910]: you might as well add all the other old patches that were ever created here.
This is beyond stupid

Comment (elad335) [reply Utilities/bin_patch.cpp:910]: I disagree, virtually all users who played MGS4 had this patch enabled before, the harm has already been done. I will consider removing this code it if the performance benefit won't be considerably large.

Comment (Megamouse) [reply Utilities/bin_patch.cpp:910]: I think it's bad practise and it has no place here.
It's not our responsibility to care about patches in the first place.

**Comment by cipherxof** [comment]
Amazing work @elad335 

Performance seems to be the same as the master build, however.

[RPCS3.log.gz](https://github.com/user-attachments/files/19407830/RPCS3.log.gz)

<details>
  <summary>Master</summary>
  
image

</details>

<details>
  <summary>PR</summary>
 
image
 
</details>

File: Utilities/bin_patch.cpp (hunk 1 above)
Comment (AniLeo) [reply Utilities/bin_patch.cpp:910]: What if we disable PRX patching of firmware modules? It doesn't have any other use case AFAIK. PRX patching is used but on game code only, besides this. Also avoids people working around this by renaming the patch.

Comment (HerrHulaHoop) [reply Utilities/bin_patch.cpp:910]: Alternatively, we could delete the patch from the wiki and bump the patch version from 1.2 to 1.3. That would force all users with legacy patch files to update it, removing the unwanted patch.

Comment (cipherxof) [reply Utilities/bin_patch.cpp:910]: > Alternatively, we could delete the patch from the wiki and bump the patch version from 1.2 to 1.3. That would force all users with legacy patch files to update it, removing the unwanted patch.

Invalidating all patches might be a bit too much. You're inevitably going to get a bunch of people in discord asking why their patches/games aren't working anymore. Disabling firmware patches seems like it would probably be efine.

Comment (kd-11) [reply Utilities/bin_patch.cpp:910]: Let's have clear separation of concerns here. It is not the emulator core's duty to police which patches a user is trying to enable. The reliance on patch having an exact string also brings up issues.
The solution here is straightforward - update the wiki to mention the patch is no longer needed and leave it at that.
If the patch works, the user loses some fps in the worst case, not the end of the world.
If the patch doesn't work, the wiki will tell them why and life goes on.

**Comment by FlexBy420** [comment]
Tried few games on this PR and they all seemed to run just fine.

**Comment by Jonathan44062** [comment]
I got a random freeze in SU
[Sonic Unleashed Elad PR.zip](https://github.com/user-attachments/files/19494400/Sonic.Unleashed.Elad.PR.zip)
