### PR TITLE
rsx: Fix exceptions

### LINKED ISSUE #9644: Debugger exception
Found while scrolling in debugger:

get_pretty_printing_function throws exceptions when one of the dump functions calls one of the "to_xxx" functions with an unknown type.

This causes a probably unwanted crash in the debugger.

### LINKED ISSUE #13075: Call of Duty 3 -  Unknown blend eq 0xffff
### Quick summary

It's a duplicate of #3357 which had been closed but it's still an issue.

### Details

Changing the setting to atomic or "atomic and ordered" in the advanced tab doesn't help. I remember not long ago the game was playable, now it's not even going ingame. It hangs right after the unskippable mission FMV.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10228175/RPCS3.log)

### Attach capture files for visual issues

Screenshot_251

### System configuration

My specs:
RPCS3 Version: 0.0.25-14476-7e35679e Alpha | master
i9 9980HK ES
16 gb RAM
GTX 1060
Driver 473.33

### Other details

_No response_

### PR DESCRIPTION
**Pull request by elad335**
- Do not crash RPCS3 when encountering some invalid RSX instructions in the debugger.
- Fix RSX exception message in some rare cases.

Fixes the log message in #13075, the anti-corruption mechanism was actually working just fine.
Fixes #9644

### CODE REVIEW

File: rpcs3/Emu/RSX/rsx_methods.cpp [hunk 1]
```diff
@@ -839,7 +839,7 @@ namespace rsx
 
 				default:
 					// Ignored on RSX
-					method_registers.decode(reg, method_registers.register_previous_value);
+					method_registers.registers[reg] = method_registers.register_previous_value;
```
Comment (kd-11) [inline rpcs3/Emu/RSX/rsx_methods.cpp:842]: I'd rather have a proper method for this like "store" or "set"
It is sometimes important to hook into it to debug stuff, its easier if it all happens in a single place.

**Comment by elad335** [comment]
Turns out the exception message was actually wrong, it works fine before and after this pr on my pc so the crash is about something more specific currently unknown,

**Review by kd-11 — APPROVED** [review]
Adding all those "invalid" enumerations to enums is pollution and I don't agree with the solution from a design POV.
However, there are no easy/quick solutions to that as it is a design issue in the first place.
I've created https://github.com/RPCS3/rpcs3/issues/13091 to fix the problems I have with this PR.
