### PR TITLE
fix basic_string warnings

### LINKED ISSUE #16259: Fails to build with libc++ 19
Regressed by https://github.com/llvm/llvm-project/commit/c3668779c135. From [error log](https://pkg-status.freebsd.org/beefy18/data/main-amd64-default/p645a502a4f60_s8b2e7da7085/logs/rpcs3-0.0.33.17055.log):
```c++
$ export CC=clang CXX=clang++ CXXFLAGS=-stdlib=libc++
$ cmake -G Ninja -B _build
$ cmake --build _build
[...]
/usr/include/c++/v1/string:820:42: error: implicit instantiation of undefined template 'std::char_traits<unsigned long>'
  static_assert(is_same<_CharT, typename traits_type::char_type>::value,
                                         ^
rpcs3/Emu/Cell/PPUAnalyser.h:184:25: note: in instantiation of template class 'std::basic_string<unsigned int>' requested here
        std::basic_string<u32> applied_patches;
                               ^
rpcs3/Emu/Cell/lv2/sys_prx.h:198:26: note: in instantiation of template class 'std::basic_string<bool>' requested here
        std::basic_string<bool> m_loaded_flags;
                                ^
rpcs3/Emu/System.cpp:1228:39: note: in instantiation of template class 'std::basic_string_view<unsigned char>' requested here
                                        const std::basic_string_view<u8> dirname{reinterpret_cast<const u8*>(game_data.data()), game_data.size()};
                                                                         ^
rpcs3/util/logs.cpp:401:52: note: in instantiation of template class 'std::basic_string<unsigned long>' requested here
        /*constinit thread_local*/ std::basic_string<u64> args;
                                                          ^
rpcs3/util/logs.cpp:410:7: note: in instantiation of member function 'std::basic_string<unsigned long>::resize' requested here
        args.resize(args_count);
             ^
Utilities/bin_patch.cpp:912:38: note: in instantiation of template class 'std::basic_string<unsigned int>' requested here
        const usz old_applied_size = applied.size();
                                            ^
Utilities/bin_patch.cpp:992:14: note: in instantiation of member function 'std::basic_string<unsigned int>::push_back' requested here
                                        applied.push_back(::narrow<u32>(&p - patch.data_list.data())); // Remember index in case of failure to allocate any memory
                                                ^
Utilities/bin_patch.cpp:1012:11: note: in instantiation of member function 'std::basic_string<unsigned int>::resize' requested here
                applied.resize(old_applied_size);
                        ^
/usr/include/c++/v1/string_view:300:42: error: implicit instantiation of undefined template 'std::char_traits<unsigned char>'
  static_assert(is_same<_CharT, typename traits_type::char_type>::value,
                                         ^
Utilities/File.cpp:296:31: note: in instantiation of template class 'std::basic_string_view<unsigned char>' requested here
                        std::basic_string_view<u8> data_view;
                                                   ^
Utilities/File.cpp:332:61: note: in instantiation of function template specialization 'std::__1::operator==<unsigned char, std::char_traits<unsigned char>>' requested here
                return _rhs.type_view == _lhs.type_view && _rhs.data_view == _lhs.data_view;
                                                                          ^
rpcs3/Crypto/unedat.cpp:617:15: note: in instantiation of template class 'std::basic_string_view<unsigned char>' requested here
        for (usz i = std::basic_string_view<u8>(buf.get() + 0x30, file_name.size()).find_last_of('.'); i < buf_len; i++)
                     ^
rpcs3/Crypto/unedat.cpp:617:78: note: in instantiation of member function 'std::basic_string_view<unsigned char>::find_last_of' requested here
        for (usz i = std::basic_string_view<u8>(buf.get() + 0x30, file_name.size()).find_last_of('.'); i < buf_len; i++)
                                                                                    ^
rpcs3/Emu/Cell/PPUAnalyser.h:180:8: note: while declaring the implicit move constructor for 'main_ppu_module'
struct main_ppu_module : public ppu_module
       ^
rpcs3/Emu/Cell/PPUAnalyser.h:184:25: note: in instantiation of template class 'std::basic_string<unsigned int>' requested here
        std::basic_string<u32> applied_patches;
                               ^
rpcs3/Loader/PSF.cpp:78:45: note: in instantiation of template class 'std::basic_string_view<unsigned char>' requested here
                fmt::append(out, "%s: %s\n", entry.first, std::basic_string_view<u8>(reinterpret_cast<const u8*>(entry.second.as_string().data()), entry.second.size()));
                                                          ^
```

Affects future versions of FreeBSD, macOS and Chimera Linux. See also [related downstream bug](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=282329).

### PR DESCRIPTION
**Pull request by oltolm**
This is my attempt to fix the `std::basic_string` errors when compiling with libc++19. I wasn't sure in some places whether the fix is correct which is why it is a draft. At least it build.

Fixes #16259.

### CODE REVIEW

**Comment by Nekotekina** [comment]
char32_t is not allowed to contain any 32-bit value, it's only for Unicode codepoints.

**Comment by elad335** [comment]
Replace std::basic_string with std::vector, std::basic_string_view with std::span, avoid changing value types.

**Review by elad335 — APPROVED** [review]

File: rpcs3/rpcs3qt/debugger_frame.cpp [hunk 1]
```diff
@@ -753,8 +756,8 @@ void debugger_frame::keyPressEvent(QKeyEvent* event)
 			default: break;
 			}
 
-			if (const usz pos = std::basic_string_view<u32>(res.data(), 2).find_last_not_of(umax); pos != umax)
-				m_debugger_list->ShowAddress(res[pos] - std::max(row, 0) * 4, true);
+			if (auto it = std::find_if_not(res.rbegin(), res.rend(), std::bind(std::equal_to<u32>(), _1, umax)); it != res.rend())
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/debugger_frame.cpp:759]: please use a lambda instead of std::bind

File: rpcs3/Crypto/unedat.cpp [hunk 2]
```diff
@@ -614,9 +614,11 @@ bool validate_npd_hashes(std::string_view file_name, const u8* klicensee, NPD_HE
 	std::memcpy(buf_lower.get(), buf.get(), buf_len);
 	std::memcpy(buf_upper.get(), buf.get(), buf_len);
 
-	for (usz i = std::basic_string_view<u8>(buf.get() + 0x30, file_name.size()).find_last_of('.'); i < buf_len; i++)
+	auto buf_span = std::span(buf.get(), buf.get() + buf_len);
+	auto it = std::find(buf_span.rbegin(), buf_span.rend() - 0x30, '.');
```
Comment (Megamouse) [inline rpcs3/Crypto/unedat.cpp:618]:
```suggestion
	const auto buf_span = std::span(buf.get(), buf.get() + buf_len);
	const auto it = std::find(buf_span.rbegin(), buf_span.rend() - 0x30, '.');
```

File: rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp [hunk 3]
```diff
@@ -479,7 +482,7 @@ error_code sceNpTrophyCreateContext(vm::ptr<u32> context, vm::cptr<SceNpCommunic
 		return SCE_NP_TROPHY_ERROR_INVALID_NP_COMM_ID;
 	}
 
-	if (std::basic_string_view<u8>(&commSign_data.data[6], 6).find_first_not_of('\0') != umax)
+	if (std::all_of(&commSign_data.data[6], &commSign_data.data[6] + 6, std::bind(std::equal_to<u8>(), _1, '\0')))
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp:485]: please use a lambda instead of std::bind

File: rpcs3/Emu/Cell/SPUCommonRecompiler.cpp [hunk 4]
```diff
@@ -33,6 +34,15 @@ const extern spu_decoder<spu_iflag> g_spu_iflag;
 
 constexpr u32 s_reg_max = spu_recompiler_base::s_reg_max;
 
+struct SpanLess
+{
+
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/SPUCommonRecompiler.cpp:39]: empty line

File: rpcs3/rpcs3qt/debugger_frame.cpp (hunk 1 above)
Comment (elad335) [reply rpcs3/rpcs3qt/debugger_frame.cpp:759]: With the godsend FN macro

File: rpcs3/Emu/Cell/PPUModule.cpp [hunk 5]
```diff
@@ -1363,12 +1362,14 @@ static void ppu_check_patch_spu_images(const ppu_module& mod, const ppu_segment&
 			}
 
 			// Apply the patch
-			applied += g_fxo->get<patch_engine>().apply(hash, [&](u32 addr, u32 /*size*/) { return addr + elf_header + prog.p_offset; }, prog.p_filesz, prog.p_vaddr);
+			auto tmp = g_fxo->get<patch_engine>().apply(hash, [&](u32 addr, u32 /*size*/) { return addr + elf_header + prog.p_offset; }, prog.p_filesz, prog.p_vaddr);
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/PPUModule.cpp:1365]:
```suggestion
			const auto tmp = g_fxo->get<patch_engine>().apply(hash, [&](u32 addr, u32 /*size*/) { return addr + elf_header + prog.p_offset; }, prog.p_filesz, prog.p_vaddr);
```

File: rpcs3/Emu/Cell/PPUModule.cpp [hunk 6]
```diff
@@ -1363,12 +1362,14 @@ static void ppu_check_patch_spu_images(const ppu_module& mod, const ppu_segment&
...
+			applied.insert(applied.end(), tmp.begin(), tmp.end());
 
 			if (!Emu.GetTitleID().empty())
 			{
 				// Alternative patch
-				applied += g_fxo->get<patch_engine>().apply(Emu.GetTitleID() + '-' + hash, [&](u32 addr, u32 /*size*/) { return addr + elf_header + prog.p_offset; }, prog.p_filesz, prog.p_vaddr);
+				auto tmp = g_fxo->get<patch_engine>().apply(Emu.GetTitleID() + '-' + hash, [&](u32 addr, u32 /*size*/) { return addr + elf_header + prog.p_offset; }, prog.p_filesz, prog.p_vaddr);
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/PPUModule.cpp:1371]:
```suggestion
				const auto tmp = g_fxo->get<patch_engine>().apply(Emu.GetTitleID() + '-' + hash, [&](u32 addr, u32 /*size*/) { return addr + elf_header + prog.p_offset; }, prog.p_filesz, prog.p_vaddr);
```

File: rpcs3/Emu/Cell/PPUModule.cpp [hunk 7]
```diff
@@ -1846,13 +1847,14 @@ std::shared_ptr<lv2_prx> ppu_load_prx(const ppu_prx_object& elf, bool virtual_lo
 		if (!Emu.GetTitleID().empty())
 		{
 			// Alternative patch
-			_applied += g_fxo->get<patch_engine>().apply(Emu.GetTitleID() + '-' + hash_seg, [&](u32 addr, u32 size) { return prx->get_ptr<u8>(addr + seg.addr, size); }, seg.size);
+			auto tmp = g_fxo->get<patch_engine>().apply(Emu.GetTitleID() + '-' + hash_seg, [&](u32 addr, u32 size) { return prx->get_ptr<u8>(addr + seg.addr, size); }, seg.size);
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/PPUModule.cpp:1850]:
```suggestion
			const auto tmp = g_fxo->get<patch_engine>().apply(Emu.GetTitleID() + '-' + hash_seg, [&](u32 addr, u32 size) { return prx->get_ptr<u8>(addr + seg.addr, size); }, seg.size);
```

File: rpcs3/Emu/Cell/PPUModule.cpp [hunk 8]
```diff
@@ -1877,10 +1879,11 @@ std::shared_ptr<lv2_prx> ppu_load_prx(const ppu_prx_object& elf, bool virtual_lo
 				// Find the first segment
 				if (prog.p_type == 0x1u /* LOAD */ && prog.p_memsz)
 				{
-					std::basic_string_view<uchar> elf_memory{prog.bin.data(), prog.bin.size()};
-					elf_memory.remove_prefix(end - prx->segs[0].addr);
+					std::span<const uchar> elf_memory{prog.bin.begin(), prog.bin.size()};
+					elf_memory = elf_memory.subspan(end - prx->segs[0].addr);
 
-					if (elf_memory != std::basic_string_view<uchar>{&prx->get_ref<uchar>(end), elf_memory.size()})
+					auto tmp = std::span<uchar>{&prx->get_ref<uchar>(end), elf_memory.size()};
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/PPUModule.cpp:1885]:
```suggestion
					const auto tmp = std::span<uchar>{&prx->get_ref<uchar>(end), elf_memory.size()};
```

File: rpcs3/Emu/Cell/PPUModule.cpp [hunk 9]
```diff
@@ -2203,7 +2206,8 @@ bool ppu_load_exec(const ppu_exec_object& elf, bool virtual_load, const std::str
 	if (!ar && !Emu.GetTitleID().empty())
 	{
 		// Alternative patch
-		applied += g_fxo->get<patch_engine>().apply(Emu.GetTitleID() + '-' + hash, [&](u32 addr, u32 size) { return _main.get_ptr<u8>(addr, size); });
+		auto tmp = g_fxo->get<patch_engine>().apply(Emu.GetTitleID() + '-' + hash, [&](u32 addr, u32 size) { return _main.get_ptr<u8>(addr, size); });
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/PPUModule.cpp:2209]:
```suggestion
		const auto tmp = g_fxo->get<patch_engine>().apply(Emu.GetTitleID() + '-' + hash, [&](u32 addr, u32 size) { return _main.get_ptr<u8>(addr, size); });
```

File: Utilities/bin_patch.h [hunk 10]
```diff
@@ -215,7 +215,7 @@ class patch_engine
 	void append_title_patches(std::string_view title_id);
 
 	// Apply patch (returns the number of entries applied)
-	std::basic_string<u32> apply(const std::string& name, std::function<u8*(u32, u32)> mem_translate, u32 filesz = -1, u32 min_addr = 0);
+	std::vector<u32> apply(const std::string& name, std::function<u8*(u32, u32)> mem_translate, u32 filesz = -1, u32 min_addr = 0);
```
Comment (elad335) [inline Utilities/bin_patch.h:218]: Actually because the result is used in insertation almost exclusively, better to append the result to incoming vector argument reference.

File: rpcs3/Emu/Cell/PPUModule.cpp [hunk 11]
```diff
@@ -2216,10 +2220,11 @@ bool ppu_load_exec(const ppu_exec_object& elf, bool virtual_load, const std::str
 				// Find the first segment
 				if (prog.p_type == 0x1u /* LOAD */ && prog.p_memsz)
 				{
-					std::basic_string_view<uchar> elf_memory{prog.bin.data(), prog.bin.size()};
-					elf_memory.remove_prefix(end - _main.segs[0].addr);
+					std::span<const uchar> elf_memory{prog.bin.begin(), prog.bin.size()};
+					elf_memory = elf_memory.subspan(end - _main.segs[0].addr);
 
-					if (elf_memory != std::basic_string_view<uchar>{&_main.get_ref<u8>(end), elf_memory.size()})
+					auto tmp = std::span<uchar>{&_main.get_ref<u8>(end), elf_memory.size()};
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/PPUModule.cpp:2226]:
```suggestion
					const auto tmp = std::span<uchar>{&_main.get_ref<u8>(end), elf_memory.size()};
```

**Review by elad335 — CHANGES_REQUESTED** [review]

File: rpcs3/Emu/Cell/PPUModule.cpp [hunk 12]
```diff
@@ -2886,7 +2891,8 @@ std::pair<std::shared_ptr<lv2_overlay>, CellError> ppu_load_overlay(const ppu_ex
 	if (!Emu.DeserialManager() && !Emu.GetTitleID().empty())
 	{
 		// Alternative patch
-		applied += g_fxo->get<patch_engine>().apply(Emu.GetTitleID() + '-' + hash, [ovlm](u32 addr, u32 size) { return ovlm->get_ptr<u8>(addr, size); });
+		const auto& tmp = g_fxo->get<patch_engine>().apply(Emu.GetTitleID() + '-' + hash, [ovlm](u32 addr, u32 size) { return ovlm->get_ptr<u8>(addr, size); });
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/PPUModule.cpp:2894]:
```suggestion
		const auto tmp = g_fxo->get<patch_engine>().apply(Emu.GetTitleID() + '-' + hash, [ovlm](u32 addr, u32 size) { return ovlm->get_ptr<u8>(addr, size); });
```

File: rpcs3/rpcs3qt/debugger_frame.cpp (hunk 1 above)
Comment (Megamouse) [reply rpcs3/rpcs3qt/debugger_frame.cpp:759]: I hate that macro XD
terrible design decision

File: rpcs3/Emu/Cell/PPUModule.cpp (hunk 12 above)
Comment (elad335) [reply rpcs3/Emu/Cell/PPUModule.cpp:2894]: All of these can be eliminated per the suggestion at https://github.com/RPCS3/rpcs3/pull/16261#discussion_r1827046740

File: rpcs3/Emu/Cell/SPUCommonRecompiler.cpp [hunk 13]
```diff
@@ -33,6 +34,14 @@ const extern spu_decoder<spu_iflag> g_spu_iflag;
 
 constexpr u32 s_reg_max = spu_recompiler_base::s_reg_max;
 
+struct SpanLess
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/SPUCommonRecompiler.cpp:37]: snake_case

Comment (oltolm) [reply rpcs3/Emu/Cell/SPUCommonRecompiler.cpp]: fixed

File: rpcs3/Crypto/unedat.cpp (hunk 2 above)
Comment (oltolm) [reply rpcs3/Crypto/unedat.cpp]: also fixed

File: rpcs3/Emu/Cell/SPUCommonRecompiler.cpp [hunk 14]
```diff
@@ -33,6 +34,21 @@ const extern spu_decoder<spu_iflag> g_spu_iflag;
 
 constexpr u32 s_reg_max = spu_recompiler_base::s_reg_max;
 
+template <typename T>
+bool operator<(const std::span<T>& this_, const std::span<T>& that)
+{
+	return std::lexicographical_compare(this_.begin(), this_.end(), that.begin(), that.end());
```
Comment (elad335) [inline rpcs3/Emu/Cell/SPUCommonRecompiler.cpp:40]: You can use std::memcmp or something like that for SPU data comparison, its just bits.. there is no reason for it to preserve this bwhaviour it only needs to detect unequality properly for ordered containers.

Comment (oltolm) [reply rpcs3/Emu/Cell/SPUCommonRecompiler.cpp]: I hope I understood you correctly. I changed it to use `std::memcmp` and do a comparison that does not take the span length into account.

Comment (elad335) [reply rpcs3/Emu/Cell/SPUCommonRecompiler.cpp]: What I mean is, remove this operator overload and perform this code in SPU specifically.

Comment (oltolm) [reply rpcs3/Emu/Cell/SPUCommonRecompiler.cpp]: I removed it. If it is still not correct, just push to this PR. It's faster than trying to explain it.

**Review by elad335 — APPROVED** [review]

File: Utilities/File.cpp [hunk 15]
```diff
@@ -311,7 +312,7 @@ namespace fs
 			}
 
 			// Remove offsets data
-			id.data_view.remove_suffix(sizeof(u64) * offset_count);
```
Comment (elad335) [inline Utilities/File.cpp:314]: Lmao, I think this fixed a bug. 👍
