### PR TITLE
cellGame: Revert cellGameDataCheckCreate2 change for now

### LINKED ISSUE #12180: Rock Band 2 reverts to version 1.0 and doesn't launch after exiting (0.0.22-13752)
(fixed wrong build number in report i am sorry)

## Quick summary
After stopping emulation of Rock Band 2 in build 0.0.22-13752 (https://github.com/RPCS3/rpcs3/pull/12179), the game reverts back to version 1.00 and can no longer boot again until game patch 1.02 is reapplied. Attempting to boot the game again right after exiting gives the error message "Boot failed: The selected file or folder is invalid or corrupted." Reapplying the latest official game patch will allow the game to run one more time before causing this error again.

In build 0.0.22-13750, this behavior is not present and works as intended.

## Details
Previously it would keep whatever patch was installed and still be able to boot without reinstalling.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
* 0.0.22-13752 (https://github.com/RPCS3/rpcs3/pull/12179) is causing the issue.
* 0.0.22-13750 is the latest build without the issue.

#### 2. Please attach TWO logs:
* Error log (game fails to boot second time): [RPCS3.log](https://github.com/RPCS3/rpcs3/files/8841053/RPCS3.log)

* Correct behavior log (game boots multiple times): [RPCS3.log](https://github.com/RPCS3/rpcs3/files/8841060/RPCS3.log)

(fixed incorrect logs)

#### 3. If you describe graphical regression, please provide an RSX capture and a RenderDoc capture that demonstrate it.
None.

#### 4. Please attach screenshots of your problem.
screenshot regression
This is the error box that shows up. No error messages show up until the game is already exited and attempted to re-boot.

#### 5. Please provide comparison with real PS3.
N/A

#### Please provide your system configuration:
* Windows 10 64-bit
* Intel i7-9700k
* RTX 2080 Super

I think it might have something to do with "• 0.0.22-13752: cellGame: Make stats storage non-temporary, fix cbSet->setParam"?

### PR DESCRIPTION
**Pull request by elad335**
Should fix #12180

### CODE REVIEW

File: rpcs3/Emu/Cell/Modules/cellGame.cpp [hunk 1]
```diff
@@ -802,8 +802,8 @@ error_code cellGameDataCheckCreate2(ppu_thread& ppu, u32 version, vm::cptr<char>
 		strcpy_trunc(cbGet->getParam.titleLang[i], psf::get_string(sfo, fmt::format("TITLE_%02d", i)));
 	}
 
-	std::memset(g_file_param.get_ptr(), 0, sizeof(*g_file_param));
-	cbSet->setParam = g_file_param;
+	//std::memset(g_file_param.get_ptr(), 0, sizeof(*g_file_param));
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/Modules/cellGame.cpp:805]: Please add a comment

Comment (elad335) [reply rpcs3/Emu/Cell/Modules/cellGame.cpp:806]: Fixed.

Comment (Megamouse) [reply rpcs3/Emu/Cell/Modules/cellGame.cpp:806]: the setParam is assigned in the CELL_GAMEDATA_CBRESULT_OK below.
Maybe just move this code there

Comment (Megamouse) [reply rpcs3/Emu/Cell/Modules/cellGame.cpp:806]: I think you can safely remove this code.
The developer is supposed to set this parameter in funcStat, which is then used to update the PARAM.SFO.
It's recommended to use null, since it's some broken legacy feature.
