### PR TITLE
Fix sys_mmapper_unmap_shared_memory

### LINKED ISSUE #17119: [Regression] Entire emulator crashes with some games
### Quick summary

it seems PR #17116 is causing the crash of the emulator with some games. With GT5 the emulator crashes after displaying the logo. With Killzone 3 the emulator crashes once you close the game.
Unfortunately no log file has been produced.

### Details

_No response_

### Build with regression

v0.0.36-17842

### Attach two log files

no log file was produced

### Attach capture files for visual issues

_No response_

### System configuration

_No response_

### Other details

_No response_

### PR DESCRIPTION
**Pull request by elad335**
Should fix #17119

### CODE REVIEW

File: rpcs3/Emu/Cell/lv2/sys_mmapper.cpp [hunk 1]
```diff
@@ -629,13 +629,17 @@ error_code sys_mmapper_map_shared_memory(ppu_thread& ppu, u32 addr, u32 mem_id,
 			return CELL_EALIGN;
 		}
 
-		while (!mem.shm)
+		for (stx::shared_ptr<std::shared_ptr<utils::shm>> to_insert, null; !mem.shm;)
```
Comment (Megamouse) [inline rpcs3/Emu/Cell/lv2/sys_mmapper.cpp:632]: what is null for ?

Comment (elad335) [reply rpcs3/Emu/Cell/lv2/sys_mmapper.cpp:632]: its to compare with old value, and save the old value in case of commit failure.

**Comment by Megamouse** [comment]
Can you also remove this ?
/rpcs3/rpcs3/Emu/Cell/PPUAnalyser.cpp:535:37: warning: unused variable 'is_range' [-Wunused-const-variable]
  535 | static constexpr struct range_tag{} is_range;

**Comment by digant73** [comment]
@elad335 thanks, I can test this night
