### PR TITLE
Replace QNetwork operations with libcurl + wolfssl

### LINKED ISSUE #7575: OpenSSL broken on the Linux Appimage
## Quick summary
RPCS3 is unable to use its own updater nor download the compatibility database for games either. Forcing the user to have to go to the RPCS3 website to download any updates. OpenSSL _**is**_ installed on the home system.

## Details
Logs: https://files.catbox.moe/9sn4zo.gz

System specs: https://i.imgur.com/SxBEIaA.png

Proof that OpenSSL is installed on my system: https://i.imgur.com/ELRdq8l.png

### PR DESCRIPTION
**Pull request by RipleyTom**
closes #7575

### CODE REVIEW

File: rpcs3/rpcs3qt/game_compatibility.cpp [hunk 1]
```diff
@@ -4,22 +4,59 @@
...
 }
 
+size_t game_compatibility::update_buffer(char* data, size_t size)
+{
+	if (m_curl_abort)
+	{
+		return 0;
+	}
+
+	auto old_size = m_curl_buf.size();
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/game_compatibility.cpp]: const

File: rpcs3/rpcs3qt/game_compatibility.cpp [hunk 2]
```diff
@@ -4,22 +4,59 @@
...
+	auto new_size = old_size + size;
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/game_compatibility.cpp]: const

File: rpcs3/rpcs3qt/game_compatibility.cpp [hunk 3]
```diff
@@ -118,112 +155,44 @@ void game_compatibility::RequestCompatibility(bool online)
...
+	curl_easy_setopt(m_curl, CURLOPT_WRITEFUNCTION, curl_write_cb_compat);
+	curl_easy_setopt(m_curl, CURLOPT_WRITEDATA, this);
+	curl_easy_setopt(m_curl, CURLOPT_FOLLOWLOCATION, 1);
+
+	m_curl_buf.clear();
+	m_curl_abort = false;
 
 	// Handle abort
-	connect(m_progress_dialog, &QProgressDialog::canceled, network_reply, &QNetworkReply::abort);
+	connect(m_progress_dialog, &QProgressDialog::canceled, [&] { m_curl_abort = true; });
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/game_compatibility.cpp]: [this] should be enough in the capture

File: rpcs3/rpcs3qt/update_manager.cpp [hunk 4]
```diff
@@ -214,11 +195,10 @@ bool update_manager::handle_json(const QByteArray& data, bool automatic)
 		tm cur_tm, lts_tm;
 		QString timediff = "";
 
-		auto time_from_str = [](const std::string& str, const std::string& format, tm* tm) -> bool
-		{
+		auto time_from_str = [](const std::string& str, const std::string& format, tm* tm) -> bool {
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/update_manager.cpp]: Format

File: rpcs3/rpcs3qt/update_manager.cpp [hunk 5]
```diff
@@ -252,41 +232,47 @@ bool update_manager::handle_json(const QByteArray& data, bool automatic)
 	m_progress_dialog->setWindowTitle(tr("Downloading Update"));
 
 	// Download RPCS3
+	m_progress_dialog->setMaximum(m_expected_size);
 	m_progress_dialog->setValue(0);
-	QNetworkReply* reply_rpcs3 = m_manager.get(QNetworkRequest(QUrl(latest[os]["download"].toString())));
+	m_update_dialog = true;
 
-	connect(m_progress_dialog, &QProgressDialog::canceled, reply_rpcs3, &QNetworkReply::abort);
+	std::string request_url = latest[os]["download"].toString().toStdString();
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/update_manager.cpp]: Const

File: rpcs3/rpcs3qt/game_compatibility.cpp [hunk 6]
```diff
@@ -4,22 +4,59 @@
...
+	}
+
+	auto old_size = m_curl_buf.size();
+	auto new_size = old_size + size;
+	m_curl_buf.resize(new_size);
+	memcpy(m_curl_buf.data() + old_size, data, size);
+
+	if (!actual_dwnld_size)
+	{
+		if (curl_easy_getinfo(m_curl, CURLINFO_CONTENT_LENGTH_DOWNLOAD, &actual_dwnld_size) != -1)
```
Comment (MSuih) [inline rpcs3/rpcs3qt/game_compatibility.cpp]: The docs don't mention any CURLcode with value of -1, are you sure this comparison is correct?

File: rpcs3/rpcs3qt/game_compatibility.h [hunk 7]
```diff
@@ -39,12 +41,13 @@ class game_compatibility : public QObject
 	};
 	int m_timer_count = 0;
 	QString m_filepath;
-	QString m_url;
-	QNetworkRequest m_network_request;
+	std::string m_url;
+	std::atomic<bool> m_curl_abort = false;
+	double actual_dwnld_size = 0;
```
Comment (MSuih) [inline rpcs3/rpcs3qt/game_compatibility.h]:
```suggestion
	double m_actual_dwnld_size = 0;
```

File: rpcs3/rpcs3qt/update_manager.cpp [hunk 8]
```diff
@@ -44,90 +75,44 @@ void update_manager::check_for_updates(bool automatic, QWidget* parent)
...
+	connect(m_progress_dialog, &QProgressDialog::canceled, [&]() { m_curl_abort = true; });
 	connect(m_progress_dialog, &QProgressDialog::finished, m_progress_dialog, &QProgressDialog::deleteLater);
 
-	// clang-format off
-	connect(reply_json, &QNetworkReply::downloadProgress, [&](qint64 bytesReceived, qint64 bytesTotal)
-	{
-		m_progress_dialog->setMaximum(bytesTotal);
-		m_progress_dialog->setValue(bytesReceived);
-	});
+	std::string request_url = m_update_url + rpcs3::get_commit_and_hash().second;
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/update_manager.cpp]:
```suggestion
	const std::string request_url = m_update_url + rpcs3::get_commit_and_hash().second;
```

File: rpcs3/rpcs3qt/update_manager.cpp [hunk 9]
```diff
@@ -29,9 +34,35 @@
...
+
+size_t update_manager::update_buffer(char* data, size_t size)
+{
+	if (m_curl_abort)
+	{
+		return 0;
+	}
+
+	auto old_size = m_curl_buf.size();
+	auto new_size = old_size + size;
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/update_manager.cpp]:
```suggestion
	const auto old_size = m_curl_buf.size();
	const auto new_size = old_size + size;
```

File: rpcs3/rpcs3qt/game_compatibility.cpp [hunk 10]
```diff
@@ -118,112 +155,44 @@ void game_compatibility::RequestCompatibility(bool online)
...
-		}
-
-		if (error != QNetworkReply::OperationCanceledError)
-		{
-			// We failed to retrieve a new database, therefore refresh gamelist to old state
-			const QString error = network_reply->errorString();
-			Q_EMIT DownloadError(error);
-			compat_log.error("Network Error - %s", sstr(error));
-		}
+		auto result = curl_easy_perform(m_curl);
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/game_compatibility.cpp]:
```suggestion
		const auto result = curl_easy_perform(m_curl);
```

File: rpcs3/rpcs3qt/update_manager.cpp [hunk 11]
```diff
@@ -44,90 +75,44 @@ void update_manager::check_for_updates(bool automatic, QWidget* parent)
...
-
-	return true;
 }
 
-bool update_manager::handle_json(const QByteArray& data, bool automatic)
+bool update_manager::handle_json(bool automatic)
 {
-	const QJsonObject json_data = QJsonDocument::fromJson(data).object();
+	const QJsonObject json_data = QJsonDocument::fromJson(m_curl_buf).object();
 	int return_code             = json_data["return_code"].toInt(-255);
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/update_manager.cpp]:
```suggestion
	const QJsonObject json_data = QJsonDocument::fromJson(m_curl_buf).object();
	const int return_code       = json_data["return_code"].toInt(-255);
```

File: rpcs3/rpcs3qt/game_compatibility.h [hunk 12]
```diff
@@ -4,9 +4,10 @@
 
 #include <QPainter>
 #include <QJsonObject>
-#include <QNetworkAccessManager>
-#include <QNetworkRequest>
-#include <QTimer>
+
+#define NOMINMAX
+#define CURL_STATICLIB
+#include <curl/curl.h>
```
Comment (Nekotekina) [inline rpcs3/rpcs3qt/game_compatibility.h]: CURL probably can be declared as a forward declaration under extern "C"{}, with an actual include in cpp file.

File: rpcs3/rpcs3qt/debugger_frame.cpp [hunk 13]
```diff
@@ -536,41 +535,9 @@ u64 debugger_frame::EvaluateExpression(const QString& expression)
...
-		for (int i = 0; i < 128; ++i)
-		{
-			scriptEngine.globalObject().setProperty(QString("r%1hi").arg(i), QJSValue(spu->gpr[i]._u32[0]));
-			scriptEngine.globalObject().setProperty(QString("r%1lo").arg(i), QJSValue(spu->gpr[i]._u32[1]));
-			scriptEngine.globalObject().setProperty(QString("r%1hilo").arg(i), QJSValue(spu->gpr[i]._u32[2]));
-			scriptEngine.globalObject().setProperty(QString("r%1hihi").arg(i), QJSValue(spu->gpr[i]._u32[3]));
-		}
-	}
-
+	// Parse expression(or at least used to, was nuked to remove the need for QtJsEngine)
```
Comment (elad335) [inline rpcs3/rpcs3qt/debugger_frame.cpp]: Press F to pay respects.

Comment (Satan86) [reply rpcs3/rpcs3qt/debugger_frame.cpp]: F

Comment (illusion0001) [reply rpcs3/rpcs3qt/debugger_frame.cpp]:
```cpp
// Press F from elad
```
