### PR TITLE
GUI: Fix exception on invalid AudioRenderer

### LINKED ISSUE #8971: Emulator crashes when trying to view config
## Quick summary
When I try to open the configuration to edit it, the emulator crashes.

## Details
When clicking on Configuration at the top, or trying to create a custom config for a specific game, the emulator crashes.
```
Assertion failed: var_list.size() == 2 && var_list[0].canConvert<QString>()
(in file ../rpcs3/rpcs3qt/settings_dialog.cpp:648)
```

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5279374/RPCS3.log)

#### 2. Please attach screenshots of your problem.
Screenshot from 2020-09-24 14-35-13

#### 3. Please provide your system configuration:
* OS: Pop OS
* AMD Ryzen 9 3900x
* Nvidia GTX 1080ti
* Driver 450.66

### PR DESCRIPTION
**Pull request by bevanweiss**
The findData() on the invalid value correction wasn't working, and was still returning -1.
This was then used in the enable_buffering lambda as the IndexChanged callback, and throwing the Assert.

Have replaced this usage with a lambda to manually find the appropriate entry.  Since we localise the text displayed, neither findData nor findText of the combo box did the job.
I haven't touched the is_ranged use of findData.

Fixes #8971

### CODE REVIEW

File: rpcs3/rpcs3qt/emu_settings.cpp [hunk 1]
```diff
@@ -225,30 +225,39 @@ void emu_settings::EnhanceComboBox(QComboBox* combobox, emu_settings_type type,
 	const QString selected_q = qstr(selected);
 	int index = -1;
 
-	if (is_ranged)
-	{
-		index = combobox->findData(selected_q);
-	}
-	else
+	// Since the QComboBox has localised strings, we can't just findText / findData, so we need to manually iterate through it to find our index
+	auto findIndex = [&](QString value)
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/emu_settings.cpp:229]:
```suggestion
	auto find_index = [&](const QString& value)
```

File: rpcs3/rpcs3qt/emu_settings.cpp [hunk 2]
```diff
@@ -225,30 +225,39 @@ void emu_settings::EnhanceComboBox(QComboBox* combobox, emu_settings_type type,
...
 
-	if (is_ranged)
-	{
-		index = combobox->findData(selected_q);
-	}
-	else
+	// Since the QComboBox has localised strings, we can't just findText / findData, so we need to manually iterate through it to find our index
+	auto find_index = [&](const QString& value)
 	{
+		int idx = -1;
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/emu_settings.cpp:231]: no need for this var.
Just return -1 by default and return i in the loop.

File: rpcs3/rpcs3qt/emu_settings.cpp [hunk 3]
```diff
@@ -225,30 +225,39 @@ void emu_settings::EnhanceComboBox(QComboBox* combobox, emu_settings_type type,
...
 		for (int i = 0; i < combobox->count(); i++)
 		{
 			const QVariantList var_list = combobox->itemData(i).toList();
 			ASSERT(var_list.size() == 2 && var_list[0].canConvert<QString>());
 
 			if (selected_q == var_list[0].toString())
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/emu_settings.cpp:237]: Quite the useless change without this:
```suggestion
			if (value == var_list[0].toString())
```

File: rpcs3/rpcs3qt/emu_settings.cpp [hunk 4]
```diff
@@ -225,30 +225,39 @@ void emu_settings::EnhanceComboBox(QComboBox* combobox, emu_settings_type type,
...
+	{
+		index = find_index(selected_q);
 	}
 
 	if (index == -1)
 	{
 		const std::string def = GetSettingDefault(type);
 		cfg_log.error("EnhanceComboBox '%s' tried to set an invalid value: %s. Setting to default: %s", cfg_adapter::get_setting_name(type), selected, def);
-		combobox->setCurrentIndex(combobox->findData(qstr(def)));
+		index = find_index(qstr(def));
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/emu_settings.cpp:259]: This will not work for ranged lists...
Use this:
```suggestion
		if (is_ranged)
		{
			index = combobox->findData(qstr(def));
		}
		else
		{
			index = find_index(qstr(def));
		}
```

**Review by Megamouse — COMMENTED** [review]
Did you even test your own code? 😝

**Comment by bevanweiss** [comment]
> Did you even test your own code? 😝

I should have just stuck with the first version.  Then I saw findText and thought it would be much nicer... but localisation got in the way.  My reversion obviously had issues.

File: rpcs3/rpcs3qt/emu_settings.cpp [hunk 5]
```diff
@@ -225,30 +225,46 @@ void emu_settings::EnhanceComboBox(QComboBox* combobox, emu_settings_type type,
 	const QString selected_q = qstr(selected);
 	int index = -1;
```
Comment (sampletext32) [inline rpcs3/rpcs3qt/emu_settings.cpp:226]: I think this should be moved closer to usage - below the find_index

File: rpcs3/rpcs3qt/emu_settings.cpp [hunk 6]
```diff
@@ -221,34 +221,50 @@ void emu_settings::EnhanceComboBox(QComboBox* combobox, emu_settings_type type,
...
+		if (is_ranged)
+		{
+			index = combobox->findData(selected_q);
+		}
+		else
+		{
+			index = find_index(qstr(def));
+		}
+
+		combobox->setCurrentIndex(index);
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/emu_settings.cpp:267]: looking at the code now, you can just drop the else path and use this afterwards

Comment (bevanweiss) [reply rpcs3/rpcs3qt/emu_settings.cpp:267]: Use what afterwards?

Comment (Megamouse) [reply rpcs3/rpcs3qt/emu_settings.cpp:267]: this line

File: rpcs3/rpcs3qt/emu_settings.cpp [hunk 7]
```diff
@@ -221,34 +221,50 @@ void emu_settings::EnhanceComboBox(QComboBox* combobox, emu_settings_type type,
...
-				index = i;
-				break;
+				return i;
 			}
 		}
+		return -1;
+	};
+
+	const std::string selected = GetSetting(type);
+	const QString selected_q  = qstr(selected);
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/emu_settings.cpp:241]: spacing
```suggestion
	const QString selected_q = qstr(selected);
```

File: rpcs3/rpcs3qt/emu_settings.cpp [hunk 8]
```diff
@@ -221,34 +221,50 @@ void emu_settings::EnhanceComboBox(QComboBox* combobox, emu_settings_type type,
...
+	int index  = -1;
```
Comment (Megamouse) [inline rpcs3/rpcs3qt/emu_settings.cpp:242]: spacing
```suggestion
	int index = -1;
```

File: rpcs3/rpcs3qt/emu_settings.cpp (hunk 6 above)
Comment (bevanweiss) [reply rpcs3/rpcs3qt/emu_settings.cpp:267]: Index needs to be updated based on the default value.  And index is only updated in the else (for non is_range).

Comment (Megamouse) [reply rpcs3/rpcs3qt/emu_settings.cpp:267]: combobox->setCurrentIndex(index); is currently executed in both the if and the else block.
So it can just be refactored to be called after the if/else.
And you need to rebase
